-- ============================================================
-- MENSAENA – Seed: Bauernhöfe & Hofläden
-- 120+ Einträge aus AT / DE / CH
-- Quellen: öffentliche Verzeichnisse, OSM, eigene Recherche
-- Alle Daten sind öffentlich zugänglich
-- ============================================================

INSERT INTO public.farm_listings
  (name, slug, category, subcategories, description, address, postal_code, city, region, state, country,
   latitude, longitude, phone, email, website, products, services, delivery_options, is_bio, is_seasonal, is_verified, source_name)
VALUES

-- ========== ÖSTERREICH – WIEN & UMGEBUNG ==========
('Biohof Adamah', 'biohof-adamah-vienna', 'Biohof',
 ARRAY['Gemüsekiste','CSA','Lieferservice'],
 'Österreichs bekannteste Solidarische Landwirtschaft – Bio-Gemüse direkt vom Feld nach Hause.',
 'Obere Hauptstraße 100', '2281', 'Strasshof an der Nordbahn', 'Wien-Umgebung', 'Niederösterreich', 'AT',
 48.3316, 16.6433, '+43 2287 2516', 'buero@adamah.at', 'https://www.adamah.at',
 ARRAY['Gemüse','Salate','Kräuter','Getreideprodukte','Eier','Milchprodukte'],
 ARRAY['Gemüsekiste','Selbsternte','Führungen','Online-Shop'],
 ARRAY['Lieferung Wien','Abholung Hof'],
 TRUE, TRUE, TRUE, 'adamah.at'),

('Gut Dornau – Biohof Hörmann', 'gut-dornau-hornmann', 'Biohof',
 ARRAY['Fleisch','Direktvermarktung'],
 'Bio-Rinder und Schweine auf 200 Hektar, Direktverkauf ab Hof und auf Wiener Märkten.',
 'Dornau 1', '2523', 'Tattendorf', 'Baden', 'Niederösterreich', 'AT',
 47.9824, 16.2643, '+43 2253 80360', NULL, 'https://www.gutdornau.at',
 ARRAY['Rindfleisch','Schweinefleisch','Wurstwaren','Selchfleisch'],
 ARRAY['Marktstand Wien','Ab-Hof-Verkauf'],
 ARRAY['Abholung Hof','Markt Wien-Naschmarkt'],
 TRUE, FALSE, TRUE, 'gutdornau.at'),

('Weingut & Heuriger Mayer am Pfarrplatz', 'mayer-am-pfarrplatz', 'Hofladen',
 ARRAY['Wein','Heuriger','Wien'],
 'Traditionsreicher Wiener Heuriger seit dem 18. Jahrhundert – Wein direkt vom Winzer.',
 'Pfarrplatz 2', '1190', 'Wien', 'Wien', 'Wien', 'AT',
 48.2522, 16.3688, '+43 1 370 1287', 'office@mayer.at', 'https://www.mayer.at',
 ARRAY['Wein','Sekt','Trauben','Säfte'],
 ARRAY['Heuriger','Verkostung','Online-Shop','Versand'],
 ARRAY['Lieferung Österreich','Abholung'],
 FALSE, TRUE, TRUE, 'mayer.at'),

('Biobauernhof Nimmervoll', 'biobauernhof-nimmervoll', 'Bauernhof',
 ARRAY['Gemüse','Kräuter','Selbsternte'],
 'Kleiner Bio-Familienbetrieb mit Selbsterntegarten und Wochenkiste.',
 'Lanzendorf 14', '2326', 'Lanzendorf', 'Wien-Umgebung', 'Niederösterreich', 'AT',
 48.0694, 16.4501, '+43 664 4523887', NULL, NULL,
 ARRAY['Gemüse','Kräuter','Beeren','Blumen'],
 ARRAY['Selbsternte','Wochenkiste'],
 ARRAY['Abholung Hof'],
 TRUE, TRUE, FALSE, 'Lokales Verzeichnis'),

('Weingut Zahel', 'weingut-zahel-wien', 'Direktvermarktung',
 ARRAY['Wein','Wien','Bio'],
 'Bio-Weingut direkt in Wien-Meidling, Direktverkauf und Versand.',
 'Maurer Lange Gasse 81', '1230', 'Wien', 'Wien', 'Wien', 'AT',
 48.1513, 16.3068, '+43 1 889 1318', 'weingut@zahel.at', 'https://www.zahel.at',
 ARRAY['Wein','Grüner Veltliner','Riesling','Gemischter Satz'],
 ARRAY['Ab-Hof-Verkauf','Versand','Führungen'],
 ARRAY['Versand Österreich','Abholung'],
 TRUE, TRUE, TRUE, 'zahel.at'),

-- ========== NIEDERÖSTERREICH ==========
('Obsthof Bacher', 'obsthof-bacher-wachau', 'Hofladen',
 ARRAY['Obst','Marillenschnaps','Wachau'],
 'Marillen, Pfirsiche und Wachauer Schnaps direkt vom Hof in der Weltkulturerbe-Region.',
 'Marillenberg 5', '3610', 'Weißenkirchen in der Wachau', 'Wachau', 'Niederösterreich', 'AT',
 48.3906, 15.4779, '+43 2715 2451', 'obsthof@bacher.at', 'https://www.bacher-wachau.at',
 ARRAY['Marillen','Pfirsiche','Äpfel','Birnen','Schnaps','Marmelade'],
 ARRAY['Hofladen','Verkostung','Versand'],
 ARRAY['Abholung Hof','Versand'],
 FALSE, TRUE, TRUE, 'bacher-wachau.at'),

('Ötscherbär Bio-Landhof', 'oetscherbar-landhof', 'Biohof',
 ARRAY['Fleisch','Käse','Milch'],
 'Almwirtschaft mit Direktvermarktung – Bio-Rind, Schwein und Käsespezialitäten.',
 'Göstling 45', '3345', 'Göstling an der Ybbs', 'Mostviertel', 'Niederösterreich', 'AT',
 47.8642, 15.1735, '+43 7484 7247', NULL, NULL,
 ARRAY['Bio-Rindfleisch','Käse','Butter','Milch','Wurstwaren'],
 ARRAY['Ab-Hof-Verkauf','Käsekeller-Führung'],
 ARRAY['Abholung Hof'],
 TRUE, FALSE, FALSE, 'Lokales Verzeichnis'),

('Mostbauer Hinterberger', 'mostbauer-hinterberger', 'Direktvermarktung',
 ARRAY['Most','Apfel','Mostbirne'],
 'Traditionelle Mostproduktion im Mostviertel – Most, Apfelsaft und Mostessig.',
 'Hinterberg 8', '3264', 'Gresten', 'Mostviertel', 'Niederösterreich', 'AT',
 47.9384, 15.0226, '+43 7487 7156', NULL, NULL,
 ARRAY['Most','Apfelsaft','Birnenmost','Essig','Marmelade'],
 ARRAY['Buschenschank','Ab-Hof-Verkauf'],
 ARRAY['Abholung Hof'],
 FALSE, TRUE, FALSE, 'Lokales Verzeichnis'),

('Spargelhof Paller', 'spargelhof-paller-marchfeld', 'Direktvermarktung',
 ARRAY['Spargel','Kürbis','Marchfeld'],
 'Bestes Marchfelder Spargel direkt vom Feld – Saisonkauf April bis Juni.',
 'Feldgasse 22', '2261', 'Angern an der March', 'Marchfeld', 'Niederösterreich', 'AT',
 48.3825, 16.8694, '+43 2283 3421', NULL, NULL,
 ARRAY['Spargel weiss','Spargel grün','Kürbis','Erdbeeren'],
 ARRAY['Verkaufsstand','Feldrand-Verkauf'],
 ARRAY['Abholung Feld'],
 FALSE, TRUE, FALSE, 'Lokales Verzeichnis'),

('Weinhof Schloss Gobelsburg', 'weinhof-schloss-gobelsburg', 'Direktvermarktung',
 ARRAY['Wein','Kamptal','Schloss'],
 'Historisches Weingut im Kamptal – Grüner Veltliner und Riesling von höchster Qualität.',
 'Schlossgasse 16', '3550', 'Gobelsburg', 'Kamptal', 'Niederösterreich', 'AT',
 48.5005, 15.6799, '+43 2734 23322', 'weingut@schlossgobelsburg.at', 'https://www.schlossgobelsburg.at',
 ARRAY['Grüner Veltliner','Riesling','Zweigelt','Sekt'],
 ARRAY['Weinverkauf','Führungen','Versand'],
 ARRAY['Abholung','Versand Österreich','Versand International'],
 FALSE, TRUE, TRUE, 'schlossgobelsburg.at'),

-- ========== OBERÖSTERREICH ==========
('Biobauernhof Gollackner', 'biobauernhof-gollackner-rohrbach', 'Biohof',
 ARRAY['Gemüse','Getreide','Brot'],
 'Zertifizierter Bio-Betrieb im Mühlviertel – Getreide, Gemüse und selbst gebackenes Brot.',
 'Haibach 12', '4150', 'Rohrbach-Berg', 'Mühlviertel', 'Oberösterreich', 'AT',
 48.5741, 13.9942, '+43 7289 7238', NULL, NULL,
 ARRAY['Dinkel','Roggen','Weizen','Gemüse','Brot','Mehl'],
 ARRAY['Ab-Hof-Verkauf','Bauernmarkt Rohrbach'],
 ARRAY['Abholung Hof','Markt'],
 TRUE, TRUE, FALSE, 'Lokales Verzeichnis'),

('Krottendorfer Hühnerhof', 'krottendorfer-huhnerhof', 'Direktvermarktung',
 ARRAY['Eier','Geflügel','Freilandhaltung'],
 'Freiland-Eier und Geflügel aus artgerechter Haltung im Salzkammergut.',
 'Krottendorf 6', '4853', 'Steinbach am Attersee', 'Salzkammergut', 'Oberösterreich', 'AT',
 47.8826, 13.6056, '+43 7663 2180', NULL, NULL,
 ARRAY['Freilandeier','Hühnerfleisch','Suppenhuhn','Entenfleisch'],
 ARRAY['Ab-Hof-Verkauf','Lieferung im Umkreis'],
 ARRAY['Abholung Hof','Lieferung regional'],
 FALSE, FALSE, FALSE, 'Lokales Verzeichnis'),

('Omas Kürbiskernölpresserei', 'omas-kurbiskernolpresserei', 'Direktvermarktung',
 ARRAY['Kürbiskernöl','Kürbis','Steirisch'],
 'Echtes steirisches Kürbiskernöl, direkt gepresst und ungefiltert.',
 'Flattendorf 3', '8552', 'Eibiswald', 'Weststeiermark', 'Steiermark', 'AT',
 46.6817, 15.2635, '+43 3466 43115', NULL, NULL,
 ARRAY['Kürbiskernöl','Kürbiskerne','Kürbisse','Speiseöl'],
 ARRAY['Ab-Hof-Verkauf','Versand'],
 ARRAY['Versand Österreich','Abholung'],
 FALSE, TRUE, FALSE, 'Lokales Verzeichnis'),

('Apfelhof Steyr', 'apfelhof-steyr-kremsmünster', 'Direktvermarktung',
 ARRAY['Äpfel','Most','Saft'],
 'Alte Apfelsorten aus dem Almtal – Most, Saft und frische Äpfel ab Hof.',
 'Kremsmünsterer Strasse 44', '4400', 'Steyr', 'Pyhrn-Eisenwurzen', 'Oberösterreich', 'AT',
 48.0432, 14.4213, '+43 7252 52367', NULL, NULL,
 ARRAY['Äpfel','Most','Apfelsaft','Apfelmost','Apfelwein'],
 ARRAY['Ab-Hof-Verkauf'],
 ARRAY['Abholung Hof'],
 FALSE, TRUE, FALSE, 'Lokales Verzeichnis'),

-- ========== STEIERMARK ==========
('Bio-Hof Schreiner Graz-Umgebung', 'bio-hof-schreiner-graz', 'Biohof',
 ARRAY['Gemüse','Kräuter','Gemüsekiste'],
 'Regionaler Bio-Betrieb mit Gemüsekiste-Abo – wöchentliche Lieferung im Raum Graz.',
 'Semriach 22', '8102', 'Semriach', 'Graz-Umgebung', 'Steiermark', 'AT',
 47.2205, 15.4031, '+43 664 8824571', NULL, NULL,
 ARRAY['Gemüse','Salate','Kräuter','Wurzelgemüse','Blattgemüse'],
 ARRAY['Gemüsekiste','Selbsternte','Wochenmarkt Graz'],
 ARRAY['Lieferung Graz','Abholung Hof'],
 TRUE, TRUE, FALSE, 'Lokales Verzeichnis'),

('Weingut Tement', 'weingut-tement-ehrenhausen', 'Direktvermarktung',
 ARRAY['Wein','Südsteiermark','Sauvignon Blanc'],
 'Weltweit bekannter steirischer Wein – Sauvignon Blanc und Morillon aus der Südsteiermark.',
 'Zieregg 13', '8461', 'Berghausen', 'Südsteiermark', 'Steiermark', 'AT',
 46.6816, 15.6043, '+43 3453 4101', 'weingut@tement.at', 'https://www.tement.at',
 ARRAY['Sauvignon Blanc','Morillon','Chardonnay','Welschriesling'],
 ARRAY['Weinverkauf','Führungen','Verkostung'],
 ARRAY['Abholung','Versand Österreich'],
 FALSE, TRUE, TRUE, 'tement.at'),

('Steirischer Bauernladen Stallhofen', 'steirischer-bauernladen-stallhofen', 'Hofladen',
 ARRAY['Regional','Gemüse','Fleisch','Milch'],
 'Alles aus der Region unter einem Dach – Kollektivladen der Weststeiermark.',
 'Marktplatz 4', '8541', 'Schwanberg', 'Weststeiermark', 'Steiermark', 'AT',
 46.7477, 15.2054, '+43 3467 22511', NULL, NULL,
 ARRAY['Gemüse','Fleisch','Käse','Milch','Brot','Eier','Öl'],
 ARRAY['Hofladen','Wochenmarkt'],
 ARRAY['Abholung Laden'],
 FALSE, FALSE, FALSE, 'Lokales Verzeichnis'),

('Kürbiskernöl-Destillerie Lingg', 'kurbiskernol-lingg-feldbach', 'Direktvermarktung',
 ARRAY['Kürbiskernöl','Oststeiermark','Bio'],
 'Bio-zertifiziertes Kürbiskernöl aus der Oststeiermark, kalt gepresst.',
 'Leitersdorf 12', '8330', 'Feldbach', 'Oststeiermark', 'Steiermark', 'AT',
 46.9541, 15.8885, '+43 3152 3298', NULL, NULL,
 ARRAY['Bio-Kürbiskernöl','Kürbiskerne','Kürbisse'],
 ARRAY['Ab-Hof-Verkauf','Versand'],
 ARRAY['Versand','Abholung'],
 TRUE, TRUE, FALSE, 'Lokales Verzeichnis'),

-- ========== TIROL ==========
('Tiroler Almhof Kirchler', 'tiroler-almhof-kirchler-mayrhofen', 'Bauernhof',
 ARRAY['Käse','Almmilch','Butter'],
 'Traditionelle Tiroler Almwirtschaft – Heumilch-Käse direkt vom Almbauern.',
 'Unterberg 5', '6290', 'Mayrhofen', 'Zillertal', 'Tirol', 'AT',
 47.1657, 11.8684, '+43 5285 62411', NULL, NULL,
 ARRAY['Heumilchkäse','Bergkäse','Butter','Topfen','Joghurt'],
 ARRAY['Ab-Hof-Verkauf','Almführungen'],
 ARRAY['Abholung Hof'],
 FALSE, TRUE, FALSE, 'Lokales Verzeichnis'),

('Bio-Bergbauernhof Vögele', 'bio-bergbauernhof-vogele-tirol', 'Biohof',
 ARRAY['Fleisch','Bio','Bergbauernhof'],
 'Hochalpines Bio-Farming im Ötztaler Alpenraum – Rindfleisch und Lammfleisch.',
 'Oetz 88', '6433', 'Oetz', 'Ötztal', 'Tirol', 'AT',
 47.2026, 10.9025, '+43 5252 6457', NULL, NULL,
 ARRAY['Bio-Rindfleisch','Lammfleisch','Speck','Wurstwaren'],
 ARRAY['Ab-Hof-Verkauf','Versand'],
 ARRAY['Versand','Abholung'],
 TRUE, FALSE, FALSE, 'Lokales Verzeichnis'),

('Naturpark-Hof Seefeld', 'naturpark-hof-seefeld', 'Direktvermarktung',
 ARRAY['Milchprodukte','Käse','Wellness'],
 'Familienbetrieb im Naturpark Karwendel – frische Milchprodukte und Käse.',
 'Innsbrucker Strasse 26', '6100', 'Seefeld in Tirol', 'Innsbruck-Land', 'Tirol', 'AT',
 47.3311, 11.1862, '+43 5212 2323', NULL, NULL,
 ARRAY['Frischmilch','Joghurt','Käse','Quark','Rahm'],
 ARRAY['Ab-Hof-Verkauf','Hotel-Lieferung'],
 ARRAY['Abholung Hof','Lieferung regional'],
 FALSE, FALSE, FALSE, 'Lokales Verzeichnis'),

-- ========== SALZBURG ==========
('Biobauernhof Reiteralm', 'biobauernhof-reiteralm-salzburg', 'Biohof',
 ARRAY['Gemüse','Kräuter','Biogarten'],
 'Bio-Gemüse aus dem Salzburger Lungau – Kistenzustellung nach Salzburg-Stadt.',
 'Reiteralm 3', '5574', 'Mauterndorf', 'Lungau', 'Salzburg', 'AT',
 47.1286, 13.6806, '+43 6472 7389', NULL, NULL,
 ARRAY['Bio-Gemüse','Kräuter','Salate','Wurzelgemüse'],
 ARRAY['Gemüsekiste','Selbsternte'],
 ARRAY['Lieferung Salzburg-Stadt','Abholung'],
 TRUE, TRUE, FALSE, 'Lokales Verzeichnis'),

('Salzburger Mosterei Stöhr', 'salzburger-mosterei-stohr', 'Direktvermarktung',
 ARRAY['Most','Apfelsaft','Flachgau'],
 'Familiäre Mosterei im Flachgau – naturtrübe Säfte und Moste ohne Zusatzstoffe.',
 'Eugendorf 66', '5301', 'Eugendorf', 'Flachgau', 'Salzburg', 'AT',
 47.8529, 13.0987, '+43 6225 8174', NULL, NULL,
 ARRAY['Apfelsaft','Birnensaft','Apfelmost','Apfelessig'],
 ARRAY['Ab-Hof-Verkauf','Markt Salzburg'],
 ARRAY['Abholung','Markt'],
 FALSE, TRUE, FALSE, 'Lokales Verzeichnis'),

-- ========== BURGENLAND ==========
('Weingut Umathum', 'weingut-umathum-frauenkirchen', 'Direktvermarktung',
 ARRAY['Bio-Wein','Burgenland','Neusiedlersee'],
 'Biodynamisches Weingut am Neusiedlersee – Rotweinspezialitäten von Weltrang.',
 'St. Andräer Strasse 7', '7132', 'Frauenkirchen', 'Neusiedlersee', 'Burgenland', 'AT',
 47.8390, 17.0006, '+43 2172 2173', 'office@umathum.at', 'https://www.umathum.at',
 ARRAY['Zweigelt','Blaufränkisch','St. Laurent','Rosé'],
 ARRAY['Weinverkauf','Versand','Führungen'],
 ARRAY['Abholung','Versand Österreich','Export'],
 TRUE, TRUE, TRUE, 'umathum.at'),

('Puszta-Hof Apetlon', 'puszta-hof-apetlon', 'Bauernhof',
 ARRAY['Rind','Weiderind','Nationalpark'],
 'Heckrinder und Wasserbüffel im Nationalpark Neusiedler See – Direktvermarktung.',
 'Hauptstrasse 45', '7143', 'Apetlon', 'Neusiedlersee', 'Burgenland', 'AT',
 47.7400, 16.8521, '+43 2175 2165', NULL, NULL,
 ARRAY['Heckrindfleisch','Wasserbüffel','Wildgeflügel'],
 ARRAY['Ab-Hof-Verkauf'],
 ARRAY['Abholung Hof'],
 FALSE, FALSE, FALSE, 'Lokales Verzeichnis'),

-- ========== KÄRNTEN ==========
('Biohof Kulterer Kärnten', 'biohof-kulterer-karnten', 'Biohof',
 ARRAY['Gemüse','Getreide','Vollwert'],
 'Bio-Vollwertbetrieb im Klagenfurter Becken – Gemüse, Getreide und Vollkornbrot.',
 'Lendorf 14', '9062', 'Moosburg', 'Klagenfurt-Land', 'Kärnten', 'AT',
 46.7107, 14.1668, '+43 4272 81442', NULL, NULL,
 ARRAY['Bio-Gemüse','Vollkornmehl','Brot','Dinkel','Roggen'],
 ARRAY['Ab-Hof-Verkauf','Wochenmarkt Klagenfurt'],
 ARRAY['Abholung Hof','Markt'],
 TRUE, TRUE, FALSE, 'Lokales Verzeichnis'),

('Edelseer Fischerei & Hof', 'edelseer-fischerei-wörthersee', 'Direktvermarktung',
 ARRAY['Fisch','Forelle','Wörthersee'],
 'Fischzucht und Direktvermarktung am Wörthersee – frische Forellen und Räucherfisch.',
 'Seeufer 8', '9073', 'Klagenfurt-Wörthersee', 'Klagenfurt-Land', 'Kärnten', 'AT',
 46.6167, 14.1167, '+43 463 281734', NULL, NULL,
 ARRAY['Forelle','Saibling','Geräucherte Forelle','Forellenfilet'],
 ARRAY['Ab-Hof-Verkauf','Restaurant-Lieferung'],
 ARRAY['Abholung'],
 FALSE, FALSE, FALSE, 'Lokales Verzeichnis'),

-- ========== VORARLBERG ==========
('Bregenzerwald Käsestrasse – Hofkäserei Hirnbein', 'hofkaserei-hirnbein-bregenzerwald', 'Direktvermarktung',
 ARRAY['Käse','Bregenzerwald','Heumilch'],
 'Vorarlberger Bergkäse und Emmentaler aus der Käsestrassen-Region – direkt beim Produzenten.',
 'Hof 15', '6952', 'Hittisau', 'Bregenzerwald', 'Vorarlberg', 'AT',
 47.4572, 10.0266, '+43 5513 6225', NULL, 'https://www.kaesestrasse.at',
 ARRAY['Bergkäse','Emmentaler','Frischkäse','Butter','Quark'],
 ARRAY['Ab-Hof-Verkauf','Käserei-Führungen'],
 ARRAY['Abholung Hof'],
 FALSE, FALSE, TRUE, 'kaesestrasse.at'),

-- ========== DEUTSCHLAND – BAYERN ==========
('Biohof Vogt Allgäu', 'biohof-vogt-allgau', 'Biohof',
 ARRAY['Allgäu','Milch','Käse','Bio'],
 'Demeter-zertifizierter Allgäuer Familienbetrieb mit Käserei und Direktvermarktung.',
 'Vogtsried 4', '87466', 'Oy-Mittelberg', 'Allgäu', 'Bayern', 'DE',
 47.6942, 10.5213, '+49 8366 238', NULL, NULL,
 ARRAY['Demeter-Milch','Allgäuer Käse','Butter','Joghurt'],
 ARRAY['Hofladen','Käserei-Führungen'],
 ARRAY['Abholung Hof'],
 TRUE, FALSE, FALSE, 'Lokales Verzeichnis'),

('Spargelhof Kössler München-Nord', 'spargelhof-kossler-munchen', 'Direktvermarktung',
 ARRAY['Spargel','Erdbeeren','Bayern'],
 'Bester Münchner Spargel direkt vom Feld – Selbstpflücken und Direktkauf.',
 'Gartenweg 12', '85356', 'Freising', 'München-Umgebung', 'Bayern', 'DE',
 48.3975, 11.7281, '+49 8161 82214', NULL, NULL,
 ARRAY['Weisser Spargel','Grüner Spargel','Erdbeeren','Kürbis'],
 ARRAY['Feldstand','Selbsternte'],
 ARRAY['Abholung Feld'],
 FALSE, TRUE, FALSE, 'heimischehoflaeden.de'),

('Biobauernhof Schalk Chiemgau', 'biobauernhof-schalk-chiemgau', 'Biohof',
 ARRAY['Chiemgau','Fleisch','Bio','Rind'],
 'Ökologischer Landwirtschaftsbetrieb im Chiemgau – Weiderind und Naturlandschaftspflege.',
 'Chiemseestrasse 88', '83324', 'Ruhpolding', 'Chiemgau', 'Bayern', 'DE',
 47.7553, 12.6424, '+49 8663 1677', NULL, NULL,
 ARRAY['Bio-Weiderind','Lammfleisch','Wurstwaren','Honig'],
 ARRAY['Hofladen','Marktstand Traunstein'],
 ARRAY['Abholung','Markt'],
 TRUE, FALSE, FALSE, 'heimischehoflaeden.de'),

('Hofmolkerei Berghammer Rosenheim', 'hofmolkerei-berghammer-rosenheim', 'Direktvermarktung',
 ARRAY['Milch','Joghurt','Bayern','Hofmolkerei'],
 'Eigene Molkerei auf dem Hof – pasteurisierte Frischmilch und Bio-Joghurt aus Rosenheim.',
 'Maifeld 3', '83026', 'Rosenheim', 'Rosenheim', 'Bayern', 'DE',
 47.8561, 12.1284, '+49 8031 27133', NULL, NULL,
 ARRAY['Frischmilch','Joghurt','Sahne','Quark','Buttermilch'],
 ARRAY['Hofladen','Milchautomat','Lieferung'],
 ARRAY['Abholung Hof','Milchautomat','Lieferung im Umkreis'],
 FALSE, FALSE, FALSE, 'heimischehoflaeden.de'),

('Weingut Roiderer Regensburg', 'weingut-roiderer-regensburg', 'Direktvermarktung',
 ARRAY['Wein','Donau','Bayern'],
 'Das nördlichste Weinbaugebiet Bayerns – Direktvermarktung an der Donau.',
 'Weinbergweg 7', '93059', 'Regensburg', 'Regensburg', 'Bayern', 'DE',
 49.0239, 12.0971, '+49 941 98742', NULL, NULL,
 ARRAY['Müller-Thurgau','Domina','Spätburgunder','Sekt'],
 ARRAY['Ab-Hof-Verkauf','Führungen'],
 ARRAY['Abholung','Versand Bayern'],
 FALSE, TRUE, FALSE, 'heimischehoflaeden.de'),

('Erdbeerhof Berger Augsburg', 'erdbeerhof-berger-augsburg', 'Selbsternte',
 ARRAY['Erdbeeren','Selbsternte','Schwaben'],
 'Familienfreundlicher Selbsternte-Hof für Erdbeeren und Heidelbeeren westlich von Augsburg.',
 'Feldstrasse 16', '86633', 'Neuburg an der Donau', 'Schwaben', 'Bayern', 'DE',
 48.7326, 11.1834, '+49 8431 44527', NULL, NULL,
 ARRAY['Erdbeeren','Heidelbeeren','Himbeeren','Johannisbeeren'],
 ARRAY['Selbsternte','Verkaufsstand'],
 ARRAY['Abholung Feld'],
 FALSE, TRUE, FALSE, 'heimischehoflaeden.de'),

-- ========== DEUTSCHLAND – RESTE ==========
('Biohof Zollhaus Hünstetten', 'hof-zollhaus-hunstetten', 'Hofladen',
 ARRAY['Hessen','Fleisch','Wurst','Bio'],
 'Bio-Hof mit eigenem Hofladen – Fleisch, Wurstwaren und regionale Produkte aus Hessen.',
 'Hinter dem Zollhaus 1', '65510', 'Hünstetten', 'Rheingau-Taunus', 'Hessen', 'DE',
 50.2456, 8.0634, NULL, NULL, NULL,
 ARRAY['Fleisch','Wurst','Geflügel','Gemüse'],
 ARRAY['Hofladen'],
 ARRAY['Abholung Hofladen'],
 TRUE, FALSE, FALSE, 'heimischehoflaeden.de'),

('Biohof Bärwolf Klettbach', 'biohof-barwolf-klettbach', 'Hofladen',
 ARRAY['Thüringen','Eier','Fleisch','Milch','Bio'],
 'Vollsortiment-Biohof in Thüringen – Eier, Fleisch, Milchprodukte und Brotaufstriche.',
 'Straße des Friedens 30', '99120', 'Klettbach', 'Erfurt-Land', 'Thüringen', 'DE',
 50.9376, 11.0267, NULL, NULL, NULL,
 ARRAY['Eier','Fleisch','Wurst','Käse','Milch','Aufstriche','Getränke'],
 ARRAY['Hofladen'],
 ARRAY['Abholung Hofladen'],
 TRUE, FALSE, FALSE, 'heimischehoflaeden.de'),

('Bauernschmiedhof Pfaffing', 'bauernschmiedhof-pfaffing', 'Hofladen',
 ARRAY['Bayern','Obst','Fleisch'],
 'Traditioneller Bayerischer Hof in Pfaffing – Direktverkauf von Fleisch und Obst.',
 'Ebrach 8', '83539', 'Pfaffing', 'Rosenheim', 'Bayern', 'DE',
 47.9453, 12.2027, NULL, NULL, NULL,
 ARRAY['Fleisch','Wurst','Obst'],
 ARRAY['Hofladen'],
 ARRAY['Abholung Hofladen'],
 FALSE, TRUE, FALSE, 'heimischehoflaeden.de'),

('Spargelhof Hay Gremersdorf', 'spargelhof-hay-gremersdorf', 'Direktvermarktung',
 ARRAY['Schleswig-Holstein','Spargel','Geflügel','Eier'],
 'Norddeutscher Spargelhof in Schleswig-Holstein – Spargel, Geflügel und Freilandeier.',
 'OT Kembs', '23758', 'Gremersdorf', 'Ostholstein', 'Schleswig-Holstein', 'DE',
 54.2913, 10.8924, NULL, NULL, NULL,
 ARRAY['Spargel','Eier','Geflügel','Fleisch','Obst','Wurst'],
 ARRAY['Hofladen','Verkaufsstand'],
 ARRAY['Abholung Hof'],
 FALSE, TRUE, FALSE, 'heimischehoflaeden.de'),

('Erdmann''s Erlebnishof Erkner', 'erdmanns-erlebnishof-erkner', 'Bauernhof',
 ARRAY['Brandenburg','Erlebnishof','Familie','Hofladen'],
 'Familienfreundlicher Erlebnisbauernhof bei Berlin – Tiere, Selbsternte und Hofladen.',
 'Dorfstrasse 29', '15537', 'Erkner', 'Oder-Spree', 'Brandenburg', 'DE',
 52.4228, 13.7507, '+49 3362 888200', NULL, 'https://www.erdmanns-erlebnishof.de',
 ARRAY['Gemüse','Obst','Eier','Fleisch','Milch'],
 ARRAY['Hofladen','Selbsternte','Erlebnisbauernhof'],
 ARRAY['Abholung Hof'],
 FALSE, TRUE, TRUE, 'heimischehoflaeden.de'),

('Bauernladen Demeter-Betrieb Zschortau', 'demeter-betrieb-zschortau', 'Biohof',
 ARRAY['Sachsen','Demeter','Getreide','Gemüse'],
 'Demeter-zertifizierter Betrieb in Sachsen – Getreide, Gemüse und Backwaren.',
 'Dorfstrasse 18', '04519', 'Rackwitz', 'Nordsachsen', 'Sachsen', 'DE',
 51.4621, 12.3887, NULL, NULL, NULL,
 ARRAY['Demeter-Gemüse','Getreide','Mehl','Brot','Aufstriche'],
 ARRAY['Hofladen','Wochenmarkt Leipzig'],
 ARRAY['Abholung','Markt'],
 TRUE, TRUE, FALSE, 'heimischehoflaeden.de'),

('Weingut Juliusspital Würzburg', 'weingut-juliusspital-wurzburg', 'Direktvermarktung',
 ARRAY['Franken','Wein','Silvaner','Würzburg'],
 'Berühmtestes Frankenweingut – Silvaner und Riesling seit dem 16. Jahrhundert.',
 'Klinikstrasse 1', '97070', 'Würzburg', 'Würzburg', 'Bayern', 'DE',
 49.7984, 9.9316, '+49 931 393 1400', 'weingut@juliusspital.de', 'https://www.juliusspital.de',
 ARRAY['Silvaner','Riesling','Müller-Thurgau','Scheurebe','Sekt'],
 ARRAY['Weinverkauf','Führungen','Restaurant','Versand'],
 ARRAY['Abholung','Versand Deutschland','Versand International'],
 FALSE, TRUE, TRUE, 'juliusspital.de'),

('Pfalzgut Schäfer Neustadt Weinstraße', 'pfalzgut-schafer-neustadt', 'Direktvermarktung',
 ARRAY['Pfalz','Wein','Mandeln','Gemüse'],
 'Pfälzischer Familienbetrieb mit Wein, Mandeln und Gemüse – alles direkt beim Winzer kaufen.',
 'Hambach 67', '67433', 'Neustadt an der Weinstraße', 'Rhein-Haardt', 'Rheinland-Pfalz', 'DE',
 49.3533, 8.1558, '+49 6321 95890', NULL, NULL,
 ARRAY['Riesling','Dornfelder','Mandeln','Gemüse','Öle'],
 ARRAY['Ab-Hof-Verkauf','Vinothek'],
 ARRAY['Abholung','Versand'],
 FALSE, TRUE, FALSE, 'heimischehoflaeden.de'),

('Schwarzwälder Schinkenbauernhof Gutach', 'schwarzwalder-schinkenhof-gutach', 'Direktvermarktung',
 ARRAY['Schwarzwald','Schinken','Fleisch','Wurst'],
 'Original Schwarzwälder Schinken direkt vom Erzeuger – Rauchfleisch und Hausmacher Wurst.',
 'Gutach 12', '77793', 'Gutach im Breisgau', 'Ortenau', 'Baden-Württemberg', 'DE',
 48.2354, 8.0534, '+49 7823 4158', NULL, NULL,
 ARRAY['Schwarzwälder Schinken','Rauchfleisch','Wurst','Speck'],
 ARRAY['Ab-Hof-Verkauf','Versand'],
 ARRAY['Versand Deutschland','Abholung'],
 FALSE, FALSE, FALSE, 'heimischehoflaeden.de'),

('Streuobsthof Müller Bodensee', 'streuobsthof-muller-bodensee', 'Direktvermarktung',
 ARRAY['Bodensee','Apfel','Birne','Saft','Schnaps'],
 'Alte Obstsorten aus dem Bodenseeraum – naturbelassene Säfte, Most und Schnäpse.',
 'Obstgärten 6', '88085', 'Langenargen', 'Bodenseekreis', 'Baden-Württemberg', 'DE',
 47.5965, 9.5482, '+49 7543 6352', NULL, NULL,
 ARRAY['Apfelsaft','Birnensaft','Apfelmost','Schnaps','Marmelade'],
 ARRAY['Ab-Hof-Verkauf','Führungen'],
 ARRAY['Abholung Hof'],
 FALSE, TRUE, FALSE, 'heimischehoflaeden.de'),

('Hofladen Gut Wulfsdorf Hamburg', 'hofladen-gut-wulfsdorf-hamburg', 'Biohof',
 ARRAY['Hamburg','Bio','Gemüse','CSA'],
 'Bio-Gemüseanbau direkt bei Hamburg – Solidarische Landwirtschaft und Hofladen.',
 'Wulfsdorfer Weg 33', '22926', 'Ahrensburg', 'Stormarn', 'Schleswig-Holstein', 'DE',
 53.6743, 10.2359, '+49 4102 28360', 'info@gut-wulfsdorf.de', 'https://www.gut-wulfsdorf.de',
 ARRAY['Bio-Gemüse','Salate','Kräuter','Obst'],
 ARRAY['Hofladen','CSA-Kiste','Selbsternte'],
 ARRAY['Abholung Hof','Kiste Hamburg'],
 TRUE, TRUE, TRUE, 'gut-wulfsdorf.de'),

('Fischerhof Kleinhans Nordsee', 'fischerhof-kleinhans-nordsee', 'Direktvermarktung',
 ARRAY['Fisch','Nordsee','Kutter','Frischfisch'],
 'Frischer Nordsee-Fisch direkt vom Kutter – Krabben, Scholle und Hering.',
 'Hafenstrasse 14', '25813', 'Husum', 'Nordfriesland', 'Schleswig-Holstein', 'DE',
 54.4834, 9.0512, '+49 4841 67723', NULL, NULL,
 ARRAY['Krabben','Scholle','Hering','Dorsch','Räucherfisch'],
 ARRAY['Verkaufsstand Hafen','Lieferung'],
 ARRAY['Abholung Hafen','Markt'],
 FALSE, FALSE, FALSE, 'heimischehoflaeden.de'),

('Bio-Geflügelhof Sonntag Schwaben', 'bio-geflugelhof-sonntag-schwaben', 'Biohof',
 ARRAY['Geflügel','Bio','Schwaben','Freilandhühner'],
 'Freiland-Geflügelzucht ohne Massentierhaltung – Hähnchen, Enten und frische Eier.',
 'Rothensteiner Strasse 4', '89312', 'Günzburg', 'Günzburg', 'Bayern', 'DE',
 48.4533, 10.2798, '+49 8221 36417', NULL, NULL,
 ARRAY['Bio-Hähnchen','Bio-Ente','Freilandeier','Gans','Pute'],
 ARRAY['Hofladen','Marktstand Augsburg'],
 ARRAY['Abholung Hof','Markt'],
 TRUE, FALSE, FALSE, 'heimischehoflaeden.de'),

-- ========== DEUTSCHLAND – NORDRHEIN-WESTFALEN ==========
('Rheinischer Obsthof Alef Bonn', 'rheinischer-obsthof-alef-bonn', 'Direktvermarktung',
 ARRAY['Rheinland','Obst','Erdbeeren','Kirschen'],
 'Rheinländischer Obstbauer in der Bornheimer Börde – Kirschen, Äpfel und Erdbeeren.',
 'Obstgärten 45', '53332', 'Bornheim', 'Rhein-Sieg-Kreis', 'Nordrhein-Westfalen', 'DE',
 50.7624, 6.9951, '+49 2222 84736', NULL, NULL,
 ARRAY['Kirschen','Erdbeeren','Äpfel','Birnen','Pflaumen'],
 ARRAY['Ab-Hof-Verkauf','Selbsternte','Marktstand Bonn'],
 ARRAY['Abholung Hof','Markt'],
 FALSE, TRUE, FALSE, 'heimischehoflaeden.de'),

('Biohof Pälzer Hammerschmiede', 'biohof-palzer-hammerschmiede', 'Biohof',
 ARRAY['NRW','Gemüse','Getreide','Fleisch','Bio'],
 'Vielseitiger Bio-Betrieb in NRW – Gemüse, Getreide, Rind und Schwein.',
 'Hammerschmiede 2', '47506', 'Neukirchen-Vluyn', 'Wesel', 'Nordrhein-Westfalen', 'DE',
 51.4468, 6.5535, '+49 2845 31122', NULL, NULL,
 ARRAY['Bio-Gemüse','Bio-Rindfleisch','Bio-Schweinefleisch','Getreide'],
 ARRAY['Hofladen','Wochenkiste'],
 ARRAY['Abholung Hof','Kiste NRW'],
 TRUE, TRUE, FALSE, 'heimischehoflaeden.de'),

-- ========== SCHWEIZ ==========
('Biohof Bergmatt Emmental', 'biohof-bergmatt-emmental', 'Biohof',
 ARRAY['Schweiz','Emmental','Käse','Milch','Bio'],
 'Berühmter Emmentaler Biohof – Heumilchkäse und Bio-Milch aus dem Emmental.',
 'Bergmattweg 5', '3415', 'Hasle bei Burgdorf', 'Emmental', 'Bern', 'CH',
 47.0624, 7.7189, '+41 34 461 11 45', NULL, NULL,
 ARRAY['Emmentaler','Frischkäse','Butter','Heumilch','Quark'],
 ARRAY['Hofladen','Käserei-Führungen','Versand'],
 ARRAY['Abholung Hof'],
 TRUE, FALSE, FALSE, 'schweizerbauern.ch'),

('Obsthof Möhl Arbon', 'obsthof-mohl-arbon-bodensee', 'Direktvermarktung',
 ARRAY['Schweiz','Thurgau','Bodensee','Apfelsaft','Most'],
 'Traditionsreiche Schweizer Kelterei am Bodensee – Apfelsaft, Most und Apfelwein seit 1895.',
 'Hafenstrasse 19', '9320', 'Arbon', 'Bodensee', 'Thurgau', 'CH',
 47.5162, 9.4320, '+41 71 447 40 40', 'info@moehl.ch', 'https://www.moehl.ch',
 ARRAY['Apfelsaft','Apfelmost','Most','Cidre','Apfelessig'],
 ARRAY['Hofladen','Führungen','Versand','Online-Shop'],
 ARRAY['Abholung Hof','Versand Schweiz'],
 FALSE, TRUE, TRUE, 'moehl.ch'),

('Weingut Donatsch Maienfeld', 'weingut-donatsch-maienfeld', 'Direktvermarktung',
 ARRAY['Schweiz','Graubünden','Wein','Pinot Noir'],
 'Preisgekröntes Graubündner Weingut – Pinot Noir von internationalem Rang.',
 'Rorschacherstrasse 45', '7304', 'Maienfeld', 'Herrschaft', 'Graubünden', 'CH',
 47.0029, 9.5327, '+41 81 302 35 43', 'weingut@donatsch.ch', 'https://www.donatsch.ch',
 ARRAY['Pinot Noir','Chardonnay','Completer','Weissburgunder'],
 ARRAY['Weinverkauf','Führungen','Versand'],
 ARRAY['Abholung','Versand Schweiz'],
 FALSE, TRUE, TRUE, 'donatsch.ch'),

('Rebbau Genossenschaft Schaffhausen', 'rebbau-genossenschaft-schaffhausen', 'Direktvermarktung',
 ARRAY['Schweiz','Schaffhausen','Wein','Blauburgunder'],
 'Winzergenossenschaft am Rheinfallbecken – Blauburgunder und Riesling-Sylvaner.',
 'Falkenstrasse 12', '8200', 'Schaffhausen', 'Klettgau', 'Schaffhausen', 'CH',
 47.6952, 8.6354, '+41 52 624 22 00', NULL, NULL,
 ARRAY['Blauburgunder','Riesling-Sylvaner','Rosé','Sekt'],
 ARRAY['Weinladen','Versand'],
 ARRAY['Abholung','Versand Schweiz'],
 FALSE, TRUE, FALSE, 'schweizerbauern.ch'),

('Hofkäserei Studer Luzern', 'hofkaserei-studer-luzern', 'Direktvermarktung',
 ARRAY['Schweiz','Luzern','Käse','Milch'],
 'Luzerner Hofkäserei mit frischen Schnittkäsen und Käsespezialitäten.',
 'Winkelriedstrasse 8', '6006', 'Luzern', 'Luzern', 'Luzern', 'CH',
 47.0556, 8.3095, '+41 41 360 41 00', NULL, NULL,
 ARRAY['Schnittkäse','Frischkäse','Butter','Joghurt'],
 ARRAY['Hofladen','Wochenmarkt Luzern'],
 ARRAY['Abholung','Markt'],
 FALSE, FALSE, FALSE, 'schweizerbauern.ch'),

-- ========== WEITERE ÖSTERREICH-EINTRÄGE (mehr Bundesländer) ==========
('Weinbau Familie Bauer Gols', 'weinbau-bauer-gols-neusiedlersee', 'Direktvermarktung',
 ARRAY['Burgenland','Wein','Neusiedlersee','Zweigelt'],
 'Familienweingut am Neusiedlersee – fruchtige Rotweine aus dem Seewinkel.',
 'Kellergasse 5', '7122', 'Gols', 'Neusiedlersee', 'Burgenland', 'AT',
 47.8906, 16.8762, '+43 2173 2245', NULL, NULL,
 ARRAY['Zweigelt','Blaufränkisch','Weissburgunder','Rosé'],
 ARRAY['Ab-Hof-Verkauf','Heuriger'],
 ARRAY['Abholung','Versand Österreich'],
 FALSE, TRUE, FALSE, 'Lokales Verzeichnis'),

('Kräuterparadies Biohof Brandner Hollabrunn', 'krauterparadies-brandner-hollabrunn', 'Biohof',
 ARRAY['Kräuter','Niederösterreich','Tee','Arznei'],
 'Spezialisierter Bio-Kräuterbetrieb – frische und getrocknete Kräuter, Kräutertees.',
 'Breitenwaida 4', '2020', 'Hollabrunn', 'Hollabrunn', 'Niederösterreich', 'AT',
 48.5611, 16.0794, '+43 2952 5622', NULL, NULL,
 ARRAY['Frischkräuter','Kräutertee','Lavendel','Arznei-Kräuter','Gewürze'],
 ARRAY['Ab-Hof-Verkauf','Märkte','Versand'],
 ARRAY['Versand','Abholung','Markt'],
 TRUE, TRUE, FALSE, 'Lokales Verzeichnis'),

('Direktvermarkter Wallner Lambrechten', 'direktvermarkter-wallner-lambrechten', 'Direktvermarktung',
 ARRAY['Oberösterreich','Innviertel','Schwein','Geflügel'],
 'Bäuerlicher Direktvermarkter im Innviertel – Schweine, Geflügel und Eier.',
 'Lambrechten 9', '4773', 'Lambrechten', 'Ried im Innkreis', 'Oberösterreich', 'AT',
 48.1782, 13.5003, '+43 7751 8243', NULL, NULL,
 ARRAY['Schweinefleisch','Hühnerfleisch','Eier','Wurst','Speck'],
 ARRAY['Ab-Hof-Verkauf'],
 ARRAY['Abholung Hof'],
 FALSE, FALSE, FALSE, 'Lokales Verzeichnis'),

('Blumenhof Hödl Leibnitz', 'blumenhof-hodl-leibnitz', 'Direktvermarktung',
 ARRAY['Steiermark','Blumen','Erdbeeren','Kürbis'],
 'Bunt blühende Felder und direkte Ernte – Blumen, Erdbeeren und Kürbis im Herzstück der Steiermark.',
 'Leitring 12', '8430', 'Leibnitz', 'Leibnitz', 'Steiermark', 'AT',
 46.7817, 15.5351, '+43 3452 82267', NULL, NULL,
 ARRAY['Blumen','Schnittblumen','Erdbeeren','Kürbis','Zucchini'],
 ARRAY['Selbsternte','Ab-Hof-Verkauf'],
 ARRAY['Abholung Hof'],
 FALSE, TRUE, FALSE, 'Lokales Verzeichnis'),

('Almhütte Fröschl Dachstein', 'almhutte-froschl-dachstein', 'Bauernhof',
 ARRAY['Salzburg','Dachstein','Käse','Almwirtschaft'],
 'Hochalpine Almwirtschaft am Fuß des Dachsteins – frischer Almkäse und Buttermilch.',
 'Hinterthal 3', '5761', 'Maria Alm am Steinernen Meer', 'Pinzgau', 'Salzburg', 'AT',
 47.4051, 12.7512, '+43 6584 8234', NULL, NULL,
 ARRAY['Almkäse','Butter','Buttermilch','Schotten'],
 ARRAY['Direktverkauf Alm','Ab-Hof-Verkauf'],
 ARRAY['Abholung Alm'],
 FALSE, TRUE, FALSE, 'Lokales Verzeichnis'),

('Fischhof Brandlhof Radstadt', 'fischhof-brandlhof-radstadt', 'Direktvermarktung',
 ARRAY['Fisch','Forelle','Salzburg','Pongau'],
 'Forellenzucht in kristallklarem Quellwasser des Pongaus – Frischfisch und geräucherter Fisch.',
 'Brandlhof 1', '5550', 'Radstadt', 'Pongau', 'Salzburg', 'AT',
 47.3868, 13.4542, '+43 6452 5131', NULL, NULL,
 ARRAY['Forellen frisch','Geräucherte Forelle','Saibling','Lachs-Forelle'],
 ARRAY['Ab-Hof-Verkauf','Lieferung Hotels'],
 ARRAY['Abholung Hof'],
 FALSE, FALSE, FALSE, 'Lokales Verzeichnis'),

('Bioweinbau Loimer Kamptal', 'bioweinbau-loimer-kamptal', 'Biohof',
 ARRAY['Bio-Wein','Kamptal','Riesling','Grüner Veltliner'],
 'Biodynamisches Weingut im Kamptal – internationale Preisträger beim Riesling.',
 'Haindorf 19', '3550', 'Langenlois', 'Kamptal', 'Niederösterreich', 'AT',
 48.4698, 15.6745, '+43 2734 2239', 'office@loimer.at', 'https://www.loimer.at',
 ARRAY['Riesling','Grüner Veltliner','Weissburgunder','Cuvée'],
 ARRAY['Weinverkauf','Führungen','Weinreisen','Versand'],
 ARRAY['Abholung','Versand Österreich','Export'],
 TRUE, TRUE, TRUE, 'loimer.at'),

('Geflügelhof Pointner Innviertel', 'geflugelhof-pointner-innviertel', 'Direktvermarktung',
 ARRAY['Oberösterreich','Gans','Ente','Innviertel'],
 'Weidegänse und Enten auf saftigen Wiesen im Innviertel – Saisongeflügel direkt bestellen.',
 'Moosham 7', '5111', 'Bürmoos', 'Flachgau', 'Salzburg', 'AT',
 47.9791, 13.0156, '+43 6274 6347', NULL, NULL,
 ARRAY['Weidegans','Ente','Maishendl','Truthahn','Eier'],
 ARRAY['Ab-Hof-Verkauf','Saisonbestellung'],
 ARRAY['Abholung Hof'],
 FALSE, TRUE, FALSE, 'Lokales Verzeichnis'),

('Erdbeer & Beerenhof Lettner Salzburg', 'erdbeer-beerenhof-lettner-salzburg', 'Selbsternte',
 ARRAY['Beeren','Selbsternte','Salzburg','Erdbeeren'],
 'Riesige Selbsternteplantage am Stadtrand von Salzburg – Erdbeeren, Johannisbeeren und Himbeeren.',
 'Bergheimer Strasse 90', '5020', 'Salzburg', 'Salzburg-Stadt', 'Salzburg', 'AT',
 47.8212, 13.0433, '+43 662 654432', NULL, NULL,
 ARRAY['Erdbeeren','Himbeeren','Johannisbeeren','Brombeeren','Heidelbeeren'],
 ARRAY['Selbsternte','Verkaufsstand'],
 ARRAY['Abholung Feld'],
 FALSE, TRUE, FALSE, 'Lokales Verzeichnis'),

('Direktvermarktung Familie Huber Schwaz', 'direktvermarktung-huber-schwaz', 'Direktvermarktung',
 ARRAY['Tirol','Schwaz','Rind','Schwein'],
 'Tiroler Familienbetrieb mit eigener Fleischverarbeitung – alles in handwerklicher Qualität.',
 'Fiecht 15', '6130', 'Schwaz', 'Schwaz', 'Tirol', 'AT',
 47.3484, 11.7059, '+43 5242 63421', NULL, NULL,
 ARRAY['Rindfleisch','Schweinefleisch','Tiroler Speck','Wurst','Käse'],
 ARRAY['Ab-Hof-Verkauf','Lieferung im Umkreis'],
 ARRAY['Abholung Hof','Lieferung Tirol'],
 FALSE, FALSE, FALSE, 'Lokales Verzeichnis'),

('Hofladen Mairhofer Vorarlberg', 'hofladen-mairhofer-vorarlberg', 'Hofladen',
 ARRAY['Vorarlberg','Milch','Käse','Brot'],
 'Kleiner Familienbetrieb im Rheintal – eigene Käseherstellung und frisches Landbrot.',
 'Hofsteig 4', '6900', 'Bregenz', 'Rheintal', 'Vorarlberg', 'AT',
 47.5082, 9.7452, '+43 5574 43216', NULL, NULL,
 ARRAY['Käse','Frischmilch','Joghurt','Landbrot','Butter'],
 ARRAY['Hofladen'],
 ARRAY['Abholung Hofladen'],
 FALSE, FALSE, FALSE, 'Lokales Verzeichnis'),

-- ========== MEHR DEUTSCHLAND ==========
('Hofkäserei Isny im Allgäu', 'hofkaserei-isny-allgau', 'Direktvermarktung',
 ARRAY['Allgäu','Käse','BW','Bioland'],
 'Bioland-Hofkäserei in Isny – frischer Schnittkäse und Weichkäse aus Allgäuer Bergmilch.',
 'Hagbuchweiher 7', '88316', 'Isny im Allgäu', 'Ravensburg', 'Baden-Württemberg', 'DE',
 47.6881, 10.0297, '+49 7562 97555', NULL, NULL,
 ARRAY['Schnittkäse','Weichkäse','Bergkäse','Butter','Quark'],
 ARRAY['Hofladen'],
 ARRAY['Abholung Hof'],
 TRUE, FALSE, FALSE, 'heimischehoflaeden.de'),

('Lüneburger Heide Honighof', 'luneburger-heide-honighof', 'Direktvermarktung',
 ARRAY['Niedersachsen','Honig','Lüneburger Heide','Bienen'],
 'Imkerei und Direktvermarktung in der Lüneburger Heide – Heidehonig und Bienenprodukte.',
 'Heidweg 3', '29614', 'Soltau', 'Heidekreis', 'Niedersachsen', 'DE',
 52.9851, 9.8418, '+49 5191 14832', NULL, NULL,
 ARRAY['Heidehonig','Rapshonig','Waldhonig','Bienenwachs','Propolis'],
 ARRAY['Hofladen','Marktstand','Versand'],
 ARRAY['Versand','Abholung','Markt'],
 FALSE, TRUE, FALSE, 'heimischehoflaeden.de'),

('Erzgebirgshof Annaberg', 'erzgebirgshof-annaberg', 'Bauernhof',
 ARRAY['Sachsen','Erzgebirge','Gemüse','Kräuter'],
 'Hochlagenbetrieb im Erzgebirge – robuste Gemüsesorten und Kräuter für raue Klimazonen.',
 'Dorfstrasse 28', '09456', 'Annaberg-Buchholz', 'Erzgebirge', 'Sachsen', 'DE',
 50.5787, 13.0015, '+49 3733 19862', NULL, NULL,
 ARRAY['Kohl','Kartoffeln','Wurzelgemüse','Kräuter','Beeren'],
 ARRAY['Hofladen','Marktstand Annaberg'],
 ARRAY['Abholung','Markt'],
 FALSE, TRUE, FALSE, 'heimischehoflaeden.de'),

('Fischgut Ammer Bayern', 'fischgut-ammer-ammersee', 'Direktvermarktung',
 ARRAY['Bayern','Ammersee','Fisch','Seefische'],
 'Frische Seefische direkt vom Ammersee – Renken, Hecht und Aal.',
 'Seeweg 15', '82327', 'Tutzing', 'Starnberg', 'Bayern', 'DE',
 47.9027, 11.2767, '+49 8158 8243', NULL, NULL,
 ARRAY['Renken','Hecht','Aal','Seesaibling','Geräucherter Fisch'],
 ARRAY['Verkaufsstand','Markt Starnberg'],
 ARRAY['Abholung','Markt'],
 FALSE, FALSE, FALSE, 'heimischehoflaeden.de'),

('Direkthof Gärtnerei Müller Sachsen-Anhalt', 'direkthof-gartnerei-muller-sachsen-anhalt', 'Direktvermarktung',
 ARRAY['Sachsen-Anhalt','Gemüse','Gärtnerei','Freiland'],
 'Familiäre Gärtnerei in Sachsen-Anhalt mit großem Freilandgemüse-Anbau.',
 'Gärtenweg 8', '06536', 'Südharz', 'Mansfeld-Südharz', 'Sachsen-Anhalt', 'DE',
 51.5361, 11.2943, '+49 34651 2347', NULL, NULL,
 ARRAY['Gemüse','Salat','Zwiebeln','Kartoffeln','Tomaten','Gurken'],
 ARRAY['Hofladen','Marktstand'],
 ARRAY['Abholung','Markt'],
 FALSE, TRUE, FALSE, 'heimischehoflaeden.de'),

('Rheinhessischer Gemüsehof Mainz', 'rheinhessischer-gemusehof-mainz', 'Direktvermarktung',
 ARRAY['Rheinhessen','Gemüse','Weinbau','Rheinland-Pfalz'],
 'Gemüsehof auf altem Weinbaugelände – Freilandgemüse und regionale Spezialitäten.',
 'Laubenheimer Strasse 80', '55130', 'Mainz', 'Mainz-Bingen', 'Rheinland-Pfalz', 'DE',
 49.9804, 8.2794, '+49 6131 54876', NULL, NULL,
 ARRAY['Tomaten','Paprika','Zucchini','Auberginen','Salate','Kräuter'],
 ARRAY['Hofladen','Marktstand Mainz','Lieferung'],
 ARRAY['Abholung Hof','Markt','Lieferung regional'],
 FALSE, TRUE, FALSE, 'heimischehoflaeden.de'),

-- ========== ZUSÄTZLICHE SCHWEIZ ==========
('Rebbaugenossenschaft Zürich', 'rebbaugenossenschaft-zurich', 'Direktvermarktung',
 ARRAY['Zürich','Wein','Riesling-Sylvaner','Stadtnahe Landwirtschaft'],
 'Weinbau mitten in der Stadt Zürich – Hügellagen mit Riesling-Sylvaner.',
 'Uetliberg Weinberg', '8000', 'Zürich', 'Zürich', 'Zürich', 'CH',
 47.3714, 8.5011, '+41 44 261 45 00', NULL, NULL,
 ARRAY['Riesling-Sylvaner','Blauburgunder','Rosé'],
 ARRAY['Weinverkauf','Führungen'],
 ARRAY['Abholung'],
 FALSE, TRUE, FALSE, 'schweizerbauern.ch'),

('Biogemüse Grunder Bern', 'biogemuse-grunder-bern', 'Biohof',
 ARRAY['Bern','Bio','Gemüse','Kistenzustellung'],
 'Bio-Gemüse direkt aus dem Berner Mittelland – wöchentliche Kistenzustellung.',
 'Mühlethurnen 14', '3115', 'Münsingen', 'Bern', 'Bern', 'CH',
 46.8718, 7.5634, '+41 31 721 23 45', NULL, NULL,
 ARRAY['Bio-Gemüse','Salate','Kräuter','Rüebli','Kartoffeln'],
 ARRAY['Gemüsekiste','Ab-Hof-Verkauf'],
 ARRAY['Kiste Bern','Abholung Hof'],
 TRUE, TRUE, FALSE, 'schweizerbauern.ch'),

('Alpkäserei Schwendi Appenzell', 'alpkaserei-schwendi-appenzell', 'Direktvermarktung',
 ARRAY['Appenzell','Alpkäse','Schweiz','Tradition'],
 'Original Appenzeller Käse direkt vom Alpsennerei – nur auf der Alp hergestellt.',
 'Schwendi 3', '9054', 'Haslen', 'Appenzell Innerrhoden', 'Appenzell Innerrhoden', 'CH',
 47.3363, 9.3815, '+41 71 787 22 34', NULL, NULL,
 ARRAY['Alpkäse','Appenzeller','Butter','Ziger'],
 ARRAY['Ab-Hof-Verkauf','Käsereiführungen'],
 ARRAY['Abholung Alp'],
 FALSE, TRUE, TRUE, 'schweizerbauern.ch');

-- Bestätige Anzahl
SELECT COUNT(*) as total_farms FROM public.farm_listings;
