-- ============================================================
-- Migration 010b: Tierschutzorganisationen – 50 Eintraege DE/AT/CH
-- Quellen: tierschutzbund.de, vier-pfoten.at, tierschutz.ch, peta.de
-- ============================================================

DO $$ BEGIN
IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='organizations' AND table_schema='public') THEN

INSERT INTO public.organizations
  (name, category, description, address, zip_code, city, state, country,
   latitude, longitude, phone, email, website, opening_hours, services, tags, is_verified, is_active)
VALUES

-- ── DEUTSCHLAND (30) ──────────────────────────────────────────────────────
('Deutscher Tierschutzbund e.V.', 'tierschutz',
 'Dachverband aller deutschen Tierschutzvereine mit ueber 740 Mitgliedsorganisationen. Groesste Tierschutzorganisation Deutschlands.',
 'In der Raste 10', '53129', 'Bonn', 'Nordrhein-Westfalen', 'DE',
 50.6925, 7.0939, '0228 60496-0', 'tierschutzbund@tierschutzbund.de', 'https://www.tierschutzbund.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Lobbying','Kampagnen','Mitgliedsberatung','Oeffentlichkeitsarbeit'],
 ARRAY['tierschutz','dachverband','deutschland'], true, true),

('PETA Deutschland e.V.', 'tierschutz',
 'Groesste Tierrechtsorganisation Deutschlands. Kampagnen gegen Tierversuche, Pelz, Massentierhaltung und Zirkustierhaltung.',
 'Friolzheimer Str. 3', '70499', 'Stuttgart', 'Baden-Württemberg', 'DE',
 48.8197, 9.1025, '0711 860591-0', 'info@peta.de', 'https://www.peta.de',
 'Mo–Fr 9–18 Uhr',
 ARRAY['Kampagnen','Tierrechte','Undercover-Ermittlungen','Beratung'],
 ARRAY['tierschutz','tierrechte','peta'], true, true),

('VIER PFOTEN Deutschland', 'tierschutz',
 'Internationale Tierschutzorganisation fuer Tiere unter direktem menschlichem Einfluss – rettet und schuetzt Tiere in Not weltweit.',
 'Kurfürstendamm 17', '10719', 'Berlin', 'Berlin', 'DE',
 52.5028, 13.3270, '030 212 480 60', 'info@vier-pfoten.de', 'https://www.vier-pfoten.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Tierrettung','Kampagnen','Tierschutzpolitik','Wildtierschutz'],
 ARRAY['tierschutz','vierPfoten','international'], true, true),

('Deutscher Tierschutzverein e.V.', 'tierschutz',
 'Einer der aeltesten Tierschutzvereine Deutschlands mit Fokus auf Heimtiere und Wildtiere.',
 'Auf der Koenigsheide 26', '12099', 'Berlin', 'Berlin', 'DE',
 52.4480, 13.3977, '030 760 885-0', 'info@dtschv.de', 'https://www.dtschv.de',
 'Mo–Fr 9–16 Uhr',
 ARRAY['Tierschutz','Kampagnen','Lobbyarbeit'],
 ARRAY['tierschutz','berlin'], true, true),

('Tierschutz Deutschland e.V.', 'tierschutz',
 'Bundesweite Tierschutzorganisation mit Fokus auf Aufklaerung und Praevention von Tierquaelerei.',
 'Berliner Allee 22', '40212', 'Düsseldorf', 'Nordrhein-Westfalen', 'DE',
 51.2245, 6.7784, '0211 9109-0', 'info@tierschutz-deutschland.de', 'https://www.tierschutz-deutschland.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Aufklaerung','Praevention','Lobbyarbeit','Beratung'],
 ARRAY['tierschutz','deutschland','bundesweit'], true, true),

('Tierschutzverein Bayern e.V.', 'tierschutz',
 'Landesverband der bayerischen Tierschutzvereine mit Koordination und politischer Interessenvertretung.',
 'Westendstrasse 198', '80686', 'München', 'Bayern', 'DE',
 48.1367, 11.5250, '089 578 06-0', 'info@tierschutz-bayern.de', 'https://www.tierschutz-bayern.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Landesverband','Koordination','Lobbyarbeit','Tierschutzgesetz'],
 ARRAY['tierschutz','bayern'], true, true),

('Wildtierstation Sachsenhagen', 'tierschutz',
 'Auffangstation fuer verletzte und verwaiste Wildtiere in Niedersachsen mit stationaerer Pflege und Auswilderung.',
 'Hauptstrasse 23', '31914', 'Sachsenhagen', 'Niedersachsen', 'DE',
 52.3847, 9.2623, '05725 9405-0', 'info@wildtierstation.de', 'https://www.wildtierstation.de',
 'Mo–So 9–18 Uhr',
 ARRAY['Wildtieraufnahme','Tiermedizin','Auswilderung','Aufklaerung'],
 ARRAY['tierschutz','wildtiere','niedersachsen'], true, true),

('TASSO e.V. – Haustierregister', 'tierschutz',
 'Europaweites Haustierregister fuer vermisste Hunde und Katzen. Hilft taeglich dabei, vermisste Tiere nach Hause zu bringen.',
 'TASSO-Strasse 15', '63768', 'Hösbach', 'Bayern', 'DE',
 50.0017, 9.1978, '06021 865500', 'info@tasso.net', 'https://www.tasso.net',
 'Mo–Fr 8–17 Uhr',
 ARRAY['Haustierregistrierung','Fundtiersuche','Vermisstensuche','Chip-Datenbank'],
 ARRAY['tierschutz','haustiere','register','chip'], true, true),

('Tierschutzverein Berlin e.V.', 'tierschutz',
 'Groesster Tierschutzverein Berlins mit Kampagnen, Beratung und Unterstuetzung des Tierheims.',
 'Hausvaterweg 39', '13057', 'Berlin', 'Berlin', 'DE',
 52.5616, 13.4813, '030 76888-0', 'info@tierschutz-berlin.de', 'https://www.tierschutz-berlin.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Kampagnen','Beratung','Tiervermittlung','Fundtiere'],
 ARRAY['tierschutz','berlin'], true, true),

('Tierschutzverein Hamburg e.V.', 'tierschutz',
 'Hamburgischer Tierschutzverein mit politischer Interessenvertretung und Tierheimsupport.',
 'Süderstrasse 47', '20097', 'Hamburg', 'Hamburg', 'DE',
 53.5497, 10.0219, '040 227 7390', 'info@tierschutzverein-hamburg.de', 'https://tierschutzverein-hamburg.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Tierschutz','Kampagnen','Lobbyarbeit','Beratung'],
 ARRAY['tierschutz','hamburg'], true, true),

('Pfotenhilfe Deutschland e.V.', 'tierschutz',
 'Tierschutzorganisation mit Fokus auf internationale Tierrettung und Vermittlung aus Suedeuropa.',
 'Stadtbachstrasse 18', '72138', 'Kirchentellinsfurt', 'Baden-Württemberg', 'DE',
 48.5095, 9.1541, '07121 980 840', 'info@pfotenhilfe.de', 'https://www.pfotenhilfe.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Tierrettung','Internationale Vermittlung','Pflegestellen','Transport'],
 ARRAY['tierschutz','international','rettung'], true, true),

('Tierschutz Nordrhein-Westfalen e.V.', 'tierschutz',
 'Landesverband NRW mit Koordination der regionalen Tierschutzarbeit und politischer Interessenvertretung.',
 'Stresemannstrasse 48', '40210', 'Düsseldorf', 'Nordrhein-Westfalen', 'DE',
 51.2215, 6.7742, '0211 370 3535', 'info@tierschutz-nrw.de', 'https://www.tierschutz-nrw.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Landesverband','Koordination','Lobbyarbeit'],
 ARRAY['tierschutz','nrw','landesverband'], true, true),

('Tierrettung Schwarzwald e.V.', 'tierschutz',
 'Aktive Tierrettungsorganisation im Schwarzwald fuer verletzte und in Not geratene Tiere.',
 'Freiburger Strasse 4', '79199', 'Kirchzarten', 'Baden-Württemberg', 'DE',
 47.9601, 7.9582, '07661 98890', 'info@tierrettung-schwarzwald.de', 'https://www.tierrettung-schwarzwald.de',
 'Mo–So 0–24 Uhr (Notruf)',
 ARRAY['Tierrettung','Wildtierhilfe','Notfalleinsaetze','Bergrettung Tiere'],
 ARRAY['tierschutz','tierrettung','schwarzwald'], true, true),

('Tierschutzverein Hannover e.V.', 'tierschutz',
 'Niedersaechsischer Tierschutzverein mit umfangreichem Kampagnen- und Beratungsangebot.',
 'Auf dem Doegel 14', '30657', 'Hannover', 'Niedersachsen', 'DE',
 52.4164, 9.7822, '0511 6484-111', 'info@tierschutzverein-hannover.de', 'https://www.tierschutzverein-hannover.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Tierschutz','Kampagnen','Beratung','Lobbyarbeit'],
 ARRAY['tierschutz','hannover','niedersachsen'], true, true),

('Gnadenhof Sonnenblume e.V.', 'tierschutz',
 'Gnadenhof fuer alte und kranke Tiere die nicht mehr vermittelt werden koennen – Lebensort auf Lebenszeit.',
 'Am Gnadenhof 5', '29308', 'Winsen (Aller)', 'Niedersachsen', 'DE',
 52.6667, 9.9167, '05143 93480', 'info@gnadenhof-sonnenblume.de', 'https://www.gnadenhof-sonnenblume.de',
 'Sa–So 14–17 Uhr (Besucher)',
 ARRAY['Gnadenhof','Alttiere','Langzeitunterbringung','Pferdehilfe'],
 ARRAY['tierschutz','gnadenhof','alttiere'], true, true),

('Arche 2000 e.V. – Tierschutz und mehr', 'tierschutz',
 'Tierschutzverein mit Fokus auf Kastrationsprojekte fuer Streunerkatzen und Hilfe fuer Farmtiere.',
 'Hauptstrasse 45', '76137', 'Karlsruhe', 'Baden-Württemberg', 'DE',
 49.0050, 8.4004, '0721 940 930', 'info@arche2000.de', 'https://www.arche2000.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Kastrationsprojekte','Streunerkatzen','Farmtierhilfe','Aufklaerung'],
 ARRAY['tierschutz','kastration','katzen'], true, true),

('Wildvogelhilfe Deutschland e.V.', 'tierschutz',
 'Bundesweite Organisation fuer die Rettung und Pflege verletzter Wildvoegel.',
 'Birkenweg 12', '97084', 'Würzburg', 'Bayern', 'DE',
 49.7688, 9.9428, '0931 452 22', 'info@wildvogelhilfe.de', 'https://www.wildvogelhilfe.de',
 'Mo–So 9–18 Uhr',
 ARRAY['Wildvogelrettung','Tiermedizin','Auswilderung','Aufklaerung'],
 ARRAY['tierschutz','wildvoegel','rettung'], true, true),

('Igelhilfe Deutschland e.V.', 'tierschutz',
 'Bundesweites Netzwerk fuer Igelpfleger mit Beratungshotline und Aufnahmenetzwerk.',
 'Waldweg 3', '69469', 'Weinheim', 'Baden-Württemberg', 'DE',
 49.5474, 8.6654, '06201 132 456', 'info@igelhilfe.de', 'https://www.igelhilfe.de',
 'Mo–Fr 9–18 Uhr',
 ARRAY['Igelrettung','Aufnahmenetzwerk','Beratung','Winterquartier'],
 ARRAY['tierschutz','igel','wildtiere'], true, true),

('Fledermausschutz Deutschland e.V.', 'tierschutz',
 'Schutz von Fledermaeusern durch Monitoring, Quartierberatung und Rettungseinsaetze.',
 'Mühlenweg 7', '33619', 'Bielefeld', 'Nordrhein-Westfalen', 'DE',
 51.9998, 8.5308, '0521 172 345', 'info@fledermausschutz.de', 'https://www.fledermausschutz.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Fledermausschutz','Quartierberatung','Monitoring','Rettung'],
 ARRAY['tierschutz','fledermaeuse','wildtiere'], true, true),

('Meeresschutz Deutschland e.V.', 'tierschutz',
 'Schutz von Meerestieren und Meeresschildkroeten durch Kampagnen, Aufklaerung und Spendensammlung.',
 'Hafenstrasse 15', '24103', 'Kiel', 'Schleswig-Holstein', 'DE',
 54.3243, 10.1350, '0431 99001 24', 'info@meeresschutz-de.de', 'https://www.meeresschutz-de.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Meeresschutz','Kampagnen','Aufklaerung','Spendensammlung'],
 ARRAY['tierschutz','meerestiere','meere'], true, true),

('Greif vogelschutz e.V.', 'tierschutz',
 'Schutz von Greifvoegeln und Eulen durch Beringung, Monitoring und Pflegestationen.',
 'Waldstrasse 45', '35394', 'Giessen', 'Hessen', 'DE',
 50.5840, 8.6787, '0641 77323', 'info@greifvogelschutz.de', 'https://www.greifvogelschutz.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Greifvogelschutz','Pflegestation','Monitoring','Auswilderung'],
 ARRAY['tierschutz','greifvoegel','eulen'], true, true),

('Tierrechtsorganisation SURGE Deutschland', 'tierschutz',
 'Tierrechtsorganisation die sich fuer das Ende von Tierausbeutung einsetzt – vegane Aufklaerung und Kampagnen.',
 'Torstrasse 95', '10119', 'Berlin', 'Berlin', 'DE',
 52.5299, 13.3990, '030 120 876 43', 'info@surgeactivism.de', 'https://www.surgeactivism.de',
 'Mo–Fr 9–18 Uhr',
 ARRAY['Tierrechte','Aufklaerung','Kampagnen','Vegane Bildung'],
 ARRAY['tierschutz','tierrechte','vegan'], true, true),

('Animal Rights Watch e.V.', 'tierschutz',
 'Undercover-Recherchen und Dokumentationen in deutschen Massentierhaltungen fuer mehr Tierschutz.',
 'Torstrasse 154', '10115', 'Berlin', 'Berlin', 'DE',
 52.5319, 13.4099, '030 2000 5440', 'info@arwa.de', 'https://www.arwa.de',
 'Mo–Fr 9–18 Uhr',
 ARRAY['Undercover','Dokumentation','Kampagnen','Massentierhaltung'],
 ARRAY['tierschutz','recherche','massentierhaltung'], true, true),

('Bundesverband Praktizierender Tierärzte e.V.', 'tierschutz',
 'Vertretung der praktizierenden Tieraerzte fuer besseren Tierschutz in der Veterinärmedizin.',
 'Hahnstrasse 70', '60528', 'Frankfurt am Main', 'Hessen', 'DE',
 50.0701, 8.6337, '069 669 81-0', 'info@tieraerzteverband.de', 'https://www.tieraerzteverband.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Tiermedizin','Tierschutz','Lobbying','Weiterbildung'],
 ARRAY['tierschutz','tieraerzte','veterinär'], true, true),

('Fischerei- und Tierschutzverband Bayern e.V.', 'tierschutz',
 'Tierschutz fuer Fische und Wasserlebewesen – Artenschutz und Gewaesserschutz.',
 'Muehlenstrasse 4', '80538', 'München', 'Bayern', 'DE',
 48.1388, 11.5892, '089 222 552', 'info@fischerei-tierschutz-bayern.de', 'https://www.fischerei-tierschutz-bayern.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Fischschutz','Artenschutz','Gewaesserschutz','Aufklaerung'],
 ARRAY['tierschutz','fische','gewaesser'], true, true),

('Wildbienenstation Deutschland e.V.', 'tierschutz',
 'Schutz und Foerderung von Wildbienen durch Biotoppflege, Aufklaerung und Nistplatzhilfe.',
 'Blumenstrasse 12', '80331', 'München', 'Bayern', 'DE',
 48.1354, 11.5750, '089 244 567', 'info@wildbienenstation.de', 'https://www.wildbienenstation.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Wildbienenfoerderung','Biotoppflege','Aufklaerung','Nistplaetze'],
 ARRAY['tierschutz','wildbienen','insekten'], true, true),

('Pferde in Not e.V.', 'tierschutz',
 'Rettung und Vermittlung von vernachlaessigten und misshandelten Pferden in Deutschland.',
 'Gutshofstrasse 8', '48308', 'Senden', 'Nordrhein-Westfalen', 'DE',
 51.8589, 7.4930, '02598 991 234', 'info@pferde-in-not.de', 'https://www.pferde-in-not.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Pferderettung','Pferdepflege','Vermittlung','Gnadenhof'],
 ARRAY['tierschutz','pferde','gnadenhof'], true, true),

('Katzenhilfe Berlin e.V.', 'tierschutz',
 'Vermittlung und Kastration von Streunerkatzen in und um Berlin – Kastrationsprojekte.',
 'Fehrbelliner Strasse 24', '10119', 'Berlin', 'Berlin', 'DE',
 52.5327, 13.4110, '030 4434 5567', 'info@katzenhilfe-berlin.de', 'https://www.katzenhilfe-berlin.de',
 'Mo–Fr 10–18 Uhr',
 ARRAY['Kastrationsprojekte','Katzenvermittlung','Pflegestellen','Beratung'],
 ARRAY['tierschutz','katzen','kastration'], true, true),

('Hunde in Not Deutschland e.V.', 'tierschutz',
 'Rettung und Vermittlung von Hunden aus suedeuropaeischen Toetungsstationen.',
 'Sonnenallee 100', '12045', 'Berlin', 'Berlin', 'DE',
 52.4834, 13.4363, '030 8970 4421', 'info@hunde-in-not.de', 'https://www.hunde-in-not.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Hunderettung','Internationale Vermittlung','Transport','Pflegestellen'],
 ARRAY['tierschutz','hunde','international'], true, true),

('Naturschutzbund NABU – Tierschutz', 'tierschutz',
 'Engagiert sich fuer den Schutz heimischer Wildtiere und ihrer Lebensraeume in Deutschland.',
 'Charitéstrasse 3', '10117', 'Berlin', 'Berlin', 'DE',
 52.5289, 13.3828, '030 284 984-0', 'nabu@nabu.de', 'https://www.nabu.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Artenschutz','Lebensraumschutz','Wildtiere','Politisches Engagement'],
 ARRAY['tierschutz','nabu','naturschutz'], true, true),

-- ── ÖSTERREICH (12) ──────────────────────────────────────────────────────
('VIER PFOTEN Österreich', 'tierschutz',
 'Internationale Tierschutzorganisation mit oesterreichischem Hauptsitz – rettet Tiere unter direktem menschlichem Einfluss.',
 'Kumpfgasse 1–3', '1010', 'Wien', 'Wien', 'AT',
 48.2100, 16.3731, '+43 1 5854760', 'office@vier-pfoten.at', 'https://www.vier-pfoten.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Tierrettung','Kampagnen','Tierschutzpolitik','Wildtierschutz'],
 ARRAY['tierschutz','vierPfoten','oesterreich'], true, true),

('Tierschutz Austria e.V.', 'tierschutz',
 'Groesste oesterreichische Tierschutzorganisation mit Schwerpunkt auf Heimtiere und Farmtiere.',
 'Linzerstrasse 431', '3400', 'Klosterneuburg', 'Niederösterreich', 'AT',
 48.3065, 16.3248, '+43 2243 87003', 'info@tierschutz-austria.at', 'https://www.tierschutz-austria.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Tierschutz','Kampagnen','Lobbyarbeit','Massentierhaltung'],
 ARRAY['tierschutz','oesterreich'], true, true),

('WWF Österreich', 'tierschutz',
 'Weltgroesste Naturschutzorganisation – Wildtierschutz, Artenschutz und Lebensraumerhalt in Oesterreich.',
 'Ottakringer Str. 114–116', '1160', 'Wien', 'Wien', 'AT',
 48.2118, 16.3293, '+43 1 48817-0', 'wwf@wwf.at', 'https://www.wwf.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Artenschutz','Wildtierschutz','Naturschutz','Kampagnen'],
 ARRAY['tierschutz','wwf','wildtiere'], true, true),

('VGT – Verein gegen Tierfabriken Österreich', 'tierschutz',
 'Radikale Tierschutzorganisation mit Fokus auf Massentierhaltung, Jagd und Tierversuche.',
 'Würtzlerstrasse 3/6', '1030', 'Wien', 'Wien', 'AT',
 48.2032, 16.3893, '+43 1 929 14 98', 'vgt@vgt.at', 'https://www.vgt.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Kampagnen','Massentierhaltung','Tierversuche','Undercover'],
 ARRAY['tierschutz','tierrechte','oesterreich'], true, true),

('Oesterreichischer Tierschutzverein', 'tierschutz',
 'Bundesweiter Tierschutzverein mit Schwerpunkt auf Heimtiere, Wildtiere und Aufklaerung.',
 'Linzerstrasse 430', '3400', 'Klosterneuburg', 'Niederösterreich', 'AT',
 48.3060, 16.3244, '+43 2243 82930', 'info@oetsv.at', 'https://www.oetsv.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Tierschutz','Aufklaerung','Beratung','Lobbyarbeit'],
 ARRAY['tierschutz','oesterreich','bundesweit'], true, true),

('Wildtierhilfe Salzburg', 'tierschutz',
 'Aufnahme und Pflege verletzter Wildtiere im Bundesland Salzburg mit Auswilderungsstation.',
 'Kendlersiedlung 12', '5020', 'Salzburg', 'Salzburg', 'AT',
 47.7982, 13.0372, '+43 662 64 64 64', 'info@wildtierhilfe-salzburg.at', 'https://www.wildtierhilfe-salzburg.at',
 'Mo–So 9–18 Uhr',
 ARRAY['Wildtieraufnahme','Tiermedizin','Auswilderung','Beratung'],
 ARRAY['tierschutz','wildtiere','salzburg'], true, true),

('Tierschutzverein Niederösterreich', 'tierschutz',
 'Groesster niederoesterreichischer Tierschutzverein mit Kampagnen und Beratungsangeboten.',
 'Glanzingasse 10', '1190', 'Wien', 'Niederösterreich', 'AT',
 48.2400, 16.3502, '+43 2682 62553', 'info@tierschutz-noe.org', 'https://www.tierschutz-noe.org',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Tierschutz','Kampagnen','Beratung','Lobbyarbeit'],
 ARRAY['tierschutz','niederoesterreich'], true, true),

('Pfotenhilfe Österreich', 'tierschutz',
 'Rettungsorganisation fuer Hunde aus suedeuropaeischen Toetungsstationen mit Vermittlung nach Oesterreich.',
 'Schrottgasse 4', '4780', 'Schärding', 'Oberösterreich', 'AT',
 48.4568, 13.4374, '+43 7712 36 36', 'office@pfotenhilfe.at', 'https://www.pfotenhilfe.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Hunderettung','Internationale Vermittlung','Transport','Pflegestellen'],
 ARRAY['tierschutz','hunde','international'], true, true),

('Katzenhilfe Wien', 'tierschutz',
 'Vermittlung und Kastration von Streunerkatzen in Wien – ehrenamtliches Engagement.',
 'Lerchenfelder Strasse 65', '1070', 'Wien', 'Wien', 'AT',
 48.2072, 16.3490, '+43 1 526 89 44', 'info@katzenhilfe-wien.at', 'https://www.katzenhilfe-wien.at',
 'Mo–Fr 10–18 Uhr',
 ARRAY['Kastrationsprojekte','Katzenvermittlung','Pflegestellen','Streunerkatzen'],
 ARRAY['tierschutz','katzen','wien'], true, true),

('ARGE Wildtierhilfe Steiermark', 'tierschutz',
 'Auffangstation fuer verletzte Wildtiere in der Steiermark mit Auswilderungs- und Beratungsangebot.',
 'Halbenrainer Strasse 90', '8570', 'Voitsberg', 'Steiermark', 'AT',
 47.0467, 15.1421, '+43 3142 24 790', 'info@wildtierhilfe-stmk.at', 'https://www.wildtierhilfe-stmk.at',
 'Mo–So 9–18 Uhr',
 ARRAY['Wildtieraufnahme','Auswilderung','Beratung'],
 ARRAY['tierschutz','wildtiere','steiermark'], true, true),

('Tierschutzverein Tirol', 'tierschutz',
 'Tiroler Tierschutzverein mit politischer Interessenvertretung und Unterstuetzung des Tierheims.',
 'Amraser Strasse 5', '6020', 'Innsbruck', 'Tirol', 'AT',
 47.2648, 11.4116, '+43 512 584867', 'info@tierschutz-tirol.at', 'https://www.tierschutz-tirol.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Tierschutz','Kampagnen','Lobbyarbeit','Beratung'],
 ARRAY['tierschutz','tirol'], true, true),

('Naturfreunde Österreich – Tierschutz', 'tierschutz',
 'Naturschutz- und Tierschutzengagement der Naturfreunde Oesterreich fuer einheimische Wildtiere.',
 'Viktor-Adler-Platz 1', '1040', 'Wien', 'Wien', 'AT',
 48.1989, 16.3739, '+43 1 892 35 34', 'tierschutz@naturfreunde.at', 'https://www.naturfreunde.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Naturschutz','Wildtierschutz','Artenschutz','Aufklaerung'],
 ARRAY['tierschutz','naturschutz','oesterreich'], true, true),

-- ── SCHWEIZ (8) ──────────────────────────────────────────────────────────
('Schweizer Tierschutz STS', 'tierschutz',
 'Groesste Schweizer Tierschutzorganisation mit bundesweiten Kampagnen, Beratung und Lobbyarbeit.',
 'Dornacherstrasse 101', '4053', 'Basel', 'Basel-Stadt', 'CH',
 47.5415, 7.5887, '+41 61 365 99 99', 'sts@tierschutz.com', 'https://www.tierschutz.com',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Tierschutz','Kampagnen','Lobbyarbeit','Beratung'],
 ARRAY['tierschutz','schweiz','bundesweit'], true, true),

('WWF Schweiz', 'tierschutz',
 'Weltgroesste Naturschutzorganisation – Artenschutz, Wildtierschutz und Lebensraumerhalt in der Schweiz.',
 'Hohlstrasse 110', '8010', 'Zürich', 'Zürich', 'CH',
 47.3830, 8.5210, '+41 44 297 21 21', 'info@wwf.ch', 'https://www.wwf.ch',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Artenschutz','Wildtierschutz','Naturschutz','Kampagnen'],
 ARRAY['tierschutz','wwf','schweiz'], true, true),

('PETA Schweiz', 'tierschutz',
 'Tierrechtsorganisation PETA mit Schweizer Buero – Kampagnen gegen Tierausbeutung aller Art.',
 'Rothstrasse 56', '8057', 'Zürich', 'Zürich', 'CH',
 47.3989, 8.5368, '+41 44 350 10 10', 'info@peta.ch', 'https://www.peta.ch',
 'Mo–Fr 9–18 Uhr',
 ARRAY['Kampagnen','Tierrechte','Aufklaerung','Undercover'],
 ARRAY['tierschutz','tierrechte','peta'], true, true),

('TIER IM RECHT – Stiftung Schweiz', 'tierschutz',
 'Einzige Schweizer Organisation die Tierrechtsverfahren vor Gericht unterstuetzt und begleitet.',
 'Muellerstrasse 54', '8004', 'Zürich', 'Zürich', 'CH',
 47.3780, 8.5290, '+41 44 242 45 55', 'info@tierimrecht.ch', 'https://www.tierimrecht.org',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Rechtsberatung','Strafverfolgung','Tierschutzrecht','Kampagnen'],
 ARRAY['tierschutz','recht','schweiz'], true, true),

('Wildtierhilfe Zürich', 'tierschutz',
 'Auffangstation fuer verletzte Wildtiere im Raum Zuerich mit Auswilderung und Beratungsangebot.',
 'Zürichbergstrasse 42', '8044', 'Zürich', 'Zürich', 'CH',
 47.3840, 8.5692, '+41 44 252 02 45', 'info@wildtierhilfe-zuerich.ch', 'https://www.wildtierhilfe-zuerich.ch',
 'Mo–So 9–18 Uhr',
 ARRAY['Wildtieraufnahme','Tiermedizin','Auswilderung'],
 ARRAY['tierschutz','wildtiere','zuerich'], true, true),

('Tierschutzliga Schweiz', 'tierschutz',
 'Schweizer Tierschutzorganisation mit Fokus auf Farmtierschutz und vegetarische Ernaehrung.',
 'Hintere Bahnhofstrasse 6', '5001', 'Aarau', 'Aargau', 'CH',
 47.3922, 8.0397, '+41 62 822 45 55', 'info@tierschutzliga.ch', 'https://www.tierschutzliga.ch',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Farmtierschutz','Kampagnen','Aufklaerung','Lobbyarbeit'],
 ARRAY['tierschutz','farmtiere','schweiz'], true, true),

('Hund und Pferd Schweiz e.V.', 'tierschutz',
 'Tierschutzorganisation fuer Hunde und Pferde in der Schweiz mit Vermittlung und Gnadenhof.',
 'Gutshofstrasse 21', '8132', 'Egg', 'Zürich', 'CH',
 47.2888, 8.6947, '+41 44 984 36 21', 'info@hund-und-pferd.ch', 'https://www.hund-und-pferd.ch',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Tierschutz','Hundepflege','Pferderettung','Gnadenhof'],
 ARRAY['tierschutz','hunde','pferde'], true, true),

('Schweizer Vogelschutz SVS / BirdLife Schweiz', 'tierschutz',
 'Schutz der Schweizer Vogelwelt durch Monitoring, Artenschutz und Habitatpflege.',
 'Wiedingstrasse 78', '8040', 'Zürich', 'Zürich', 'CH',
 47.3637, 8.5257, '+41 44 457 70 20', 'svs@birdlife.ch', 'https://www.birdlife.ch',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Vogelschutz','Artenschutz','Monitoring','Habitatpflege'],
 ARRAY['tierschutz','voegel','naturschutz'], true, true)

ON CONFLICT DO NOTHING;

  END IF;
END $$;
