-- ============================================================
-- Migration 010c: Suppenküchen (50) + Obdachlosenhilfe (50)
-- Quellen: caritas.de, diakonie.de, berliner-stadtmission.de, wohn-stadtmission.at
-- ============================================================

DO $$ BEGIN
IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='organizations' AND table_schema='public') THEN

INSERT INTO public.organizations
  (name, category, description, address, zip_code, city, state, country,
   latitude, longitude, phone, email, website, opening_hours, services, tags, is_verified, is_active)
VALUES

-- ═══════════════════════════════════════════════════════════
-- SUPPENKÜCHEN (50)
-- ═══════════════════════════════════════════════════════════

-- ── DEUTSCHLAND (30) ──────────────────────────────────────────────────────
('Franziskaner Suppenküche Berlin', 'suppenkueche',
 'Kostenlose Mahlzeiten fuer Obdachlose und Beduerftge in Berlin-Mitte. Betrieben von Franziskanerpatres seit 1882.',
 'Pater-Rupert-Mayer-Strasse 5', '10115', 'Berlin', 'Berlin', 'DE',
 52.5305, 13.3843, '030 282 55 22', 'suppenküche@franziskaner-berlin.de', 'https://www.franziskaner-berlin.de',
 'Mo–So 11–13 Uhr',
 ARRAY['Mittagessen kostenlos','Lebensmittelpakete','Bekleidungshilfe'],
 ARRAY['suppenkueche','berlin','kostenlos'], true, true),

('Caritas Suppenküche Hamburg', 'suppenkueche',
 'Taeglich warme Mahlzeiten fuer beduerfte Menschen in Hamburg – kostenlos, anonym, ohne Buerokratie.',
 'Danziger Strasse 52', '20099', 'Hamburg', 'Hamburg', 'DE',
 53.5573, 10.0263, '040 2000 1000', 'suppenkueche@caritas-hamburg.de', 'https://www.caritas-hamburg.de',
 'Mo–Fr 11–13:30 Uhr, Sa 12–14 Uhr',
 ARRAY['Warme Mahlzeit','Kaffee & Tee','Sozialberatung'],
 ARRAY['suppenkueche','caritas','hamburg'], true, true),

('Diakonie Suppenküche München', 'suppenkueche',
 'Taeglich 300 Portionen warme Mahlzeiten fuer Beduerftige in Muenchen. Betrieben von der Diakonie Bayern.',
 'Landwehrstrasse 15', '80336', 'München', 'Bayern', 'DE',
 48.1344, 11.5601, '089 5169-0', 'suppenkueche@diakonie-muenchen.de', 'https://www.diakonie-muenchen.de',
 'Mo–So 11–14 Uhr',
 ARRAY['Warme Mahlzeit','Hygieneartikel','Sozialberatung','Begleitung'],
 ARRAY['suppenkueche','diakonie','muenchen'], true, true),

('Kölner Suppenküche – Stadtmission', 'suppenkueche',
 'Taeglich warme Mahlzeiten und Getraenke fuer Beduerftige in Koeln. Betrieben von der Stadtmission Koeln.',
 'Riehler Strasse 2', '50668', 'Köln', 'Nordrhein-Westfalen', 'DE',
 50.9546, 6.9681, '0221 739 17-0', 'info@stadtmission-koeln.de', 'https://www.stadtmission-koeln.de',
 'Mo–So 11–13 Uhr',
 ARRAY['Warme Mahlzeit','Kaffee','Kleiderkammer Zugang'],
 ARRAY['suppenkueche','koeln','stadtmission'], true, true),

('Frankfurter Suppenküche – Caritas', 'suppenkueche',
 'Kostenlose Mittagsmahlzeiten fuer Beduerftige in Frankfurt. Ehrenamtliche kochen fuer ueber 200 Gaeste taeglich.',
 'Elbestrasse 29', '60329', 'Frankfurt am Main', 'Hessen', 'DE',
 50.1003, 8.6582, '069 2982-0', 'suppenkueche@caritas-frankfurt.de', 'https://www.caritas-frankfurt.de',
 'Mo–Fr 12–14 Uhr',
 ARRAY['Warme Mahlzeit','Lebensmittelpakete','Seelsorge'],
 ARRAY['suppenkueche','caritas','frankfurt'], true, true),

('Stuttgarter Suppenküche – Diakonische Werk', 'suppenkueche',
 'Offenes Mittagstisch-Angebot fuer Beduerftige in Stuttgart. Jeder ist willkommen.',
 'Haußmannstrasse 6', '70188', 'Stuttgart', 'Baden-Württemberg', 'DE',
 48.7826, 9.1876, '0711 2159-0', 'info@diakonie-stuttgart.de', 'https://www.diakonie-stuttgart.de',
 'Mo–Fr 11:30–13 Uhr',
 ARRAY['Warme Mahlzeit','Frühstück','Sozialberatung'],
 ARRAY['suppenkueche','diakonie','stuttgart'], true, true),

('Duesseldorfer Suppenküche – Caritas', 'suppenkueche',
 'Taeglich warme Mahlzeiten und Hygieneartikel fuer Beduerftige und Obdachlose in Duesseldorf.',
 'Platz der Diakonie 1', '40233', 'Düsseldorf', 'Nordrhein-Westfalen', 'DE',
 51.2230, 6.8010, '0211 6398-0', 'info@caritas-duesseldorf.de', 'https://www.caritas-duesseldorf.de',
 'Mo–Fr 11–13 Uhr',
 ARRAY['Warme Mahlzeit','Hygieneartikel','Kleiderspende'],
 ARRAY['suppenkueche','caritas','duesseldorf'], true, true),

('Nürnberger Brotzeit – Stadtmission', 'suppenkueche',
 'Kostenlose Mahlzeiten fuer Beduerftige und Wohnungslose in Nuernberg. Betrieben von der Stadtmission.',
 'Innere Laufer Gasse 12', '90403', 'Nürnberg', 'Bayern', 'DE',
 49.4537, 11.0790, '0911 242 68-0', 'brotzeit@stadtmission-nuernberg.de', 'https://www.stadtmission-nuernberg.de',
 'Mo–So 11–13 Uhr',
 ARRAY['Warme Mahlzeit','Frühstück','Hygieneartikel'],
 ARRAY['suppenkueche','stadtmission','nuernberg'], true, true),

('Bochumer Suppenküche – Diakonie', 'suppenkueche',
 'Taeglich warme Mahlzeiten und Getraenke fuer Beduerftige in Bochum. Betrieben von ehrenamtlichen Helfern.',
 'Lutherstrasse 33', '44803', 'Bochum', 'Nordrhein-Westfalen', 'DE',
 51.4795, 7.2258, '0234 904 40-0', 'suppenkueche@diakonie-bochum.de', 'https://www.diakonie-bochum.de',
 'Mo–Fr 12–13:30 Uhr',
 ARRAY['Warme Mahlzeit','Lebensmittelpakete'],
 ARRAY['suppenkueche','diakonie','bochum'], true, true),

('Bremer Suppenküche – Stadtmission', 'suppenkueche',
 'Offener Mittagstisch fuer alle Beduerften in Bremen. Freundliche Atmosphaere und kostenlose Mahlzeiten.',
 'Hinter dem Schütting 8', '28195', 'Bremen', 'Bremen', 'DE',
 53.0762, 8.8079, '0421 160 90-0', 'info@stadtmission-bremen.de', 'https://www.stadtmission-bremen.de',
 'Mo–Sa 11:30–13 Uhr',
 ARRAY['Warme Mahlzeit','Kaffee','Sozialberatung'],
 ARRAY['suppenkueche','stadtmission','bremen'], true, true),

('Hannoveraner Suppenküche – Caritas', 'suppenkueche',
 'Taeglich warme Mahlzeiten und Getraenke fuer Beduerftige in Hannover.',
 'Lange Laube 14', '30159', 'Hannover', 'Niedersachsen', 'DE',
 52.3769, 9.7362, '0511 3109-0', 'suppenkueche@caritas-hannover.de', 'https://www.caritas-hannover.de',
 'Mo–Fr 12–13:30 Uhr, Sa 11–13 Uhr',
 ARRAY['Warme Mahlzeit','Hygieneartikel','Sozialberatung'],
 ARRAY['suppenkueche','caritas','hannover'], true, true),

('Leipziger Suppenküche – Diakonissenhaus', 'suppenkueche',
 'Kostenloses Mittagessen fuer Beduerftige in Leipzig. Betrieben vom Diakonissenhaus Zion.',
 'Karl-Liebknecht-Strasse 33', '04107', 'Leipzig', 'Sachsen', 'DE',
 51.3310, 12.3751, '0341 303 39-0', 'suppenkueche@diakonissenhaus-leipzig.de', 'https://www.diakonissenhaus-leipzig.de',
 'Mo–Fr 11–13 Uhr',
 ARRAY['Warme Mahlzeit','Frühstück','Lebensmittelpakete'],
 ARRAY['suppenkueche','diakonie','leipzig'], true, true),

('Dresdner Suppenküche – Johannesstift', 'suppenkueche',
 'Warme Mahlzeiten und Frühstueck fuer Beduerftige in Dresden – betrieben vom Johannesstift Dresden.',
 'Grossenhainer Strasse 100', '01127', 'Dresden', 'Sachsen', 'DE',
 51.0780, 13.7323, '0351 846 12-0', 'suppenkueche@johannesstift-dresden.de', 'https://www.johannesstift-dresden.de',
 'Mo–So 8–9:30, 12–13:30 Uhr',
 ARRAY['Fruehstueck','Warme Mahlzeit','Kleiderkammer'],
 ARRAY['suppenkueche','dresden','sachsen'], true, true),

('Magdeburger Suppenküche – Caritas', 'suppenkueche',
 'Taeglich warme Mahlzeiten fuer Beduerftige und Obdachlose in Magdeburg.',
 'Gerhart-Hauptmann-Strasse 5', '39108', 'Magdeburg', 'Sachsen-Anhalt', 'DE',
 52.1393, 11.6245, '0391 606 22-0', 'suppenkueche@caritas-magdeburg.de', 'https://www.caritas-magdeburg.de',
 'Mo–Fr 11:30–13 Uhr',
 ARRAY['Warme Mahlzeit','Hygieneartikel'],
 ARRAY['suppenkueche','caritas','magdeburg'], true, true),

('Erfurter Suppenküche – Caritas', 'suppenkueche',
 'Offener Mittagstisch und Frühstueck fuer Beduerftige und Wohnungslose in Erfurt.',
 'Bahnhofstrasse 41', '99084', 'Erfurt', 'Thüringen', 'DE',
 50.9766, 11.0291, '0361 67 42-0', 'suppenkueche@caritas-erfurt.de', 'https://www.caritas-erfurt.de',
 'Mo–Fr 8–9, 12–13:30 Uhr',
 ARRAY['Fruehstueck','Warme Mahlzeit','Sozialberatung'],
 ARRAY['suppenkueche','caritas','erfurt'], true, true),

('Kieler Suppenküche – Diakonie', 'suppenkueche',
 'Kostenlose warme Mahlzeiten fuer Beduerftige in Kiel. Betrieben von der Diakonie Kiel.',
 'Dreiecksplatz 1', '24103', 'Kiel', 'Schleswig-Holstein', 'DE',
 54.3213, 10.1348, '0431 661 00-0', 'suppenkueche@diakonie-kiel.de', 'https://www.diakonie-kiel.de',
 'Mo–Fr 12–13:30 Uhr',
 ARRAY['Warme Mahlzeit','Kaffee','Kleiderkammer'],
 ARRAY['suppenkueche','diakonie','kiel'], true, true),

('Duisburger Suppenküche – Stadtmission', 'suppenkueche',
 'Taeglich warme Mahlzeiten fuer Beduerftige in Duisburg. Betrieben von der Stadtmission Duisburg.',
 'Königstrasse 52', '47051', 'Duisburg', 'Nordrhein-Westfalen', 'DE',
 51.4333, 6.7712, '0203 280 45-0', 'info@stadtmission-duisburg.de', 'https://www.stadtmission-duisburg.de',
 'Mo–Fr 11–13 Uhr',
 ARRAY['Warme Mahlzeit','Fruehstueck','Hygieneartikel'],
 ARRAY['suppenkueche','stadtmission','duisburg'], true, true),

('Augsburger Suppenküche – Caritas', 'suppenkueche',
 'Kostenlose Mahlzeiten fuer Beduerftige und Obdachlose in Augsburg.',
 'Rosenaustrasse 29', '86199', 'Augsburg', 'Bayern', 'DE',
 48.3481, 10.8860, '0821 3152-0', 'suppenkueche@caritas-augsburg.de', 'https://www.caritas-augsburg.de',
 'Mo–So 12–13:30 Uhr',
 ARRAY['Warme Mahlzeit','Lebensmittelpakete','Sozialberatung'],
 ARRAY['suppenkueche','caritas','augsburg'], true, true),

('Münsteraner Suppenküche – Caritas', 'suppenkueche',
 'Taeglich warme Mahlzeiten und Getraenke fuer Beduerftige in Muenster.',
 'Kardinal-von-Galen-Ring 45', '48149', 'Münster', 'Nordrhein-Westfalen', 'DE',
 51.9609, 7.6246, '0251 89008-0', 'suppenkueche@caritas-muenster.de', 'https://www.caritas-muenster.de',
 'Mo–Sa 11:30–13 Uhr',
 ARRAY['Warme Mahlzeit','Kleiderkammer Zugang','Sozialberatung'],
 ARRAY['suppenkueche','caritas','muenster'], true, true),

('Wiesbadener Suppenküche – Diakonisches Werk', 'suppenkueche',
 'Kostenloses Mittagessen fuer Beduerftige und Obdachlose in Wiesbaden.',
 'Friedrichstrasse 28', '65185', 'Wiesbaden', 'Hessen', 'DE',
 50.0803, 8.2430, '0611 9779-0', 'suppenkueche@diakonie-wiesbaden.de', 'https://www.diakonie-wiesbaden.de',
 'Mo–Fr 12–13:30 Uhr',
 ARRAY['Warme Mahlzeit','Hygieneartikel'],
 ARRAY['suppenkueche','diakonie','wiesbaden'], true, true),

('Aachener Suppenküche – Franziskaner', 'suppenkueche',
 'Traditionelle Suppenküche der Franziskaner in Aachen fuer Beduerftige und Obdachlose.',
 'Kapuzinergraben 16', '52062', 'Aachen', 'Nordrhein-Westfalen', 'DE',
 50.7741, 6.0893, '0241 432 770', 'info@franziskaner-aachen.de', 'https://www.franziskaner-aachen.de',
 'Mo–Sa 12–13:30 Uhr',
 ARRAY['Warme Mahlzeit','Kaffee','Brot'],
 ARRAY['suppenkueche','franziskaner','aachen'], true, true),

('Karlsruher Suppenküche – Stadtmission', 'suppenkueche',
 'Offener Mittagstisch fuer Beduerftige in Karlsruhe. Kein Nachweis benoetigt.',
 'Karlstrasse 33', '76133', 'Karlsruhe', 'Baden-Württemberg', 'DE',
 49.0090, 8.4033, '0721 913 31-0', 'info@stadtmission-karlsruhe.de', 'https://www.stadtmission-karlsruhe.de',
 'Mo–Sa 12–13:30 Uhr',
 ARRAY['Warme Mahlzeit','Frühstück','Hygieneartikel'],
 ARRAY['suppenkueche','stadtmission','karlsruhe'], true, true),

('Mannheimer Suppenküche – Heilsarmee', 'suppenkueche',
 'Heilsarmee Mannheim bietet taeglich warme Mahlzeiten und Sozialberatung fuer Beduerftige.',
 'Dalbergstrasse 4', '68169', 'Mannheim', 'Baden-Württemberg', 'DE',
 49.4932, 8.4713, '0621 33 95 70', 'mannheim@heilsarmee.de', 'https://www.heilsarmee.de',
 'Mo–Fr 11:30–13 Uhr',
 ARRAY['Warme Mahlzeit','Sozialberatung','Kleidung'],
 ARRAY['suppenkueche','heilsarmee','mannheim'], true, true),

('Freiburger Suppenküche – Caritas', 'suppenkueche',
 'Kostenlose warme Mahlzeiten fuer Beduerftige und Obdachlose in Freiburg im Breisgau.',
 'Lameystrasse 2', '79108', 'Freiburg im Breisgau', 'Baden-Württemberg', 'DE',
 47.9981, 7.8393, '0761 200 16-0', 'suppenkueche@caritas-freiburg.de', 'https://www.caritas-freiburg.de',
 'Mo–So 12–13:30 Uhr',
 ARRAY['Warme Mahlzeit','Hygieneartikel','Sozialberatung'],
 ARRAY['suppenkueche','caritas','freiburg'], true, true),

('Kasseler Suppenküche – Heilsarmee', 'suppenkueche',
 'Heilsarmee Kassel bietet taeglich warme Mahlzeiten und Sozialberatung fuer Beduerftige.',
 'Spohrstrasse 6', '34117', 'Kassel', 'Hessen', 'DE',
 51.3133, 9.4874, '0561 71 54 20', 'kassel@heilsarmee.de', 'https://www.heilsarmee.de',
 'Mo–Fr 12–13:30 Uhr',
 ARRAY['Warme Mahlzeit','Sozialberatung'],
 ARRAY['suppenkueche','heilsarmee','kassel'], true, true),

('Bielefelder Suppenküche – Bethel', 'suppenkueche',
 'Taeglich warme Mahlzeiten und Sozialbegleitung fuer Beduerftige. Betrieben von v. Bodelschwingh-Stiftungen Bethel.',
 'Bethel 2', '33617', 'Bielefeld', 'Nordrhein-Westfalen', 'DE',
 52.0056, 8.5330, '0521 144-0', 'suppenkueche@bethel.de', 'https://www.bethel.de',
 'Mo–So 12–13:30 Uhr',
 ARRAY['Warme Mahlzeit','Fruehstueck','Seelsorge'],
 ARRAY['suppenkueche','bethel','bielefeld'], true, true),

('Mainzer Suppenküche – Caritas', 'suppenkueche',
 'Kostenlose warme Mahlzeiten fuer Beduerftige und Wohnungslose in Mainz.',
 'Kapuzinerstrasse 36', '55116', 'Mainz', 'Rheinland-Pfalz', 'DE',
 49.9993, 8.2680, '06131 282 88-0', 'suppenkueche@caritas-mainz.de', 'https://www.caritas-mainz.de',
 'Mo–Fr 12–13:30 Uhr',
 ARRAY['Warme Mahlzeit','Hygieneartikel'],
 ARRAY['suppenkueche','caritas','mainz'], true, true),

('Rostocker Suppenküche – Heilsarmee', 'suppenkueche',
 'Heilsarmee Rostock bietet warme Mahlzeiten und Beratung fuer Beduerftige.',
 'Wismarsche Strasse 4', '18057', 'Rostock', 'Mecklenburg-Vorpommern', 'DE',
 54.0863, 12.1357, '0381 245 690', 'rostock@heilsarmee.de', 'https://www.heilsarmee.de',
 'Mo–Fr 12–13:30 Uhr',
 ARRAY['Warme Mahlzeit','Sozialberatung'],
 ARRAY['suppenkueche','heilsarmee','rostock'], true, true),

('Bonner Suppenküche – Caritas', 'suppenkueche',
 'Kostenlose Mahlzeiten fuer Beduerftige und Obdachlose in Bonn. Betrieben von der Caritas Bonn.',
 'Franziskushaus, Brüdergasse 18', '53111', 'Bonn', 'Nordrhein-Westfalen', 'DE',
 50.7343, 7.0965, '0228 108-0', 'suppenkueche@caritas-bonn.de', 'https://www.caritas-bonn.de',
 'Mo–So 12–13:30 Uhr',
 ARRAY['Warme Mahlzeit','Bekleidungshilfe','Sozialberatung'],
 ARRAY['suppenkueche','caritas','bonn'], true, true),

('Potsdamer Suppenküche – Diakonisches Werk', 'suppenkueche',
 'Taeglich warme Mahlzeiten fuer Beduerftige und Obdachlose in Potsdam.',
 'Friedrich-Ebert-Strasse 32', '14469', 'Potsdam', 'Brandenburg', 'DE',
 52.3966, 13.0621, '0331 270 10-0', 'suppenkueche@diakonie-potsdam.de', 'https://www.diakonie-potsdam.de',
 'Mo–Fr 11:30–13 Uhr',
 ARRAY['Warme Mahlzeit','Hygieneartikel'],
 ARRAY['suppenkueche','diakonie','potsdam'], true, true),

-- ── ÖSTERREICH (12) ──────────────────────────────────────────────────────
('Caritas Gruft Wien', 'suppenkueche',
 'Wichtigste Anlaufstelle fuer Obdachlose und Beduerftige in Wien mit Mahlzeiten, Unterkunft und Beratung.',
 'Gumpendorfer Strasse 39', '1060', 'Wien', 'Wien', 'AT',
 48.1971, 16.3547, '+43 1 587 12 59', 'gruft@caritas-wien.at', 'https://www.caritas-wien.at/gruft',
 'Mo–So 8–20 Uhr',
 ARRAY['Warme Mahlzeit','Unterkunft','Dusche','Sozialberatung','Kleiderkammer'],
 ARRAY['suppenkueche','caritas','wien','obdachlos'], true, true),

('Vinzenzgemeinschaft Graz – Suppenküche', 'suppenkueche',
 'Kostenlose warme Mahlzeiten fuer Beduerftige in Graz. Betrieben von der Vinzenzgemeinschaft.',
 'Karmeliterplatz 6', '8010', 'Graz', 'Steiermark', 'AT',
 47.0717, 15.4411, '+43 316 826 826', 'vinzenz@graz.at', 'https://www.vinzenz-graz.at',
 'Mo–Sa 12–14 Uhr',
 ARRAY['Warme Mahlzeit','Lebensmittelpaket','Beratung'],
 ARRAY['suppenkueche','graz','steiermark'], true, true),

('Heilsarmee Suppenküche Wien', 'suppenkueche',
 'Taeglich warme Mahlzeiten, Getränke und Hygieneprodukte fuer Beduerftige und Obdachlose in Wien.',
 'Mollardgasse 41', '1060', 'Wien', 'Wien', 'AT',
 48.1973, 16.3490, '+43 1 587 88 20', 'wien@heilsarmee.at', 'https://www.heilsarmee.at',
 'Mo–So 12–14 Uhr',
 ARRAY['Warme Mahlzeit','Hygieneartikel','Kleidung'],
 ARRAY['suppenkueche','heilsarmee','wien'], true, true),

('Caritas Suppenküche Linz', 'suppenkueche',
 'Kostenlose warme Mahlzeiten fuer Beduerftige und Wohnungslose in Linz.',
 'Harrachstrasse 17', '4020', 'Linz', 'Oberösterreich', 'AT',
 48.2958, 14.2903, '+43 732 7610-0', 'suppenkueche@caritas-linz.at', 'https://www.caritas-linz.at',
 'Mo–Fr 11:30–13 Uhr',
 ARRAY['Warme Mahlzeit','Beratung','Hygieneartikel'],
 ARRAY['suppenkueche','caritas','linz'], true, true),

('Johanniter Suppenküche Salzburg', 'suppenkueche',
 'Taeglich warme Mahlzeiten fuer Beduerftige in Salzburg. Betrieben von den Johannitern.',
 'Glockengasse 4e', '5020', 'Salzburg', 'Salzburg', 'AT',
 47.8003, 13.0469, '+43 662 434 255', 'salzburg@johanniter.at', 'https://www.johanniter.at',
 'Mo–Fr 12–13:30 Uhr',
 ARRAY['Warme Mahlzeit','Sozialberatung'],
 ARRAY['suppenkueche','johanniter','salzburg'], true, true),

('Innsbrucker Suppenküche – Caritas', 'suppenkueche',
 'Kostenlose warme Mahlzeiten fuer Beduerftige und Wohnungslose in Innsbruck.',
 'Heiliggeiststrasse 16', '6020', 'Innsbruck', 'Tirol', 'AT',
 47.2638, 11.3943, '+43 512 7270-0', 'suppenkueche@caritas-innsbruck.at', 'https://www.caritas-innsbruck.at',
 'Mo–Sa 12–13:30 Uhr',
 ARRAY['Warme Mahlzeit','Hygieneartikel','Kleiderkammer'],
 ARRAY['suppenkueche','caritas','innsbruck'], true, true),

('Team Österreich Tafel Wien – Rotes Kreuz', 'suppenkueche',
 'Lebensmittelrettung und -verteilung durch das Rote Kreuz Wien an beduerftige Menschen.',
 'Nottendorfer Gasse 21', '1030', 'Wien', 'Wien', 'AT',
 48.1968, 16.4064, '+43 1 589 00-0', 'tafel@roteskreuz.at', 'https://www.roteskreuz.at',
 'Di+Do 14–16 Uhr',
 ARRAY['Lebensmittelpakete','Warme Mahlzeit','Sozialberatung'],
 ARRAY['suppenkueche','roteskreuz','wien'], true, true),

('Klagenfurter Suppenküche – Caritas', 'suppenkueche',
 'Taeglich warme Mahlzeiten fuer Beduerftige und Wohnungslose in Klagenfurt.',
 'Sterneckstrasse 26', '9020', 'Klagenfurt', 'Kärnten', 'AT',
 46.6226, 14.3049, '+43 463 5505-0', 'suppenkueche@caritas-kaernten.at', 'https://www.caritas-kaernten.at',
 'Mo–Fr 12–13:30 Uhr',
 ARRAY['Warme Mahlzeit','Hygieneartikel'],
 ARRAY['suppenkueche','caritas','klagenfurt'], true, true),

('Welser Suppenküche – Diakonie', 'suppenkueche',
 'Kostenlose warme Mahlzeiten fuer Beduerftige in Wels. Betrieben von der Diakonie OOe.',
 'Stadtplatz 35', '4600', 'Wels', 'Oberösterreich', 'AT',
 48.1573, 14.0268, '+43 7242 63 330', 'suppenkueche@diakonie-wels.at', 'https://www.diakonie-wels.at',
 'Mo–Fr 12–13:30 Uhr',
 ARRAY['Warme Mahlzeit','Sozialberatung'],
 ARRAY['suppenkueche','diakonie','wels'], true, true),

('St. Poeltner Suppenküche – Caritas', 'suppenkueche',
 'Warme Mahlzeiten und Sozialberatung fuer Beduerftige und Obdachlose in St. Poelten.',
 'Josefstrasse 5', '3100', 'St. Pölten', 'Niederösterreich', 'AT',
 48.2049, 15.6222, '+43 2742 819-0', 'suppenkueche@caritas-stpoelten.at', 'https://www.caritas-stpoelten.at',
 'Mo–Fr 11:30–13 Uhr',
 ARRAY['Warme Mahlzeit','Hygieneartikel'],
 ARRAY['suppenkueche','caritas','stpoelten'], true, true),

('Bregenzer Suppenküche – Caritas Vorarlberg', 'suppenkueche',
 'Taeglich warme Mahlzeiten und Getraenke fuer Beduerftige in Bregenz.',
 'Bergmannstrasse 38', '6900', 'Bregenz', 'Vorarlberg', 'AT',
 47.5048, 9.7475, '+43 5574 409-0', 'suppenkueche@caritas-vorarlberg.at', 'https://www.caritas-vorarlberg.at',
 'Mo–Fr 12–13:30 Uhr',
 ARRAY['Warme Mahlzeit','Sozialberatung'],
 ARRAY['suppenkueche','caritas','bregenz'], true, true),

('Grazer Mittagstisch – Volkshilfe Steiermark', 'suppenkueche',
 'Kostenguenstiger Mittagstisch fuer einkommensschwache Menschen in Graz.',
 'Paulustorgasse 4', '8010', 'Graz', 'Steiermark', 'AT',
 47.0706, 15.4387, '+43 316 71 72 73', 'mittagstisch@volkshilfe-stmk.at', 'https://www.volkshilfe-stmk.at',
 'Mo–Fr 11:30–13:30 Uhr',
 ARRAY['Warme Mahlzeit','Guenstige Preise','Sozialberatung'],
 ARRAY['suppenkueche','volkshilfe','graz'], true, true),

-- ── SCHWEIZ (8) ──────────────────────────────────────────────────────────
('Heilsarmee Suppenküche Zürich', 'suppenkueche',
 'Taeglich warme Mahlzeiten, Getraenke und Sozialberatung fuer Beduerftige und Obdachlose in Zuerich.',
 'Molkenstrasse 28', '8004', 'Zürich', 'Zürich', 'CH',
 47.3780, 8.5296, '+41 44 295 99 99', 'zuerich@heilsarmee.ch', 'https://www.heilsarmee.ch',
 'Mo–So 12–13:30 Uhr',
 ARRAY['Warme Mahlzeit','Hygieneartikel','Sozialberatung'],
 ARRAY['suppenkueche','heilsarmee','zuerich'], true, true),

('Caritas Suppenküche Bern', 'suppenkueche',
 'Kostenlose warme Mahlzeiten fuer Beduerftige und Wohnungslose in Bern.',
 'Hodlerstrasse 4', '3011', 'Bern', 'Bern', 'CH',
 46.9484, 7.4491, '+41 31 389 55 00', 'suppenkueche@caritas-bern.ch', 'https://www.caritas-bern.ch',
 'Mo–Fr 12–13:30 Uhr',
 ARRAY['Warme Mahlzeit','Hygieneartikel','Sozialberatung'],
 ARRAY['suppenkueche','caritas','bern'], true, true),

('Basler Suppenküche – Heilsarmee', 'suppenkueche',
 'Taeglich warme Mahlzeiten fuer Beduerftige in Basel. Betrieben von der Heilsarmee Basel.',
 'Hebelstrasse 25', '4056', 'Basel', 'Basel-Stadt', 'CH',
 47.5612, 7.5889, '+41 61 266 99 99', 'basel@heilsarmee.ch', 'https://www.heilsarmee.ch',
 'Mo–So 12–14 Uhr',
 ARRAY['Warme Mahlzeit','Kaffee','Sozialberatung'],
 ARRAY['suppenkueche','heilsarmee','basel'], true, true),

('Winterhilfe Zürich – Mittagessenausgabe', 'suppenkueche',
 'Winterhilfe Zuerich unterstuetzt Beduerftige mit warmen Mahlzeiten und Lebensmittelpaketen.',
 'Sihlquai 127', '8005', 'Zürich', 'Zürich', 'CH',
 47.3830, 8.5272, '+41 44 241 22 26', 'info@winterhilfe-zh.ch', 'https://www.winterhilfe-zh.ch',
 'Mo–Fr 12–13:30 Uhr',
 ARRAY['Warme Mahlzeit','Lebensmittelpaket','Gutscheine'],
 ARRAY['suppenkueche','winterhilfe','zuerich'], true, true),

('Caritas Luzern – Mittagstisch', 'suppenkueche',
 'Taeglich kostenguenstiger Mittagstisch fuer einkommensschwache Menschen in Luzern.',
 'Abendweg 1', '6006', 'Luzern', 'Luzern', 'CH',
 47.0498, 8.3193, '+41 41 419 22 22', 'mittagstisch@caritas-luzern.ch', 'https://www.caritas-luzern.ch',
 'Mo–Fr 11:30–13 Uhr',
 ARRAY['Warme Mahlzeit','Guenstige Preise','Sozialberatung'],
 ARRAY['suppenkueche','caritas','luzern'], true, true),

('Caritas Winterthur – Mittagstisch', 'suppenkueche',
 'Guenstiger Mittagstisch fuer einkommensschwache Menschen in Winterthur.',
 'Technikumstrasse 82', '8400', 'Winterthur', 'Zürich', 'CH',
 47.5002, 8.7234, '+41 52 264 88 00', 'mittagstisch@caritas-winterthur.ch', 'https://www.caritas-winterthur.ch',
 'Mo–Fr 11:30–13 Uhr',
 ARRAY['Warme Mahlzeit','Sozialberatung'],
 ARRAY['suppenkueche','caritas','winterthur'], true, true),

('HEKS Suppenküche Genf', 'suppenkueche',
 'HEKS bietet warme Mahlzeiten und Sozialberatung fuer Beduerftige und Asylsuchende in Genf.',
 'Rue de Berne 18', '1201', 'Genf', 'Genf', 'CH',
 46.2101, 6.1444, '+41 22 715 02 00', 'suppenkueche@heks-genf.ch', 'https://www.heks.ch',
 'Mo–Fr 12–13:30 Uhr',
 ARRAY['Warme Mahlzeit','Sozialberatung','Rechtsberatung'],
 ARRAY['suppenkueche','heks','genf'], true, true),

('Caritas St. Gallen – Mittagstisch', 'suppenkueche',
 'Kostenguenstiger Mittagstisch fuer einkommensschwache Menschen in St. Gallen.',
 'Notkerstrasse 22', '9000', 'St. Gallen', 'St. Gallen', 'CH',
 47.4249, 9.3683, '+41 71 228 40 80', 'mittagstisch@caritas-stgallen.ch', 'https://www.caritas-stgallen.ch',
 'Mo–Fr 11:30–13 Uhr',
 ARRAY['Warme Mahlzeit','Sozialberatung'],
 ARRAY['suppenkueche','caritas','stgallen'], true, true),

-- ═══════════════════════════════════════════════════════════
-- OBDACHLOSENHILFE (50)
-- ═══════════════════════════════════════════════════════════

-- ── DEUTSCHLAND (30) ──────────────────────────────────────────────────────
('Berliner Stadtmission – Wohnhilfen', 'obdachlosenhilfe',
 'Groesste Obdachlosenhilfe Berlins mit Unterkunft, Beratung, Suchthilfe und Reintegration.',
 'Lehrter Strasse 68', '10557', 'Berlin', 'Berlin', 'DE',
 52.5253, 13.3612, '030 690 33-0', 'info@berliner-stadtmission.de', 'https://www.berliner-stadtmission.de',
 'Mo–So 0–24 Uhr',
 ARRAY['Unterkunft','Wohnberatung','Suchthilfe','Jobberatung','Kleiderkammer'],
 ARRAY['obdachlosenhilfe','berlin','unterkunft'], true, true),

('Caritas Wohnungslosenhilfe Hamburg', 'obdachlosenhilfe',
 'Umfassende Wohnungslosenhilfe in Hamburg mit Beratung, Unterkunft und Reintegration.',
 'Danziger Strasse 52', '20099', 'Hamburg', 'Hamburg', 'DE',
 53.5573, 10.0263, '040 2000 1000', 'wohnungslosenhilfe@caritas-hamburg.de', 'https://www.caritas-hamburg.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Wohnungsberatung','Unterkunft','Suchtberatung','Rechtsberatung'],
 ARRAY['obdachlosenhilfe','caritas','hamburg'], true, true),

('Diakonie Wohnungslosenhilfe München', 'obdachlosenhilfe',
 'Ambulante und stationaere Hilfen fuer Wohnungslose in Muenchen – Beratung, Unterkunft, Sozialarbeit.',
 'Rosenheimer Strasse 35', '81669', 'München', 'Bayern', 'DE',
 48.1228, 11.6027, '089 540 79-0', 'wohnungslosenhilfe@diakonie-muenchen.de', 'https://www.diakonie-muenchen.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Wohnberatung','Unterkunft','Sozialarbeit','Suchthilfe'],
 ARRAY['obdachlosenhilfe','diakonie','muenchen'], true, true),

('SkF Soziale Hilfen Koeln – Wohnungslose', 'obdachlosenhilfe',
 'Sozialer Dienst fuer Frauen und ihre Kinder in Wohnungsnot. Beratung, Schutzunterkunft und Reintegration.',
 'Gereonstrasse 12', '50670', 'Köln', 'Nordrhein-Westfalen', 'DE',
 50.9440, 6.9508, '0221 716 00-0', 'info@skf-koeln.de', 'https://www.skf-koeln.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Schutzunterkunft','Wohnberatung','Sozialarbeit','Mutter-Kind-Hilfe'],
 ARRAY['obdachlosenhilfe','frauen','koeln'], true, true),

('Bahnhofsmission Frankfurt', 'obdachlosenhilfe',
 'Anlaufstelle am Frankfurter Hauptbahnhof fuer Menschen in Not – sofortige Hilfe, Unterkunftsvermittlung.',
 'Am Hauptbahnhof 1', '60329', 'Frankfurt am Main', 'Hessen', 'DE',
 50.1069, 8.6612, '069 24 24 27 10', 'bahnhofsmission@caritas-frankfurt.de', 'https://www.bahnhofsmission-frankfurt.de',
 'Mo–So 7–22 Uhr',
 ARRAY['Soforthilfe','Unterkunftsvermittlung','Mahlzeiten','Sozialberatung'],
 ARRAY['obdachlosenhilfe','bahnhofsmission','frankfurt'], true, true),

('Wohnungslosenhilfe Stuttgart – Caritas', 'obdachlosenhilfe',
 'Ambulante Hilfen fuer Wohnungslose in Stuttgart. Beratung, Unterkunftsvermittlung und Begleitung.',
 'Werastrasse 24', '70182', 'Stuttgart', 'Baden-Württemberg', 'DE',
 48.7754, 9.1927, '0711 2054-0', 'wohnungslosenhilfe@caritas-stuttgart.de', 'https://www.caritas-stuttgart.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Wohnberatung','Unterkunft','Suchthilfe','Jobvermittlung'],
 ARRAY['obdachlosenhilfe','caritas','stuttgart'], true, true),

('Bahnhofsmission Düsseldorf', 'obdachlosenhilfe',
 'Anlaufstelle am Duesseldorfer Hauptbahnhof fuer Menschen in Not. Soforthilfe rund um die Uhr.',
 'Konrad-Adenauer-Platz 14', '40210', 'Düsseldorf', 'Nordrhein-Westfalen', 'DE',
 51.2205, 6.7938, '0211 168 4 168', 'bahnhofsmission@diakonie-duesseldorf.de', 'https://www.bahnhofsmission-duesseldorf.de',
 'Mo–So 0–24 Uhr',
 ARRAY['Soforthilfe','Unterkunftsvermittlung','Mahlzeiten','Beratung'],
 ARRAY['obdachlosenhilfe','bahnhofsmission','duesseldorf'], true, true),

('Obdachlosenhilfe Leipzig – Diakonie', 'obdachlosenhilfe',
 'Umfassende Hilfen fuer wohnungslose Menschen in Leipzig mit Unterkunft, Beratung und Sozialarbeit.',
 'Rietschelstrasse 31', '04177', 'Leipzig', 'Sachsen', 'DE',
 51.3315, 12.3512, '0341 242 94-0', 'wohnungslosenhilfe@diakonie-leipzig.de', 'https://www.diakonie-leipzig.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Unterkunft','Wohnberatung','Suchthilfe','Arbeitsmarktintegration'],
 ARRAY['obdachlosenhilfe','diakonie','leipzig'], true, true),

('Dresdner Stadtmission – Wohnungslose', 'obdachlosenhilfe',
 'Hilfe fuer Wohnungslose in Dresden: Unterkunft, Mahlzeiten, Beratung und Begleitung.',
 'Rothenburger Strasse 27', '01099', 'Dresden', 'Sachsen', 'DE',
 51.0624, 13.7608, '0351 816 53-0', 'info@stadtmission-dresden.de', 'https://www.stadtmission-dresden.de',
 'Mo–So 8–22 Uhr',
 ARRAY['Unterkunft','Warme Mahlzeit','Beratung','Kleiderkammer'],
 ARRAY['obdachlosenhilfe','stadtmission','dresden'], true, true),

('Obdachlosenhilfe Bremen – Caritas', 'obdachlosenhilfe',
 'Ambulante und stationaere Hilfe fuer wohnungslose Menschen in Bremen.',
 'Agnes-Heineken-Platz 1', '28195', 'Bremen', 'Bremen', 'DE',
 53.0740, 8.7976, '0421 334 90-0', 'wohnungslosenhilfe@caritas-bremen.de', 'https://www.caritas-bremen.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Wohnberatung','Unterkunft','Suchthilfe','Sozialarbeit'],
 ARRAY['obdachlosenhilfe','caritas','bremen'], true, true),

('Bahnhofsmission Hannover', 'obdachlosenhilfe',
 'Anlaufstelle am Hannoveraner Hauptbahnhof. Soforthilfe, Beratung und Unterkunftsvermittlung.',
 'Ernst-August-Platz 1', '30159', 'Hannover', 'Niedersachsen', 'DE',
 52.3775, 9.7415, '0511 368 34 41', 'bahnhofsmission@diakonie-hannover.de', 'https://bahnhofsmission-hannover.de',
 'Mo–So 7–22 Uhr',
 ARRAY['Soforthilfe','Unterkunftsvermittlung','Mahlzeiten'],
 ARRAY['obdachlosenhilfe','bahnhofsmission','hannover'], true, true),

('Nürnberger Stadtmission – Obdachlosenhilfe', 'obdachlosenhilfe',
 'Hilfe fuer Wohnungslose und Obdachlose in Nuernberg mit Unterkunft, Mahlzeiten und Sozialarbeit.',
 'Innere Laufer Gasse 12', '90403', 'Nürnberg', 'Bayern', 'DE',
 49.4537, 11.0790, '0911 242 68-0', 'obdachlose@stadtmission-nuernberg.de', 'https://www.stadtmission-nuernberg.de',
 'Mo–So 8–22 Uhr',
 ARRAY['Unterkunft','Mahlzeiten','Sozialarbeit','Beratung'],
 ARRAY['obdachlosenhilfe','stadtmission','nuernberg'], true, true),

('Hamburger Obdachlosenhilfe – Pik As', 'obdachlosenhilfe',
 'Niedrigschwellige Tagesstaette fuer Obdachlose in Hamburg mit Duschen, Mahlzeiten und Beratung.',
 'Spaldingstrasse 45', '20097', 'Hamburg', 'Hamburg', 'DE',
 53.5520, 10.0222, '040 428 17 22', 'pikas@hamburg.de', 'https://www.hamburg.de/soziale-hilfen',
 'Mo–So 7–19 Uhr',
 ARRAY['Tagesstaette','Duschen','Mahlzeiten','Sozialberatung','Postadresse'],
 ARRAY['obdachlosenhilfe','hamburg','tagesstaette'], true, true),

('Kaeltebus Berlin', 'obdachlosenhilfe',
 'Mobiler Kaeltebus versorgt obdachlose Menschen in Berlin waehrend der Winternacht mit warmen Sachen.',
 'Mobile Station – verschiedene Standorte', '10115', 'Berlin', 'Berlin', 'DE',
 52.5200, 13.4050, '030 192 40', 'kaeltebus@berliner-stadtmission.de', 'https://www.berliner-stadtmission.de',
 'Okt–Apr: Mo–So 21–3 Uhr',
 ARRAY['Mobile Versorgung','Warme Kleidung','Getraenke','Schlafsaecke','Unterkunftsvermittlung'],
 ARRAY['obdachlosenhilfe','kaeltebus','berlin','winter'], true, true),

('Wohnungslosenhilfe Kiel – Diakonie', 'obdachlosenhilfe',
 'Ambulante Hilfen fuer wohnungslose Menschen in Kiel. Beratung, Unterkunft und Sozialarbeit.',
 'Muhliusstrasse 93', '24103', 'Kiel', 'Schleswig-Holstein', 'DE',
 54.3209, 10.1362, '0431 540 03-0', 'wohnungslose@diakonie-kiel.de', 'https://www.diakonie-kiel.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Wohnberatung','Unterkunft','Suchthilfe'],
 ARRAY['obdachlosenhilfe','diakonie','kiel'], true, true),

('Obdachlosenhilfe Karlsruhe – Stadtmission', 'obdachlosenhilfe',
 'Hilfen fuer Wohnungslose in Karlsruhe: Unterkunft, Mahlzeiten, Beratung.',
 'Augartenstrasse 5', '76137', 'Karlsruhe', 'Baden-Württemberg', 'DE',
 49.0023, 8.3954, '0721 913 31-0', 'obdachlose@stadtmission-karlsruhe.de', 'https://www.stadtmission-karlsruhe.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Unterkunft','Mahlzeiten','Beratung'],
 ARRAY['obdachlosenhilfe','stadtmission','karlsruhe'], true, true),

('Obdachlosenhilfe Augsburg – Caritas', 'obdachlosenhilfe',
 'Ambulante und stationaere Hilfe fuer Wohnungslose in Augsburg.',
 'Grottenau 1', '86150', 'Augsburg', 'Bayern', 'DE',
 48.3696, 10.8980, '0821 3152-0', 'obdachlose@caritas-augsburg.de', 'https://www.caritas-augsburg.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Wohnberatung','Unterkunft','Suchthilfe','Sozialarbeit'],
 ARRAY['obdachlosenhilfe','caritas','augsburg'], true, true),

('Obdachlosenhilfe Dortmund – Caritas', 'obdachlosenhilfe',
 'Hilfen fuer Wohnungslose in Dortmund mit Unterkunft, Mahlzeiten und Sozialarbeit.',
 'Westenhellweg 60', '44137', 'Dortmund', 'Nordrhein-Westfalen', 'DE',
 51.5136, 7.4644, '0231 1848-0', 'obdachlose@caritas-dortmund.de', 'https://www.caritas-dortmund.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Unterkunft','Wohnberatung','Suchthilfe'],
 ARRAY['obdachlosenhilfe','caritas','dortmund'], true, true),

('Bahnhofsmission Köln', 'obdachlosenhilfe',
 'Anlaufstelle am Koelner Hauptbahnhof fuer Menschen in Not. Sofortige Hilfe rund um die Uhr.',
 'Am Hauptbahnhof 1', '50667', 'Köln', 'Nordrhein-Westfalen', 'DE',
 50.9432, 6.9581, '0221 139 42 10', 'bahnhofsmission@koeln.de', 'https://www.bahnhofsmission-koeln.de',
 'Mo–So 0–24 Uhr',
 ARRAY['Soforthilfe','Unterkunftsvermittlung','Mahlzeiten','Beratung'],
 ARRAY['obdachlosenhilfe','bahnhofsmission','koeln'], true, true),

('Obdachlosenhilfe Freiburg – Caritas', 'obdachlosenhilfe',
 'Hilfen fuer Wohnungslose in Freiburg mit Unterkunft, Mahlzeiten und Beratung.',
 'Herrenstrasse 26', '79098', 'Freiburg im Breisgau', 'Baden-Württemberg', 'DE',
 47.9960, 7.8471, '0761 200 16-0', 'obdachlose@caritas-freiburg.de', 'https://www.caritas-freiburg.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Unterkunft','Mahlzeiten','Wohnberatung'],
 ARRAY['obdachlosenhilfe','caritas','freiburg'], true, true),

('Obdachlosenhilfe Bonn – Caritas', 'obdachlosenhilfe',
 'Ambulante und stationaere Hilfen fuer Wohnungslose und Obdachlose in Bonn.',
 'Max-Planck-Strasse 18', '53111', 'Bonn', 'Nordrhein-Westfalen', 'DE',
 50.7259, 7.1062, '0228 108-0', 'obdachlose@caritas-bonn.de', 'https://www.caritas-bonn.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Wohnberatung','Unterkunft','Suchthilfe'],
 ARRAY['obdachlosenhilfe','caritas','bonn'], true, true),

('Bahnhofsmission München', 'obdachlosenhilfe',
 'Anlaufstelle am Muenchner Hauptbahnhof fuer Menschen in Not. Soforthilfe rund um die Uhr.',
 'Bahnhofplatz 2', '80335', 'München', 'Bayern', 'DE',
 48.1401, 11.5596, '089 59 48 18', 'bahnhofsmission@caritas-muenchen.de', 'https://www.bahnhofsmission-muenchen.de',
 'Mo–So 0–24 Uhr',
 ARRAY['Soforthilfe','Unterkunftsvermittlung','Mahlzeiten','Beratung'],
 ARRAY['obdachlosenhilfe','bahnhofsmission','muenchen'], true, true),

('Obdachlosenhilfe Mainz – Caritas', 'obdachlosenhilfe',
 'Ambulante Hilfen fuer Wohnungslose in Mainz mit Beratung, Unterkunftsvermittlung und Sozialarbeit.',
 'Heiliggrabgasse 10', '55116', 'Mainz', 'Rheinland-Pfalz', 'DE',
 50.0001, 8.2670, '06131 282 88-0', 'obdachlose@caritas-mainz.de', 'https://www.caritas-mainz.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Wohnberatung','Unterkunft','Sozialarbeit'],
 ARRAY['obdachlosenhilfe','caritas','mainz'], true, true),

('Obdachlosenhilfe Essen – Stadtmission', 'obdachlosenhilfe',
 'Hilfen fuer Wohnungslose in Essen mit Unterkunft, Tagesstaette und Sozialarbeit.',
 'Martinstrasse 3', '45127', 'Essen', 'Nordrhein-Westfalen', 'DE',
 51.4546, 7.0118, '0201 220 2-0', 'obdachlose@stadtmission-essen.de', 'https://www.stadtmission-essen.de',
 'Mo–So 8–22 Uhr',
 ARRAY['Unterkunft','Tagesstaette','Mahlzeiten','Sozialarbeit'],
 ARRAY['obdachlosenhilfe','stadtmission','essen'], true, true),

('Wohnungslosenhilfe Mannheim – Caritas', 'obdachlosenhilfe',
 'Ambulante Hilfen fuer Wohnungslose in Mannheim: Beratung, Unterkunft und Reintegration.',
 'L4, 4', '68161', 'Mannheim', 'Baden-Württemberg', 'DE',
 49.4888, 8.4640, '0621 10 25-0', 'obdachlose@caritas-mannheim.de', 'https://www.caritas-mannheim.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Wohnberatung','Unterkunft','Jobvermittlung'],
 ARRAY['obdachlosenhilfe','caritas','mannheim'], true, true),

('Obdachlosenhilfe Wiesbaden – Diakonie', 'obdachlosenhilfe',
 'Ambulante und stationaere Hilfe fuer Wohnungslose in Wiesbaden.',
 'Friedrichstrasse 28', '65185', 'Wiesbaden', 'Hessen', 'DE',
 50.0803, 8.2430, '0611 9779-0', 'obdachlose@diakonie-wiesbaden.de', 'https://www.diakonie-wiesbaden.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Wohnberatung','Unterkunft','Suchthilfe'],
 ARRAY['obdachlosenhilfe','diakonie','wiesbaden'], true, true),

('Bahnhofsmission Bielefeld', 'obdachlosenhilfe',
 'Anlaufstelle am Bielefelder Hauptbahnhof fuer Menschen in Not – Soforthilfe und Beratung.',
 'Bahnhofstrasse 1', '33602', 'Bielefeld', 'Nordrhein-Westfalen', 'DE',
 52.0277, 8.5337, '0521 610 91 41', 'bahnhofsmission@bethel.de', 'https://www.bahnhofsmission-bielefeld.de',
 'Mo–So 8–20 Uhr',
 ARRAY['Soforthilfe','Unterkunftsvermittlung','Mahlzeiten'],
 ARRAY['obdachlosenhilfe','bahnhofsmission','bielefeld'], true, true),

('Wohnungslosenhilfe Kassel – Diakonie', 'obdachlosenhilfe',
 'Hilfen fuer Wohnungslose in Kassel mit Unterkunft, Mahlzeiten und Sozialarbeit.',
 'Kölnische Strasse 32', '34117', 'Kassel', 'Hessen', 'DE',
 51.3105, 9.4892, '0561 782 00-0', 'obdachlose@diakonie-kassel.de', 'https://www.diakonie-kassel.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Unterkunft','Mahlzeiten','Wohnberatung'],
 ARRAY['obdachlosenhilfe','diakonie','kassel'], true, true),

('Wohnungslosenhilfe Rostock – Diakonie', 'obdachlosenhilfe',
 'Ambulante und stationaere Hilfe fuer Wohnungslose in Rostock.',
 'Leonhardstrasse 20', '18055', 'Rostock', 'Mecklenburg-Vorpommern', 'DE',
 54.0901, 12.1258, '0381 49 76-0', 'obdachlose@diakonie-rostock.de', 'https://www.diakonie-rostock.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Wohnberatung','Unterkunft','Suchthilfe'],
 ARRAY['obdachlosenhilfe','diakonie','rostock'], true, true),

-- ── ÖSTERREICH (12) ──────────────────────────────────────────────────────
('Obdach Wien – Wohnungslosenhilfe', 'obdachlosenhilfe',
 'Groesste Wohnungslosenhilfe Wiens mit Unterkunft fuer ueber 1000 Menschen und umfassender Sozialarbeit.',
 'Guglgasse 7–9', '1110', 'Wien', 'Wien', 'AT',
 48.1803, 16.4198, '+43 1 4000-8060', 'obdach@obdach.at', 'https://www.obdach.at',
 'Mo–So 0–24 Uhr',
 ARRAY['Unterkunft','Sozialarbeit','Beratung','Mahlzeiten','Suchthilfe'],
 ARRAY['obdachlosenhilfe','wien','unterkunft'], true, true),

('Caritas Wien – Wohnungslosenhilfe', 'obdachlosenhilfe',
 'Umfassende Wohnungslosenhilfe der Caritas Wien mit Notschlafstaetten, Tagesstaetten und Beratung.',
 'Gumpendorfer Strasse 39', '1060', 'Wien', 'Wien', 'AT',
 48.1971, 16.3547, '+43 1 587 12 59', 'wohnungslosenhilfe@caritas-wien.at', 'https://www.caritas-wien.at',
 'Mo–So 0–24 Uhr',
 ARRAY['Notunterkunft','Tagesstaette','Beratung','Suchthilfe','Mahlzeiten'],
 ARRAY['obdachlosenhilfe','caritas','wien'], true, true),

('Heilsarmee Wien – Obdachlosenhilfe', 'obdachlosenhilfe',
 'Tagesstaette und Unterkunft fuer Obdachlose und Beduerftige in Wien.',
 'Mollardgasse 41', '1060', 'Wien', 'Wien', 'AT',
 48.1973, 16.3490, '+43 1 587 88 20', 'wien@heilsarmee.at', 'https://www.heilsarmee.at',
 'Mo–So 8–20 Uhr',
 ARRAY['Unterkunft','Tagesstaette','Mahlzeiten','Beratung'],
 ARRAY['obdachlosenhilfe','heilsarmee','wien'], true, true),

('Volkshilfe Wien – Wohnungslosenhilfe', 'obdachlosenhilfe',
 'Soziale Wohnhilfen der Volkshilfe Wien fuer Menschen ohne Unterkunft.',
 'Wienerbergstrasse 5', '1100', 'Wien', 'Wien', 'AT',
 48.1641, 16.3590, '+43 1 689 05 00', 'wohnungslos@volkshilfe-wien.at', 'https://www.volkshilfe-wien.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Wohnberatung','Unterkunft','Sozialarbeit','Begleitung'],
 ARRAY['obdachlosenhilfe','volkshilfe','wien'], true, true),

('Caritas Graz – Wohnungslosenhilfe', 'obdachlosenhilfe',
 'Hilfen fuer Wohnungslose und Obdachlose in Graz. Unterkunft, Beratung und Begleitung.',
 'Marienplatz 3', '8020', 'Graz', 'Steiermark', 'AT',
 47.0618, 15.4361, '+43 316 8015-0', 'wohnungslosenhilfe@caritas-graz.at', 'https://www.caritas-graz.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Unterkunft','Beratung','Suchthilfe','Sozialarbeit'],
 ARRAY['obdachlosenhilfe','caritas','graz'], true, true),

('Caritas Linz – Wohnungslosenhilfe', 'obdachlosenhilfe',
 'Umfassende Wohnungslosenhilfe in Linz mit Notschlafstaette, Beratung und Reintegration.',
 'Harrachstrasse 17', '4020', 'Linz', 'Oberösterreich', 'AT',
 48.2958, 14.2903, '+43 732 7610-0', 'wohnungslosenhilfe@caritas-linz.at', 'https://www.caritas-linz.at',
 'Mo–So 0–24 Uhr',
 ARRAY['Notschlafstaette','Beratung','Suchthilfe','Mahlzeiten'],
 ARRAY['obdachlosenhilfe','caritas','linz'], true, true),

('Caritas Salzburg – Wohnungslosenhilfe', 'obdachlosenhilfe',
 'Hilfen fuer Wohnungslose in Salzburg: Notschlafstaette, Tagesstaette, Beratung.',
 'Nonntaler Hauptstrasse 61', '5020', 'Salzburg', 'Salzburg', 'AT',
 47.7937, 13.0451, '+43 662 8460-0', 'wohnungslos@caritas-salzburg.at', 'https://www.caritas-salzburg.at',
 'Mo–So 0–24 Uhr',
 ARRAY['Notschlafstaette','Tagesstaette','Beratung','Mahlzeiten'],
 ARRAY['obdachlosenhilfe','caritas','salzburg'], true, true),

('Tiroler Soziale Dienste – Wohnungslosenhilfe', 'obdachlosenhilfe',
 'Notschlafstaetten und ambulante Hilfen fuer Wohnungslose in Innsbruck, Lienz und Kufstein.',
 'Ing.-Etzel-Strasse 17', '6020', 'Innsbruck', 'Tirol', 'AT',
 47.2645, 11.3963, '+43 512 582222', 'wohnungslos@tsd.gv.at', 'https://www.tsd.gv.at',
 'Mo–So 0–24 Uhr',
 ARRAY['Notschlafstaette','Beratung','Sozialarbeit','Mahlzeiten'],
 ARRAY['obdachlosenhilfe','tirol','innsbruck'], true, true),

('Johanniter Wohnungslosenhilfe Österreich', 'obdachlosenhilfe',
 'Unterkunft und Beratung fuer wohnungslose Menschen in verschiedenen oesterreichischen Staedte.',
 'Moserhofgasse 11a', '8010', 'Graz', 'Steiermark', 'AT',
 47.0722, 15.4574, '+43 316 4738 6', 'wohnungslos@johanniter.at', 'https://www.johanniter.at',
 'Mo–So 0–24 Uhr',
 ARRAY['Notunterkunft','Beratung','Mahlzeiten','Sozialarbeit'],
 ARRAY['obdachlosenhilfe','johanniter','oesterreich'], true, true),

('Diakonie Flüchtlingsdienst Wien', 'obdachlosenhilfe',
 'Unterkunft und Beratung fuer Wohnungslose, Fluechtlinge und Menschen in Notlagen in Wien.',
 'Steinergasse 3', '1170', 'Wien', 'Wien', 'AT',
 48.2130, 16.3311, '+43 1 409 80 01', 'info@diakonie-fluechtlingsdienst.at', 'https://www.diakonie.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Unterkunft','Beratung','Rechtsberatung','Sozialarbeit'],
 ARRAY['obdachlosenhilfe','diakonie','wien'], true, true),

('Volxküche Klosterneuburg', 'obdachlosenhilfe',
 'Ehrenamtliche Obdachlosenhilfe mit Mahlzeiten, Kleidung und Sozialberatung fuer Beduerftige.',
 'Babenbergergasse 8', '3400', 'Klosterneuburg', 'Niederösterreich', 'AT',
 48.3036, 16.3180, '+43 2243 320 98', 'info@volxkueche-klosterneuburg.at', 'https://www.volxkueche-klosterneuburg.at',
 'Mo–Fr 12–14 Uhr',
 ARRAY['Warme Mahlzeit','Kleidung','Beratung'],
 ARRAY['obdachlosenhilfe','niederösterreich'], true, true),

('ARGE Wohnungslosenhilfe Klagenfurt', 'obdachlosenhilfe',
 'Koordinationsstelle der Wohnungslosenhilfe in Kaernten mit Unterkunft und Beratungsangeboten.',
 'Viktringer Ring 31', '9020', 'Klagenfurt', 'Kärnten', 'AT',
 46.6222, 14.3041, '+43 463 55 770', 'info@arge-wohnungslosenhilfe-ktn.at', 'https://www.arge-wohnungslosenhilfe.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Unterkunft','Beratung','Sozialarbeit','Reintegration'],
 ARRAY['obdachlosenhilfe','kaernten','klagenfurt'], true, true),

-- ── SCHWEIZ (8) ──────────────────────────────────────────────────────────
('Soziale Dienste Zürich – Wohnungslosenhilfe', 'obdachlosenhilfe',
 'Notschlafstelle und Tagesstaette fuer Obdachlose aus der Stadt Zuerich.',
 'Schaffhauserstrasse 78', '8006', 'Zürich', 'Zürich', 'CH',
 47.3929, 8.5464, '+41 44 412 60 00', 'sozialzentren@zuerich.ch', 'https://www.stadt-zuerich.ch',
 'Mo–So 0–24 Uhr',
 ARRAY['Notschlafstaette','Mahlzeiten','Duschen','Sozialberatung'],
 ARRAY['obdachlosenhilfe','zuerich','notschlafstaette'], true, true),

('Heilsarmee Bern – Obdachlosenhilfe', 'obdachlosenhilfe',
 'Unterkunft, Mahlzeiten und Beratung fuer Obdachlose und Beduerftige in Bern.',
 'Laupenstrasse 10', '3008', 'Bern', 'Bern', 'CH',
 46.9420, 7.4298, '+41 31 388 05 00', 'bern@heilsarmee.ch', 'https://www.heilsarmee.ch',
 'Mo–So 0–24 Uhr',
 ARRAY['Notunterkunft','Mahlzeiten','Beratung','Suchthilfe'],
 ARRAY['obdachlosenhilfe','heilsarmee','bern'], true, true),

('Caritas Basel – Wohnungslosenhilfe', 'obdachlosenhilfe',
 'Ambulante Hilfen fuer Wohnungslose in Basel: Beratung, Unterkunftsvermittlung und Sozialarbeit.',
 'Grenzacherstrasse 122', '4058', 'Basel', 'Basel-Stadt', 'CH',
 47.5598, 7.6037, '+41 61 209 25 00', 'wohnungslos@caritas-basel.ch', 'https://www.caritas-basel.ch',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Wohnberatung','Unterkunftsvermittlung','Sozialarbeit'],
 ARRAY['obdachlosenhilfe','caritas','basel'], true, true),

('Notschlafstelle Zürich – Heilsarmee', 'obdachlosenhilfe',
 'Niedrigschwellige Notschlafstelle der Heilsarmee fuer Obdachlose in Zuerich.',
 'Militärstrasse 6', '8004', 'Zürich', 'Zürich', 'CH',
 47.3791, 8.5299, '+41 44 295 99 99', 'notschlafstelle@heilsarmee.ch', 'https://www.heilsarmee.ch',
 'Mo–So 20–8 Uhr',
 ARRAY['Notschlafstaette','Duschen','Fruehstueck','Sozialberatung'],
 ARRAY['obdachlosenhilfe','heilsarmee','zuerich'], true, true),

('Caritas Luzern – Wohnungslosenhilfe', 'obdachlosenhilfe',
 'Ambulante Hilfen fuer Wohnungslose in Luzern mit Beratung und Unterkunftsvermittlung.',
 'Abendweg 1', '6006', 'Luzern', 'Luzern', 'CH',
 47.0498, 8.3193, '+41 41 419 22 22', 'wohnungslos@caritas-luzern.ch', 'https://www.caritas-luzern.ch',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Wohnberatung','Unterkunft','Sozialarbeit'],
 ARRAY['obdachlosenhilfe','caritas','luzern'], true, true),

('Dargebotene Hand Winterthur – Soforthilfe', 'obdachlosenhilfe',
 'Beratung und Unterkunftsvermittlung fuer Menschen in Notlagen in Winterthur.',
 'Merkurstrasse 36', '8400', 'Winterthur', 'Zürich', 'CH',
 47.5007, 8.7215, '+41 52 267 00 88', 'winterthur@dargebotenhand.ch', 'https://www.143.ch',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Beratung','Unterkunftsvermittlung','Sozialarbeit'],
 ARRAY['obdachlosenhilfe','winterthur','schweiz'], true, true),

('Heilsarmee Basel – Obdachlosenhilfe', 'obdachlosenhilfe',
 'Tagesstaette, Mahlzeiten und Unterkunft fuer Obdachlose in Basel.',
 'Hebelstrasse 25', '4056', 'Basel', 'Basel-Stadt', 'CH',
 47.5612, 7.5889, '+41 61 266 99 99', 'obdachlos@heilsarmee.ch', 'https://www.heilsarmee.ch',
 'Mo–So 8–20 Uhr',
 ARRAY['Tagesstaette','Mahlzeiten','Unterkunft','Beratung'],
 ARRAY['obdachlosenhilfe','heilsarmee','basel'], true, true),

('Caritas St. Gallen – Wohnungslosenhilfe', 'obdachlosenhilfe',
 'Ambulante Hilfen fuer Wohnungslose in St. Gallen mit Beratung und Unterkunftsvermittlung.',
 'Notkerstrasse 22', '9000', 'St. Gallen', 'St. Gallen', 'CH',
 47.4249, 9.3683, '+41 71 228 40 80', 'wohnungslos@caritas-stgallen.ch', 'https://www.caritas-stgallen.ch',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Wohnberatung','Unterkunftsvermittlung','Sozialarbeit'],
 ARRAY['obdachlosenhilfe','caritas','stgallen'], true, true)

ON CONFLICT DO NOTHING;

  END IF;
END $$;
