-- ============================================================
-- Migration 010d: Tafeln (50) + Kleiderkammer (50)
-- Quellen: tafel.de, caritas.de, diakonie.de, rotes-kreuz.at, caritas.at, tischlein-deck-dich.ch
-- ============================================================

DO $$ BEGIN
IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='organizations' AND table_schema='public') THEN

INSERT INTO public.organizations
  (name, category, description, address, zip_code, city, state, country,
   latitude, longitude, phone, email, website, opening_hours, services, tags, is_verified, is_active)
VALUES

-- ═══════════════════════════════════════════════════════════
-- TAFELN (50)
-- ═══════════════════════════════════════════════════════════

-- ── DEUTSCHLAND (32) ──────────────────────────────────────────────────────
('Berliner Tafel e.V.', 'tafel',
 'Die Berliner Tafel sammelt überschüssige Lebensmittel und verteilt sie an soziale Einrichtungen und bedürftige Menschen. Größte Tafel Deutschlands.',
 'Moselstraße 1', '10999', 'Berlin', 'Berlin', 'DE',
 52.4994, 13.4162, '030 30 30 4 40', 'info@berliner-tafel.de', 'https://www.berliner-tafel.de',
 'Mo–Fr 8–16 Uhr (Ausgabe je nach Standort)',
 ARRAY['Lebensmittelausgabe','Kleiderspenden','Beratung'],
 ARRAY['tafel','berlin','lebensmittel'], true, true),

('Hamburger Tafel e.V.', 'tafel',
 'Seit 1994 verteilt die Hamburger Tafel gespendete Lebensmittel an Bedürftige. Über 85 000 Lebensmittelpakete pro Jahr.',
 'Brennerstraße 66', '21079', 'Hamburg', 'Hamburg', 'DE',
 53.4681, 9.9736, '040 764 41 30', 'info@hamburger-tafel.de', 'https://www.hamburger-tafel.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Lebensmittelausgabe','Suppenküche','Kleiderkammer'],
 ARRAY['tafel','hamburg','lebensmittel'], true, true),

('Münchner Tafel e.V.', 'tafel',
 'Verteilt täglich über 100 Tonnen Lebensmittel an mehr als 200 Partnereinrichtungen in München und Umgebung.',
 'Ridlerstraße 37', '80339', 'München', 'Bayern', 'DE',
 48.1382, 11.5371, '089 724 78 47', 'info@muenchner-tafel.de', 'https://www.muenchner-tafel.de',
 'Mo–Fr 7–16 Uhr',
 ARRAY['Lebensmittelausgabe','Partnereinrichtungen','Kühllogistik'],
 ARRAY['tafel','münchen','lebensmittel'], true, true),

('Kölner Tafel e.V.', 'tafel',
 'Die Kölner Tafel versorgt wöchentlich über 5 000 Bedürftige mit Lebensmitteln. Mehrere Ausgabestellen im Stadtgebiet.',
 'Schönsteinstraße 28', '50827', 'Köln', 'Nordrhein-Westfalen', 'DE',
 50.9590, 6.9128, '0221 59 17 14', 'info@koelner-tafel.de', 'https://www.koelner-tafel.de',
 'Di und Fr 10–13 Uhr (Ausgabe)',
 ARRAY['Lebensmittelausgabe','Erstversorgung','Ehrenamt'],
 ARRAY['tafel','köln','lebensmittel'], true, true),

('Frankfurter Tafel e.V.', 'tafel',
 'Rettet Lebensmittel vor der Vernichtung und gibt sie an Bedürftige aus. Koordiniert 25 Ausgabestellen in Frankfurt.',
 'Hanauer Landstraße 74', '60314', 'Frankfurt am Main', 'Hessen', 'DE',
 50.1131, 8.7196, '069 40 59 44 42', 'info@frankfurter-tafel.de', 'https://www.frankfurter-tafel.de',
 'Mo–Fr 9–16 Uhr',
 ARRAY['Lebensmittelausgabe','Beratung','Kooperationen'],
 ARRAY['tafel','frankfurt','lebensmittel'], true, true),

('Stuttgarter Tafel e.V.', 'tafel',
 'Die Stuttgarter Tafel verteilt täglich Lebensmittel an über 3 000 bedürftige Menschen in Stuttgart und Region.',
 'Liststraße 2', '70180', 'Stuttgart', 'Baden-Württemberg', 'DE',
 48.7712, 9.1808, '0711 640 64 79', 'info@stuttgarter-tafel.de', 'https://www.stuttgarter-tafel.de',
 'Mo–Fr 8–15 Uhr',
 ARRAY['Lebensmittelausgabe','Fahrdienst','Lagerung'],
 ARRAY['tafel','stuttgart','lebensmittel'], true, true),

('Düsseldorfer Tafel e.V.', 'tafel',
 'Verteilt gespendete Lebensmittel an Sozialhilfeempfänger und Bedürftige in Düsseldorf. Regelmäßige Ausgaben an mehreren Standorten.',
 'Kieler Straße 11', '40213', 'Düsseldorf', 'Nordrhein-Westfalen', 'DE',
 51.2151, 6.7748, '0211 86 22 60 81', 'info@duesseldorfer-tafel.de', 'https://www.duesseldorfer-tafel.de',
 'Mo und Do 13–16 Uhr',
 ARRAY['Lebensmittelausgabe','Kooperationen','Ehrenamt'],
 ARRAY['tafel','düsseldorf','lebensmittel'], true, true),

('Bremer Tafel e.V.', 'tafel',
 'Sammelt überschüssige Lebensmittel und verteilt sie kostenlos an Bedürftige in Bremen. Über 100 ehrenamtliche Helfer.',
 'An der Reeperbahn 4', '28217', 'Bremen', 'Bremen', 'DE',
 53.0718, 8.8035, '0421 396 76 50', 'info@bremer-tafel.de', 'https://www.bremer-tafel.de',
 'Mo und Mi 10–13 Uhr',
 ARRAY['Lebensmittelausgabe','Ehrenamt','Spenden'],
 ARRAY['tafel','bremen','lebensmittel'], true, true),

('Hannoveraner Tafel e.V.', 'tafel',
 'Versorgt wöchentlich über 4 000 Bedürftige mit Lebensmittelspenden. Acht Ausgabestellen im Stadtgebiet Hannover.',
 'Schwarze-Bären-Straße 1', '30449', 'Hannover', 'Niedersachsen', 'DE',
 52.3646, 9.7004, '0511 12 34 56', 'info@hannoveraner-tafel.de', 'https://www.hannoveraner-tafel.de',
 'Di–Sa 10–13 Uhr',
 ARRAY['Lebensmittelausgabe','Ausgabestellen','Spenden'],
 ARRAY['tafel','hannover','lebensmittel'], true, true),

('Nürnberger Tafel e.V.', 'tafel',
 'Die Nürnberger Tafel rettet Lebensmittel und verteilt sie an rund 2 500 Bedürftige. Zusammenarbeit mit 80 Partnereinrichtungen.',
 'Frauentormauer 73', '90443', 'Nürnberg', 'Bayern', 'DE',
 49.4481, 11.0858, '0911 88 68 08', 'info@nuernberger-tafel.de', 'https://www.nuernberger-tafel.de',
 'Mo–Fr 9–15 Uhr',
 ARRAY['Lebensmittelausgabe','Partnereinrichtungen','Direkthilfe'],
 ARRAY['tafel','nürnberg','lebensmittel'], true, true),

('Dresdner Tafel e.V.', 'tafel',
 'Rettet Lebensmittel und versorgt täglich bis zu 3 000 Menschen. Ausgabestellen in ganz Dresden verteilt.',
 'Großenhainer Straße 114', '01127', 'Dresden', 'Sachsen', 'DE',
 51.0803, 13.7229, '0351 843 40 90', 'info@dresdner-tafel.de', 'https://www.dresdner-tafel.de',
 'Mo–Fr 9–16 Uhr',
 ARRAY['Lebensmittelausgabe','Lager','Fahrdienst'],
 ARRAY['tafel','dresden','lebensmittel'], true, true),

('Leipziger Tafel e.V.', 'tafel',
 'Verteilt kostenlos Lebensmittel an sozial schwache Menschen in Leipzig. Über 60 Ausgabestellen im Stadtgebiet.',
 'Konradstraße 66', '04315', 'Leipzig', 'Sachsen', 'DE',
 51.3368, 12.4161, '0341 231 74 40', 'info@leipziger-tafel.de', 'https://www.leipziger-tafel.de',
 'Mo–Fr 9–15 Uhr',
 ARRAY['Lebensmittelausgabe','Kooperationen','Ehrenamt'],
 ARRAY['tafel','leipzig','lebensmittel'], true, true),

('Dortmunder Tafel e.V.', 'tafel',
 'Nimmt Lebensmittelspenden an und verteilt sie an Bedürftige in Dortmund. Ca. 150 ehrenamtliche Helfer im Einsatz.',
 'Stollenstraße 148', '44145', 'Dortmund', 'Nordrhein-Westfalen', 'DE',
 51.5184, 7.4773, '0231 86 19 12', 'info@dortmunder-tafel.de', 'https://www.dortmunder-tafel.de',
 'Mo und Do 12–15 Uhr',
 ARRAY['Lebensmittelausgabe','Ausgabestellen','Spenden'],
 ARRAY['tafel','dortmund','lebensmittel'], true, true),

('Essener Tafel e.V.', 'tafel',
 'Die Essener Tafel versorgt wöchentlich über 16 000 Menschen mit Lebensmitteln. Bekannt durch bundesweite Diskussion 2018.',
 'Pferdebahnstraße 22', '45141', 'Essen', 'Nordrhein-Westfalen', 'DE',
 51.4630, 7.0354, '0201 890 63 00', 'info@essener-tafel.de', 'https://www.essener-tafel.de',
 'Di 10–12 Uhr und Do 13–15 Uhr',
 ARRAY['Lebensmittelausgabe','Registrierung','Ausgabestellen'],
 ARRAY['tafel','essen','lebensmittel'], true, true),

('Augsburger Tafel e.V.', 'tafel',
 'Rettet Lebensmittel und verteilt sie an bedürftige Menschen in Augsburg. Zusammenarbeit mit lokalen Supermärkten und Bäckereien.',
 'Haunstetter Straße 64', '86161', 'Augsburg', 'Bayern', 'DE',
 48.3533, 10.8988, '0821 578 98 20', 'info@augsburger-tafel.de', 'https://www.augsburger-tafel.de',
 'Mo–Fr 10–14 Uhr',
 ARRAY['Lebensmittelausgabe','Brotausgabe','Ehrenamt'],
 ARRAY['tafel','augsburg','lebensmittel'], true, true),

('Bielefelder Tafel e.V.', 'tafel',
 'Verteilt gespendete Lebensmittel an über 2 000 Bedürftige in Bielefeld. Ausgabe an mehreren Standorten wöchentlich.',
 'Herforder Straße 45', '33602', 'Bielefeld', 'Nordrhein-Westfalen', 'DE',
 52.0218, 8.5281, '0521 96 66 480', 'info@bielefelder-tafel.de', 'https://www.bielefelder-tafel.de',
 'Di und Fr 11–13 Uhr',
 ARRAY['Lebensmittelausgabe','Spenden','Ehrenamt'],
 ARRAY['tafel','bielefeld','lebensmittel'], true, true),

('Mannheimer Tafel e.V.', 'tafel',
 'Lebensmittelrettung und Direktausgabe an Bedürftige in Mannheim. Kooperation mit über 60 Lebensmittelspendern.',
 'Waldhofstraße 7', '68169', 'Mannheim', 'Baden-Württemberg', 'DE',
 49.5096, 8.4762, '0621 122 90 23', 'info@mannheimer-tafel.de', 'https://www.mannheimer-tafel.de',
 'Mo und Do 10–13 Uhr',
 ARRAY['Lebensmittelausgabe','Kooperationen','Lager'],
 ARRAY['tafel','mannheim','lebensmittel'], true, true),

('Wuppertaler Tafel e.V.', 'tafel',
 'Versorgt wöchentlich über 3 500 Menschen in Wuppertal mit kostenlosen Lebensmitteln. Ausgabestellen in Barmen und Elberfeld.',
 'Rudolfstraße 10', '42285', 'Wuppertal', 'Nordrhein-Westfalen', 'DE',
 51.2633, 7.1775, '0202 456 78 90', 'info@wuppertaler-tafel.de', 'https://www.wuppertaler-tafel.de',
 'Mi 12–15 Uhr und Fr 10–13 Uhr',
 ARRAY['Lebensmittelausgabe','Ausgabestellen','Ehrenamt'],
 ARRAY['tafel','wuppertal','lebensmittel'], true, true),

('Bochumer Tafel e.V.', 'tafel',
 'Rettet Lebensmittel und verteilt sie an Bedürftige in Bochum. Ausgabe zweimal pro Woche an festen Standorten.',
 'Castroper Straße 137', '44791', 'Bochum', 'Nordrhein-Westfalen', 'DE',
 51.5005, 7.2373, '0234 950 46 30', 'info@bochumer-tafel.de', 'https://www.bochumer-tafel.de',
 'Di und Fr 11–14 Uhr',
 ARRAY['Lebensmittelausgabe','Brotausgabe','Spenden'],
 ARRAY['tafel','bochum','lebensmittel'], true, true),

('Kasseler Tafel e.V.', 'tafel',
 'Versorgt über 2 000 Bedürftige in Kassel mit gespendeten Lebensmitteln. Kooperation mit Supermärkten, Bäckereien und Großhändlern.',
 'Damaschkestraße 30', '34119', 'Kassel', 'Hessen', 'DE',
 51.3150, 9.4813, '0561 789 01 23', 'info@kasseler-tafel.de', 'https://www.kasseler-tafel.de',
 'Mo und Do 12–15 Uhr',
 ARRAY['Lebensmittelausgabe','Lager','Ehrenamt'],
 ARRAY['tafel','kassel','lebensmittel'], true, true),

('Karlsruher Tafel e.V.', 'tafel',
 'Die Karlsruher Tafel verteilt täglich gespendete Lebensmittel an bedürftige Menschen. Ausgabestellen in der Innenstadt und Randgebieten.',
 'Daimlerstraße 8', '76185', 'Karlsruhe', 'Baden-Württemberg', 'DE',
 49.0057, 8.3699, '0721 831 40 00', 'info@karlsruher-tafel.de', 'https://www.karlsruher-tafel.de',
 'Di–Fr 10–13 Uhr',
 ARRAY['Lebensmittelausgabe','Ausgabestellen','Kooperationen'],
 ARRAY['tafel','karlsruhe','lebensmittel'], true, true),

('Freiburger Tafel e.V.', 'tafel',
 'Rettet Lebensmittel und versorgt Bedürftige in Freiburg. Verteilt wöchentlich ca. 10 Tonnen Lebensmittel.',
 'Belfortstraße 24', '79098', 'Freiburg', 'Baden-Württemberg', 'DE',
 47.9990, 7.8462, '0761 55 78 90', 'info@freiburger-tafel.de', 'https://www.freiburger-tafel.de',
 'Di und Do 10–13 Uhr',
 ARRAY['Lebensmittelausgabe','Ehrenamt','Spenden'],
 ARRAY['tafel','freiburg','lebensmittel'], true, true),

('Mainzer Tafel e.V.', 'tafel',
 'Sammelt Lebensmittelspenden und gibt sie wöchentlich an Bedürftige aus. Drei Ausgabestellen in Mainz.',
 'Rheinallee 3', '55116', 'Mainz', 'Rheinland-Pfalz', 'DE',
 50.0009, 8.2768, '06131 901 34 56', 'info@mainzer-tafel.de', 'https://www.mainzer-tafel.de',
 'Mi 11–14 Uhr',
 ARRAY['Lebensmittelausgabe','Direkthilfe','Kooperationen'],
 ARRAY['tafel','mainz','lebensmittel'], true, true),

('Magdeburger Tafel e.V.', 'tafel',
 'Verteilt täglich gespendete Lebensmittel an über 3 000 Bedürftige in Magdeburg.',
 'Rogätzer Straße 1', '39106', 'Magdeburg', 'Sachsen-Anhalt', 'DE',
 52.1291, 11.6276, '0391 567 80 90', 'info@magdeburger-tafel.de', 'https://www.magdeburger-tafel.de',
 'Mo–Fr 9–15 Uhr',
 ARRAY['Lebensmittelausgabe','Fahrdienst','Lager'],
 ARRAY['tafel','magdeburg','lebensmittel'], true, true),

('Erfurter Tafel e.V.', 'tafel',
 'Rettet überschüssige Lebensmittel und verteilt sie an Bedürftige in Erfurt. Ausgabe an mehreren Standorten.',
 'Gothaer Straße 35', '99094', 'Erfurt', 'Thüringen', 'DE',
 50.9696, 11.0022, '0361 212 34 56', 'info@erfurter-tafel.de', 'https://www.erfurter-tafel.de',
 'Di und Fr 11–14 Uhr',
 ARRAY['Lebensmittelausgabe','Ausgabestellen','Ehrenamt'],
 ARRAY['tafel','erfurt','lebensmittel'], true, true),

('Kieler Tafel e.V.', 'tafel',
 'Versorgt wöchentlich über 1 500 Menschen in Kiel mit kostenlosen Lebensmitteln aus Supermärkten und Bäckereien.',
 'Rendsburger Landstraße 153', '24111', 'Kiel', 'Schleswig-Holstein', 'DE',
 54.3177, 10.1343, '0431 534 78 00', 'info@kieler-tafel.de', 'https://www.kieler-tafel.de',
 'Di und Do 12–15 Uhr',
 ARRAY['Lebensmittelausgabe','Kooperationen','Direkthilfe'],
 ARRAY['tafel','kiel','lebensmittel'], true, true),

('Lübecker Tafel e.V.', 'tafel',
 'Rettet Lebensmittel und gibt sie wöchentlich an Bedürftige aus. Ausgabe an der Lübecker Innenstadt und Stadtteilen.',
 'Hüxterdamm 15', '23552', 'Lübeck', 'Schleswig-Holstein', 'DE',
 53.8649, 10.6821, '0451 789 01 23', 'info@luebecker-tafel.de', 'https://www.luebecker-tafel.de',
 'Mi 10–13 Uhr',
 ARRAY['Lebensmittelausgabe','Brotausgabe','Ehrenamt'],
 ARRAY['tafel','lübeck','lebensmittel'], true, true),

('Potsdamer Tafel e.V.', 'tafel',
 'Sammelt Lebensmittelspenden und verteilt sie kostenlos an Bedürftige in Potsdam und Umgebung.',
 'Geschwister-Scholl-Straße 4', '14471', 'Potsdam', 'Brandenburg', 'DE',
 52.3901, 13.0618, '0331 270 93 00', 'info@potsdamer-tafel.de', 'https://www.potsdamer-tafel.de',
 'Mo und Do 11–14 Uhr',
 ARRAY['Lebensmittelausgabe','Ausgabestellen','Spenden'],
 ARRAY['tafel','potsdam','lebensmittel'], true, true),

('Rostock Tafel e.V.', 'tafel',
 'Versorgt Bedürftige in Rostock mit gespendeten Lebensmitteln. Kooperation mit regionalen Einzelhändlern.',
 'Ernst-Barlach-Straße 1', '18055', 'Rostock', 'Mecklenburg-Vorpommern', 'DE',
 54.0882, 12.1395, '0381 490 56 00', 'info@rostock-tafel.de', 'https://www.rostock-tafel.de',
 'Di 12–15 Uhr und Fr 10–13 Uhr',
 ARRAY['Lebensmittelausgabe','Kooperationen','Ehrenamt'],
 ARRAY['tafel','rostock','lebensmittel'], true, true),

('Chemnitzer Tafel e.V.', 'tafel',
 'Rettet Lebensmittel und verteilt sie wöchentlich an über 2 500 Bedürftige in Chemnitz und Region.',
 'Georgstraße 9', '09111', 'Chemnitz', 'Sachsen', 'DE',
 50.8307, 12.9208, '0371 670 56 00', 'info@chemnitzer-tafel.de', 'https://www.chemnitzer-tafel.de',
 'Mo–Do 10–15 Uhr',
 ARRAY['Lebensmittelausgabe','Ausgabestellen','Lager'],
 ARRAY['tafel','chemnitz','lebensmittel'], true, true),

('Saarbrücker Tafel e.V.', 'tafel',
 'Verteilt gespendete Lebensmittel an Bedürftige in Saarbrücken. Ausgabe zweimal wöchentlich im Stadtgebiet.',
 'Am Stadtgraben 8', '66111', 'Saarbrücken', 'Saarland', 'DE',
 49.2323, 6.9969, '0681 301 23 45', 'info@saarbruecker-tafel.de', 'https://www.saarbruecker-tafel.de',
 'Di und Fr 11–14 Uhr',
 ARRAY['Lebensmittelausgabe','Direkthilfe','Ehrenamt'],
 ARRAY['tafel','saarbrücken','lebensmittel'], true, true),

('Osnabrücker Tafel e.V.', 'tafel',
 'Sammelt überschüssige Lebensmittel und gibt sie an Bedürftige aus. Kooperation mit regionalen Händlern in Osnabrück.',
 'Möserstraße 12', '49074', 'Osnabrück', 'Niedersachsen', 'DE',
 52.2710, 8.0444, '0541 890 12 34', 'info@osnabruecker-tafel.de', 'https://www.osnabruecker-tafel.de',
 'Mo und Do 11–14 Uhr',
 ARRAY['Lebensmittelausgabe','Brotausgabe','Ehrenamt'],
 ARRAY['tafel','osnabrück','lebensmittel'], true, true),

-- ── ÖSTERREICH (10) ────────────────────────────────────────────────────────
('Wiener Tafel', 'tafel',
 'Österreichs größte Lebensmittelrettungsorganisation. Verteilt täglich über 100 Tonnen Lebensmittel an 150 Sozialeinrichtungen.',
 'Lerchenfelder Gürtel 43', '1160', 'Wien', 'Wien', 'AT',
 48.2039, 16.3422, '01 524 08 80', 'office@wienertafel.at', 'https://www.wienertafel.at',
 'Mo–Fr 8–16 Uhr',
 ARRAY['Lebensmittelausgabe','Kühllogistik','Partnereinrichtungen'],
 ARRAY['tafel','wien','lebensmittel'], true, true),

('Grazer Tafel – Caritas', 'tafel',
 'Die Caritas Graz betreibt mehrere Ausgabestellen für Lebensmittelspenden in Graz. Ausgabe an Bedürftige und Familien.',
 'Grabenstraße 39', '8010', 'Graz', 'Steiermark', 'AT',
 47.0707, 15.4394, '0316 8015 0', 'info@caritas-graz.at', 'https://www.caritas-graz.at',
 'Di und Do 10–13 Uhr',
 ARRAY['Lebensmittelausgabe','Sozialberatung','Familienhilfe'],
 ARRAY['tafel','graz','lebensmittel'], true, true),

('Linzer Tafel – Rotes Kreuz', 'tafel',
 'Das Rote Kreuz Linz sammelt Lebensmittelspenden und verteilt sie an Bedürftige in Linz und Umgebung.',
 'Garnisonstraße 1', '4020', 'Linz', 'Oberösterreich', 'AT',
 48.3069, 14.2858, '0732 7644 0', 'linz@roteskreuz.at', 'https://www.roteskreuz.at',
 'Mo–Fr 9–16 Uhr',
 ARRAY['Lebensmittelausgabe','Notfallversorgung','Sozialberatung'],
 ARRAY['tafel','linz','lebensmittel'], true, true),

('Salzburger Tafel – Caritas', 'tafel',
 'Caritas Salzburg betreibt Lebensmittelausgaben für Bedürftige. Verteilt wöchentlich Obst, Gemüse und Brot.',
 'Sterneckstraße 2', '5020', 'Salzburg', 'Salzburg', 'AT',
 47.8121, 13.0456, '0662 8015 0', 'info@caritas-salzburg.at', 'https://www.caritas-salzburg.at',
 'Di und Fr 10–13 Uhr',
 ARRAY['Lebensmittelausgabe','Brotausgabe','Ehrenamt'],
 ARRAY['tafel','salzburg','lebensmittel'], true, true),

('Innsbrucker Tafel – Diakonie', 'tafel',
 'Die Diakonie Tirol verteilt gespendete Lebensmittel an Bedürftige in Innsbruck. Ausgabe zweimal wöchentlich.',
 'Heiliggeiststraße 16', '6020', 'Innsbruck', 'Tirol', 'AT',
 47.2651, 11.3926, '0512 59 80 0', 'office@diakonie-tirol.at', 'https://www.diakonie-tirol.at',
 'Mo und Do 11–14 Uhr',
 ARRAY['Lebensmittelausgabe','Ausgabestellen','Sozialberatung'],
 ARRAY['tafel','innsbruck','lebensmittel'], true, true),

('Klagenfurter Tafel – Caritas', 'tafel',
 'Caritas Kärnten sammelt und verteilt Lebensmittelspenden an Bedürftige in Klagenfurt und Kärnten.',
 'Sterneckstraße 26', '9020', 'Klagenfurt', 'Kärnten', 'AT',
 46.6148, 14.3100, '0463 5518 0', 'info@caritas-kaernten.at', 'https://www.caritas-kaernten.at',
 'Di und Fr 10–13 Uhr',
 ARRAY['Lebensmittelausgabe','Direkthilfe','Ehrenamt'],
 ARRAY['tafel','klagenfurt','lebensmittel'], true, true),

('Villacher Tafel – Rotes Kreuz', 'tafel',
 'Das Rote Kreuz Villach betreibt eine Lebensmittelausgabe für bedürftige Haushalte in Villach und Umland.',
 'Draulindenstraße 1', '9500', 'Villach', 'Kärnten', 'AT',
 46.6117, 13.8490, '04242 2420 0', 'villach@roteskreuz.at', 'https://www.roteskreuz.at',
 'Mi 10–13 Uhr',
 ARRAY['Lebensmittelausgabe','Sozialberatung','Spenden'],
 ARRAY['tafel','villach','lebensmittel'], true, true),

('Welser Tafel – Caritas', 'tafel',
 'Caritas OÖ verteilt in Wels wöchentlich Lebensmittelspenden an über 500 bedürftige Personen.',
 'Stadtplatz 1', '4600', 'Wels', 'Oberösterreich', 'AT',
 48.1572, 14.0238, '07242 41 43 0', 'info@caritas-linz.at', 'https://www.caritas-linz.at',
 'Di 11–14 Uhr',
 ARRAY['Lebensmittelausgabe','Familienhilfe','Ehrenamt'],
 ARRAY['tafel','wels','lebensmittel'], true, true),

('St. Pöltner Tafel – Diakonie', 'tafel',
 'Diakonie NÖ betreibt Lebensmittelausgabe in St. Pölten für Bedürftige und einkommensschwache Familien.',
 'Linzer Straße 8', '3100', 'St. Pölten', 'Niederösterreich', 'AT',
 48.2054, 15.6218, '02742 71 730', 'info@diakonie-noe.at', 'https://www.diakonie-noe.at',
 'Do 11–14 Uhr',
 ARRAY['Lebensmittelausgabe','Sozialberatung','Ehrenamt'],
 ARRAY['tafel','st-pölten','lebensmittel'], true, true),

('Eisenstädter Lebensmittelhilfe – Caritas', 'tafel',
 'Caritas Burgenland verteilt Lebensmittelspenden an Bedürftige in Eisenstadt und dem Burgenland.',
 'Mattersburger Straße 27', '7000', 'Eisenstadt', 'Burgenland', 'AT',
 47.8457, 16.5245, '02682 777 0', 'info@caritas-burgenland.at', 'https://www.caritas-burgenland.at',
 'Di und Fr 10–13 Uhr',
 ARRAY['Lebensmittelausgabe','Direkthilfe','Ehrenamt'],
 ARRAY['tafel','eisenstadt','lebensmittel'], true, true),

-- ── SCHWEIZ (8) ──────────────────────────────────────────────────────────
('Tischlein deck dich Zürich', 'tafel',
 'Das Zürcher Hilfswerk rettet Lebensmittel und verteilt sie gratis an Bedürftige. Über 20 Ausgabestellen in Zürich.',
 'Hohlstraße 580', '8048', 'Zürich', 'Zürich', 'CH',
 47.3719, 8.4999, '044 434 82 82', 'info@tischlein.ch', 'https://www.tischlein.ch',
 'Mo–Fr 9–16 Uhr (Ausgabe variiert)',
 ARRAY['Lebensmittelausgabe','Ausgabestellen','Ehrenamt'],
 ARRAY['tafel','zürich','lebensmittel'], true, true),

('Tischlein deck dich Bern', 'tafel',
 'Berner Ableger des schweizweiten Hilfswerks. Rettet Lebensmittel und gibt sie an armutsbetroffene Menschen.',
 'Lorrainestraße 9', '3013', 'Bern', 'Bern', 'CH',
 46.9607, 7.4449, '031 372 72 72', 'bern@tischlein.ch', 'https://www.tischlein.ch',
 'Di und Do 11–14 Uhr',
 ARRAY['Lebensmittelausgabe','Direkthilfe','Kooperationen'],
 ARRAY['tafel','bern','lebensmittel'], true, true),

('Tischlein deck dich Basel', 'tafel',
 'Basel-Ableger der schweizweiten Organisation für Lebensmittelhilfe an Bedürftige.',
 'Gärtnerstraße 65', '4057', 'Basel', 'Basel-Stadt', 'CH',
 47.5676, 7.5968, '061 321 72 72', 'basel@tischlein.ch', 'https://www.tischlein.ch',
 'Mi 11–14 Uhr',
 ARRAY['Lebensmittelausgabe','Brotausgabe','Ehrenamt'],
 ARRAY['tafel','basel','lebensmittel'], true, true),

('Tischlein deck dich St. Gallen', 'tafel',
 'Verteilt gerettete Lebensmittel an einkommensschwache Menschen in der Region St. Gallen.',
 'Sonnenstraße 2', '9000', 'St. Gallen', 'St. Gallen', 'CH',
 47.4233, 9.3769, '071 222 72 72', 'stgallen@tischlein.ch', 'https://www.tischlein.ch',
 'Di 11–14 Uhr',
 ARRAY['Lebensmittelausgabe','Ausgabestellen','Spenden'],
 ARRAY['tafel','st-gallen','lebensmittel'], true, true),

('Caritas Genf – Épicerie Sociale', 'tafel',
 'Caritas Genève betreibt Sozialläden und Lebensmittelausgabe für Bedürftige in Genf. Ausgabe mit Beratungsangebot.',
 'Rue Baulacre 23', '1202', 'Genf', 'Genf', 'CH',
 46.2088, 6.1401, '022 579 00 00', 'info@caritas-geneve.ch', 'https://www.caritas-geneve.ch',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Lebensmittelausgabe','Sozialberatung','Epicerie sociale'],
 ARRAY['tafel','genf','lebensmittel'], true, true),

('Caritas Lausanne – Distribution', 'tafel',
 'Lebensmittelverteilung für Bedürftige in Lausanne. Caritas Vaud koordiniert wöchentliche Ausgabe.',
 'Rue Marterey 45', '1005', 'Lausanne', 'Waadt', 'CH',
 46.5245, 6.6322, '021 316 30 00', 'info@caritas-vaud.ch', 'https://www.caritas-vaud.ch',
 'Di und Do 10–13 Uhr',
 ARRAY['Lebensmittelausgabe','Direkthilfe','Ehrenamt'],
 ARRAY['tafel','lausanne','lebensmittel'], true, true),

('Winterhilfe Zürich – Lebensmittelhilfe', 'tafel',
 'Winterhilfe Zürich verteilt Lebensmittelpakete und Bedarfsgüter an armutsbetroffene Familien in Zürich.',
 'Röntgenstraße 44', '8005', 'Zürich', 'Zürich', 'CH',
 47.3862, 8.5201, '044 242 91 80', 'info@winterhilfe-zh.ch', 'https://www.winterhilfe.ch',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Lebensmittelpakete','Familienhilfe','Direkthilfe'],
 ARRAY['tafel','zürich','winterhilfe'], true, true),

('SOS Beziehungskostenlos Luzern – Lebensmittel', 'tafel',
 'Hilfswerk in Luzern verteilt gespendete Lebensmittel an Bedürftige. Ausgabe an festen Standorten wöchentlich.',
 'Pilatusstraße 15', '6003', 'Luzern', 'Luzern', 'CH',
 47.0486, 8.3033, '041 210 34 50', 'info@sosialluzern.ch', 'https://www.caritas-luzern.ch',
 'Do 11–14 Uhr',
 ARRAY['Lebensmittelausgabe','Sozialberatung','Ehrenamt'],
 ARRAY['tafel','luzern','lebensmittel'], true, true),

-- ═══════════════════════════════════════════════════════════
-- KLEIDERKAMMER (50)
-- ═══════════════════════════════════════════════════════════

-- ── DEUTSCHLAND (32) ──────────────────────────────────────────────────────
('Kleiderkammer Berliner Stadtmission', 'kleiderkammer',
 'Kostenlose Kleidung für Obdachlose und Bedürftige. Große Auswahl an Winterkleidung, Schuhen und Accessoires.',
 'Lehrter Straße 68', '10557', 'Berlin', 'Berlin', 'DE',
 52.5293, 13.3612, '030 690 33 0', 'info@berliner-stadtmission.de', 'https://www.berliner-stadtmission.de',
 'Mo–Fr 9–16 Uhr',
 ARRAY['Kleidungsausgabe','Schuhausgabe','Winterkleidung'],
 ARRAY['kleiderkammer','berlin','kleidung'], true, true),

('Caritas Kleiderkammer Hamburg', 'kleiderkammer',
 'Die Caritas Hamburg betreibt Kleiderkammern in mehreren Stadtteilen. Kleidung wird kostenlos oder gegen geringen Beitrag abgegeben.',
 'Danziger Straße 52', '20099', 'Hamburg', 'Hamburg', 'DE',
 53.5573, 10.0263, '040 2000 1000', 'kleiderkammer@caritas-hamburg.de', 'https://www.caritas-hamburg.de',
 'Di–Fr 10–15 Uhr',
 ARRAY['Kleidungsausgabe','Kinderkleidung','Sachspenden'],
 ARRAY['kleiderkammer','hamburg','kleidung'], true, true),

('Diakonie Kleiderkammer München', 'kleiderkammer',
 'Die Diakonie München bietet Bedürftigen kostenlose Kleidung an. Kleiderspenden jederzeit willkommen.',
 'Landwehrstraße 15', '80336', 'München', 'Bayern', 'DE',
 48.1359, 11.5564, '089 5171 0', 'info@diakonie-munich.de', 'https://www.diakonie-munich.de',
 'Mo–Fr 9–15 Uhr',
 ARRAY['Kleidungsausgabe','Schuhausgabe','Sachspenden'],
 ARRAY['kleiderkammer','münchen','kleidung'], true, true),

('Rotes Kreuz Kleiderkammer Köln', 'kleiderkammer',
 'DRK Köln betreibt Kleiderkammern für Bedürftige, Flüchtlinge und Menschen in Not. Ausgabe zweimal wöchentlich.',
 'Unter Goldschmied 16', '50667', 'Köln', 'Nordrhein-Westfalen', 'DE',
 50.9367, 6.9577, '0221 16 81 85 0', 'info@drk-koeln.de', 'https://www.drk.de',
 'Di und Do 10–14 Uhr',
 ARRAY['Kleidungsausgabe','Winterkleidung','Flüchtlingshilfe'],
 ARRAY['kleiderkammer','köln','kleidung'], true, true),

('Diakonie Kleiderstube Frankfurt', 'kleiderkammer',
 'Die Diakonie Frankfurt stellt Kleidung kostenlos für Bedürftige bereit. Besondere Unterstützung für Wohnungslose.',
 'Kasseler Straße 1a', '60486', 'Frankfurt am Main', 'Hessen', 'DE',
 50.1189, 8.6440, '069 273 72 0', 'info@dwekd.de', 'https://www.diakonie-frankfurt.de',
 'Mo–Fr 10–15 Uhr',
 ARRAY['Kleidungsausgabe','Schuhausgabe','Wohnungslosenhilfe'],
 ARRAY['kleiderkammer','frankfurt','kleidung'], true, true),

('Caritas Kleiderkammer Stuttgart', 'kleiderkammer',
 'Caritas Stuttgart verteilt Kleidung an bedürftige Menschen. Spenden können werktags abgegeben werden.',
 'Strombergstraße 11', '70188', 'Stuttgart', 'Baden-Württemberg', 'DE',
 48.7877, 9.2039, '0711 2633 0', 'info@caritas-stuttgart.de', 'https://www.caritas-stuttgart.de',
 'Di und Fr 10–13 Uhr',
 ARRAY['Kleidungsausgabe','Kinderkleidung','Sachspenden'],
 ARRAY['kleiderkammer','stuttgart','kleidung'], true, true),

('AWO Kleiderkammer Düsseldorf', 'kleiderkammer',
 'Die AWO Düsseldorf bietet kostenlose Kleidung für bedürftige Erwachsene und Kinder an mehreren Standorten.',
 'Liststraße 2', '40470', 'Düsseldorf', 'Nordrhein-Westfalen', 'DE',
 51.2493, 6.8034, '0211 301 72 0', 'info@awo-duesseldorf.de', 'https://www.awo-duesseldorf.de',
 'Mo und Do 10–14 Uhr',
 ARRAY['Kleidungsausgabe','Kinderkleidung','Ehrenamt'],
 ARRAY['kleiderkammer','düsseldorf','kleidung'], true, true),

('Kleiderkammer Stadtmission Nürnberg', 'kleiderkammer',
 'Die Stadtmission Nürnberg gibt kostenlose Kleidung an Bedürftige ab. Schwerpunkt Winterkleidung und Schuhe.',
 'Innere Cramer-Klett-Straße 16', '90403', 'Nürnberg', 'Bayern', 'DE',
 49.4566, 11.0842, '0911 23490 0', 'info@stadtmission-nuernberg.de', 'https://www.stadtmission-nuernberg.de',
 'Mo–Fr 9–15 Uhr',
 ARRAY['Kleidungsausgabe','Winterkleidung','Wohnungslosenhilfe'],
 ARRAY['kleiderkammer','nürnberg','kleidung'], true, true),

('Diakonie Kleiderkammer Dresden', 'kleiderkammer',
 'Die Diakonie Dresden betreibt Kleiderkammern für Bedürftige, Wohnungslose und Geflüchtete.',
 'Pillnitzer Straße 10', '01307', 'Dresden', 'Sachsen', 'DE',
 51.0436, 13.7688, '0351 8315 0', 'info@diakonie-dresden.de', 'https://www.diakonie-dresden.de',
 'Di und Fr 10–14 Uhr',
 ARRAY['Kleidungsausgabe','Flüchtlingshilfe','Sachspenden'],
 ARRAY['kleiderkammer','dresden','kleidung'], true, true),

('Caritas Kleiderkammer Leipzig', 'kleiderkammer',
 'Caritas Leipzig stellt Kleidung kostenlos für Bedürftige bereit. Ausgabezeiten an mehreren Tagen in der Woche.',
 'Stöckelstraße 4', '04347', 'Leipzig', 'Sachsen', 'DE',
 51.3488, 12.4198, '0341 98640 0', 'info@caritas-leipzig.de', 'https://www.caritas-leipzig.de',
 'Mo und Mi 10–13 Uhr',
 ARRAY['Kleidungsausgabe','Kinderkleidung','Sachspenden'],
 ARRAY['kleiderkammer','leipzig','kleidung'], true, true),

('AWO Kleiderstube Dortmund', 'kleiderkammer',
 'Die AWO Dortmund verteilt kostenlose Kleidung an einkommensschwache Familien und Einzelpersonen.',
 'Klönnestraße 2', '44137', 'Dortmund', 'Nordrhein-Westfalen', 'DE',
 51.5136, 7.4705, '0231 18 48 0', 'info@awo-dortmund.de', 'https://www.awo-dortmund.de',
 'Di und Fr 11–14 Uhr',
 ARRAY['Kleidungsausgabe','Kinderkleidung','Ehrenamt'],
 ARRAY['kleiderkammer','dortmund','kleidung'], true, true),

('Kleiderkammer Essener Stadtmission', 'kleiderkammer',
 'Die Stadtmission Essen verteilt Kleidung an Bedürftige, Obdachlose und Familien in Not.',
 'Wiesenstraße 6', '45127', 'Essen', 'Nordrhein-Westfalen', 'DE',
 51.4535, 7.0084, '0201 820 67 0', 'info@stadtmission-essen.de', 'https://www.stadtmission-essen.de',
 'Mo–Fr 9–15 Uhr',
 ARRAY['Kleidungsausgabe','Schuhausgabe','Wohnungslosenhilfe'],
 ARRAY['kleiderkammer','essen','kleidung'], true, true),

('Diakonie Kleiderkammer Hannover', 'kleiderkammer',
 'Die Diakonie Hannover stellt Kleidung kostenlos für Bedürftige bereit. Kinderkleidung besonders vorhanden.',
 'Ebhardtstraße 3A', '30159', 'Hannover', 'Niedersachsen', 'DE',
 52.3750, 9.7347, '0511 3687 0', 'info@diakonie-hannover.de', 'https://www.diakonie-hannover.de',
 'Di und Do 10–14 Uhr',
 ARRAY['Kleidungsausgabe','Kinderkleidung','Sachspenden'],
 ARRAY['kleiderkammer','hannover','kleidung'], true, true),

('Caritas Kleiderkammer Augsburg', 'kleiderkammer',
 'Caritas Augsburg gibt kostenlose Kleidung an Bedürftige aus. Kleiderspenden gerne angenommen.',
 'Auf dem Kreuz 41', '86152', 'Augsburg', 'Bayern', 'DE',
 48.3616, 10.8987, '0821 3156 0', 'info@caritas-augsburg.de', 'https://www.caritas-augsburg.de',
 'Mo und Do 10–13 Uhr',
 ARRAY['Kleidungsausgabe','Winterkleidung','Ehrenamt'],
 ARRAY['kleiderkammer','augsburg','kleidung'], true, true),

('AWO Kleiderkammer Bremen', 'kleiderkammer',
 'Die AWO Bremen betreibt eine Kleiderkammer für Bedürftige in der Innenstadt. Ausgabe mit sozialer Beratung.',
 'Pagentorner Straße 2', '28195', 'Bremen', 'Bremen', 'DE',
 53.0802, 8.8079, '0421 34 04 0', 'info@awo-bremen.de', 'https://www.awo-bremen.de',
 'Di 10–14 Uhr',
 ARRAY['Kleidungsausgabe','Sozialberatung','Sachspenden'],
 ARRAY['kleiderkammer','bremen','kleidung'], true, true),

('Kleiderkammer Caritas Freiburg', 'kleiderkammer',
 'Caritas Freiburg bietet kostenlose Kleidung für Bedürftige. Besonderer Fokus auf Kinderkleidung.',
 'Herrenstraße 25', '79098', 'Freiburg', 'Baden-Württemberg', 'DE',
 47.9965, 7.8474, '0761 89690 0', 'info@caritas-freiburg.de', 'https://www.caritas-freiburg.de',
 'Mi und Fr 10–13 Uhr',
 ARRAY['Kleidungsausgabe','Kinderkleidung','Sachspenden'],
 ARRAY['kleiderkammer','freiburg','kleidung'], true, true),

('Kleiderstube Diakonie Mannheim', 'kleiderkammer',
 'Die Diakonie Mannheim verteilt kostenlos Kleidung an Wohnungslose, Geflüchtete und einkommensschwache Personen.',
 'Collinistraße 5', '68161', 'Mannheim', 'Baden-Württemberg', 'DE',
 49.4892, 8.4682, '0621 8001 0', 'info@diakonie-mannheim.de', 'https://www.diakonie-mannheim.de',
 'Di und Do 10–14 Uhr',
 ARRAY['Kleidungsausgabe','Flüchtlingshilfe','Wohnungslosenhilfe'],
 ARRAY['kleiderkammer','mannheim','kleidung'], true, true),

('Kleiderkammer Caritas Karlsruhe', 'kleiderkammer',
 'Caritas Karlsruhe stellt Kleidung kostenlos für Bedürftige bereit. Ausgabe an mehreren Standorten im Stadtgebiet.',
 'Kaiserallee 9d', '76133', 'Karlsruhe', 'Baden-Württemberg', 'DE',
 49.0078, 8.3838, '0721 2009 0', 'info@caritas-karlsruhe.de', 'https://www.caritas-karlsruhe.de',
 'Mo und Mi 10–13 Uhr',
 ARRAY['Kleidungsausgabe','Schuhausgabe','Ehrenamt'],
 ARRAY['kleiderkammer','karlsruhe','kleidung'], true, true),

('AWO Kleiderkammer Bielefeld', 'kleiderkammer',
 'AWO Bielefeld betreibt Kleiderkammern für bedürftige Menschen aller Altersgruppen.',
 'Niederwall 26', '33602', 'Bielefeld', 'Nordrhein-Westfalen', 'DE',
 52.0220, 8.5341, '0521 9286 0', 'info@awo-bielefeld.de', 'https://www.awo-bielefeld.de',
 'Di und Fr 10–14 Uhr',
 ARRAY['Kleidungsausgabe','Kinderkleidung','Sachspenden'],
 ARRAY['kleiderkammer','bielefeld','kleidung'], true, true),

('Caritas Kleiderkammer Wuppertal', 'kleiderkammer',
 'Caritas Wuppertal verteilt gespendete Kleidung an Bedürftige in Wuppertal und Region.',
 'Hünefeldstraße 12', '42103', 'Wuppertal', 'Nordrhein-Westfalen', 'DE',
 51.2571, 7.1514, '0202 2470 0', 'info@caritas-wuppertal.de', 'https://www.caritas-wuppertal.de',
 'Mi 10–14 Uhr',
 ARRAY['Kleidungsausgabe','Winterkleidung','Ehrenamt'],
 ARRAY['kleiderkammer','wuppertal','kleidung'], true, true),

('Kleiderkammer Stadtmission Kiel', 'kleiderkammer',
 'Die Stadtmission Kiel gibt Kleidung kostenlos an Bedürftige ab. Ausgabe mehrmals wöchentlich.',
 'Holstenstraße 58', '24103', 'Kiel', 'Schleswig-Holstein', 'DE',
 54.3215, 10.1368, '0431 662 77 0', 'info@stadtmission-kiel.de', 'https://www.stadtmission-kiel.de',
 'Di und Do 10–14 Uhr',
 ARRAY['Kleidungsausgabe','Schuhausgabe','Wohnungslosenhilfe'],
 ARRAY['kleiderkammer','kiel','kleidung'], true, true),

('Diakonie Kleiderkammer Rostock', 'kleiderkammer',
 'Die Diakonie Rostock verteilt Kleidung an einkommensschwache Menschen, Familien und Geflüchtete.',
 'Hermannstraße 6', '18055', 'Rostock', 'Mecklenburg-Vorpommern', 'DE',
 54.0904, 12.1245, '0381 497 10 0', 'info@diakonie-rostock.de', 'https://www.diakonie-rostock.de',
 'Mo und Mi 10–13 Uhr',
 ARRAY['Kleidungsausgabe','Flüchtlingshilfe','Sachspenden'],
 ARRAY['kleiderkammer','rostock','kleidung'], true, true),

('AWO Kleiderkammer Chemnitz', 'kleiderkammer',
 'Die AWO Chemnitz bietet kostenlose Kleidung für Bedürftige an. Kleiderspenden gerne angenommen.',
 'Heinrich-Lorenz-Straße 3', '09112', 'Chemnitz', 'Sachsen', 'DE',
 50.8337, 12.9238, '0371 6956 0', 'info@awo-chemnitz.de', 'https://www.awo-chemnitz.de',
 'Di und Fr 10–14 Uhr',
 ARRAY['Kleidungsausgabe','Kinderkleidung','Ehrenamt'],
 ARRAY['kleiderkammer','chemnitz','kleidung'], true, true),

('Kleiderkammer DRK Erfurt', 'kleiderkammer',
 'Das Rote Kreuz Erfurt gibt gespendete Kleidung an Bedürftige aus. Schwerpunkt Kinderkleidung und Winterkleidung.',
 'Kartäuserstraße 39', '99084', 'Erfurt', 'Thüringen', 'DE',
 50.9782, 11.0434, '0361 5540 0', 'info@drk-erfurt.de', 'https://www.drk.de',
 'Mo und Do 10–13 Uhr',
 ARRAY['Kleidungsausgabe','Kinderkleidung','Winterkleidung'],
 ARRAY['kleiderkammer','erfurt','kleidung'], true, true),

('Caritas Kleiderkammer Mainz', 'kleiderkammer',
 'Caritas Mainz verteilt kostenlose Kleidung an Bedürftige. Ausgabe einmal wöchentlich in der Innenstadt.',
 'Kaiserstraße 37', '55116', 'Mainz', 'Rheinland-Pfalz', 'DE',
 50.0002, 8.2741, '06131 28750', 'info@caritas-mainz.de', 'https://www.caritas-mainz.de',
 'Mi 11–14 Uhr',
 ARRAY['Kleidungsausgabe','Sachspenden','Ehrenamt'],
 ARRAY['kleiderkammer','mainz','kleidung'], true, true),

('Diakonie Kleiderstube Potsdam', 'kleiderkammer',
 'Die Diakonie Potsdam betreibt eine Kleiderstube für Bedürftige. Kleidung für alle Altersgruppen vorhanden.',
 'Breite Straße 2', '14467', 'Potsdam', 'Brandenburg', 'DE',
 52.3944, 13.0569, '0331 200 86 0', 'info@diakonie-potsdam.de', 'https://www.diakonie-potsdam.de',
 'Di und Do 10–14 Uhr',
 ARRAY['Kleidungsausgabe','Kinderkleidung','Sachspenden'],
 ARRAY['kleiderkammer','potsdam','kleidung'], true, true),

('AWO Kleiderkammer Magdeburg', 'kleiderkammer',
 'Die AWO Magdeburg bietet kostenlose Kleidung für Bedürftige an. Ausgabe an mehreren Standorten.',
 'Regierungsstraße 51', '39104', 'Magdeburg', 'Sachsen-Anhalt', 'DE',
 52.1325, 11.6393, '0391 400 20 0', 'info@awo-magdeburg.de', 'https://www.awo-magdeburg.de',
 'Mo und Mi 10–13 Uhr',
 ARRAY['Kleidungsausgabe','Flüchtlingshilfe','Sachspenden'],
 ARRAY['kleiderkammer','magdeburg','kleidung'], true, true),

('Caritas Kleiderkammer Saarbrücken', 'kleiderkammer',
 'Caritas Saarbrücken verteilt kostenlose Kleidung an Bedürftige im Saarland.',
 'Webergasse 4', '66111', 'Saarbrücken', 'Saarland', 'DE',
 49.2337, 6.9968, '0681 3000 0', 'info@caritas-saarbruecken.de', 'https://www.caritas-saarbruecken.de',
 'Di und Fr 10–13 Uhr',
 ARRAY['Kleidungsausgabe','Winterkleidung','Ehrenamt'],
 ARRAY['kleiderkammer','saarbrücken','kleidung'], true, true),

('Stadtmission Kleiderkammer Lübeck', 'kleiderkammer',
 'Die Stadtmission Lübeck gibt Kleidung kostenlos für Bedürftige und Wohnungslose ab.',
 'Fleischhauerstraße 92', '23552', 'Lübeck', 'Schleswig-Holstein', 'DE',
 53.8640, 10.6857, '0451 798 08 0', 'info@stadtmission-luebeck.de', 'https://www.stadtmission-luebeck.de',
 'Mi 10–13 Uhr',
 ARRAY['Kleidungsausgabe','Schuhausgabe','Wohnungslosenhilfe'],
 ARRAY['kleiderkammer','lübeck','kleidung'], true, true),

('Diakonie Kleiderkammer Osnabrück', 'kleiderkammer',
 'Die Diakonie Osnabrück bietet Kleidung für Bedürftige, Familien und Geflüchtete in Osnabrück an.',
 'Martinistraße 52', '49074', 'Osnabrück', 'Niedersachsen', 'DE',
 52.2760, 8.0451, '0541 338 93 0', 'info@diakonie-osnabrueck.de', 'https://www.diakonie-osnabrueck.de',
 'Di und Do 10–14 Uhr',
 ARRAY['Kleidungsausgabe','Kinderkleidung','Flüchtlingshilfe'],
 ARRAY['kleiderkammer','osnabrück','kleidung'], true, true),

('Caritas Kleiderkammer Bochum', 'kleiderkammer',
 'Caritas Bochum stellt Bedürftigen kostenlose Kleidung zur Verfügung. Ausgabe wöchentlich.',
 'Propsteihof 10', '44787', 'Bochum', 'Nordrhein-Westfalen', 'DE',
 51.4820, 7.2170, '0234 9340 0', 'info@caritas-bochum.de', 'https://www.caritas-bochum.de',
 'Di und Fr 10–14 Uhr',
 ARRAY['Kleidungsausgabe','Sachspenden','Ehrenamt'],
 ARRAY['kleiderkammer','bochum','kleidung'], true, true),

-- ── ÖSTERREICH (10) ────────────────────────────────────────────────────────
('Caritas Kleiderkammer Wien', 'kleiderkammer',
 'Caritas Wien betreibt mehrere Kleiderkammern in Wien. Gratis Kleidung für Bedürftige, Obdachlose und Geflüchtete.',
 'Albrechtskreithgasse 19-21', '1160', 'Wien', 'Wien', 'AT',
 48.2093, 16.3167, '01 87812 0', 'kleiderkammer@caritas-wien.at', 'https://www.caritas.at',
 'Mo–Fr 9–16 Uhr',
 ARRAY['Kleidungsausgabe','Winterkleidung','Flüchtlingshilfe'],
 ARRAY['kleiderkammer','wien','kleidung'], true, true),

('Rotes Kreuz Kleiderkammer Wien', 'kleiderkammer',
 'Das Rote Kreuz Wien verteilt gespendete Kleidung an Bedürftige. Ausgabe an mehreren Standorten in Wien.',
 'Wiedner Hauptstraße 32', '1040', 'Wien', 'Wien', 'AT',
 48.1960, 16.3659, '01 589 00 0', 'kleiderkammer@w.roteskreuz.at', 'https://www.w.roteskreuz.at',
 'Di und Do 10–14 Uhr',
 ARRAY['Kleidungsausgabe','Kinderkleidung','Sachspenden'],
 ARRAY['kleiderkammer','wien','kleidung'], true, true),

('Diakonie Kleiderkammer Graz', 'kleiderkammer',
 'Die Diakonie Graz bietet kostenlose Kleidung für Bedürftige an. Ausgabe zweimal wöchentlich.',
 'Riesstraße 79', '8010', 'Graz', 'Steiermark', 'AT',
 47.0570, 15.4668, '0316 7060 0', 'info@diakonie-steiermark.at', 'https://www.diakonie-steiermark.at',
 'Di und Do 10–13 Uhr',
 ARRAY['Kleidungsausgabe','Sachspenden','Ehrenamt'],
 ARRAY['kleiderkammer','graz','kleidung'], true, true),

('Caritas Kleiderkammer Linz', 'kleiderkammer',
 'Caritas OÖ stellt Kleidung kostenlos für Bedürftige in Linz bereit. Schwerpunkt Kinder- und Winterkleidung.',
 'Kapuzinerstraße 84', '4020', 'Linz', 'Oberösterreich', 'AT',
 48.2972, 14.2784, '0732 7610 0', 'info@caritas-linz.at', 'https://www.caritas-linz.at',
 'Mo und Mi 10–13 Uhr',
 ARRAY['Kleidungsausgabe','Kinderkleidung','Winterkleidung'],
 ARRAY['kleiderkammer','linz','kleidung'], true, true),

('Rotes Kreuz Kleiderkammer Salzburg', 'kleiderkammer',
 'Das Rote Kreuz Salzburg verteilt Kleidung an Bedürftige und Geflüchtete im Stadtgebiet Salzburg.',
 'Strubergasse 36', '5020', 'Salzburg', 'Salzburg', 'AT',
 47.8045, 13.0323, '0662 4444 0', 'salzburg@roteskreuz.at', 'https://www.roteskreuz.at',
 'Di und Fr 10–13 Uhr',
 ARRAY['Kleidungsausgabe','Flüchtlingshilfe','Sachspenden'],
 ARRAY['kleiderkammer','salzburg','kleidung'], true, true),

('Caritas Kleiderkammer Innsbruck', 'kleiderkammer',
 'Caritas Tirol betreibt eine Kleiderkammer in Innsbruck für Bedürftige und Geflüchtete.',
 'Heiliggeiststraße 16', '6020', 'Innsbruck', 'Tirol', 'AT',
 47.2651, 11.3926, '0512 7270 0', 'info@caritas-tirol.at', 'https://www.caritas-tirol.at',
 'Mo und Do 10–14 Uhr',
 ARRAY['Kleidungsausgabe','Winterkleidung','Ehrenamt'],
 ARRAY['kleiderkammer','innsbruck','kleidung'], true, true),

('Diakonie Kleiderkammer Klagenfurt', 'kleiderkammer',
 'Die Diakonie Kärnten verteilt Kleidung an Bedürftige und Wohnungslose in Klagenfurt.',
 'Pfarrplatz 1', '9020', 'Klagenfurt', 'Kärnten', 'AT',
 46.6228, 14.3060, '0463 5571 0', 'info@diakonie-kaernten.at', 'https://www.diakonie-kaernten.at',
 'Di und Fr 10–13 Uhr',
 ARRAY['Kleidungsausgabe','Wohnungslosenhilfe','Sachspenden'],
 ARRAY['kleiderkammer','klagenfurt','kleidung'], true, true),

('AWÖ Kleiderkammer St. Pölten', 'kleiderkammer',
 'Die Arbeiterwohlfahrt NÖ bietet Kleidung für einkommensschwache Personen in St. Pölten an.',
 'Linzer Straße 8', '3100', 'St. Pölten', 'Niederösterreich', 'AT',
 48.2054, 15.6218, '02742 355 58 0', 'info@awoe-noe.at', 'https://www.awoe-noe.at',
 'Mi 10–14 Uhr',
 ARRAY['Kleidungsausgabe','Kinderkleidung','Ehrenamt'],
 ARRAY['kleiderkammer','st-pölten','kleidung'], true, true),

('Rotes Kreuz Kleiderkammer Villach', 'kleiderkammer',
 'Das Rote Kreuz Villach verteilt gespendete Kleidung an Bedürftige in Villach und Umland.',
 'Gaswerkstraße 8', '9500', 'Villach', 'Kärnten', 'AT',
 46.6085, 13.8550, '04242 25252 0', 'villach@roteskreuz.at', 'https://www.roteskreuz.at',
 'Do 10–13 Uhr',
 ARRAY['Kleidungsausgabe','Winterkleidung','Sachspenden'],
 ARRAY['kleiderkammer','villach','kleidung'], true, true),

('Caritas Kleiderkammer Wels', 'kleiderkammer',
 'Caritas OÖ betreibt in Wels eine Kleiderkammer für Bedürftige, Familien und Geflüchtete.',
 'Stadtplatz 1', '4600', 'Wels', 'Oberösterreich', 'AT',
 48.1572, 14.0238, '07242 41 43 0', 'info@caritas-linz.at', 'https://www.caritas-linz.at',
 'Di 10–13 Uhr',
 ARRAY['Kleidungsausgabe','Kinderkleidung','Flüchtlingshilfe'],
 ARRAY['kleiderkammer','wels','kleidung'], true, true),

-- ── SCHWEIZ (8) ──────────────────────────────────────────────────────────
('Caritas Zürich – Kleiderbörse', 'kleiderkammer',
 'Caritas Zürich betreibt Kleiderbörsen in Zürich, wo Kleidung günstig oder kostenlos abgegeben wird.',
 'Beckenhofstraße 16', '8006', 'Zürich', 'Zürich', 'CH',
 47.3840, 8.5389, '044 366 68 68', 'info@caritas-zh.ch', 'https://www.caritas-zuerich.ch',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Kleidungsausgabe','Kleiderbörse','Sachspenden'],
 ARRAY['kleiderkammer','zürich','kleidung'], true, true),

('Caritas Bern – Kleiderkammer', 'kleiderkammer',
 'Caritas Bern verteilt Kleidung an Bedürftige in der Region Bern. Ausgabe an mehreren Standorten.',
 'Dammweg 8-10', '3013', 'Bern', 'Bern', 'CH',
 46.9572, 7.4504, '031 380 65 65', 'info@caritasbern.ch', 'https://www.caritasbern.ch',
 'Di und Do 10–14 Uhr',
 ARRAY['Kleidungsausgabe','Kinderkleidung','Sachspenden'],
 ARRAY['kleiderkammer','bern','kleidung'], true, true),

('Rotes Kreuz Kleiderkammer Basel', 'kleiderkammer',
 'Das Schweizerische Rote Kreuz Basel verteilt gespendete Kleidung an Bedürftige und Geflüchtete.',
 'Murbacherstraße 11', '4013', 'Basel', 'Basel-Stadt', 'CH',
 47.5633, 7.5849, '061 269 33 11', 'srk-bs@redcross.ch', 'https://www.srk-beider-basel.ch',
 'Di 10–14 Uhr',
 ARRAY['Kleidungsausgabe','Flüchtlingshilfe','Sachspenden'],
 ARRAY['kleiderkammer','basel','kleidung'], true, true),

('Caritas Luzern – Kleiderkammer', 'kleiderkammer',
 'Caritas Luzern stellt Kleidung kostenlos für Bedürftige bereit. Kinderkleidung und Winterkleidung vorhanden.',
 'Kasernenplatz 3', '6003', 'Luzern', 'Luzern', 'CH',
 47.0469, 8.3100, '041 368 50 50', 'info@caritas-luzern.ch', 'https://www.caritas-luzern.ch',
 'Mo und Mi 10–13 Uhr',
 ARRAY['Kleidungsausgabe','Kinderkleidung','Winterkleidung'],
 ARRAY['kleiderkammer','luzern','kleidung'], true, true),

('Rotes Kreuz Kleiderkammer St. Gallen', 'kleiderkammer',
 'Das Rote Kreuz St. Gallen verteilt Kleidung an Bedürftige und Geflüchtete in der Region.',
 'Brühlgasse 11', '9000', 'St. Gallen', 'St. Gallen', 'CH',
 47.4224, 9.3757, '071 227 57 57', 'info@srk-sg.ch', 'https://www.srk-sg.ch',
 'Di und Fr 10–13 Uhr',
 ARRAY['Kleidungsausgabe','Flüchtlingshilfe','Sachspenden'],
 ARRAY['kleiderkammer','st-gallen','kleidung'], true, true),

('Winterhilfe Bern – Kleiderhilfe', 'kleiderkammer',
 'Winterhilfe Bern verteilt Kleidung und Bedarfsgüter an Bedürftige in der Region Bern.',
 'Casinoplatz 2', '3011', 'Bern', 'Bern', 'CH',
 46.9502, 7.4408, '031 310 47 80', 'info@winterhilfe-bern.ch', 'https://www.winterhilfe.ch',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Kleidungsausgabe','Winterkleidung','Sachspenden'],
 ARRAY['kleiderkammer','bern','winterhilfe'], true, true),

('Caritas Lausanne – Vêtements', 'kleiderkammer',
 'Caritas Vaud verteilt Kleidung an Bedürftige in der Region Lausanne. Ausgabe wöchentlich.',
 'Rue Marterey 45', '1005', 'Lausanne', 'Waadt', 'CH',
 46.5245, 6.6322, '021 316 30 30', 'info@caritas-vaud.ch', 'https://www.caritas-vaud.ch',
 'Di 10–14 Uhr',
 ARRAY['Kleidungsausgabe','Kinderkleidung','Sachspenden'],
 ARRAY['kleiderkammer','lausanne','kleidung'], true, true),

('Rotes Kreuz Kleiderkammer Winterthur', 'kleiderkammer',
 'Das Schweizerische Rote Kreuz Winterthur verteilt gespendete Kleidung an Bedürftige.',
 'Rudolfstraße 1', '8400', 'Winterthur', 'Zürich', 'CH',
 47.5007, 8.7239, '052 266 50 60', 'srk-winterthur@redcross.ch', 'https://www.srk-zuerich.ch',
 'Di und Do 10–14 Uhr',
 ARRAY['Kleidungsausgabe','Winterkleidung','Sachspenden'],
 ARRAY['kleiderkammer','winterthur','kleidung'], true, true);

END IF;
END $$;
