-- ============================================================
-- Migration 010g: Seniorenhilfe (50) + Flüchtlingshilfe (50)
-- Quellen: caritas.de, diakonie.de, caritas.at, unhcr.org, caritas.ch
-- ============================================================

-- Ensure all required categories are allowed before inserting
ALTER TABLE public.organizations DROP CONSTRAINT IF EXISTS organizations_category_check;
ALTER TABLE public.organizations ADD CONSTRAINT organizations_category_check CHECK (category IN (
  'tierheim','tierschutz','suppenkueche','obdachlosenhilfe',
  'tafel','kleiderkammer','sozialkaufhaus','krisentelefon',
  'notschlafstelle','jugend','jugendhilfe','senioren','seniorenhilfe',
  'behinderung','sucht','fluechtlingshilfe','allgemein'
));

DO $$ BEGIN
IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='organizations' AND table_schema='public') THEN

INSERT INTO public.organizations
  (name, category, description, address, zip_code, city, state, country,
   latitude, longitude, phone, email, website, opening_hours, services, tags, is_verified, is_active)
VALUES

-- ═══════════════════════════════════════════════════════════
-- SENIORENHILFE (50)
-- ═══════════════════════════════════════════════════════════

-- ── DEUTSCHLAND (32) ──────────────────────────────────────────────────────
('AWO Seniorenberatung Berlin', 'seniorenhilfe',
 'Die AWO Berlin bietet Seniorenberatung, Begegnungsstätten und ambulante Hilfen für ältere Menschen.',
 'Müllerstraße 163', '13353', 'Berlin', 'Berlin', 'DE',
 52.5527, 13.3588, '030 916 09 0', 'seniorenberatung@awo-berlin.de', 'https://www.awo-berlin.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Seniorenberatung','Begegnungsstätte','Ambulante Hilfe','Hausbesuche'],
 ARRAY['seniorenhilfe','berlin','awo'], true, true),

('Caritas Seniorenhilfe Hamburg', 'seniorenhilfe',
 'Caritas Hamburg bietet Seniorenberatung, Betreuung und Alltagshilfe für ältere Menschen in Hamburg.',
 'Danziger Straße 52', '20099', 'Hamburg', 'Hamburg', 'DE',
 53.5573, 10.0263, '040 2000 1000', 'senioren@caritas-hamburg.de', 'https://www.caritas-hamburg.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Seniorenberatung','Alltagshilfe','Hausbesuche','Betreuung'],
 ARRAY['seniorenhilfe','hamburg','caritas'], true, true),

('Diakonie Seniorenhilfe München', 'seniorenhilfe',
 'Diakonie München bietet umfassende Seniorenhilfe: Beratung, Betreuung, ambulante Dienste und Tagesbetreuung.',
 'Landwehrstraße 15', '80336', 'München', 'Bayern', 'DE',
 48.1359, 11.5564, '089 5171 0', 'senioren@diakonie-munich.de', 'https://www.diakonie-munich.de',
 'Mo–Fr 8–17 Uhr',
 ARRAY['Seniorenberatung','Tagesbetreuung','Ambulante Dienste','Hospiz'],
 ARRAY['seniorenhilfe','münchen','diakonie'], true, true),

('Caritas Seniorenhilfe Köln', 'seniorenhilfe',
 'Caritas Köln bietet Seniorenberatung, ambulante Betreuung und Begegnungsangebote für ältere Menschen.',
 'Schönsteinstraße 28', '50827', 'Köln', 'Nordrhein-Westfalen', 'DE',
 50.9590, 6.9128, '0221 20 40 0', 'senioren@caritas-koeln.de', 'https://www.caritas-koeln.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Seniorenberatung','Begegnungsstätte','Ambulante Hilfe'],
 ARRAY['seniorenhilfe','köln','caritas'], true, true),

('AWO Seniorenberatung Frankfurt', 'seniorenhilfe',
 'AWO Frankfurt bietet Seniorenberatung, ambulante Betreuung und Begegnungsstätten für ältere Menschen.',
 'Henschelstraße 11', '60314', 'Frankfurt am Main', 'Hessen', 'DE',
 50.1121, 8.7218, '069 298 07 0', 'senioren@awo-frankfurt.de', 'https://www.awo-frankfurt.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Seniorenberatung','Ambulante Hilfe','Begegnungsstätte'],
 ARRAY['seniorenhilfe','frankfurt','awo'], true, true),

('Diakonie Seniorenzentrum Stuttgart', 'seniorenhilfe',
 'Diakonie Stuttgart betreibt Seniorenzentren und bietet ambulante Betreuung und Beratung für ältere Menschen.',
 'Alexanderstraße 7', '70182', 'Stuttgart', 'Baden-Württemberg', 'DE',
 48.7780, 9.1882, '0711 229 77 0', 'senioren@diakonie-wuerttemberg.de', 'https://www.diakonie-wuerttemberg.de',
 'Mo–Fr 8–17 Uhr',
 ARRAY['Seniorenzentrum','Ambulante Betreuung','Tagesbetreuung','Beratung'],
 ARRAY['seniorenhilfe','stuttgart','diakonie'], true, true),

('Caritas Seniorenhilfe Düsseldorf', 'seniorenhilfe',
 'Caritas Düsseldorf bietet Seniorenberatung, ambulante Betreuung und Begegnungsangebote.',
 'Benrather Straße 10', '40213', 'Düsseldorf', 'Nordrhein-Westfalen', 'DE',
 51.2143, 6.7759, '0211 160 04 0', 'senioren@caritas-duesseldorf.de', 'https://www.caritas-duesseldorf.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Seniorenberatung','Begegnungsstätte','Ambulante Hilfe'],
 ARRAY['seniorenhilfe','düsseldorf','caritas'], true, true),

('AWO Seniorenhilfe Nürnberg', 'seniorenhilfe',
 'AWO Nürnberg bietet Seniorenberatung, Tagesbetreuung und ambulante Pflege für ältere Menschen in Nürnberg.',
 'Valznerweiherstraße 160', '90480', 'Nürnberg', 'Bayern', 'DE',
 49.4557, 11.1219, '0911 4506 0', 'senioren@awo-nuernberg.de', 'https://www.awo-nuernberg.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Seniorenberatung','Tagesbetreuung','Ambulante Pflege'],
 ARRAY['seniorenhilfe','nürnberg','awo'], true, true),

('Caritas Seniorenhilfe Dresden', 'seniorenhilfe',
 'Caritas Dresden bietet Seniorenberatung, ambulante Betreuung und Begegnungsangebote für ältere Menschen.',
 'Breitscheidstraße 7', '01237', 'Dresden', 'Sachsen', 'DE',
 51.0174, 13.7756, '0351 467 34 0', 'senioren@caritas-dresden.de', 'https://www.caritas-dresden.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Seniorenberatung','Ambulante Hilfe','Begegnungsstätte'],
 ARRAY['seniorenhilfe','dresden','caritas'], true, true),

('Diakonie Seniorenhilfe Leipzig', 'seniorenhilfe',
 'Diakonie Leipzig bietet umfassende Seniorenhilfe: Beratung, ambulante Betreuung und Tagesangebote.',
 'Gustav-Adolf-Straße 5', '04105', 'Leipzig', 'Sachsen', 'DE',
 51.3395, 12.3797, '0341 129 96 0', 'senioren@diakonie-leipzig.de', 'https://www.diakonie-leipzig.de',
 'Mo–Fr 8–17 Uhr',
 ARRAY['Seniorenberatung','Tagesbetreuung','Ambulante Hilfe'],
 ARRAY['seniorenhilfe','leipzig','diakonie'], true, true),

('AWO Seniorenhilfe Dortmund', 'seniorenhilfe',
 'AWO Dortmund bietet Seniorenberatung, Begegnungsstätten und ambulante Hilfe für ältere Menschen.',
 'Klönnestraße 2', '44137', 'Dortmund', 'Nordrhein-Westfalen', 'DE',
 51.5136, 7.4705, '0231 18 48 0', 'senioren@awo-dortmund.de', 'https://www.awo-dortmund.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Seniorenberatung','Begegnungsstätte','Ambulante Hilfe'],
 ARRAY['seniorenhilfe','dortmund','awo'], true, true),

('Caritas Seniorenhilfe Essen', 'seniorenhilfe',
 'Caritas Essen bietet Seniorenberatung, ambulante Betreuung und Begegnungsangebote für Senioren.',
 'Hachestraße 8', '45130', 'Essen', 'Nordrhein-Westfalen', 'DE',
 51.4441, 7.0099, '0201 2209 0', 'senioren@caritas-essen.de', 'https://www.caritas-essen.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Seniorenberatung','Ambulante Hilfe','Tagesbetreuung'],
 ARRAY['seniorenhilfe','essen','caritas'], true, true),

('Diakonie Seniorenhilfe Hannover', 'seniorenhilfe',
 'Diakonie Hannover bietet Seniorenberatung, ambulante Dienste und Begegnungsangebote für ältere Menschen.',
 'Ebhardtstraße 3A', '30159', 'Hannover', 'Niedersachsen', 'DE',
 52.3750, 9.7347, '0511 3687 0', 'senioren@diakonie-hannover.de', 'https://www.diakonie-hannover.de',
 'Mo–Fr 8–17 Uhr',
 ARRAY['Seniorenberatung','Ambulante Dienste','Begegnungsstätte'],
 ARRAY['seniorenhilfe','hannover','diakonie'], true, true),

('AWO Seniorenhilfe Bremen', 'seniorenhilfe',
 'AWO Bremen bietet Seniorenberatung, ambulante Betreuung und Begegnungsstätten für ältere Menschen.',
 'Pagentorner Straße 2', '28195', 'Bremen', 'Bremen', 'DE',
 53.0802, 8.8079, '0421 34 04 0', 'senioren@awo-bremen.de', 'https://www.awo-bremen.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Seniorenberatung','Begegnungsstätte','Ambulante Hilfe'],
 ARRAY['seniorenhilfe','bremen','awo'], true, true),

('Caritas Seniorenzentrum Augsburg', 'seniorenhilfe',
 'Caritas Augsburg betreibt Seniorenzentren und bietet ambulante Betreuung und Beratung für Senioren.',
 'Auf dem Kreuz 41', '86152', 'Augsburg', 'Bayern', 'DE',
 48.3616, 10.8987, '0821 3156 0', 'senioren@caritas-augsburg.de', 'https://www.caritas-augsburg.de',
 'Mo–Fr 8–17 Uhr',
 ARRAY['Seniorenzentrum','Ambulante Betreuung','Tagesbetreuung'],
 ARRAY['seniorenhilfe','augsburg','caritas'], true, true),

('Diakonie Seniorenhilfe Bielefeld', 'seniorenhilfe',
 'Diakonie Bielefeld bietet Seniorenberatung und ambulante Hilfe für ältere Menschen in Bielefeld.',
 'Rotebühlstraße 58', '33602', 'Bielefeld', 'Nordrhein-Westfalen', 'DE',
 52.0246, 8.5399, '0521 589 01 0', 'senioren@diakonie-bielefeld.de', 'https://www.diakonie-bielefeld.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Seniorenberatung','Ambulante Hilfe','Begegnungsstätte'],
 ARRAY['seniorenhilfe','bielefeld','diakonie'], true, true),

('AWO Seniorenhilfe Wuppertal', 'seniorenhilfe',
 'AWO Wuppertal bietet Seniorenberatung, Begegnungsstätten und ambulante Hilfe für ältere Menschen.',
 'Friedrich-Engels-Allee 25', '42285', 'Wuppertal', 'Nordrhein-Westfalen', 'DE',
 51.2623, 7.1760, '0202 2963 0', 'senioren@awo-wuppertal.de', 'https://www.awo-wuppertal.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Seniorenberatung','Begegnungsstätte','Ambulante Hilfe'],
 ARRAY['seniorenhilfe','wuppertal','awo'], true, true),

('Caritas Seniorenhilfe Freiburg', 'seniorenhilfe',
 'Caritas Freiburg bietet Seniorenberatung, ambulante Betreuung und Begegnungsangebote für Senioren.',
 'Herrenstraße 25', '79098', 'Freiburg', 'Baden-Württemberg', 'DE',
 47.9965, 7.8474, '0761 89690 0', 'senioren@caritas-freiburg.de', 'https://www.caritas-freiburg.de',
 'Mo–Fr 8–17 Uhr',
 ARRAY['Seniorenberatung','Ambulante Hilfe','Tagesbetreuung'],
 ARRAY['seniorenhilfe','freiburg','caritas'], true, true),

('Diakonie Seniorenhilfe Karlsruhe', 'seniorenhilfe',
 'Diakonie Karlsruhe bietet Seniorenberatung und ambulante Hilfe für ältere Menschen in Karlsruhe.',
 'Karl-Friedrich-Straße 9', '76133', 'Karlsruhe', 'Baden-Württemberg', 'DE',
 49.0078, 8.4042, '0721 9349 0', 'senioren@diakonie-karlsruhe.de', 'https://www.diakonie-karlsruhe.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Seniorenberatung','Ambulante Hilfe','Begegnungsstätte'],
 ARRAY['seniorenhilfe','karlsruhe','diakonie'], true, true),

('AWO Seniorenhilfe Mannheim', 'seniorenhilfe',
 'AWO Mannheim bietet Seniorenberatung, Begegnungsstätten und ambulante Hilfe für ältere Menschen.',
 'Mollstraße 13', '68165', 'Mannheim', 'Baden-Württemberg', 'DE',
 49.4919, 8.4867, '0621 401 81 0', 'senioren@awo-mannheim.de', 'https://www.awo-mannheim.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Seniorenberatung','Begegnungsstätte','Ambulante Hilfe'],
 ARRAY['seniorenhilfe','mannheim','awo'], true, true),

('Caritas Seniorenhilfe Bochum', 'seniorenhilfe',
 'Caritas Bochum bietet Seniorenberatung, ambulante Betreuung und Begegnungsangebote für Senioren.',
 'Propsteihof 10', '44787', 'Bochum', 'Nordrhein-Westfalen', 'DE',
 51.4820, 7.2170, '0234 9340 0', 'senioren@caritas-bochum.de', 'https://www.caritas-bochum.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Seniorenberatung','Ambulante Hilfe','Tagesbetreuung'],
 ARRAY['seniorenhilfe','bochum','caritas'], true, true),

('Diakonie Seniorenhilfe Kassel', 'seniorenhilfe',
 'Diakonie Kassel bietet Seniorenberatung und ambulante Hilfe für ältere Menschen in Nordhessen.',
 'Landgraf-Karl-Straße 22', '34131', 'Kassel', 'Hessen', 'DE',
 51.3014, 9.4802, '0561 788 00 0', 'senioren@diakonie-kassel.de', 'https://www.diakonie-kassel.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Seniorenberatung','Ambulante Hilfe','Begegnungsstätte'],
 ARRAY['seniorenhilfe','kassel','diakonie'], true, true),

('AWO Seniorenhilfe Mainz', 'seniorenhilfe',
 'AWO Mainz bietet Seniorenberatung, Begegnungsstätten und ambulante Unterstützung für ältere Menschen.',
 'Schillerstraße 20', '55116', 'Mainz', 'Rheinland-Pfalz', 'DE',
 50.0011, 8.2726, '06131 9834 0', 'senioren@awo-mainz.de', 'https://www.awo-mainz.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Seniorenberatung','Begegnungsstätte','Ambulante Hilfe'],
 ARRAY['seniorenhilfe','mainz','awo'], true, true),

('Caritas Seniorenhilfe Erfurt', 'seniorenhilfe',
 'Caritas Thüringen bietet Seniorenberatung, ambulante Betreuung und Begegnungsangebote in Erfurt.',
 'Gothaer Straße 35', '99094', 'Erfurt', 'Thüringen', 'DE',
 50.9696, 11.0022, '0361 212 34 56', 'senioren@caritas-thueringen.de', 'https://www.caritas-thueringen.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Seniorenberatung','Ambulante Hilfe','Tagesbetreuung'],
 ARRAY['seniorenhilfe','erfurt','caritas'], true, true),

('Diakonie Seniorenhilfe Magdeburg', 'seniorenhilfe',
 'Diakonie Sachsen-Anhalt bietet Seniorenberatung, ambulante Dienste und Begegnungsangebote.',
 'Olvenstedter Straße 3', '39108', 'Magdeburg', 'Sachsen-Anhalt', 'DE',
 52.1355, 11.6188, '0391 850 76 0', 'senioren@diakonie-magdeburg.de', 'https://www.diakonie-magdeburg.de',
 'Mo–Fr 8–17 Uhr',
 ARRAY['Seniorenberatung','Ambulante Dienste','Begegnungsstätte'],
 ARRAY['seniorenhilfe','magdeburg','diakonie'], true, true),

('AWO Seniorenhilfe Rostock', 'seniorenhilfe',
 'AWO Rostock bietet Seniorenberatung, Begegnungsstätten und ambulante Hilfe für ältere Menschen.',
 'Erich-Schlesinger-Straße 50', '18059', 'Rostock', 'Mecklenburg-Vorpommern', 'DE',
 54.0801, 12.0882, '0381 490 43 0', 'senioren@awo-rostock.de', 'https://www.awo-rostock.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Seniorenberatung','Begegnungsstätte','Ambulante Hilfe'],
 ARRAY['seniorenhilfe','rostock','awo'], true, true),

('Caritas Seniorenhilfe Kiel', 'seniorenhilfe',
 'Caritas Kiel bietet Seniorenberatung, ambulante Betreuung und Begegnungsangebote für Senioren.',
 'Holstenstraße 58', '24103', 'Kiel', 'Schleswig-Holstein', 'DE',
 54.3215, 10.1368, '0431 662 77 0', 'senioren@caritas-kiel.de', 'https://www.caritas-kiel.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Seniorenberatung','Ambulante Hilfe','Tagesbetreuung'],
 ARRAY['seniorenhilfe','kiel','caritas'], true, true),

('Diakonie Seniorenhilfe Lübeck', 'seniorenhilfe',
 'Diakonie Lübeck bietet Seniorenberatung und ambulante Dienste für ältere Menschen in Lübeck.',
 'Kronsforder Allee 15', '23560', 'Lübeck', 'Schleswig-Holstein', 'DE',
 53.8783, 10.6930, '0451 4005 0', 'senioren@diakonie-luebeck.de', 'https://www.diakonie-luebeck.de',
 'Mo–Fr 8–17 Uhr',
 ARRAY['Seniorenberatung','Ambulante Dienste','Begegnungsstätte'],
 ARRAY['seniorenhilfe','lübeck','diakonie'], true, true),

('AWO Seniorenhilfe Potsdam', 'seniorenhilfe',
 'AWO Potsdam bietet Seniorenberatung, Begegnungsstätten und ambulante Hilfe für ältere Menschen.',
 'Geschwister-Scholl-Straße 4', '14471', 'Potsdam', 'Brandenburg', 'DE',
 52.3901, 13.0618, '0331 200 86 0', 'senioren@awo-potsdam.de', 'https://www.awo-potsdam.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Seniorenberatung','Begegnungsstätte','Ambulante Hilfe'],
 ARRAY['seniorenhilfe','potsdam','awo'], true, true),

('Caritas Seniorenhilfe Saarbrücken', 'seniorenhilfe',
 'Caritas Saarbrücken bietet Seniorenberatung, ambulante Betreuung und Begegnungsangebote.',
 'Webergasse 4', '66111', 'Saarbrücken', 'Saarland', 'DE',
 49.2337, 6.9968, '0681 3000 0', 'senioren@caritas-saarbruecken.de', 'https://www.caritas-saarbruecken.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Seniorenberatung','Ambulante Hilfe','Tagesbetreuung'],
 ARRAY['seniorenhilfe','saarbrücken','caritas'], true, true),

('Diakonie Seniorenhilfe Chemnitz', 'seniorenhilfe',
 'Diakonie Chemnitz bietet Seniorenberatung, ambulante Betreuung und Begegnungsangebote für Senioren.',
 'Georgstraße 9', '09111', 'Chemnitz', 'Sachsen', 'DE',
 50.8307, 12.9208, '0371 670 56 0', 'senioren@diakonie-chemnitz.de', 'https://www.diakonie-chemnitz.de',
 'Mo–Fr 8–17 Uhr',
 ARRAY['Seniorenberatung','Ambulante Dienste','Begegnungsstätte'],
 ARRAY['seniorenhilfe','chemnitz','diakonie'], true, true),

-- ── ÖSTERREICH (10) ────────────────────────────────────────────────────────
('Caritas Seniorenhilfe Wien', 'seniorenhilfe',
 'Caritas Wien bietet umfassende Seniorenhilfe: Beratung, mobile Betreuung, Pflegedienste und Begegnungsstätten.',
 'Albrechtskreithgasse 19', '1160', 'Wien', 'Wien', 'AT',
 48.2093, 16.3167, '01 87812 0', 'senioren@caritas-wien.at', 'https://www.caritas.at',
 'Mo–Fr 8–17 Uhr',
 ARRAY['Seniorenberatung','Mobile Betreuung','Pflegedienste','Begegnungsstätte'],
 ARRAY['seniorenhilfe','wien','caritas'], true, true),

('Volkshilfe Seniorenhilfe Wien', 'seniorenhilfe',
 'Volkshilfe Wien bietet Seniorenhilfe, Alltagsbegleitung und mobile Pflegedienste für ältere Menschen.',
 'Stöbergasse 8', '1050', 'Wien', 'Wien', 'AT',
 48.1946, 16.3526, '01 589 98 0', 'senioren@volkshilfe-wien.at', 'https://www.volkshilfe-wien.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Seniorenberatung','Alltagsbegleitung','Mobile Pflegedienste'],
 ARRAY['seniorenhilfe','wien','volkshilfe'], true, true),

('Caritas Seniorenhilfe Graz', 'seniorenhilfe',
 'Caritas Graz bietet Seniorenberatung, ambulante Pflege und Begegnungsangebote für ältere Menschen in der Steiermark.',
 'Grabenstraße 39', '8010', 'Graz', 'Steiermark', 'AT',
 47.0707, 15.4394, '0316 8015 0', 'senioren@caritas-graz.at', 'https://www.caritas-graz.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Seniorenberatung','Ambulante Pflege','Begegnungsstätte'],
 ARRAY['seniorenhilfe','graz','caritas'], true, true),

('Rotes Kreuz Seniorenhilfe Linz', 'seniorenhilfe',
 'Das Rote Kreuz Linz bietet Seniorenberatung, Hauskrankenpflege und Fahrtendienste für ältere Menschen.',
 'Garnisonstraße 1', '4020', 'Linz', 'Oberösterreich', 'AT',
 48.3069, 14.2858, '0732 7644 0', 'senioren@roteskreuz-linz.at', 'https://www.roteskreuz.at',
 'Mo–Fr 8–17 Uhr',
 ARRAY['Seniorenberatung','Hauskrankenpflege','Fahrtendienst'],
 ARRAY['seniorenhilfe','linz','drk'], true, true),

('Diakonie Seniorenhilfe Salzburg', 'seniorenhilfe',
 'Diakonie Salzburg bietet Seniorenberatung, mobile Betreuung und Begegnungsangebote für ältere Menschen.',
 'Mühlbacherhofweg 4', '5020', 'Salzburg', 'Salzburg', 'AT',
 47.8060, 13.0396, '0662 8881 0', 'senioren@diakonie-salzburg.at', 'https://www.diakonie-salzburg.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Seniorenberatung','Mobile Betreuung','Begegnungsstätte'],
 ARRAY['seniorenhilfe','salzburg','diakonie'], true, true),

('Caritas Seniorenhilfe Innsbruck', 'seniorenhilfe',
 'Caritas Tirol bietet Seniorenberatung, ambulante Pflege und Begegnungsangebote für Senioren in Tirol.',
 'Heiliggeiststraße 16', '6020', 'Innsbruck', 'Tirol', 'AT',
 47.2651, 11.3926, '0512 7270 0', 'senioren@caritas-tirol.at', 'https://www.caritas-tirol.at',
 'Mo–Fr 8–17 Uhr',
 ARRAY['Seniorenberatung','Ambulante Pflege','Tagesbetreuung'],
 ARRAY['seniorenhilfe','innsbruck','caritas'], true, true),

('Volkshilfe Seniorenhilfe Graz', 'seniorenhilfe',
 'Volkshilfe Steiermark bietet Seniorenhilfe, mobile Dienste und Alltagsbegleitung für ältere Menschen.',
 'Plüddemanngasse 45', '8010', 'Graz', 'Steiermark', 'AT',
 47.0621, 15.4601, '0316 71 76 0', 'senioren@volkshilfe-stmk.at', 'https://www.volkshilfe-stmk.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Seniorenberatung','Mobile Dienste','Alltagsbegleitung'],
 ARRAY['seniorenhilfe','graz','volkshilfe'], true, true),

('Rotes Kreuz Seniorenhilfe Salzburg', 'seniorenhilfe',
 'Rotes Kreuz Salzburg bietet Seniorenberatung, Hauskrankenpflege und Fahrtendienste für ältere Menschen.',
 'Strubergasse 36', '5020', 'Salzburg', 'Salzburg', 'AT',
 47.8045, 13.0323, '0662 4444 0', 'senioren@salzburg.roteskreuz.at', 'https://www.roteskreuz.at',
 'Mo–Fr 8–17 Uhr',
 ARRAY['Seniorenberatung','Hauskrankenpflege','Fahrtendienst'],
 ARRAY['seniorenhilfe','salzburg','drk'], true, true),

('Caritas Seniorenhilfe Klagenfurt', 'seniorenhilfe',
 'Caritas Kärnten bietet Seniorenberatung, ambulante Betreuung und Begegnungsangebote in Kärnten.',
 'Sterneckstraße 26', '9020', 'Klagenfurt', 'Kärnten', 'AT',
 46.6148, 14.3100, '0463 5518 0', 'senioren@caritas-kaernten.at', 'https://www.caritas-kaernten.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Seniorenberatung','Ambulante Betreuung','Begegnungsstätte'],
 ARRAY['seniorenhilfe','klagenfurt','caritas'], true, true),

('Diakonie Seniorenhilfe St. Pölten', 'seniorenhilfe',
 'Diakonie NÖ bietet Seniorenberatung, mobile Pflegedienste und Tagesbetreuung für Senioren in NÖ.',
 'Linzer Straße 8', '3100', 'St. Pölten', 'Niederösterreich', 'AT',
 48.2054, 15.6218, '02742 71 730', 'senioren@diakonie-noe.at', 'https://www.diakonie-noe.at',
 'Mo–Fr 8–17 Uhr',
 ARRAY['Seniorenberatung','Mobile Pflegedienste','Tagesbetreuung'],
 ARRAY['seniorenhilfe','st-pölten','diakonie'], true, true),

-- ── SCHWEIZ (8) ──────────────────────────────────────────────────────────
('Spitex Zürich – Seniorenhilfe', 'seniorenhilfe',
 'Spitex Zürich bietet ambulante Pflege, Seniorenberatung und Alltagshilfe für ältere Menschen zu Hause.',
 'Rolandstraße 25', '8004', 'Zürich', 'Zürich', 'CH',
 47.3784, 8.5266, '044 412 42 50', 'info@spitex-zuerich.ch', 'https://www.spitex-zuerich.ch',
 'Mo–Fr 7–18 Uhr',
 ARRAY['Ambulante Pflege','Seniorenberatung','Alltagshilfe'],
 ARRAY['seniorenhilfe','zürich','spitex'], true, true),

('Caritas Seniorenhilfe Zürich', 'seniorenhilfe',
 'Caritas Zürich bietet Seniorenberatung, Alltagsbegleitung und ambulante Unterstützung für Senioren.',
 'Beckenhofstraße 16', '8006', 'Zürich', 'Zürich', 'CH',
 47.3840, 8.5389, '044 366 68 68', 'senioren@caritas-zh.ch', 'https://www.caritas-zuerich.ch',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Seniorenberatung','Alltagsbegleitung','Ambulante Unterstützung'],
 ARRAY['seniorenhilfe','zürich','caritas'], true, true),

('Pro Senectute Zürich', 'seniorenhilfe',
 'Pro Senectute Zürich ist die Hauptorganisation für Seniorenhilfe in Zürich. Beratung, Betreuung, Kurse.',
 'Auenstraße 4', '8600', 'Dübendorf', 'Zürich', 'CH',
 47.3968, 8.6182, '044 200 20 20', 'info@pszh.ch', 'https://www.pro-senectute.ch',
 'Mo–Fr 8–17 Uhr',
 ARRAY['Seniorenberatung','Tagesbetreuung','Kurse','Alltagsbegleitung'],
 ARRAY['seniorenhilfe','zürich','pro-senectute'], true, true),

('Pro Senectute Bern', 'seniorenhilfe',
 'Pro Senectute Bern bietet Seniorenberatung, Alltagshilfe und Begegnungsangebote für ältere Menschen.',
 'Thunstraße 3', '3005', 'Bern', 'Bern', 'CH',
 46.9454, 7.4668, '031 359 03 03', 'info@prosenectutebern.ch', 'https://www.pro-senectute.ch',
 'Mo–Fr 8–17 Uhr',
 ARRAY['Seniorenberatung','Alltagshilfe','Begegnungsangebote'],
 ARRAY['seniorenhilfe','bern','pro-senectute'], true, true),

('Spitex Basel – Seniorenhilfe', 'seniorenhilfe',
 'Spitex Basel bietet ambulante Pflege und Seniorenhilfe. Unterstützung für ältere Menschen zu Hause.',
 'Güterstraße 18', '4053', 'Basel', 'Basel-Stadt', 'CH',
 47.5484, 7.5938, '061 285 85 85', 'info@spitex-basel.ch', 'https://www.spitex-basel.ch',
 'Mo–Fr 7–18 Uhr',
 ARRAY['Ambulante Pflege','Seniorenberatung','Alltagshilfe'],
 ARRAY['seniorenhilfe','basel','spitex'], true, true),

('Pro Senectute Luzern', 'seniorenhilfe',
 'Pro Senectute Luzern bietet Seniorenberatung, Alltagsbegleitung und Freizeitangebote für Senioren.',
 'Wesemlinstraße 40', '6006', 'Luzern', 'Luzern', 'CH',
 47.0614, 8.3038, '041 226 00 66', 'info@prosenectute-luzern.ch', 'https://www.pro-senectute.ch',
 'Mo–Fr 8–17 Uhr',
 ARRAY['Seniorenberatung','Alltagsbegleitung','Freizeitangebote'],
 ARRAY['seniorenhilfe','luzern','pro-senectute'], true, true),

('Caritas Seniorenhilfe Bern', 'seniorenhilfe',
 'Caritas Bern bietet Seniorenberatung, Alltagsbegleitung und Besuchsdienste für ältere Menschen.',
 'Dammweg 8-10', '3013', 'Bern', 'Bern', 'CH',
 46.9572, 7.4504, '031 380 65 65', 'senioren@caritasbern.ch', 'https://www.caritasbern.ch',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Seniorenberatung','Alltagsbegleitung','Besuchsdienst'],
 ARRAY['seniorenhilfe','bern','caritas'], true, true),

('Pro Senectute St. Gallen', 'seniorenhilfe',
 'Pro Senectute St. Gallen bietet Seniorenberatung, Alltagshilfe und Begegnungsangebote in der Ostschweiz.',
 'Marktgasse 25', '9000', 'St. Gallen', 'St. Gallen', 'CH',
 47.4228, 9.3748, '071 228 67 67', 'info@prosenectute-sg.ch', 'https://www.pro-senectute.ch',
 'Mo–Fr 8–17 Uhr',
 ARRAY['Seniorenberatung','Alltagshilfe','Begegnungsangebote'],
 ARRAY['seniorenhilfe','st-gallen','pro-senectute'], true, true),

-- ═══════════════════════════════════════════════════════════
-- FLÜCHTLINGSHILFE (50)
-- ═══════════════════════════════════════════════════════════

-- ── DEUTSCHLAND (32) ──────────────────────────────────────────────────────
('Caritas Flüchtlingshilfe Berlin', 'fluechtlingshilfe',
 'Caritas Berlin bietet umfassende Beratung und Unterstützung für Geflüchtete: Asylrecht, Sprache, Integration.',
 'Residenzstraße 90', '13409', 'Berlin', 'Berlin', 'DE',
 52.5747, 13.3452, '030 666 33 0', 'fluechtlingshilfe@caritas-berlin.de', 'https://www.caritas-berlin.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Asylberatung','Sprachkurse','Integrationsberatung','Rechtshilfe'],
 ARRAY['flüchtlingshilfe','berlin','caritas'], true, true),

('Diakonie Flüchtlingsdienst Hamburg', 'fluechtlingshilfe',
 'Diakonie Hamburg bietet Flüchtlingsberatung, Asylberatung und Integrationshilfe für Geflüchtete.',
 'Poststraße 28', '20354', 'Hamburg', 'Hamburg', 'DE',
 53.5526, 9.9965, '040 37 41 12 70', 'fluechtlinge@diakonie-hamburg.de', 'https://www.diakonie-hamburg.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Asylberatung','Integrationsberatung','Sprachkurse','Rechtshilfe'],
 ARRAY['flüchtlingshilfe','hamburg','diakonie'], true, true),

('AWO Flüchtlingshilfe München', 'fluechtlingshilfe',
 'AWO München bietet Flüchtlingsberatung, Integrationshilfe und Sprachkurse für Geflüchtete in München.',
 'Guldeinstraße 26', '80339', 'München', 'Bayern', 'DE',
 48.1401, 11.5357, '089 519 50 0', 'fluechtlinge@awo-muenchen.de', 'https://www.awo-muenchen.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Flüchtlingsberatung','Sprachkurse','Integrationsberatung'],
 ARRAY['flüchtlingshilfe','münchen','awo'], true, true),

('Caritas Flüchtlingshilfe Köln', 'fluechtlingshilfe',
 'Caritas Köln bietet Flüchtlingsberatung, Asylrechtshilfe und Integrationsangebote für Geflüchtete.',
 'Schönsteinstraße 28', '50827', 'Köln', 'Nordrhein-Westfalen', 'DE',
 50.9590, 6.9128, '0221 20 40 0', 'fluechtlinge@caritas-koeln.de', 'https://www.caritas-koeln.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Asylberatung','Integrationsberatung','Sprachkurse','Rechtshilfe'],
 ARRAY['flüchtlingshilfe','köln','caritas'], true, true),

('Diakonie Flüchtlingshilfe Frankfurt', 'fluechtlingshilfe',
 'Diakonie Frankfurt bietet Flüchtlingsberatung, Asylberatung und Integrationshilfe für Geflüchtete.',
 'Kasseler Straße 1a', '60486', 'Frankfurt am Main', 'Hessen', 'DE',
 50.1189, 8.6440, '069 27 36 42 0', 'fluechtlinge@diakonie-frankfurt.de', 'https://www.diakonie-frankfurt.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Asylberatung','Sprachkurse','Integrationsberatung'],
 ARRAY['flüchtlingshilfe','frankfurt','diakonie'], true, true),

('Caritas Flüchtlingshilfe Stuttgart', 'fluechtlingshilfe',
 'Caritas Stuttgart bietet Flüchtlingsberatung, Asylrechtshilfe und Integrationsangebote.',
 'Strombergstraße 11', '70188', 'Stuttgart', 'Baden-Württemberg', 'DE',
 48.7877, 9.2039, '0711 2633 0', 'fluechtlinge@caritas-stuttgart.de', 'https://www.caritas-stuttgart.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Asylberatung','Integrationsberatung','Sprachkurse'],
 ARRAY['flüchtlingshilfe','stuttgart','caritas'], true, true),

('AWO Flüchtlingshilfe Düsseldorf', 'fluechtlingshilfe',
 'AWO Düsseldorf bietet Flüchtlingsberatung, Sprachkurse und Integrationshilfe für Geflüchtete.',
 'Liststraße 2', '40470', 'Düsseldorf', 'Nordrhein-Westfalen', 'DE',
 51.2493, 6.8034, '0211 301 72 0', 'fluechtlinge@awo-duesseldorf.de', 'https://www.awo-duesseldorf.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Flüchtlingsberatung','Sprachkurse','Integrationsberatung'],
 ARRAY['flüchtlingshilfe','düsseldorf','awo'], true, true),

('Diakonie Flüchtlingshilfe Nürnberg', 'fluechtlingshilfe',
 'Diakonie Nürnberg bietet Flüchtlingsberatung, Asylberatung und Integrationsangebote für Geflüchtete.',
 'Innere Cramer-Klett-Straße 16', '90403', 'Nürnberg', 'Bayern', 'DE',
 49.4566, 11.0842, '0911 23490 0', 'fluechtlinge@diakonie-nuernberg.de', 'https://www.diakonie-nuernberg.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Asylberatung','Sprachkurse','Integrationsberatung','Rechtshilfe'],
 ARRAY['flüchtlingshilfe','nürnberg','diakonie'], true, true),

('Caritas Flüchtlingshilfe Dresden', 'fluechtlingshilfe',
 'Caritas Dresden bietet Flüchtlingsberatung, Asylrechtshilfe und Integrationsbegleitung.',
 'Breitscheidstraße 7', '01237', 'Dresden', 'Sachsen', 'DE',
 51.0174, 13.7756, '0351 467 34 0', 'fluechtlinge@caritas-dresden.de', 'https://www.caritas-dresden.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Asylberatung','Integrationsberatung','Sprachkurse'],
 ARRAY['flüchtlingshilfe','dresden','caritas'], true, true),

('AWO Flüchtlingshilfe Leipzig', 'fluechtlingshilfe',
 'AWO Leipzig bietet Flüchtlingsberatung, Sprachkurse und Integrationshilfe für Geflüchtete in Leipzig.',
 'Konradstraße 66', '04315', 'Leipzig', 'Sachsen', 'DE',
 51.3368, 12.4161, '0341 231 74 40', 'fluechtlinge@awo-leipzig.de', 'https://www.awo-leipzig.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Flüchtlingsberatung','Sprachkurse','Integrationsberatung'],
 ARRAY['flüchtlingshilfe','leipzig','awo'], true, true),

('Diakonie Flüchtlingshilfe Dortmund', 'fluechtlingshilfe',
 'Diakonie Dortmund bietet Flüchtlingsberatung, Asylrechtshilfe und Integrationsangebote.',
 'Klönnestraße 2', '44137', 'Dortmund', 'Nordrhein-Westfalen', 'DE',
 51.5136, 7.4705, '0231 186 60 0', 'fluechtlinge@diakonie-dortmund.de', 'https://www.diakonie-dortmund.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Asylberatung','Integrationsberatung','Sprachkurse'],
 ARRAY['flüchtlingshilfe','dortmund','diakonie'], true, true),

('Caritas Flüchtlingshilfe Essen', 'fluechtlingshilfe',
 'Caritas Essen bietet Flüchtlingsberatung, Asylberatung und Integrationsangebote für Geflüchtete.',
 'Hachestraße 8', '45130', 'Essen', 'Nordrhein-Westfalen', 'DE',
 51.4441, 7.0099, '0201 2209 0', 'fluechtlinge@caritas-essen.de', 'https://www.caritas-essen.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Asylberatung','Sprachkurse','Integrationsberatung'],
 ARRAY['flüchtlingshilfe','essen','caritas'], true, true),

('AWO Flüchtlingshilfe Hannover', 'fluechtlingshilfe',
 'AWO Hannover bietet Flüchtlingsberatung, Sprachkurse und Integrationshilfe für Geflüchtete.',
 'Hamburger Allee 24', '30161', 'Hannover', 'Niedersachsen', 'DE',
 52.3846, 9.7384, '0511 121 90 0', 'fluechtlinge@awo-hannover.de', 'https://www.awo-hannover.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Flüchtlingsberatung','Sprachkurse','Integrationsberatung'],
 ARRAY['flüchtlingshilfe','hannover','awo'], true, true),

('Caritas Flüchtlingshilfe Bremen', 'fluechtlingshilfe',
 'Caritas Bremen bietet Flüchtlingsberatung, Asylrechtshilfe und Integrationsbegleitung für Geflüchtete.',
 'Herdentorsteinweg 21', '28195', 'Bremen', 'Bremen', 'DE',
 53.0789, 8.8078, '0421 33 79 90 0', 'fluechtlinge@caritas-bremen.de', 'https://www.caritas-bremen.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Asylberatung','Integrationsberatung','Sprachkurse','Rechtshilfe'],
 ARRAY['flüchtlingshilfe','bremen','caritas'], true, true),

('Diakonie Flüchtlingshilfe Augsburg', 'fluechtlingshilfe',
 'Diakonie Augsburg bietet Flüchtlingsberatung, Asylberatung und Integrationshilfe für Geflüchtete.',
 'Morellstraße 44', '86159', 'Augsburg', 'Bayern', 'DE',
 48.3726, 10.9012, '0821 9003 0', 'fluechtlinge@diakonie-augsburg.de', 'https://www.diakonie-augsburg.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Asylberatung','Sprachkurse','Integrationsberatung'],
 ARRAY['flüchtlingshilfe','augsburg','diakonie'], true, true),

('AWO Flüchtlingshilfe Bielefeld', 'fluechtlingshilfe',
 'AWO Bielefeld bietet Flüchtlingsberatung, Sprachkurse und Integrationshilfe für Geflüchtete.',
 'Niederwall 26', '33602', 'Bielefeld', 'Nordrhein-Westfalen', 'DE',
 52.0220, 8.5341, '0521 9286 0', 'fluechtlinge@awo-bielefeld.de', 'https://www.awo-bielefeld.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Flüchtlingsberatung','Sprachkurse','Integrationsberatung'],
 ARRAY['flüchtlingshilfe','bielefeld','awo'], true, true),

('Caritas Flüchtlingshilfe Freiburg', 'fluechtlingshilfe',
 'Caritas Freiburg bietet Flüchtlingsberatung, Asylrechtshilfe und Integrationsangebote.',
 'Herrenstraße 25', '79098', 'Freiburg', 'Baden-Württemberg', 'DE',
 47.9965, 7.8474, '0761 89690 0', 'fluechtlinge@caritas-freiburg.de', 'https://www.caritas-freiburg.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Asylberatung','Integrationsberatung','Sprachkurse'],
 ARRAY['flüchtlingshilfe','freiburg','caritas'], true, true),

('Diakonie Flüchtlingshilfe Karlsruhe', 'fluechtlingshilfe',
 'Diakonie Karlsruhe bietet Flüchtlingsberatung, Asylberatung und Integrationshilfe für Geflüchtete.',
 'Karl-Friedrich-Straße 9', '76133', 'Karlsruhe', 'Baden-Württemberg', 'DE',
 49.0078, 8.4042, '0721 9349 0', 'fluechtlinge@diakonie-karlsruhe.de', 'https://www.diakonie-karlsruhe.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Asylberatung','Sprachkurse','Integrationsberatung'],
 ARRAY['flüchtlingshilfe','karlsruhe','diakonie'], true, true),

('AWO Flüchtlingshilfe Mannheim', 'fluechtlingshilfe',
 'AWO Mannheim bietet Flüchtlingsberatung, Sprachkurse und Integrationshilfe für Geflüchtete.',
 'Mollstraße 13', '68165', 'Mannheim', 'Baden-Württemberg', 'DE',
 49.4919, 8.4867, '0621 401 81 0', 'fluechtlinge@awo-mannheim.de', 'https://www.awo-mannheim.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Flüchtlingsberatung','Sprachkurse','Integrationsberatung'],
 ARRAY['flüchtlingshilfe','mannheim','awo'], true, true),

('Caritas Flüchtlingshilfe Wuppertal', 'fluechtlingshilfe',
 'Caritas Wuppertal bietet Flüchtlingsberatung, Asylrechtshilfe und Integrationsangebote.',
 'Hünefeldstraße 12', '42103', 'Wuppertal', 'Nordrhein-Westfalen', 'DE',
 51.2571, 7.1514, '0202 2470 0', 'fluechtlinge@caritas-wuppertal.de', 'https://www.caritas-wuppertal.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Asylberatung','Integrationsberatung','Sprachkurse'],
 ARRAY['flüchtlingshilfe','wuppertal','caritas'], true, true),

('Diakonie Flüchtlingshilfe Bochum', 'fluechtlingshilfe',
 'Diakonie Bochum bietet Flüchtlingsberatung, Asylberatung und Integrationshilfe für Geflüchtete.',
 'Hattinger Straße 6', '44789', 'Bochum', 'Nordrhein-Westfalen', 'DE',
 51.4799, 7.2158, '0234 32 71 0', 'fluechtlinge@diakonie-bochum.de', 'https://www.diakonie-bochum.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Asylberatung','Sprachkurse','Integrationsberatung','Rechtshilfe'],
 ARRAY['flüchtlingshilfe','bochum','diakonie'], true, true),

('AWO Flüchtlingshilfe Kassel', 'fluechtlingshilfe',
 'AWO Kassel bietet Flüchtlingsberatung, Sprachkurse und Integrationshilfe für Geflüchtete in Nordhessen.',
 'Wolfhager Straße 1', '34117', 'Kassel', 'Hessen', 'DE',
 51.3150, 9.4797, '0561 7391 0', 'fluechtlinge@awo-kassel.de', 'https://www.awo-kassel.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Flüchtlingsberatung','Sprachkurse','Integrationsberatung'],
 ARRAY['flüchtlingshilfe','kassel','awo'], true, true),

('Caritas Flüchtlingshilfe Mainz', 'fluechtlingshilfe',
 'Caritas Mainz bietet Flüchtlingsberatung, Asylrechtshilfe und Integrationsbegleitung.',
 'Kaiserstraße 37', '55116', 'Mainz', 'Rheinland-Pfalz', 'DE',
 50.0002, 8.2741, '06131 28750', 'fluechtlinge@caritas-mainz.de', 'https://www.caritas-mainz.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Asylberatung','Integrationsberatung','Sprachkurse'],
 ARRAY['flüchtlingshilfe','mainz','caritas'], true, true),

('Diakonie Flüchtlingshilfe Erfurt', 'fluechtlingshilfe',
 'Diakonie Thüringen bietet Flüchtlingsberatung, Asylberatung und Integrationshilfe für Geflüchtete.',
 'Puschkinstraße 4', '99084', 'Erfurt', 'Thüringen', 'DE',
 50.9791, 11.0359, '0361 5514 0', 'fluechtlinge@diakonie-thueringen.de', 'https://www.diakonie-thueringen.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Asylberatung','Sprachkurse','Integrationsberatung'],
 ARRAY['flüchtlingshilfe','erfurt','diakonie'], true, true),

('Caritas Flüchtlingshilfe Magdeburg', 'fluechtlingshilfe',
 'Caritas Sachsen-Anhalt bietet Flüchtlingsberatung, Asylrechtshilfe und Integrationsangebote.',
 'Thälmannstraße 50', '39104', 'Magdeburg', 'Sachsen-Anhalt', 'DE',
 52.1325, 11.6393, '0391 5448 0', 'fluechtlinge@caritas-magdeburg.de', 'https://www.caritas-magdeburg.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Asylberatung','Integrationsberatung','Sprachkurse','Rechtshilfe'],
 ARRAY['flüchtlingshilfe','magdeburg','caritas'], true, true),

('AWO Flüchtlingshilfe Rostock', 'fluechtlingshilfe',
 'AWO Rostock bietet Flüchtlingsberatung, Sprachkurse und Integrationshilfe für Geflüchtete in MV.',
 'Erich-Schlesinger-Straße 50', '18059', 'Rostock', 'Mecklenburg-Vorpommern', 'DE',
 54.0801, 12.0882, '0381 490 43 0', 'fluechtlinge@awo-rostock.de', 'https://www.awo-rostock.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Flüchtlingsberatung','Sprachkurse','Integrationsberatung'],
 ARRAY['flüchtlingshilfe','rostock','awo'], true, true),

('Diakonie Flüchtlingshilfe Kiel', 'fluechtlingshilfe',
 'Diakonie Kiel bietet Flüchtlingsberatung, Asylberatung und Integrationshilfe für Geflüchtete.',
 'Holstenstraße 72', '24103', 'Kiel', 'Schleswig-Holstein', 'DE',
 54.3205, 10.1322, '0431 9740 0', 'fluechtlinge@diakonie-kiel.de', 'https://www.diakonie-kiel.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Asylberatung','Sprachkurse','Integrationsberatung'],
 ARRAY['flüchtlingshilfe','kiel','diakonie'], true, true),

('Caritas Flüchtlingshilfe Saarbrücken', 'fluechtlingshilfe',
 'Caritas Saarbrücken bietet Flüchtlingsberatung, Asylrechtshilfe und Integrationsangebote.',
 'Webergasse 4', '66111', 'Saarbrücken', 'Saarland', 'DE',
 49.2337, 6.9968, '0681 3000 0', 'fluechtlinge@caritas-saarbruecken.de', 'https://www.caritas-saarbruecken.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Asylberatung','Integrationsberatung','Sprachkurse'],
 ARRAY['flüchtlingshilfe','saarbrücken','caritas'], true, true),

('AWO Flüchtlingshilfe Chemnitz', 'fluechtlingshilfe',
 'AWO Chemnitz bietet Flüchtlingsberatung, Sprachkurse und Integrationshilfe für Geflüchtete in Chemnitz.',
 'Morgenleite 47', '09122', 'Chemnitz', 'Sachsen', 'DE',
 50.8210, 12.9514, '0371 2305 0', 'fluechtlinge@awo-chemnitz.de', 'https://www.awo-chemnitz.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Flüchtlingsberatung','Sprachkurse','Integrationsberatung'],
 ARRAY['flüchtlingshilfe','chemnitz','awo'], true, true),

-- ── ÖSTERREICH (10) ────────────────────────────────────────────────────────
('Caritas Flüchtlingshilfe Wien', 'fluechtlingshilfe',
 'Caritas Wien bietet umfassende Flüchtlingshilfe: Asylberatung, Integrationsbegleitung, Sprachkurse, Rechtshilfe.',
 'Albrechtskreithgasse 19', '1160', 'Wien', 'Wien', 'AT',
 48.2093, 16.3167, '01 87812 0', 'fluechtlinge@caritas-wien.at', 'https://www.caritas.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Asylberatung','Integrationsbegleitung','Sprachkurse','Rechtshilfe'],
 ARRAY['flüchtlingshilfe','wien','caritas'], true, true),

('Diakonie Flüchtlingsdienst Wien', 'fluechtlingshilfe',
 'Diakonie Österreich bietet Flüchtlingsberatung, Asylrechtshilfe und Integrationshilfe in Wien.',
 'Steinergasse 3', '1170', 'Wien', 'Wien', 'AT',
 48.2167, 16.3242, '01 40 84 80', 'fluechtlinge@diakonie.at', 'https://www.diakonie.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Asylberatung','Integrationsberatung','Sprachkurse'],
 ARRAY['flüchtlingshilfe','wien','diakonie'], true, true),

('Volkshilfe Flüchtlingshilfe Wien', 'fluechtlingshilfe',
 'Volkshilfe Wien bietet Flüchtlingsberatung, Asylberatung und Integrationshilfe für Geflüchtete.',
 'Stöbergasse 8', '1050', 'Wien', 'Wien', 'AT',
 48.1946, 16.3526, '01 589 98 0', 'fluechtlinge@volkshilfe-wien.at', 'https://www.volkshilfe-wien.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Asylberatung','Sprachkurse','Integrationsberatung','Rechtshilfe'],
 ARRAY['flüchtlingshilfe','wien','volkshilfe'], true, true),

('Caritas Flüchtlingshilfe Graz', 'fluechtlingshilfe',
 'Caritas Graz bietet Flüchtlingsberatung, Asylrechtshilfe und Integrationsbegleitung in der Steiermark.',
 'Grabenstraße 39', '8010', 'Graz', 'Steiermark', 'AT',
 47.0707, 15.4394, '0316 8015 0', 'fluechtlinge@caritas-graz.at', 'https://www.caritas-graz.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Asylberatung','Integrationsbegleitung','Sprachkurse'],
 ARRAY['flüchtlingshilfe','graz','caritas'], true, true),

('Rotes Kreuz Flüchtlingshilfe Linz', 'fluechtlingshilfe',
 'Das Rote Kreuz Linz bietet Flüchtlingsberatung, Asylberatung und Integrationsangebote für Geflüchtete.',
 'Garnisonstraße 1', '4020', 'Linz', 'Oberösterreich', 'AT',
 48.3069, 14.2858, '0732 7644 0', 'fluechtlinge@roteskreuz-linz.at', 'https://www.roteskreuz.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Asylberatung','Sprachkurse','Integrationsberatung'],
 ARRAY['flüchtlingshilfe','linz','drk'], true, true),

('Diakonie Flüchtlingshilfe Salzburg', 'fluechtlingshilfe',
 'Diakonie Salzburg bietet Flüchtlingsberatung, Asylrechtshilfe und Integrationshilfe für Geflüchtete.',
 'Mühlbacherhofweg 4', '5020', 'Salzburg', 'Salzburg', 'AT',
 47.8060, 13.0396, '0662 8881 0', 'fluechtlinge@diakonie-salzburg.at', 'https://www.diakonie-salzburg.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Asylberatung','Integrationsberatung','Sprachkurse'],
 ARRAY['flüchtlingshilfe','salzburg','diakonie'], true, true),

('Caritas Flüchtlingshilfe Innsbruck', 'fluechtlingshilfe',
 'Caritas Tirol bietet Flüchtlingsberatung, Asylberatung und Integrationsangebote für Geflüchtete in Tirol.',
 'Heiliggeiststraße 16', '6020', 'Innsbruck', 'Tirol', 'AT',
 47.2651, 11.3926, '0512 7270 0', 'fluechtlinge@caritas-tirol.at', 'https://www.caritas-tirol.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Asylberatung','Sprachkurse','Integrationsberatung','Rechtshilfe'],
 ARRAY['flüchtlingshilfe','innsbruck','caritas'], true, true),

('Volkshilfe Flüchtlingshilfe Steiermark', 'fluechtlingshilfe',
 'Volkshilfe Steiermark bietet Flüchtlingsberatung, Asylrechtshilfe und Integrationshilfe für Geflüchtete.',
 'Plüddemanngasse 45', '8010', 'Graz', 'Steiermark', 'AT',
 47.0621, 15.4601, '0316 71 76 0', 'fluechtlinge@volkshilfe-stmk.at', 'https://www.volkshilfe-stmk.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Asylberatung','Integrationsberatung','Sprachkurse'],
 ARRAY['flüchtlingshilfe','graz','volkshilfe'], true, true),

('Caritas Flüchtlingshilfe Klagenfurt', 'fluechtlingshilfe',
 'Caritas Kärnten bietet Flüchtlingsberatung, Asylrechtshilfe und Integrationsbegleitung in Kärnten.',
 'Sterneckstraße 26', '9020', 'Klagenfurt', 'Kärnten', 'AT',
 46.6148, 14.3100, '0463 5518 0', 'fluechtlinge@caritas-kaernten.at', 'https://www.caritas-kaernten.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Asylberatung','Sprachkurse','Integrationsberatung'],
 ARRAY['flüchtlingshilfe','klagenfurt','caritas'], true, true),

('Diakonie Flüchtlingshilfe St. Pölten', 'fluechtlingshilfe',
 'Diakonie NÖ bietet Flüchtlingsberatung, Asylberatung und Integrationshilfe für Geflüchtete in NÖ.',
 'Linzer Straße 8', '3100', 'St. Pölten', 'Niederösterreich', 'AT',
 48.2054, 15.6218, '02742 71 730', 'fluechtlinge@diakonie-noe.at', 'https://www.diakonie-noe.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Asylberatung','Integrationsberatung','Sprachkurse'],
 ARRAY['flüchtlingshilfe','st-pölten','diakonie'], true, true),

-- ── SCHWEIZ (8) ──────────────────────────────────────────────────────────
('Caritas Flüchtlingshilfe Zürich', 'fluechtlingshilfe',
 'Caritas Zürich bietet umfassende Flüchtlingshilfe: Asylberatung, Integrationsbegleitung und Sprachkurse.',
 'Beckenhofstraße 16', '8006', 'Zürich', 'Zürich', 'CH',
 47.3840, 8.5389, '044 366 68 68', 'fluechtlinge@caritas-zh.ch', 'https://www.caritas-zuerich.ch',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Asylberatung','Integrationsbegleitung','Sprachkurse','Rechtshilfe'],
 ARRAY['flüchtlingshilfe','zürich','caritas'], true, true),

('HEKS Flüchtlingshilfe Zürich', 'fluechtlingshilfe',
 'HEKS (Hilfswerk der Evangelischen Kirchen Schweiz) bietet Flüchtlingshilfe und Integrationsangebote.',
 'Seminarstraße 28', '8057', 'Zürich', 'Zürich', 'CH',
 47.3965, 8.5422, '044 360 88 00', 'info@heks.ch', 'https://www.heks.ch',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Asylberatung','Integrationsberatung','Sprachkurse'],
 ARRAY['flüchtlingshilfe','zürich','heks'], true, true),

('Caritas Flüchtlingshilfe Bern', 'fluechtlingshilfe',
 'Caritas Bern bietet Flüchtlingsberatung, Asylrechtshilfe und Integrationsangebote für Geflüchtete.',
 'Dammweg 8-10', '3013', 'Bern', 'Bern', 'CH',
 46.9572, 7.4504, '031 380 65 65', 'fluechtlinge@caritasbern.ch', 'https://www.caritasbern.ch',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Asylberatung','Integrationsberatung','Sprachkurse','Rechtshilfe'],
 ARRAY['flüchtlingshilfe','bern','caritas'], true, true),

('HEKS Flüchtlingshilfe Bern', 'fluechtlingshilfe',
 'HEKS Bern bietet Flüchtlingsberatung, Asylberatung und Integrationsangebote für Geflüchtete in Bern.',
 'Schänzlihalde 3', '3013', 'Bern', 'Bern', 'CH',
 46.9577, 7.4450, '031 300 28 00', 'bern@heks.ch', 'https://www.heks.ch',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Asylberatung','Integrationsberatung','Sprachkurse'],
 ARRAY['flüchtlingshilfe','bern','heks'], true, true),

('Rotes Kreuz Flüchtlingshilfe Basel', 'fluechtlingshilfe',
 'Rotes Kreuz Basel bietet Flüchtlingsberatung, Asylberatung und Integrationsangebote für Geflüchtete.',
 'Murbacherstraße 11', '4013', 'Basel', 'Basel-Stadt', 'CH',
 47.5633, 7.5849, '061 269 33 11', 'fluechtlinge@srk-bb.ch', 'https://www.srk-beider-basel.ch',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Asylberatung','Sprachkurse','Integrationsberatung'],
 ARRAY['flüchtlingshilfe','basel','drk'], true, true),

('Caritas Flüchtlingshilfe Luzern', 'fluechtlingshilfe',
 'Caritas Luzern bietet Flüchtlingsberatung, Asylrechtshilfe und Integrationsangebote für Geflüchtete.',
 'Kasernenplatz 3', '6003', 'Luzern', 'Luzern', 'CH',
 47.0469, 8.3100, '041 368 50 50', 'fluechtlinge@caritas-luzern.ch', 'https://www.caritas-luzern.ch',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Asylberatung','Integrationsberatung','Sprachkurse','Rechtshilfe'],
 ARRAY['flüchtlingshilfe','luzern','caritas'], true, true),

('HEKS Flüchtlingshilfe St. Gallen', 'fluechtlingshilfe',
 'HEKS St. Gallen bietet Flüchtlingsberatung, Asylberatung und Integrationsangebote für die Ostschweiz.',
 'Brühlgasse 11', '9000', 'St. Gallen', 'St. Gallen', 'CH',
 47.4224, 9.3757, '071 244 13 66', 'stgallen@heks.ch', 'https://www.heks.ch',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Asylberatung','Integrationsberatung','Sprachkurse'],
 ARRAY['flüchtlingshilfe','st-gallen','heks'], true, true),

('Caritas Flüchtlingshilfe Genf', 'fluechtlingshilfe',
 'Caritas Genève bietet umfassende Flüchtlingshilfe: Asylberatung, Integrationsangebote und Sprachkurse.',
 'Rue Baulacre 23', '1202', 'Genf', 'Genf', 'CH',
 46.2088, 6.1401, '022 579 00 00', 'fluechtlinge@caritas-geneve.ch', 'https://www.caritas-geneve.ch',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Asylberatung','Integrationsbegleitung','Sprachkurse','Rechtshilfe'],
 ARRAY['flüchtlingshilfe','genf','caritas'], true, true);

END IF;
END $$;
