-- ============================================================================
-- Schema-Drift-Baseline — auto-generated by Claude (2026-06-06)
-- ----------------------------------------------------------------------------
-- Gleicht das Production-Schema (gyqujitkvymlmgroovch) mit den Migrationen ab.
-- Über Monate wurden Schema-Änderungen direkt auf Prod gemacht, die nie als
-- Migration versioniert wurden. Fresh-Replays auf Supabase-Preview-Branches
-- scheiterten deshalb (z.B. 20260601120000_marketplace_comments referenziert
-- marketplace_listings.user_id, das in keiner Migration deklariert war).
--
-- Diese Migration ist vollständig idempotent:
--   • Auf Production = no-op (alle Spalten/Tabellen existieren bereits).
--   • Auf Preview / Fresh = fügt fehlende Spalten und Tabellen nachträglich
--     hinzu, bevor spätere Migrationen sie referenzieren.
--
-- Constraints / RLS / Policies werden bewusst NICHT versucht — nur Spalten
-- und ggf. komplett fehlende Tabellen. Spätere Migrationen können beliebige
-- Indizes/Policies darüber legen.
-- ============================================================================

-- pgcrypto + uuid-ossp werden für gen_random_uuid() / uuid_generate_v4() benötigt.
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ----------------------------------------------------------------------------
-- 1) Fehlende Spalten auf existierenden Tabellen
-- ----------------------------------------------------------------------------

-- badges
ALTER TABLE public.badges
  ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

-- board_posts
ALTER TABLE public.board_posts
  ADD COLUMN IF NOT EXISTS fts tsvector;

-- chat_banned_users
ALTER TABLE public.chat_banned_users
  ADD COLUMN IF NOT EXISTS channel_id uuid REFERENCES public.chat_channels(id) ON DELETE CASCADE;

-- conversation_members
ALTER TABLE public.conversation_members
  ADD COLUMN IF NOT EXISTS is_muted boolean DEFAULT false;
ALTER TABLE public.conversation_members
  ADD COLUMN IF NOT EXISTS muted_until timestamptz;
ALTER TABLE public.conversation_members
  ADD COLUMN IF NOT EXISTS vanish_mode boolean DEFAULT false;

-- conversations
ALTER TABLE public.conversations
  ADD COLUMN IF NOT EXISTS vanish_mode_enabled boolean DEFAULT false;
ALTER TABLE public.conversations
  ADD COLUMN IF NOT EXISTS vanish_seconds integer DEFAULT 3600;

-- crises
ALTER TABLE public.crises
  ADD COLUMN IF NOT EXISTS ai_summary text;
ALTER TABLE public.crises
  ADD COLUMN IF NOT EXISTS ai_summary_at timestamptz;

-- dm_calls
ALTER TABLE public.dm_calls
  ADD COLUMN IF NOT EXISTS callee_hidden_at timestamptz;
ALTER TABLE public.dm_calls
  ADD COLUMN IF NOT EXISTS caller_hidden_at timestamptz;
ALTER TABLE public.dm_calls
  ADD COLUMN IF NOT EXISTS duration_seconds integer;

-- email_campaigns
ALTER TABLE public.email_campaigns
  ADD COLUMN IF NOT EXISTS ab_group text;
ALTER TABLE public.email_campaigns
  ADD COLUMN IF NOT EXISTS ab_variant text;
ALTER TABLE public.email_campaigns
  ADD COLUMN IF NOT EXISTS body_html text;
ALTER TABLE public.email_campaigns
  ADD COLUMN IF NOT EXISTS body_text text;
ALTER TABLE public.email_campaigns
  ADD COLUMN IF NOT EXISTS failure_count integer DEFAULT 0;
ALTER TABLE public.email_campaigns
  ADD COLUMN IF NOT EXISTS preheader text;
ALTER TABLE public.email_campaigns
  ADD COLUMN IF NOT EXISTS success_count integer DEFAULT 0;

-- email_opens
ALTER TABLE public.email_opens
  ADD COLUMN IF NOT EXISTS user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE;

-- events
ALTER TABLE public.events
  ADD COLUMN IF NOT EXISTS is_online boolean DEFAULT false;
ALTER TABLE public.events
  ADD COLUMN IF NOT EXISTS online_url text;
ALTER TABLE public.events
  ADD COLUMN IF NOT EXISTS parent_event_id uuid REFERENCES public.events(id) ON DELETE NO ACTION;
ALTER TABLE public.events
  ADD COLUMN IF NOT EXISTS recurrence_parent_id uuid REFERENCES public.events(id) ON DELETE SET NULL;
ALTER TABLE public.events
  ADD COLUMN IF NOT EXISTS recurrence_rule text;

-- group_posts
ALTER TABLE public.group_posts
  ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

-- groups
ALTER TABLE public.groups
  ADD COLUMN IF NOT EXISTS cover_image_url text;
ALTER TABLE public.groups
  ADD COLUMN IF NOT EXISTS created_by uuid REFERENCES public.profiles(id) ON DELETE CASCADE;
ALTER TABLE public.groups
  ADD COLUMN IF NOT EXISTS is_archived boolean DEFAULT false;
ALTER TABLE public.groups
  ADD COLUMN IF NOT EXISTS is_public boolean DEFAULT true;
ALTER TABLE public.groups
  ADD COLUMN IF NOT EXISTS latitude double precision;
ALTER TABLE public.groups
  ADD COLUMN IF NOT EXISTS longitude double precision;
ALTER TABLE public.groups
  ADD COLUMN IF NOT EXISTS max_members integer DEFAULT 100;
ALTER TABLE public.groups
  ADD COLUMN IF NOT EXISTS radius_km integer DEFAULT 5;

-- live_rooms
ALTER TABLE public.live_rooms
  ADD COLUMN IF NOT EXISTS category text;
ALTER TABLE public.live_rooms
  ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE public.live_rooms
  ADD COLUMN IF NOT EXISTS max_viewers integer DEFAULT 0;
ALTER TABLE public.live_rooms
  ADD COLUMN IF NOT EXISTS recording_url text;
ALTER TABLE public.live_rooms
  ADD COLUMN IF NOT EXISTS scheduled_for timestamptz;
ALTER TABLE public.live_rooms
  ADD COLUMN IF NOT EXISTS thumbnail_url text;
ALTER TABLE public.live_rooms
  ADD COLUMN IF NOT EXISTS viewer_count integer DEFAULT 0;

-- marketplace_listings
ALTER TABLE public.marketplace_listings
  ADD COLUMN IF NOT EXISTS condition text;
ALTER TABLE public.marketplace_listings
  ADD COLUMN IF NOT EXISTS deleted_at timestamptz;
ALTER TABLE public.marketplace_listings
  ADD COLUMN IF NOT EXISTS expires_at timestamptz DEFAULT (now() + '30 days'::interval);
ALTER TABLE public.marketplace_listings
  ADD COLUMN IF NOT EXISTS favorite_count integer DEFAULT 0;
ALTER TABLE public.marketplace_listings
  ADD COLUMN IF NOT EXISTS fts tsvector;
ALTER TABLE public.marketplace_listings
  ADD COLUMN IF NOT EXISTS images text[] DEFAULT '{}'::text[];
ALTER TABLE public.marketplace_listings
  ADD COLUMN IF NOT EXISTS latitude double precision;
ALTER TABLE public.marketplace_listings
  ADD COLUMN IF NOT EXISTS listing_type text;
ALTER TABLE public.marketplace_listings
  ADD COLUMN IF NOT EXISTS longitude double precision;
ALTER TABLE public.marketplace_listings
  ADD COLUMN IF NOT EXISTS radius_km integer DEFAULT 10;
ALTER TABLE public.marketplace_listings
  ADD COLUMN IF NOT EXISTS reserved_for uuid REFERENCES public.profiles(id) ON DELETE SET NULL;
ALTER TABLE public.marketplace_listings
  ADD COLUMN IF NOT EXISTS tags text[] DEFAULT '{}'::text[];
ALTER TABLE public.marketplace_listings
  ADD COLUMN IF NOT EXISTS thumbnail_url text;
ALTER TABLE public.marketplace_listings
  ADD COLUMN IF NOT EXISTS user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE;
ALTER TABLE public.marketplace_listings
  ADD COLUMN IF NOT EXISTS view_count integer DEFAULT 0;

-- match_preferences
ALTER TABLE public.match_preferences
  ADD COLUMN IF NOT EXISTS excluded_categories text[] DEFAULT '{}'::text[];

-- messages
ALTER TABLE public.messages
  ADD COLUMN IF NOT EXISTS auto_delete_at timestamptz;

-- notifications
ALTER TABLE public.notifications
  ADD COLUMN IF NOT EXISTS priority text DEFAULT 'normal'::text;

-- organization_reviews
ALTER TABLE public.organization_reviews
  ADD COLUMN IF NOT EXISTS admin_responded_at timestamptz;
ALTER TABLE public.organization_reviews
  ADD COLUMN IF NOT EXISTS is_flagged boolean DEFAULT false;

-- organizations
ALTER TABLE public.organizations
  ADD COLUMN IF NOT EXISTS opening_hours_text text;
ALTER TABLE public.organizations
  ADD COLUMN IF NOT EXISTS rating_sum integer DEFAULT 0;

-- post_comments
ALTER TABLE public.post_comments
  ADD COLUMN IF NOT EXISTS deleted_at timestamptz;

-- posts
ALTER TABLE public.posts
  ADD COLUMN IF NOT EXISTS availability_days text[];
ALTER TABLE public.posts
  ADD COLUMN IF NOT EXISTS availability_end time;
ALTER TABLE public.posts
  ADD COLUMN IF NOT EXISTS availability_start time;
ALTER TABLE public.posts
  ADD COLUMN IF NOT EXISTS comment_count integer DEFAULT 0;
ALTER TABLE public.posts
  ADD COLUMN IF NOT EXISTS deleted_at timestamptz;
ALTER TABLE public.posts
  ADD COLUMN IF NOT EXISTS expires_at timestamptz;
ALTER TABLE public.posts
  ADD COLUMN IF NOT EXISTS fts tsvector;
ALTER TABLE public.posts
  ADD COLUMN IF NOT EXISTS is_example boolean DEFAULT false;
ALTER TABLE public.posts
  ADD COLUMN IF NOT EXISTS is_pinned boolean DEFAULT false;
ALTER TABLE public.posts
  ADD COLUMN IF NOT EXISTS is_recurring boolean DEFAULT false;
ALTER TABLE public.posts
  ADD COLUMN IF NOT EXISTS media_urls text[];
ALTER TABLE public.posts
  ADD COLUMN IF NOT EXISTS meeting_point text;
ALTER TABLE public.posts
  ADD COLUMN IF NOT EXISTS module_key text;
ALTER TABLE public.posts
  ADD COLUMN IF NOT EXISTS module_slug text;
ALTER TABLE public.posts
  ADD COLUMN IF NOT EXISTS post_intent text DEFAULT 'general'::text;
ALTER TABLE public.posts
  ADD COLUMN IF NOT EXISTS reaction_count integer DEFAULT 0;
ALTER TABLE public.posts
  ADD COLUMN IF NOT EXISTS recurring_interval text;
ALTER TABLE public.posts
  ADD COLUMN IF NOT EXISTS scheduled_at timestamptz;
ALTER TABLE public.posts
  ADD COLUMN IF NOT EXISTS scheduled_for timestamptz;
ALTER TABLE public.posts
  ADD COLUMN IF NOT EXISTS time_hours numeric;

-- profiles
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS banned_at timestamptz;
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS banned_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL;
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS country text DEFAULT 'DE'::text;
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS dashboard_config jsonb DEFAULT '{}'::jsonb;
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS emergency_contact_1_name text;
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS emergency_contact_1_phone text;
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS emergency_contact_2_name text;
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS emergency_contact_2_phone text;
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS inactive_reminder_count integer DEFAULT 0;
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS is_verified boolean DEFAULT false;
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS karma_points integer DEFAULT 0;
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS last_login_at timestamptz;
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS last_seen_at timestamptz;
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS level text DEFAULT 'nachbar'::text;
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS neighborhood_group_id uuid REFERENCES public.groups(id) ON DELETE SET NULL;
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS onboarding_completed boolean DEFAULT false;
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS points integer DEFAULT 0;
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS preferred_modules text[];
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS region text;
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS show_profile_views boolean DEFAULT true;
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS status_emoji text;
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS status_text text;
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS status_until timestamptz;
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS timezone text DEFAULT 'Europe/Berlin'::text;
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS username text;
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS verified_at timestamptz;
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS verified_community boolean DEFAULT false;
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS verified_email boolean DEFAULT false;
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS verified_phone boolean DEFAULT false;

-- reports
ALTER TABLE public.reports
  ADD COLUMN IF NOT EXISTS reviewed_at timestamptz;
ALTER TABLE public.reports
  ADD COLUMN IF NOT EXISTS reviewed_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL;

-- saved_posts
ALTER TABLE public.saved_posts
  ADD COLUMN IF NOT EXISTS collection_id uuid REFERENCES public.save_collections(id) ON DELETE SET NULL;

-- skill_offers
ALTER TABLE public.skill_offers
  ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
ALTER TABLE public.skill_offers
  ADD COLUMN IF NOT EXISTS is_online boolean DEFAULT false;
ALTER TABLE public.skill_offers
  ADD COLUMN IF NOT EXISTS location_address text;
ALTER TABLE public.skill_offers
  ADD COLUMN IF NOT EXISTS location_lat double precision;
ALTER TABLE public.skill_offers
  ADD COLUMN IF NOT EXISTS location_lng double precision;
ALTER TABLE public.skill_offers
  ADD COLUMN IF NOT EXISTS radius_km integer DEFAULT 10;

-- testimonials
ALTER TABLE public.testimonials
  ADD COLUMN IF NOT EXISTS consent_public boolean DEFAULT false;
ALTER TABLE public.testimonials
  ADD COLUMN IF NOT EXISTS interaction_id uuid REFERENCES public.interactions(id) ON DELETE SET NULL;
ALTER TABLE public.testimonials
  ADD COLUMN IF NOT EXISTS rating smallint;

-- user_notification_prefs
ALTER TABLE public.user_notification_prefs
  ADD COLUMN IF NOT EXISTS daily_digest_enabled boolean DEFAULT false;
ALTER TABLE public.user_notification_prefs
  ADD COLUMN IF NOT EXISTS daily_digest_hour integer DEFAULT 8;

-- ----------------------------------------------------------------------------
-- 2) Tabellen, die auf Prod existieren, aber in keiner Migration deklariert sind
-- (Topologisch sortiert: referenzierte Tabellen kommen zuerst.)
-- ----------------------------------------------------------------------------

-- account_deletion_requests
CREATE TABLE IF NOT EXISTS public.account_deletion_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  requested_at timestamptz NOT NULL DEFAULT now(),
  scheduled_for timestamptz NOT NULL DEFAULT (now() + '14 days'::interval),
  reason text,
  cancelled boolean NOT NULL DEFAULT false
);

-- admin_activity_log
CREATE TABLE IF NOT EXISTS public.admin_activity_log (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  admin_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  action_type text NOT NULL,
  target_type text,
  target_id uuid,
  details jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now()
);

-- ai_chat_analytics
CREATE TABLE IF NOT EXISTS public.ai_chat_analytics (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  provider text,
  nav_key text,
  had_knowledge boolean NOT NULL DEFAULT false,
  lang text NOT NULL DEFAULT 'de'::text,
  created_at timestamptz NOT NULL DEFAULT now(),
  feature text
);

-- ai_chat_feedback
CREATE TABLE IF NOT EXISTS public.ai_chat_feedback (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  rating smallint,
  question text,
  answer text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- app_settings
CREATE TABLE IF NOT EXISTS public.app_settings (
  key text PRIMARY KEY,
  value jsonb NOT NULL DEFAULT '{}'::jsonb,
  description text,
  updated_at timestamptz DEFAULT now(),
  updated_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL
);

-- book_exchanges
CREATE TABLE IF NOT EXISTS public.book_exchanges (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  title text NOT NULL,
  author text,
  description text,
  image_url text,
  location_text text,
  latitude double precision,
  longitude double precision,
  exchange_type text NOT NULL DEFAULT 'give'::text,
  status text NOT NULL DEFAULT 'available'::text,
  created_at timestamptz DEFAULT now()
);

-- call_voicemails
CREATE TABLE IF NOT EXISTS public.call_voicemails (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  caller_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  callee_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  audio_url text NOT NULL,
  duration_seconds integer NOT NULL DEFAULT 0,
  is_listened boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- community_polls
CREATE TABLE IF NOT EXISTS public.community_polls (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  creator_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  question text NOT NULL,
  options jsonb NOT NULL DEFAULT '[]'::jsonb,
  is_anonymous boolean NOT NULL DEFAULT false,
  closes_at timestamptz,
  status text NOT NULL DEFAULT 'active'::text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- community_recaps
CREATE TABLE IF NOT EXISTS public.community_recaps (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  week_start date,
  content text,
  stats jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  share_text text
);

-- crash_logs
CREATE TABLE IF NOT EXISTS public.crash_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  platform text NOT NULL,
  app_version text,
  build_number integer,
  error_type text NOT NULL,
  error_message text NOT NULL,
  stack_trace text,
  context jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- crisis_alerts
CREATE TABLE IF NOT EXISTS public.crisis_alerts (
  id uuid PRIMARY KEY,
  creator_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  title text,
  description text,
  category text,
  urgency text,
  status text,
  location_text text,
  latitude double precision,
  longitude double precision,
  radius_km double precision,
  affected_count integer,
  image_urls text[],
  contact_phone text,
  contact_name text,
  is_anonymous boolean,
  is_verified boolean,
  verified_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  verified_at timestamptz,
  resolved_at timestamptz,
  resolved_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  false_alarm_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  helper_count integer,
  needed_helpers integer,
  needed_skills text[],
  needed_resources text[],
  created_at timestamptz,
  updated_at timestamptz
);

-- crisis_resources
CREATE TABLE IF NOT EXISTS public.crisis_resources (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  crisis_id uuid NOT NULL,
  provider_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  resource_type text NOT NULL,
  title text NOT NULL,
  description text,
  quantity text,
  location_text text,
  latitude double precision,
  longitude double precision,
  status text DEFAULT 'available'::text,
  reserved_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- crisis_volunteers
CREATE TABLE IF NOT EXISTS public.crisis_volunteers (
  id uuid PRIMARY KEY,
  crisis_id uuid,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  status text,
  message text,
  skills text[],
  eta_minutes integer,
  latitude double precision,
  longitude double precision,
  created_at timestamptz,
  updated_at timestamptz
);

-- daily_challenges
CREATE TABLE IF NOT EXISTS public.daily_challenges (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  challenge_type text NOT NULL,
  challenge_text text NOT NULL,
  karma_reward integer NOT NULL DEFAULT 5,
  is_completed boolean NOT NULL DEFAULT false,
  completed_at timestamptz,
  date date NOT NULL DEFAULT CURRENT_DATE,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- email_confirmations
CREATE TABLE IF NOT EXISTS public.email_confirmations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  token text NOT NULL,
  confirmed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- email_preferences
CREATE TABLE IF NOT EXISTS public.email_preferences (
  user_id uuid PRIMARY KEY,
  weekly_digest boolean NOT NULL DEFAULT true,
  product_updates boolean NOT NULL DEFAULT true,
  welcome_sent_at timestamptz,
  unsubscribe_token text NOT NULL DEFAULT encode(gen_random_bytes(24), 'hex'::text),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- email_segments
CREATE TABLE IF NOT EXISTS public.email_segments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  filter_type text NOT NULL,
  filter_config jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- email_sends
CREATE TABLE IF NOT EXISTS public.email_sends (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  campaign_id uuid REFERENCES public.email_campaigns(id) ON DELETE CASCADE,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  email text NOT NULL,
  template text NOT NULL,
  status text NOT NULL,
  error text,
  sent_at timestamptz NOT NULL DEFAULT now()
);

-- error_logs
CREATE TABLE IF NOT EXISTS public.error_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  platform text NOT NULL DEFAULT 'flutter'::text,
  error_type text NOT NULL,
  message text NOT NULL,
  stack text,
  app_version text,
  device_info text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- event_checkins
CREATE TABLE IF NOT EXISTS public.event_checkins (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id uuid REFERENCES public.events(id) ON DELETE CASCADE NOT NULL,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  checked_in_at timestamptz NOT NULL DEFAULT now()
);

-- event_photos
CREATE TABLE IF NOT EXISTS public.event_photos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id uuid REFERENCES public.events(id) ON DELETE CASCADE NOT NULL,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  image_url text NOT NULL,
  caption text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- farm_favorites
CREATE TABLE IF NOT EXISTS public.farm_favorites (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  farm_id uuid REFERENCES public.farm_listings(id) ON DELETE CASCADE NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- feature_flags
CREATE TABLE IF NOT EXISTS public.feature_flags (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  enabled boolean DEFAULT false,
  percentage integer DEFAULT 0,
  description text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- followed_tags
CREATE TABLE IF NOT EXISTS public.followed_tags (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  tag text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- friendships
CREATE TABLE IF NOT EXISTS public.friendships (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  requester_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  addressee_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  created_at timestamptz NOT NULL DEFAULT now(),
  responded_at timestamptz
);

-- gratitude_entries
CREATE TABLE IF NOT EXISTS public.gratitude_entries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  content text NOT NULL,
  is_public boolean DEFAULT false,
  tagged_user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- group_invitations
CREATE TABLE IF NOT EXISTS public.group_invitations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  group_id uuid REFERENCES public.groups(id) ON DELETE CASCADE NOT NULL,
  invited_by uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  invited_user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  status text DEFAULT 'pending'::text,
  created_at timestamptz DEFAULT now()
);

-- group_post_comments
CREATE TABLE IF NOT EXISTS public.group_post_comments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id uuid REFERENCES public.group_posts(id) ON DELETE CASCADE NOT NULL,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  content text NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- karma_levels
CREATE TABLE IF NOT EXISTS public.karma_levels (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  level integer NOT NULL,
  name text NOT NULL,
  min_score integer NOT NULL,
  icon text NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- karma_log
CREATE TABLE IF NOT EXISTS public.karma_log (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  delta integer NOT NULL,
  reason text NOT NULL,
  reference_type text,
  reference_id uuid,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- knowledge_article_reads
CREATE TABLE IF NOT EXISTS public.knowledge_article_reads (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  article_id uuid REFERENCES public.knowledge_articles(id) ON DELETE CASCADE NOT NULL,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  scroll_pct numeric NOT NULL DEFAULT 0,
  is_completed boolean NOT NULL DEFAULT false,
  last_read_at timestamptz NOT NULL DEFAULT now()
);

-- knowledge_article_revisions
CREATE TABLE IF NOT EXISTS public.knowledge_article_revisions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  article_id uuid REFERENCES public.knowledge_articles(id) ON DELETE CASCADE NOT NULL,
  content text NOT NULL,
  editor_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- live_locations
CREATE TABLE IF NOT EXISTS public.live_locations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id uuid REFERENCES public.conversations(id) ON DELETE CASCADE NOT NULL,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  latitude double precision NOT NULL,
  longitude double precision NOT NULL,
  expires_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now()
);

-- livestream_clips
CREATE TABLE IF NOT EXISTS public.livestream_clips (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  room_id uuid REFERENCES public.live_rooms(id) ON DELETE CASCADE NOT NULL,
  creator_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  clip_url text NOT NULL,
  duration_seconds integer NOT NULL DEFAULT 30,
  title text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- livestream_gifts
CREATE TABLE IF NOT EXISTS public.livestream_gifts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  room_id uuid REFERENCES public.live_rooms(id) ON DELETE CASCADE NOT NULL,
  sender_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  gift_type text NOT NULL,
  karma_cost integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- livestream_messages
CREATE TABLE IF NOT EXISTS public.livestream_messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  room_id uuid REFERENCES public.live_rooms(id) ON DELETE CASCADE NOT NULL,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  content text NOT NULL,
  type text NOT NULL DEFAULT 'text'::text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- livestream_polls
CREATE TABLE IF NOT EXISTS public.livestream_polls (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  room_id uuid REFERENCES public.live_rooms(id) ON DELETE CASCADE NOT NULL,
  question text NOT NULL,
  options jsonb NOT NULL DEFAULT '[]'::jsonb,
  closes_at timestamptz NOT NULL DEFAULT (now() + '00:01:00'::interval),
  created_at timestamptz NOT NULL DEFAULT now()
);

-- lost_pets
CREATE TABLE IF NOT EXISTS public.lost_pets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  pet_name text NOT NULL,
  species text NOT NULL,
  breed text,
  description text,
  image_urls text[] DEFAULT '{}'::text[],
  last_seen_text text,
  last_seen_lat double precision,
  last_seen_lng double precision,
  last_seen_at timestamptz,
  contact_phone text,
  status text NOT NULL DEFAULT 'missing'::text,
  found_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- marketing_calendar
CREATE TABLE IF NOT EXISTS public.marketing_calendar (
  id uuid PRIMARY KEY,
  channel text,
  title text,
  status text,
  scheduled_at timestamptz,
  created_at timestamptz
);

-- marketplace_favorites
CREATE TABLE IF NOT EXISTS public.marketplace_favorites (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  listing_id uuid REFERENCES public.marketplace_listings(id) ON DELETE CASCADE NOT NULL,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- marketplace_messages
CREATE TABLE IF NOT EXISTS public.marketplace_messages (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  listing_id uuid REFERENCES public.marketplace_listings(id) ON DELETE CASCADE NOT NULL,
  sender_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  receiver_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  content text NOT NULL,
  is_read boolean DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- marketplace_reports
CREATE TABLE IF NOT EXISTS public.marketplace_reports (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  listing_id uuid REFERENCES public.marketplace_listings(id) ON DELETE CASCADE NOT NULL,
  reporter_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  reason text NOT NULL,
  details text,
  status text DEFAULT 'pending'::text,
  created_at timestamptz DEFAULT now()
);

-- marketplace_reservations
CREATE TABLE IF NOT EXISTS public.marketplace_reservations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  listing_id uuid REFERENCES public.marketplace_listings(id) ON DELETE CASCADE NOT NULL,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  message text,
  status text NOT NULL DEFAULT 'pending'::text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- message_templates
CREATE TABLE IF NOT EXISTS public.message_templates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  kind text NOT NULL,
  subject text,
  body_html text,
  body_text text,
  description text,
  created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- mood_entries
CREATE TABLE IF NOT EXISTS public.mood_entries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  mood_level integer NOT NULL,
  note text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- post_contact_preferences
CREATE TABLE IF NOT EXISTS public.post_contact_preferences (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id uuid REFERENCES public.posts(id) ON DELETE CASCADE NOT NULL,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  allow_in_app_chat boolean NOT NULL DEFAULT true,
  allow_phone boolean NOT NULL DEFAULT false,
  allow_email boolean NOT NULL DEFAULT false,
  allow_whatsapp boolean NOT NULL DEFAULT false,
  allow_location_meetup boolean NOT NULL DEFAULT false,
  phone_number text,
  email_address text,
  whatsapp_number text,
  meetup_note text,
  available_from time,
  available_until time,
  available_days text[],
  contact_note text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- post_contact_requests
CREATE TABLE IF NOT EXISTS public.post_contact_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id uuid REFERENCES public.posts(id) ON DELETE CASCADE NOT NULL,
  requester_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  post_owner_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  contact_method text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  message text,
  responded_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- post_drafts
CREATE TABLE IF NOT EXISTS public.post_drafts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  draft_data jsonb NOT NULL,
  updated_at timestamptz DEFAULT now()
);

-- post_polls
CREATE TABLE IF NOT EXISTS public.post_polls (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id uuid REFERENCES public.posts(id) ON DELETE CASCADE NOT NULL,
  question text NOT NULL,
  options jsonb NOT NULL DEFAULT '[]'::jsonb,
  closes_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- post_templates
CREATE TABLE IF NOT EXISTS public.post_templates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  type text NOT NULL,
  title text NOT NULL,
  description text NOT NULL,
  category text,
  suggested_tags text[],
  is_active boolean DEFAULT true,
  created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  approved_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT now()
);

-- profile_views
CREATE TABLE IF NOT EXISTS public.profile_views (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  viewer_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  viewed_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- rate_limits
CREATE TABLE IF NOT EXISTS public.rate_limits (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  action text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- reactivation_log
CREATE TABLE IF NOT EXISTS public.reactivation_log (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  stage smallint NOT NULL,
  sent_at timestamptz NOT NULL DEFAULT now()
);

-- rides
CREATE TABLE IF NOT EXISTS public.rides (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  driver_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  title text NOT NULL,
  from_text text NOT NULL,
  from_lat double precision,
  from_lng double precision,
  to_text text NOT NULL,
  to_lat double precision,
  to_lng double precision,
  departure_at timestamptz NOT NULL,
  seats_available integer NOT NULL DEFAULT 1,
  seats_taken integer NOT NULL DEFAULT 0,
  note text,
  status text NOT NULL DEFAULT 'open'::text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- save_collections
CREATE TABLE IF NOT EXISTS public.save_collections (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  name text NOT NULL,
  emoji text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- saved_events
CREATE TABLE IF NOT EXISTS public.saved_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  event_id uuid REFERENCES public.events(id) ON DELETE CASCADE NOT NULL,
  reminder_minutes_before integer,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- scheduled_calls
CREATE TABLE IF NOT EXISTS public.scheduled_calls (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  caller_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  callee_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  scheduled_at timestamptz NOT NULL,
  call_type text NOT NULL DEFAULT 'audio'::text,
  is_cancelled boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- scheduled_streams
CREATE TABLE IF NOT EXISTS public.scheduled_streams (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  host_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  title text NOT NULL,
  description text,
  scheduled_at timestamptz NOT NULL,
  room_name text,
  cover_url text,
  is_cancelled boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- stories
CREATE TABLE IF NOT EXISTS public.stories (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  media_url text NOT NULL,
  media_type text NOT NULL DEFAULT 'image'::text,
  text_overlay text,
  expires_at timestamptz NOT NULL DEFAULT (now() + '24:00:00'::interval),
  view_count integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- thank_you_cards
CREATE TABLE IF NOT EXISTS public.thank_you_cards (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sender_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  receiver_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  interaction_id uuid REFERENCES public.interactions(id) ON DELETE SET NULL,
  design_id integer NOT NULL DEFAULT 1,
  message text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- user_safety_checkins
CREATE TABLE IF NOT EXISTS public.user_safety_checkins (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  crisis_id uuid REFERENCES public.crises(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'safe'::text,
  note text,
  latitude double precision,
  longitude double precision,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- user_streaks
CREATE TABLE IF NOT EXISTS public.user_streaks (
  user_id uuid PRIMARY KEY,
  current_streak integer NOT NULL DEFAULT 0,
  longest_streak integer NOT NULL DEFAULT 0,
  last_active_date date,
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- community_poll_votes
CREATE TABLE IF NOT EXISTS public.community_poll_votes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  poll_id uuid REFERENCES public.community_polls(id) ON DELETE CASCADE NOT NULL,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  option_index integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- livestream_poll_votes
CREATE TABLE IF NOT EXISTS public.livestream_poll_votes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  poll_id uuid REFERENCES public.livestream_polls(id) ON DELETE CASCADE NOT NULL,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  option_index integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- post_poll_votes
CREATE TABLE IF NOT EXISTS public.post_poll_votes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  poll_id uuid REFERENCES public.post_polls(id) ON DELETE CASCADE NOT NULL,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  option_index integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ride_passengers
CREATE TABLE IF NOT EXISTS public.ride_passengers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ride_id uuid REFERENCES public.rides(id) ON DELETE CASCADE NOT NULL,
  passenger_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  status text NOT NULL DEFAULT 'requested'::text,
  created_at timestamptz DEFAULT now()
);

-- scheduled_stream_reminders
CREATE TABLE IF NOT EXISTS public.scheduled_stream_reminders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  stream_id uuid REFERENCES public.scheduled_streams(id) ON DELETE CASCADE NOT NULL,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- story_views
CREATE TABLE IF NOT EXISTS public.story_views (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  story_id uuid REFERENCES public.stories(id) ON DELETE CASCADE NOT NULL,
  viewer_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- stream_clips
CREATE TABLE IF NOT EXISTS public.stream_clips (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  stream_id uuid REFERENCES public.scheduled_streams(id) ON DELETE CASCADE NOT NULL,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  title text,
  start_seconds integer NOT NULL DEFAULT 0,
  duration_seconds integer NOT NULL DEFAULT 30,
  url text,
  created_at timestamptz NOT NULL DEFAULT now()
);
