-- ============================================================
-- Migration 010a: Tierheime – 50 Eintraege DE/AT/CH
-- Quellen: tierschutzbund.de, tierheim-finder, vier-pfoten.at
-- ============================================================

DO $$ BEGIN
IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='organizations' AND table_schema='public') THEN

INSERT INTO public.organizations
  (name, category, description, address, zip_code, city, state, country,
   latitude, longitude, phone, email, website, opening_hours, services, tags, is_verified, is_active)
VALUES

-- ── DEUTSCHLAND (30) ──────────────────────────────────────────────────────
('Tierheim Berlin', 'tierheim',
 'Groesstes Tierheim Europas mit ueber 1300 Tieren. Hunde, Katzen, Kleintiere, Voegel und Reptilien werden aufgenommen und vermittelt.',
 'Hausvaterweg 39', '13057', 'Berlin', 'Berlin', 'DE',
 52.5616, 13.4813, '030 76888-0', 'info@tierschutz-berlin.de', 'https://www.tierschutz-berlin.de',
 'Mo–Fr 10–17 Uhr, Sa–So 10–16 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Tierarztversorgung','Kastrationshilfe'],
 ARRAY['tierheim','hunde','katzen','kleintiere'], true, true),

('Hamburger Tierschutzverein Tierheim Süderstrasse', 'tierheim',
 'Traditionsreiches Tierheim in Hamburg mit umfangreichem Vermittlungsangebot fuer alle Tierarten.',
 'Süderstraße 47', '20097', 'Hamburg', 'Hamburg', 'DE',
 53.5497, 10.0219, '040 227 7390', 'info@tierschutzverein-hamburg.de', 'https://tierschutzverein-hamburg.de',
 'Mo–So 11–17 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Beratung','Tierarzt vor Ort'],
 ARRAY['tierheim','hamburg','hunde','katzen'], true, true),

('Tierheim Muenchen – Muenchner Tierschutzverein', 'tierheim',
 'Das groesste Tierheim Bayerns nimmt jaehrlich tausende Tiere auf und vermittelt sie in liebevolle Haeuser.',
 'Riemer Strasse 270', '81829', 'München', 'Bayern', 'DE',
 48.1207, 11.6842, '089 921000-0', 'info@tierschutzverein-muenchen.de', 'https://www.tierschutzverein-muenchen.de',
 'Di–So 12–16 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Tierarztversorgung','Fundtierverwaltung'],
 ARRAY['tierheim','muenchen','hunde','katzen','kleintiere'], true, true),

('Kölner Tierheim – Tierschutzverein Köln', 'tierheim',
 'Modernes Tierheim in Koeln-Dellbrueck fuer Hunde, Katzen, Kleintiere und Voegel.',
 'Im Meissner Grieß 1', '51069', 'Köln', 'Nordrhein-Westfalen', 'DE',
 50.9714, 7.0946, '0221 68070-0', 'info@tierheim-koeln.de', 'https://www.tierheim-koeln.de',
 'Mo–So 10–17 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Beratung','Hundeschule'],
 ARRAY['tierheim','koeln','hunde','katzen'], true, true),

('Tierheim Frankfurt – Tierschutzverein Frankfurt', 'tierheim',
 'Eines der aeltesten Tierheime Deutschlands mit moderner Infrastruktur und engagiertem Pflegeteam.',
 'Hanauer Landstraße 391', '60314', 'Frankfurt am Main', 'Hessen', 'DE',
 50.1190, 8.7470, '069 212-45550', 'tierheim@frankfurt.de', 'https://www.stadtfrankfurt.de/tierheim',
 'Di–So 11–17 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Tierarzt','Fundtiere'],
 ARRAY['tierheim','frankfurt','hunde','katzen'], true, true),

('Tierheim Stuttgart – Tierschutzverein Stuttgart', 'tierheim',
 'Zentrales Tierheim fuer Stuttgart mit ueber 500 Tieren und professioneller Betreuung.',
 'Heilbronner Strasse 230', '70469', 'Stuttgart', 'Baden-Württemberg', 'DE',
 48.8050, 9.1650, '0711 852 85-0', 'info@tierschutzverein-stuttgart.de', 'https://www.tierschutzverein-stuttgart.de',
 'Di–So 13–17 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Kastration','Beratung'],
 ARRAY['tierheim','stuttgart','hunde','katzen'], true, true),

('Tierheim Nuernberg', 'tierheim',
 'Staedtisches Tierheim Nuernberg mit breitem Angebot fuer alle Tierarten.',
 'Nerzweg 1', '90453', 'Nürnberg', 'Bayern', 'DE',
 49.4013, 11.0577, '0911 2397-6222', 'tierheim@stadt.nuernberg.de', 'https://www.nuernberg.de/tierheim',
 'Di–So 12–16 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Fundtiere','Tierarzt'],
 ARRAY['tierheim','nuernberg','hunde','katzen'], true, true),

('Tierheim Leipzig', 'tierheim',
 'Modernes Tierheim der Stadt Leipzig fuer Hunde, Katzen, Kleintiere und Exoten.',
 'Torgauer Strasse 228', '04347', 'Leipzig', 'Sachsen', 'DE',
 51.3520, 12.4211, '0341 2319890', 'tierheim@leipzig.de', 'https://www.tierheim-leipzig.de',
 'Di–So 12–17 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Beratung','Tierarzt'],
 ARRAY['tierheim','leipzig','sachsen'], true, true),

('Tierheim Dresden – Tierschutzverein Dresden', 'tierheim',
 'Tierheim der Landeshauptstadt Dresden fuer alle Tierarten mit modernen Stallanlagen.',
 'Tiergartenstraße 1', '01219', 'Dresden', 'Sachsen', 'DE',
 51.0303, 13.7611, '0351 2780-620', 'tierheim@dresden.de', 'https://www.tierheim-dresden.de',
 'Mo–So 10–16 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Fundtiere','Kastration'],
 ARRAY['tierheim','dresden','sachsen'], true, true),

('Tierheim Hannover', 'tierheim',
 'Groesstes niedersaechsisches Tierheim mit rund 600 Tierplaetzen und professionellem Tierpflegeteam.',
 'Auf dem Doegel 14', '30657', 'Hannover', 'Niedersachsen', 'DE',
 52.4164, 9.7822, '0511 6484-111', 'info@tierschutzverein-hannover.de', 'https://www.tierschutzverein-hannover.de',
 'Di–So 12–17 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Beratung','Tierarzt'],
 ARRAY['tierheim','hannover','niedersachsen'], true, true),

('Tierheim Dortmund', 'tierheim',
 'Stadtisches Tierheim Dortmund betreut jaehrlich ueber 3000 Tiere und vermittelt sie erfolgreich.',
 'Mallinckrodtstrasse 208', '44147', 'Dortmund', 'Nordrhein-Westfalen', 'DE',
 51.5357, 7.4798, '0231 1022-660', 'tierheim@stadtdo.de', 'https://www.dortmund.de/tierheim',
 'Di–So 11–17 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Fundtiere','Kastration'],
 ARRAY['tierheim','dortmund','nrw'], true, true),

('Tierheim Bremen – Tierschutzverein Bremen', 'tierheim',
 'Traditionsreiches Tierheim in Bremen mit engagiertem ehrenamtlichem Team.',
 'Moorstrasse 13', '28217', 'Bremen', 'Bremen', 'DE',
 53.0870, 8.8008, '0421 3940-50', 'info@tierschutzverein-bremen.de', 'https://www.tierschutzverein-bremen.de',
 'Di–So 12–17 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Beratung'],
 ARRAY['tierheim','bremen'], true, true),

('Tierheim Essen – Tierschutzverein Essen', 'tierheim',
 'Gut ausgestattetes Tierheim im Ruhrgebiet fuer Hunde, Katzen und Kleintiere.',
 'Schroedterstrasse 66', '45147', 'Essen', 'Nordrhein-Westfalen', 'DE',
 51.4439, 6.9899, '0201 74 11 95', 'info@tierheim-essen.de', 'https://www.tierheim-essen.de',
 'Di–So 12–17 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Kastrationshilfe'],
 ARRAY['tierheim','essen','ruhrgebiet'], true, true),

('Tierheim Duesseldorf – Tierschutzverein Düsseldorf', 'tierheim',
 'Modernstes Tierheim NRWs mit professioneller Tierbetreuung und umfangreichem Vermittlungsservice.',
 'Ruedesheimer Strasse 104', '40472', 'Düsseldorf', 'Nordrhein-Westfalen', 'DE',
 51.2733, 6.8130, '0211 65 04 80', 'info@tierheim-duesseldorf.de', 'https://www.tierheim-duesseldorf.de',
 'Mo–So 12–17 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Tierarzt','Beratung'],
 ARRAY['tierheim','duesseldorf','nrw'], true, true),

('Tierheim Kassel – Tierschutzverein Kassel', 'tierheim',
 'Zentrales Tierheim fuer Stadt und Landkreis Kassel mit modernen Anlagen.',
 'Wolfhager Strasse 312', '34128', 'Kassel', 'Hessen', 'DE',
 51.3313, 9.4543, '0561 93 89 89', 'info@tierheim-kassel.de', 'https://www.tierheim-kassel.de',
 'Mo–Sa 10–17 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Fundtiere'],
 ARRAY['tierheim','kassel','hessen'], true, true),

('Tierheim Mannheim – Tierschutzverein Mannheim', 'tierheim',
 'Groesstes Tierheim der Metropolregion Rhein-Neckar mit breitem Betreuungsangebot.',
 'Friesenheimer Strasse 6', '68169', 'Mannheim', 'Baden-Württemberg', 'DE',
 49.5029, 8.4698, '0621 33 20 16', 'info@tierheim-mannheim.de', 'https://www.tierheim-mannheim.de',
 'Di–So 13–17 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Kastration','Beratung'],
 ARRAY['tierheim','mannheim','bw'], true, true),

('Tierheim Karlsruhe – Tierschutzverein Karlsruhe', 'tierheim',
 'Eines der groessten Tierheime Badens mit rund 400 Tierplaetzen.',
 'Tiergartenstrasse 4', '76228', 'Karlsruhe', 'Baden-Württemberg', 'DE',
 48.9956, 8.3773, '0721 94 36 10', 'info@tierschutz-karlsruhe.de', 'https://www.tierschutz-karlsruhe.de',
 'Di–So 12–16 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Tierarzt'],
 ARRAY['tierheim','karlsruhe','bw'], true, true),

('Tierheim Freiburg – Tierschutzverein Freiburg', 'tierheim',
 'Tierheim fuer den Grossraum Freiburg mit engagierten Tierpflegern und Ehrenamtlichen.',
 'Breisgaustrasse 25', '79110', 'Freiburg im Breisgau', 'Baden-Württemberg', 'DE',
 47.9912, 7.8072, '0761 45 60 70', 'info@tierheim-freiburg.de', 'https://www.tierheim-freiburg.de',
 'Di–So 11–17 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Kastrationshilfe'],
 ARRAY['tierheim','freiburg','bw'], true, true),

('Tierheim Augsburg – Tierschutzverein Augsburg', 'tierheim',
 'Tierheim der Stadt Augsburg mit rund 350 Plaetzen und professionellem Pflegeteam.',
 'Karl-Mantel-Strasse 43', '86153', 'Augsburg', 'Bayern', 'DE',
 48.3645, 10.8742, '0821 50801-0', 'info@tierheim-augsburg.de', 'https://www.tierheim-augsburg.de',
 'Di–Sa 12–17 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Tierarzt','Fundtiere'],
 ARRAY['tierheim','augsburg','bayern'], true, true),

('Tierheim Wiesbaden – Tierschutzverein Wiesbaden', 'tierheim',
 'Modernes Tierheim der hessischen Landeshauptstadt fuer alle Tierarten.',
 'Ostparkstrasse 31', '65201', 'Wiesbaden', 'Hessen', 'DE',
 50.0687, 8.2697, '0611 9714-0', 'info@tierschutzverein-wiesbaden.de', 'https://www.tierschutzverein-wiesbaden.de',
 'Di–So 11–17 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Beratung'],
 ARRAY['tierheim','wiesbaden','hessen'], true, true),

('Tierheim Bielefeld – Tierschutzverein Bielefeld', 'tierheim',
 'Tierheim in Ostwestfalen mit rund 300 Tierplaetzen und engagiertem Team.',
 'Siegfriedplatz 6', '33615', 'Bielefeld', 'Nordrhein-Westfalen', 'DE',
 51.9919, 8.5209, '0521 132-4800', 'tierheim@bielefeld.de', 'https://www.tierheim-bielefeld.de',
 'Mo–So 12–16 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Fundtiere'],
 ARRAY['tierheim','bielefeld','nrw'], true, true),

('Tierheim Muenster – Tierschutzverein Muenster', 'tierheim',
 'Eines der fuehrenden Tierheime in Westfalen mit innovativen Konzepten zur Tiervermittlung.',
 'Geisbergstrasse 10', '48153', 'Münster', 'Nordrhein-Westfalen', 'DE',
 51.9401, 7.6153, '0251 77 99 40', 'info@tierheim-muenster.de', 'https://www.tierheim-muenster.de',
 'Di–Sa 12–17 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Kastration','Online-Vermittlung'],
 ARRAY['tierheim','muenster','nrw'], true, true),

('Tierheim Bochum – Tierschutzverein Bochum', 'tierheim',
 'Tierheim fuer das Ruhrgebiet mit umfangreichem Angebot und professioneller Betreuung.',
 'Lewacker Strasse 12', '44803', 'Bochum', 'Nordrhein-Westfalen', 'DE',
 51.5059, 7.2490, '0234 326 36-0', 'info@tierheim-bochum.de', 'https://www.tierheim-bochum.de',
 'Di–So 11–17 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Kleintiere'],
 ARRAY['tierheim','bochum','ruhrgebiet'], true, true),

('Tierheim Bonn – Tierschutzverein Bonn', 'tierheim',
 'Traditionsreiches Tierheim in der ehemaligen Bundeshauptstadt fuer alle Tierarten.',
 'Auf dem Hügel 73', '53121', 'Bonn', 'Nordrhein-Westfalen', 'DE',
 50.7336, 7.0822, '0228 64 20 40', 'info@tierheim-bonn.de', 'https://www.tierheim-bonn.de',
 'Di–So 12–17 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Fundtiere','Beratung'],
 ARRAY['tierheim','bonn','nrw'], true, true),

('Tierheim Kiel – Tierschutzverein Kiel', 'tierheim',
 'Tierheim der Landeshauptstadt Schleswig-Holsteins mit modernen Anlagen direkt an der Foerde.',
 'Werftstrasse 7', '24143', 'Kiel', 'Schleswig-Holstein', 'DE',
 54.3187, 10.1295, '0431 775 41', 'info@tierheim-kiel.de', 'https://www.tierheim-kiel.de',
 'Di–So 12–17 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Tierarzt'],
 ARRAY['tierheim','kiel','schleswig-holstein'], true, true),

('Tierheim Mainz – Tierschutzverein Mainz', 'tierheim',
 'Tierheim der rheinland-pfaelzischen Landeshauptstadt mit rund 250 Tierplaetzen.',
 'Hinteren Flur 1', '55128', 'Mainz', 'Rheinland-Pfalz', 'DE',
 49.9924, 8.2263, '06131 477 50', 'info@tierheim-mainz.de', 'https://www.tierheim-mainz.de',
 'Di–Sa 13–17 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Fundtiere'],
 ARRAY['tierheim','mainz','rheinland-pfalz'], true, true),

('Tierheim Magdeburg – Tierschutzverein Magdeburg', 'tierheim',
 'Tierheim der Landeshauptstadt Sachsen-Anhalts mit breitem Betreuungsangebot.',
 'An der Steinkuhle 2a', '39126', 'Magdeburg', 'Sachsen-Anhalt', 'DE',
 52.1643, 11.6441, '0391 543 94-0', 'tierheim@magdeburg.de', 'https://www.tierheim-magdeburg.de',
 'Di–So 11–17 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Kastration'],
 ARRAY['tierheim','magdeburg','sachsen-anhalt'], true, true),

('Tierheim Erfurt – Tierschutzverein Erfurt', 'tierheim',
 'Tierheim der thueringischen Landeshauptstadt fuer Hunde, Katzen und Kleintiere.',
 'Erfurter Strasse 101', '99086', 'Erfurt', 'Thüringen', 'DE',
 50.9859, 11.0565, '0361 602 64 15', 'info@tierheim-erfurt.de', 'https://www.tierheim-erfurt.de',
 'Di–Sa 12–17 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Tierarzt'],
 ARRAY['tierheim','erfurt','thueringen'], true, true),

('Tierheim Rostock – Tierschutzverein Rostock', 'tierheim',
 'Groesstes Tierheim an der Ostseeküste mit Betreuung fuer alle Tierarten.',
 'Am Schlachthof 24', '18055', 'Rostock', 'Mecklenburg-Vorpommern', 'DE',
 54.0804, 12.1423, '0381 458 5810', 'info@tierheim-rostock.de', 'https://www.tierheim-rostock.de',
 'Di–So 11–17 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Fundtiere'],
 ARRAY['tierheim','rostock','mv'], true, true),

('Tierheim Saarbruecken – Tierschutzverein Saarbruecken', 'tierheim',
 'Modernes Tierheim im Saarland mit individueller Tierbetreuung und Vermittlungsservice.',
 'Puccinistrasse 4', '66119', 'Saarbrücken', 'Saarland', 'DE',
 49.2261, 6.9954, '0681 9893060', 'info@tierheim-saarbruecken.de', 'https://www.tierheim-saarbruecken.de',
 'Di–So 12–17 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Beratung'],
 ARRAY['tierheim','saarbruecken','saarland'], true, true),

-- ── ÖSTERREICH (12) ──────────────────────────────────────────────────────
('TierQuarTier Wien', 'tierheim',
 'Groesstes Tierheim Oesterreichs mit modernen Anlagen fuer ueber 1000 Tiere. Betrieben von der Stadt Wien.',
 'Triester Strasse 8', '1100', 'Wien', 'Wien', 'AT',
 48.1760, 16.3055, '+43 1 7495440', 'tierquartier@tierquartier.at', 'https://www.tierquartier.at',
 'Mo–So 10–18 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Tierarzt','Kastration','Fundtiere'],
 ARRAY['tierheim','wien','oesterreich'], true, true),

('Tierheim Graz – Tierschutzverein Graz', 'tierheim',
 'Tierheim der steirischen Landeshauptstadt fuer Hunde, Katzen und Kleintiere.',
 'Pluessgasse 34', '8052', 'Graz', 'Steiermark', 'AT',
 47.0435, 15.4147, '+43 316 572323', 'info@tierschutz-graz.at', 'https://www.tierschutz-graz.at',
 'Di–So 10–17 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Tierarzt','Kastration'],
 ARRAY['tierheim','graz','steiermark'], true, true),

('Tierheim Linz – Tierschutzverein Linz', 'tierheim',
 'Modernes Tierheim der oberoesterreichischen Landeshauptstadt mit engagiertem Team.',
 'Schillerstrasse 25', '4020', 'Linz', 'Oberösterreich', 'AT',
 48.2897, 14.2894, '+43 732 654422', 'office@tierschutz-linz.at', 'https://www.tierschutz-linz.at',
 'Di–So 11–17 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Kastration','Beratung'],
 ARRAY['tierheim','linz','oberoesterreich'], true, true),

('Tierheim Salzburg – Salzburger Tierschutzverein', 'tierheim',
 'Tierheim fuer Stadt und Land Salzburg mit rund 400 Tierplaetzen und professioneller Betreuung.',
 'Schlehdornweg 12', '5020', 'Salzburg', 'Salzburg', 'AT',
 47.8125, 13.0497, '+43 662 430980', 'office@tierheimrainersberg.at', 'https://www.tierheimrainersberg.at',
 'Di–So 10–17 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Tierarzt','Fundtiere'],
 ARRAY['tierheim','salzburg'], true, true),

('Tierheim Innsbruck – Tiroler Tierschutzverein', 'tierheim',
 'Tierheim der tirolerischen Landeshauptstadt fuer alle Tierarten mit moderner Infrastruktur.',
 'Amraser Strasse 5', '6020', 'Innsbruck', 'Tirol', 'AT',
 47.2648, 11.4116, '+43 512 584867', 'info@tierschutz-tirol.at', 'https://www.tierschutz-tirol.at',
 'Di–So 10–17 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Kastration','Beratung'],
 ARRAY['tierheim','innsbruck','tirol'], true, true),

('Tierheim Klagenfurt – Kaerntner Tierschutzverein', 'tierheim',
 'Kaerntnens groesstes Tierheim mit breitem Angebot fuer alle Tierarten.',
 'Klagenfurter Strasse 59', '9020', 'Klagenfurt', 'Kärnten', 'AT',
 46.6150, 14.3060, '+43 463 312311', 'info@tierschutz-kaernten.at', 'https://www.tierschutz-kaernten.at',
 'Di–So 10–16 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Tierarzt'],
 ARRAY['tierheim','klagenfurt','kaernten'], true, true),

('Tierheim St. Poelten – NOe Tierschutzverein', 'tierheim',
 'Tierheim der niederoesterreichischen Landeshauptstadt mit modernen Tierunterkuenften.',
 'Tiroler Strasse 72', '3100', 'St. Pölten', 'Niederösterreich', 'AT',
 48.1894, 15.6228, '+43 2742 77810', 'office@tierschutz-noe.at', 'https://www.tierschutz-noe.at',
 'Di–Sa 10–16 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Kastration'],
 ARRAY['tierheim','stpoelten','niederoesterreich'], true, true),

('Tierheim Bregenz – Vorarlberger Tierschutzverein', 'tierheim',
 'Einziges groesseres Tierheim in Vorarlberg fuer Hunde, Katzen und Kleintiere.',
 'Arlbergstrasse 137', '6900', 'Bregenz', 'Vorarlberg', 'AT',
 47.5015, 9.7374, '+43 5574 72323', 'info@tierschutz-vorarlberg.at', 'https://www.tierschutz-vorarlberg.at',
 'Di–Sa 10–17 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Beratung'],
 ARRAY['tierheim','bregenz','vorarlberg'], true, true),

('Tierheim Wels – Tierschutzverein Wels', 'tierheim',
 'Eines der groessten Tierheime Oberoesterreichs ausserhalb von Linz.',
 'Duerrnbergerstrasse 11', '4600', 'Wels', 'Oberösterreich', 'AT',
 48.1664, 14.0329, '+43 7242 47200', 'office@tierschutz-wels.at', 'https://www.tierschutz-wels.at',
 'Di–So 10–16 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Kastration'],
 ARRAY['tierheim','wels','oberoesterreich'], true, true),

('Tierheim Steyr – Tierschutzverein Steyr', 'tierheim',
 'Regionales Tierheim fuer die Region Steyr-Kirchdorf mit professionellem Betreuungsangebot.',
 'Stelzhamerstrase 9', '4400', 'Steyr', 'Oberösterreich', 'AT',
 48.0416, 14.4176, '+43 7252 52490', 'info@tierschutz-steyr.at', 'https://www.tierschutz-steyr.at',
 'Di–Sa 10–16 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Beratung'],
 ARRAY['tierheim','steyr','oberoesterreich'], true, true),

('Tierheim Villach – Tierschutzverein Villach', 'tierheim',
 'Tierheim der zweitgroessten Stadt Kaerntnens mit moderner Infrastruktur.',
 'Ossiacher Zeile 21', '9500', 'Villach', 'Kärnten', 'AT',
 46.6100, 13.8558, '+43 4242 25858', 'info@tierschutz-villach.at', 'https://www.tierschutz-villach.at',
 'Di–Sa 10–16 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung'],
 ARRAY['tierheim','villach','kaernten'], true, true),

('Tierheim Dornbirn – Tierschutzverein Dornbirn', 'tierheim',
 'Modernes Tierheim fuer die groesste Vorarlberger Gemeinde.',
 'Stadtstrasse 33', '6850', 'Dornbirn', 'Vorarlberg', 'AT',
 47.4143, 9.7437, '+43 5572 28190', 'info@tierschutz-dornbirn.at', 'https://www.tierschutz-dornbirn.at',
 'Mi–Sa 10–16 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Kastration'],
 ARRAY['tierheim','dornbirn','vorarlberg'], true, true),

-- ── SCHWEIZ (8) ──────────────────────────────────────────────────────────
('Zuercher Tierschutz – Tierheim Zuerich', 'tierheim',
 'Groesstes Tierheim der Deutschschweiz mit modernster Infrastruktur und professionellem Team.',
 'Weinbergstrasse 16', '8001', 'Zürich', 'Zürich', 'CH',
 47.3795, 8.5379, '+41 44 261 97 00', 'info@zuercher-tierschutz.ch', 'https://www.zuercher-tierschutz.ch',
 'Di–So 10–17 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Tierarzt','Kastration','Beratung'],
 ARRAY['tierheim','zuerich','schweiz'], true, true),

('Berner Tierschutz – Tierheim Bern', 'tierheim',
 'Traditionsreiches Tierheim der Bundesstadt Bern fuer alle Tierarten.',
 'Postfach 35', '3000', 'Bern', 'Bern', 'CH',
 46.9488, 7.4388, '+41 31 301 10 10', 'info@berner-tierschutz.ch', 'https://www.berner-tierschutz.ch',
 'Di–So 10–17 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Beratung','Tierarzt'],
 ARRAY['tierheim','bern','schweiz'], true, true),

('Basler Tierschutzverein – Tierheim Basel', 'tierheim',
 'Tierheim fuer die Region Basel mit engagiertem Pflegeteam und gutem Vermittlungsnetzwerk.',
 'Auf dem Wolf 10', '4052', 'Basel', 'Basel-Stadt', 'CH',
 47.5447, 7.5724, '+41 61 311 44 55', 'info@basler-tierschutz.ch', 'https://www.basler-tierschutz.ch',
 'Di–So 10–17 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Kastration'],
 ARRAY['tierheim','basel','schweiz'], true, true),

('Tierheim Zug – Zuger Tierschutz', 'tierheim',
 'Kleines aber feines Tierheim fuer den Kanton Zug mit hoher Vermittlungsquote.',
 'Industriestrasse 30', '6300', 'Zug', 'Zug', 'CH',
 47.1682, 8.5174, '+41 41 710 12 00', 'info@zuger-tierschutz.ch', 'https://www.zuger-tierschutz.ch',
 'Di–Sa 11–17 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Beratung'],
 ARRAY['tierheim','zug','schweiz'], true, true),

('Tierheim Luzern – Luzerner Tierschutz', 'tierheim',
 'Tierheim der Zentralschweiz fuer Hunde, Katzen und Kleintiere mit engagiertem Team.',
 'Kasernenstrasse 26', '6003', 'Luzern', 'Luzern', 'CH',
 47.0504, 8.3041, '+41 41 210 00 88', 'info@luzerner-tierschutz.ch', 'https://www.luzerner-tierschutz.ch',
 'Di–Sa 11–17 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Kastration'],
 ARRAY['tierheim','luzern','schweiz'], true, true),

('Tierheim St. Gallen – St. Galler Tierschutz', 'tierheim',
 'Tierheim der Ostschweiz mit professionellem Betreuungsangebot fuer alle Tierarten.',
 'Vadianstrasse 26', '9001', 'St. Gallen', 'St. Gallen', 'CH',
 47.4224, 9.3745, '+41 71 222 66 00', 'info@stgaller-tierschutz.ch', 'https://www.stgaller-tierschutz.ch',
 'Di–So 10–17 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Beratung'],
 ARRAY['tierheim','stgallen','ostschweiz'], true, true),

('Tierheim Winterthur – Winterthurer Tierschutz', 'tierheim',
 'Regionales Tierheim fuer Winterthur und Umgebung mit engagiertem Ehrenamtsteam.',
 'Schaffhauserstrasse 285', '8400', 'Winterthur', 'Zürich', 'CH',
 47.5040, 8.7178, '+41 52 232 28 80', 'info@winterthurer-tierschutz.ch', 'https://www.winterthurer-tierschutz.ch',
 'Di–Sa 12–17 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung'],
 ARRAY['tierheim','winterthur','schweiz'], true, true),

('Tierheim Thun – Thuner Tierschutz', 'tierheim',
 'Tierheim im Berner Oberland fuer Hunde, Katzen und Kleintiere.',
 'Seestrasse 51', '3600', 'Thun', 'Bern', 'CH',
 46.7543, 7.6241, '+41 33 222 38 30', 'info@thuner-tierschutz.ch', 'https://www.thuner-tierschutz.ch',
 'Di–Sa 11–16 Uhr',
 ARRAY['Tieraufnahme','Tiervermittlung','Kastration'],
 ARRAY['tierheim','thun','berner-oberland'], true, true)

ON CONFLICT DO NOTHING;

  END IF;
END $$;
