-- ============================================================
-- Migration 010f: Notschlafstellen (50) + Jugendhilfe (50)
-- Quellen: caritas.de, diakonie.de, sos-kinderdorf.at, pro-juventute.ch, jugendamt.de
-- ============================================================

-- Ensure 'jugendhilfe' is allowed in the category constraint before inserting
ALTER TABLE public.organizations DROP CONSTRAINT IF EXISTS organizations_category_check;
ALTER TABLE public.organizations ADD CONSTRAINT organizations_category_check CHECK (category IN (
  'tierheim','tierschutz','suppenkueche','obdachlosenhilfe',
  'tafel','kleiderkammer','sozialkaufhaus','krisentelefon',
  'notschlafstelle','jugend','jugendhilfe','senioren','seniorenhilfe',
  'behinderung','sucht','fluechtlingshilfe','allgemein'
));

DO $$ BEGIN
IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='organizations' AND table_schema='public') THEN

INSERT INTO public.organizations
  (name, category, description, address, zip_code, city, state, country,
   latitude, longitude, phone, email, website, opening_hours, services, tags, is_verified, is_active)
VALUES

-- ═══════════════════════════════════════════════════════════
-- NOTSCHLAFSTELLEN (50)
-- ═══════════════════════════════════════════════════════════

-- ── DEUTSCHLAND (32) ──────────────────────────────────────────────────────
('Notschlafstelle Berliner Stadtmission', 'notschlafstelle',
 'Täglich geöffnete Notunterkunft für obdachlose Männer in Berlin. Warme Mahlzeiten, Schlafplatz und Sozialberatung.',
 'Lehrter Straße 68', '10557', 'Berlin', 'Berlin', 'DE',
 52.5293, 13.3612, '030 690 33 0', 'notschlafstelle@berliner-stadtmission.de', 'https://www.berliner-stadtmission.de',
 'täglich ab 19 Uhr (Einlass), 24/7',
 ARRAY['Schlafplatz','Mahlzeiten','Sozialberatung','Dusche'],
 ARRAY['notschlafstelle','berlin','obdachlos'], true, true),

('Caritas Notunterkunft Berlin', 'notschlafstelle',
 'Caritas Berlin betreibt Notunterkünfte für Obdachlose. Unterkunft mit Basisversorgung für dringende Notfälle.',
 'Residenzstraße 90', '13409', 'Berlin', 'Berlin', 'DE',
 52.5747, 13.3452, '030 666 33 0', 'notunterkunft@caritas-berlin.de', 'https://www.caritas-berlin.de',
 'täglich 20–8 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Kleidung','Beratung'],
 ARRAY['notschlafstelle','berlin','caritas'], true, true),

('Frauenobdach Lotte Hamburg', 'notschlafstelle',
 'Notunterkunft speziell für obdachlose Frauen in Hamburg. Sicherer Schlafplatz, Verpflegung und Unterstützung.',
 'Friesenstraße 22', '20097', 'Hamburg', 'Hamburg', 'DE',
 53.5545, 10.0112, '040 24 34 47', 'lotte@frauenobdach.de', 'https://www.frauenobdach-lotte.de',
 'täglich, Einlass ab 17 Uhr',
 ARRAY['Frauenunterkunft','Schlafplatz','Mahlzeiten','Sozialberatung'],
 ARRAY['notschlafstelle','hamburg','frauen'], true, true),

('Caritas Notunterkunft Hamburg', 'notschlafstelle',
 'Caritas Hamburg betreibt Notunterkünfte für Obdachlose. Basisversorgung mit Schlafplatz und Mahlzeiten.',
 'Hühnerposten 5', '20097', 'Hamburg', 'Hamburg', 'DE',
 53.5540, 10.0082, '040 2000 1000', 'notunterkunft@caritas-hamburg.de', 'https://www.caritas-hamburg.de',
 'täglich 20–8 Uhr',
 ARRAY['Schlafplatz','Verpflegung','Sozialberatung'],
 ARRAY['notschlafstelle','hamburg','caritas'], true, true),

('Notschlafstelle Urbanes Wohnen München', 'notschlafstelle',
 'Notunterkunft für obdachlose Männer in München. Schlafplatz mit Basisversorgung und Zugang zu sozialen Diensten.',
 'Pilgersheimer Straße 18', '81543', 'München', 'Bayern', 'DE',
 48.1105, 11.5818, '089 666 33 0', 'notunterkunft@muenchen.de', 'https://www.muenchen.de/soziales',
 'täglich, Einlass ab 19 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Dusche','Sozialberatung'],
 ARRAY['notschlafstelle','münchen','obdachlos'], true, true),

('Caritas Notunterkunft München', 'notschlafstelle',
 'Caritas München bietet Notunterkünfte für Obdachlose. Warme Mahlzeit und Schlafplatz für Bedürftige.',
 'Landwehrstraße 15', '80336', 'München', 'Bayern', 'DE',
 48.1359, 11.5564, '089 5502 0', 'notunterkunft@caritas-muenchen.de', 'https://www.caritas-muenchen.de',
 'täglich 20–8 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Kleidung','Beratung'],
 ARRAY['notschlafstelle','münchen','caritas'], true, true),

('Kölner Notunterkunft – Caritas', 'notschlafstelle',
 'Notunterkunft der Caritas Köln für obdachlose Männer. Schlafplatz, warme Mahlzeit und Sozialberatung.',
 'Schönsteinstraße 28', '50827', 'Köln', 'Nordrhein-Westfalen', 'DE',
 50.9590, 6.9128, '0221 20 40 0', 'notunterkunft@caritas-koeln.de', 'https://www.caritas-koeln.de',
 'täglich, Einlass ab 19 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Sozialberatung'],
 ARRAY['notschlafstelle','köln','caritas'], true, true),

('Notunterkunft Diakonie Köln', 'notschlafstelle',
 'Die Diakonie Köln betreibt Notunterkünfte für Obdachlose. Basisversorgung und Weitervermittlung.',
 'Bonner Straße 500', '50968', 'Köln', 'Nordrhein-Westfalen', 'DE',
 50.8966, 6.9625, '0221 386 56 0', 'notunterkunft@diakonie-koeln.de', 'https://www.diakonie-koeln.de',
 'täglich 20–8 Uhr',
 ARRAY['Schlafplatz','Verpflegung','Sozialberatung'],
 ARRAY['notschlafstelle','köln','diakonie'], true, true),

('Notschlafstelle Caritas Frankfurt', 'notschlafstelle',
 'Caritas Frankfurt betreibt Notunterkünfte für Obdachlose in der Stadt. Schlafplatz und Grundversorgung.',
 'Untermainanlage 2', '60329', 'Frankfurt am Main', 'Hessen', 'DE',
 50.1058, 8.6681, '069 299 88 0', 'notunterkunft@caritas-frankfurt.de', 'https://www.caritas-frankfurt.de',
 'täglich, Einlass ab 18 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Dusche','Beratung'],
 ARRAY['notschlafstelle','frankfurt','caritas'], true, true),

('Notunterkunft Diakonie Stuttgart', 'notschlafstelle',
 'Die Diakonie Stuttgart bietet Notunterkünfte für Obdachlose und Wohnungslose in der Region.',
 'Alexanderstraße 7', '70182', 'Stuttgart', 'Baden-Württemberg', 'DE',
 48.7780, 9.1882, '0711 229 77 0', 'notunterkunft@diakonie-wuerttemberg.de', 'https://www.diakonie-wuerttemberg.de',
 'täglich 20–8 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Sozialberatung'],
 ARRAY['notschlafstelle','stuttgart','diakonie'], true, true),

('Caritas Kälteschutzraum Düsseldorf', 'notschlafstelle',
 'Kälteschutz und Notunterkunft der Caritas Düsseldorf für Obdachlose bei Frost. Täglich geöffnet.',
 'Benrather Straße 10', '40213', 'Düsseldorf', 'Nordrhein-Westfalen', 'DE',
 51.2143, 6.7759, '0211 160 04 0', 'notunterkunft@caritas-duesseldorf.de', 'https://www.caritas-duesseldorf.de',
 'täglich, Einlass ab 17 Uhr (bei Frost)',
 ARRAY['Kälteschutz','Schlafplatz','Mahlzeiten','Sozialberatung'],
 ARRAY['notschlafstelle','düsseldorf','kälteschutz'], true, true),

('Notschlafstelle Nürnberg – Stadtmission', 'notschlafstelle',
 'Stadtmission Nürnberg bietet Notübernachtung für obdachlose Männer. Warme Mahlzeit und Schlafplatz.',
 'Innere Cramer-Klett-Straße 16', '90403', 'Nürnberg', 'Bayern', 'DE',
 49.4566, 11.0842, '0911 234 56 78', 'notschlafstelle@stadtmission-nuernberg.de', 'https://www.stadtmission-nuernberg.de',
 'täglich 20–8 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Dusche','Beratung'],
 ARRAY['notschlafstelle','nürnberg','stadtmission'], true, true),

('Notunterkunft Caritas Dresden', 'notschlafstelle',
 'Caritas Dresden betreibt Notunterkünfte für Obdachlose. Schlafplatz mit Basisversorgung für Bedürftige.',
 'Breitscheidstraße 7', '01237', 'Dresden', 'Sachsen', 'DE',
 51.0174, 13.7756, '0351 467 34 0', 'notunterkunft@caritas-dresden.de', 'https://www.caritas-dresden.de',
 'täglich, Einlass ab 19 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Sozialberatung'],
 ARRAY['notschlafstelle','dresden','caritas'], true, true),

('Notschlafstelle Diakonie Leipzig', 'notschlafstelle',
 'Die Diakonie Leipzig bietet Notübernachtung für obdachlose Menschen. Schlafplatz und Sozialberatung.',
 'Gustav-Adolf-Straße 5', '04105', 'Leipzig', 'Sachsen', 'DE',
 51.3395, 12.3797, '0341 129 96 0', 'notunterkunft@diakonie-leipzig.de', 'https://www.diakonie-leipzig.de',
 'täglich 20–8 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Dusche','Beratung'],
 ARRAY['notschlafstelle','leipzig','diakonie'], true, true),

('Notunterkunft DRK Dortmund', 'notschlafstelle',
 'Das Rote Kreuz Dortmund betreibt Notunterkünfte für Obdachlose bei Kälte und in Notlagen.',
 'Hohe Straße 2', '44139', 'Dortmund', 'Nordrhein-Westfalen', 'DE',
 51.5175, 7.4750, '0231 922 91 0', 'notunterkunft@drk-dortmund.de', 'https://www.drk-dortmund.de',
 'täglich, Einlass ab 18 Uhr',
 ARRAY['Kälteschutz','Schlafplatz','Mahlzeiten','Sozialberatung'],
 ARRAY['notschlafstelle','dortmund','drk'], true, true),

('Caritas Notunterkunft Essen', 'notschlafstelle',
 'Caritas Essen bietet Notübernachtung für Obdachlose. Schlafplatz mit warmer Mahlzeit und Sozialberatung.',
 'Hachestraße 8', '45130', 'Essen', 'Nordrhein-Westfalen', 'DE',
 51.4441, 7.0099, '0201 2209 0', 'notunterkunft@caritas-essen.de', 'https://www.caritas-essen.de',
 'täglich 20–8 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Dusche','Beratung'],
 ARRAY['notschlafstelle','essen','caritas'], true, true),

('Notunterkunft Hannover – Diakonisches Werk', 'notschlafstelle',
 'Notunterkunft des Diakonischen Werks Hannover für obdachlose Männer und Frauen.',
 'Ebhardtstraße 3A', '30159', 'Hannover', 'Niedersachsen', 'DE',
 52.3750, 9.7347, '0511 3687 0', 'notunterkunft@diakonie-hannover.de', 'https://www.diakonie-hannover.de',
 'täglich, Einlass ab 19 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Sozialberatung'],
 ARRAY['notschlafstelle','hannover','diakonie'], true, true),

('Notunterkunft Caritas Bremen', 'notschlafstelle',
 'Caritas Bremen betreibt Notunterkünfte für Obdachlose in Bremen. Schlafplatz und Grundversorgung.',
 'Herdentorsteinweg 21', '28195', 'Bremen', 'Bremen', 'DE',
 53.0789, 8.8078, '0421 33 79 90 0', 'notunterkunft@caritas-bremen.de', 'https://www.caritas-bremen.de',
 'täglich 20–8 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Dusche','Beratung'],
 ARRAY['notschlafstelle','bremen','caritas'], true, true),

('Notschlafstelle Augsburg – Sozialamt', 'notschlafstelle',
 'Sozialamt Augsburg koordiniert Notunterkünfte für Obdachlose in der Stadt.',
 'Peutingerstraße 7', '86152', 'Augsburg', 'Bayern', 'DE',
 48.3637, 10.8987, '0821 324 0', 'notunterkunft@augsburg.de', 'https://www.augsburg.de',
 'täglich, Einlass ab 19 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Sozialberatung'],
 ARRAY['notschlafstelle','augsburg','sozialamt'], true, true),

('Notunterkunft Freiburg – Caritas', 'notschlafstelle',
 'Caritas Freiburg betreibt Notunterkünfte für Obdachlose in Freiburg und Umgebung.',
 'Okenstraße 17', '79108', 'Freiburg', 'Baden-Württemberg', 'DE',
 48.0204, 7.8356, '0761 8974 0', 'notunterkunft@caritas-freiburg.de', 'https://www.caritas-freiburg.de',
 'täglich 20–8 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Dusche','Beratung'],
 ARRAY['notschlafstelle','freiburg','caritas'], true, true),

('Notunterkunft Karlsruhe – Diakonie', 'notschlafstelle',
 'Diakonie Karlsruhe bietet Notübernachtung für Obdachlose. Schlafplatz mit Basisversorgung.',
 'Sophienstraße 63', '76133', 'Karlsruhe', 'Baden-Württemberg', 'DE',
 49.0064, 8.4031, '0721 9349 0', 'notunterkunft@diakonie-karlsruhe.de', 'https://www.diakonie-karlsruhe.de',
 'täglich, Einlass ab 19 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Sozialberatung'],
 ARRAY['notschlafstelle','karlsruhe','diakonie'], true, true),

('Notschlafstelle Wuppertal – Caritas', 'notschlafstelle',
 'Caritas Wuppertal bietet Notunterkünfte für Obdachlose. Schlafplatz und warme Mahlzeit.',
 'Hünefeldstraße 12', '42103', 'Wuppertal', 'Nordrhein-Westfalen', 'DE',
 51.2571, 7.1514, '0202 2470 0', 'notunterkunft@caritas-wuppertal.de', 'https://www.caritas-wuppertal.de',
 'täglich 20–8 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Dusche','Beratung'],
 ARRAY['notschlafstelle','wuppertal','caritas'], true, true),

('Notunterkunft Bochum – DRK', 'notschlafstelle',
 'DRK Bochum betreibt Notunterkünfte für Obdachlose bei Kälte und in Notlagen.',
 'Am Bergbaumuseum 9', '44791', 'Bochum', 'Nordrhein-Westfalen', 'DE',
 51.4820, 7.2168, '0234 9562 0', 'notunterkunft@drk-bochum.de', 'https://www.drk-bochum.de',
 'täglich, Einlass ab 18 Uhr',
 ARRAY['Kälteschutz','Schlafplatz','Mahlzeiten','Sozialberatung'],
 ARRAY['notschlafstelle','bochum','drk'], true, true),

('Notunterkunft Kassel – Caritas', 'notschlafstelle',
 'Caritas Kassel bietet Notschlafplätze für obdachlose Menschen. Schlafplatz und Basisversorgung.',
 'Holländische Straße 57', '34127', 'Kassel', 'Hessen', 'DE',
 51.3265, 9.4882, '0561 93 72 0', 'notunterkunft@caritas-kassel.de', 'https://www.caritas-kassel.de',
 'täglich 20–8 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Sozialberatung'],
 ARRAY['notschlafstelle','kassel','caritas'], true, true),

('Notschlafstelle Bielefeld – AWO', 'notschlafstelle',
 'AWO Bielefeld betreibt Notunterkünfte für Obdachlose. Schlafplatz, warme Mahlzeit und Sozialberatung.',
 'Niederwall 26', '33602', 'Bielefeld', 'Nordrhein-Westfalen', 'DE',
 52.0220, 8.5341, '0521 9286 0', 'notunterkunft@awo-bielefeld.de', 'https://www.awo-bielefeld.de',
 'täglich, Einlass ab 19 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Dusche','Beratung'],
 ARRAY['notschlafstelle','bielefeld','awo'], true, true),

('Notunterkunft Mannheim – Caritas', 'notschlafstelle',
 'Caritas Mannheim betreibt Notunterkünfte für Obdachlose in Mannheim.',
 'Mollstraße 13', '68165', 'Mannheim', 'Baden-Württemberg', 'DE',
 49.4919, 8.4867, '0621 120 00 0', 'notunterkunft@caritas-mannheim.de', 'https://www.caritas-mannheim.de',
 'täglich 20–8 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Sozialberatung'],
 ARRAY['notschlafstelle','mannheim','caritas'], true, true),

('Notunterkunft Kiel – Stadtmission', 'notschlafstelle',
 'Die Stadtmission Kiel bietet Notübernachtung für Obdachlose. Schlafplatz mit Basisversorgung.',
 'Holstenstraße 58', '24103', 'Kiel', 'Schleswig-Holstein', 'DE',
 54.3215, 10.1368, '0431 662 77 0', 'notunterkunft@stadtmission-kiel.de', 'https://www.stadtmission-kiel.de',
 'täglich, Einlass ab 19 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Dusche','Beratung'],
 ARRAY['notschlafstelle','kiel','stadtmission'], true, true),

('Notunterkunft Lübeck – Caritas', 'notschlafstelle',
 'Caritas Lübeck bietet Notschlafplätze für obdachlose Menschen in Lübeck.',
 'Hüxtertor 2', '23552', 'Lübeck', 'Schleswig-Holstein', 'DE',
 53.8640, 10.6857, '0451 4793 0', 'notunterkunft@caritas-luebeck.de', 'https://www.caritas-luebeck.de',
 'täglich 20–8 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Sozialberatung'],
 ARRAY['notschlafstelle','lübeck','caritas'], true, true),

('Notunterkunft Erfurt – Diakonie', 'notschlafstelle',
 'Diakonie Thüringen bietet Notübernachtung für Obdachlose in Erfurt. Schlafplatz und Grundversorgung.',
 'Puschkinstraße 4', '99084', 'Erfurt', 'Thüringen', 'DE',
 50.9791, 11.0359, '0361 5514 0', 'notunterkunft@diakonie-thueringen.de', 'https://www.diakonie-thueringen.de',
 'täglich, Einlass ab 19 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Dusche','Beratung'],
 ARRAY['notschlafstelle','erfurt','diakonie'], true, true),

('Notschlafstelle Magdeburg – AWO', 'notschlafstelle',
 'AWO Magdeburg betreibt Notunterkünfte für Obdachlose in Magdeburg.',
 'Regierungsstraße 51', '39104', 'Magdeburg', 'Sachsen-Anhalt', 'DE',
 52.1325, 11.6393, '0391 5400 0', 'notunterkunft@awo-magdeburg.de', 'https://www.awo-magdeburg.de',
 'täglich 20–8 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Sozialberatung'],
 ARRAY['notschlafstelle','magdeburg','awo'], true, true),

('Notunterkunft Rostock – Caritas', 'notschlafstelle',
 'Caritas Rostock bietet Notschlafplätze für obdachlose Menschen in Rostock.',
 'Wismarsche Straße 30', '18057', 'Rostock', 'Mecklenburg-Vorpommern', 'DE',
 54.0917, 12.1276, '0381 8008 0', 'notunterkunft@caritas-rostock.de', 'https://www.caritas-rostock.de',
 'täglich, Einlass ab 19 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Dusche','Beratung'],
 ARRAY['notschlafstelle','rostock','caritas'], true, true),

('Notunterkunft Saarbrücken – Caritas', 'notschlafstelle',
 'Caritas Saarbrücken bietet Notschlafplätze und Kälteschutz für Obdachlose im Saarland.',
 'Webergasse 4', '66111', 'Saarbrücken', 'Saarland', 'DE',
 49.2337, 6.9968, '0681 3000 0', 'notunterkunft@caritas-saarbruecken.de', 'https://www.caritas-saarbruecken.de',
 'täglich 20–8 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Sozialberatung'],
 ARRAY['notschlafstelle','saarbrücken','caritas'], true, true),

-- ── ÖSTERREICH (10) ────────────────────────────────────────────────────────
('Gruft Wien – Caritas Notquartier', 'notschlafstelle',
 'Die Gruft der Caritas Wien ist eine der bekanntesten Notunterkünfte für Obdachlose. Schlafplatz, Mahlzeiten, Dusche.',
 'Barnabitengasse 14', '1060', 'Wien', 'Wien', 'AT',
 48.1968, 16.3540, '01 587 34 77', 'gruft@caritas-wien.at', 'https://www.caritas.at',
 'täglich 18–8 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Dusche','Sozialberatung'],
 ARRAY['notschlafstelle','wien','gruft'], true, true),

('Vinzirast Wien', 'notschlafstelle',
 'Vinzirast bietet Notunterkünfte und mehr für Obdachlose in Wien. Basisversorgung und Sozialbetreuung.',
 'Währinger Straße 44', '1090', 'Wien', 'Wien', 'AT',
 48.2198, 16.3562, '01 317 55 00', 'office@vinzirast.at', 'https://www.vinzirast.at',
 'täglich, Einlass ab 19 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Sozialberatung'],
 ARRAY['notschlafstelle','wien','vinzirast'], true, true),

('Obdachlosenheim Graz – Caritas', 'notschlafstelle',
 'Caritas Graz betreibt Notunterkünfte für Obdachlose in Graz. Schlafplatz mit Basisversorgung.',
 'Grabenstraße 39', '8010', 'Graz', 'Steiermark', 'AT',
 47.0707, 15.4394, '0316 8015 0', 'notunterkunft@caritas-graz.at', 'https://www.caritas-graz.at',
 'täglich 20–8 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Dusche','Beratung'],
 ARRAY['notschlafstelle','graz','caritas'], true, true),

('Notschlafstelle Linz – Caritas', 'notschlafstelle',
 'Caritas OÖ bietet Notunterkünfte für Obdachlose in Linz. Schlafplatz und Grundversorgung.',
 'Kapuzinerstraße 84', '4020', 'Linz', 'Oberösterreich', 'AT',
 48.2972, 14.2784, '0732 7610 0', 'notunterkunft@caritas-linz.at', 'https://www.caritas-linz.at',
 'täglich, Einlass ab 19 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Sozialberatung'],
 ARRAY['notschlafstelle','linz','caritas'], true, true),

('Männerheim Salzburg – Caritas', 'notschlafstelle',
 'Caritas Salzburg betreibt ein Notquartier für obdachlose Männer in Salzburg.',
 'Sterneckstraße 2', '5020', 'Salzburg', 'Salzburg', 'AT',
 47.8121, 13.0456, '0662 8015 0', 'notunterkunft@caritas-salzburg.at', 'https://www.caritas-salzburg.at',
 'täglich 20–8 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Dusche','Beratung'],
 ARRAY['notschlafstelle','salzburg','caritas'], true, true),

('Notquartier Innsbruck – Caritas Tirol', 'notschlafstelle',
 'Caritas Tirol bietet in Innsbruck Notunterkünfte für obdachlose Menschen. Schlafplatz und Sozialbetreuung.',
 'Heiliggeiststraße 16', '6020', 'Innsbruck', 'Tirol', 'AT',
 47.2651, 11.3926, '0512 7270 0', 'notunterkunft@caritas-tirol.at', 'https://www.caritas-tirol.at',
 'täglich, Einlass ab 19 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Sozialberatung'],
 ARRAY['notschlafstelle','innsbruck','caritas'], true, true),

('Notschlafstelle Klagenfurt – Caritas', 'notschlafstelle',
 'Caritas Kärnten betreibt Notunterkünfte für Obdachlose in Klagenfurt.',
 'Sterneckstraße 26', '9020', 'Klagenfurt', 'Kärnten', 'AT',
 46.6148, 14.3100, '0463 5518 0', 'notunterkunft@caritas-kaernten.at', 'https://www.caritas-kaernten.at',
 'täglich 20–8 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Dusche','Beratung'],
 ARRAY['notschlafstelle','klagenfurt','caritas'], true, true),

('Notunterkunft St. Pölten – Diakonie', 'notschlafstelle',
 'Diakonie NÖ bietet Notschlafplätze für Obdachlose in St. Pölten und Niederösterreich.',
 'Linzer Straße 8', '3100', 'St. Pölten', 'Niederösterreich', 'AT',
 48.2054, 15.6218, '02742 71 730', 'notunterkunft@diakonie-noe.at', 'https://www.diakonie-noe.at',
 'täglich, Einlass ab 19 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Sozialberatung'],
 ARRAY['notschlafstelle','st-pölten','diakonie'], true, true),

('Winternotquartier Wels – Rotes Kreuz', 'notschlafstelle',
 'Rotes Kreuz Wels betreibt Notunterkünfte für Obdachlose. Schlafplatz mit Basisversorgung.',
 'Bahnhofstraße 18', '4600', 'Wels', 'Oberösterreich', 'AT',
 48.1611, 14.0247, '07242 6990 0', 'wels@roteskreuz.at', 'https://www.roteskreuz.at',
 'täglich 20–8 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Dusche','Beratung'],
 ARRAY['notschlafstelle','wels','drk'], true, true),

('Notunterkunft Eisenstadt – Caritas', 'notschlafstelle',
 'Caritas Burgenland bietet Notschlafplätze für Obdachlose in Eisenstadt und dem Burgenland.',
 'Mattersburger Straße 27', '7000', 'Eisenstadt', 'Burgenland', 'AT',
 47.8457, 16.5245, '02682 777 0', 'notunterkunft@caritas-burgenland.at', 'https://www.caritas-burgenland.at',
 'täglich, Einlass ab 19 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Sozialberatung'],
 ARRAY['notschlafstelle','eisenstadt','caritas'], true, true),

-- ── SCHWEIZ (8) ──────────────────────────────────────────────────────────
('Obdachlosenunterkunft Zürich – Soziale Einrichtungen', 'notschlafstelle',
 'Stadt Zürich betreibt mehrere Notunterkünfte für Obdachlose. Schlafplatz mit Basisversorgung.',
 'Militärstraße 75', '8004', 'Zürich', 'Zürich', 'CH',
 47.3784, 8.5244, '044 444 11 11', 'notunterkunft@zuerich.ch', 'https://www.stadt-zuerich.ch',
 'täglich, Einlass ab 20 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Dusche','Sozialberatung'],
 ARRAY['notschlafstelle','zürich','obdachlos'], true, true),

('Notschlafstelle Bern – Heilsarmee', 'notschlafstelle',
 'Die Heilsarmee Bern betreibt Notunterkünfte für Obdachlose in Bern. Schlafplatz und Grundversorgung.',
 'Laupenstraße 35', '3008', 'Bern', 'Bern', 'CH',
 46.9451, 7.4198, '031 388 05 88', 'bern@heilsarmee.ch', 'https://www.heilsarmee.ch',
 'täglich 20–8 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Sozialberatung'],
 ARRAY['notschlafstelle','bern','heilsarmee'], true, true),

('Notschlafstelle Basel – Caritas', 'notschlafstelle',
 'Caritas Basel bietet Notschlafplätze für Obdachlose in Basel. Basisversorgung inklusive.',
 'Gärtnerstraße 46', '4057', 'Basel', 'Basel-Stadt', 'CH',
 47.5672, 7.5952, '061 686 43 43', 'notunterkunft@caritas-basel.ch', 'https://www.caritas-basel.ch',
 'täglich, Einlass ab 19 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Dusche','Beratung'],
 ARRAY['notschlafstelle','basel','caritas'], true, true),

('Notunterkunft Genf – Caritas', 'notschlafstelle',
 'Caritas Genève betreibt Notunterkünfte für Obdachlose in Genf. Schlafplatz mit Verpflegung.',
 'Rue Baulacre 23', '1202', 'Genf', 'Genf', 'CH',
 46.2088, 6.1401, '022 579 00 00', 'notunterkunft@caritas-geneve.ch', 'https://www.caritas-geneve.ch',
 'täglich 20–8 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Sozialberatung'],
 ARRAY['notschlafstelle','genf','caritas'], true, true),

('Heilsarmee Obdachlosenunterkunft Zürich', 'notschlafstelle',
 'Die Heilsarmee Zürich betreibt eine Notunterkunft für Obdachlose. Schlafplatz und Basisversorgung.',
 'Molkenstraße 9', '8004', 'Zürich', 'Zürich', 'CH',
 47.3762, 8.5241, '044 444 49 44', 'info@heilsarmee-zuerich.ch', 'https://www.heilsarmee.ch',
 'täglich, Einlass ab 18 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Dusche','Beratung'],
 ARRAY['notschlafstelle','zürich','heilsarmee'], true, true),

('Caritas Notunterkunft Luzern', 'notschlafstelle',
 'Caritas Luzern bietet Notschlafplätze für Obdachlose. Basisversorgung mit Schlafplatz und Mahlzeiten.',
 'Kasernenplatz 3', '6003', 'Luzern', 'Luzern', 'CH',
 47.0469, 8.3100, '041 368 50 50', 'notunterkunft@caritas-luzern.ch', 'https://www.caritas-luzern.ch',
 'täglich 20–8 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Sozialberatung'],
 ARRAY['notschlafstelle','luzern','caritas'], true, true),

('Notunterkunft Winterthur – Heilsarmee', 'notschlafstelle',
 'Heilsarmee Winterthur bietet Notschlafplätze für Obdachlose. Schlafplatz und Grundversorgung.',
 'Rudolfstraße 1', '8400', 'Winterthur', 'Zürich', 'CH',
 47.5007, 8.7239, '052 267 22 22', 'winterthur@heilsarmee.ch', 'https://www.heilsarmee.ch',
 'täglich, Einlass ab 19 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Dusche','Beratung'],
 ARRAY['notschlafstelle','winterthur','heilsarmee'], true, true),

('Caritas Notunterkunft St. Gallen', 'notschlafstelle',
 'Caritas St. Gallen bietet Notschlafplätze für Obdachlose in der Region.',
 'Teufener Straße 65', '9000', 'St. Gallen', 'St. Gallen', 'CH',
 47.4169, 9.3666, '071 228 55 55', 'notunterkunft@caritas-stgallen.ch', 'https://www.caritas-stgallen.ch',
 'täglich 20–8 Uhr',
 ARRAY['Schlafplatz','Mahlzeiten','Sozialberatung'],
 ARRAY['notschlafstelle','st-gallen','caritas'], true, true),

-- ═══════════════════════════════════════════════════════════
-- JUGENDHILFE (50)
-- ═══════════════════════════════════════════════════════════

-- ── DEUTSCHLAND (32) ──────────────────────────────────────────────────────
('SOS-Kinderdorf Berlin', 'jugendhilfe',
 'SOS-Kinderdorf Berlin bietet Jugendhilfe, Familienunterstützung und Wohngruppen für Kinder und Jugendliche in Not.',
 'Rostocker Straße 36', '10553', 'Berlin', 'Berlin', 'DE',
 52.5300, 13.3463, '030 39 00 70', 'berlin@sos-kinderdorf.de', 'https://www.sos-kinderdorf.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Jugendhilfe','Wohngruppen','Familienberatung','Kinderschutz'],
 ARRAY['jugendhilfe','berlin','sos'], true, true),

('Caritas Jugendzentrum Hamburg', 'jugendhilfe',
 'Caritas Hamburg bietet Jugendhilfe, offene Jugendarbeit und Beratung für Kinder und Jugendliche.',
 'Brennerstraße 66', '21079', 'Hamburg', 'Hamburg', 'DE',
 53.4681, 9.9736, '040 2000 1000', 'jugendhilfe@caritas-hamburg.de', 'https://www.caritas-hamburg.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Offene Jugendarbeit','Beratung','Freizeitangebote'],
 ARRAY['jugendhilfe','hamburg','caritas'], true, true),

('SOS-Kinderdorf München', 'jugendhilfe',
 'SOS-Kinderdorf München unterstützt Kinder und Familien mit Jugendhilfe, Beratung und Wohngruppen.',
 'Göschenstraße 16', '81679', 'München', 'Bayern', 'DE',
 48.1426, 11.6058, '089 450 01 0', 'muenchen@sos-kinderdorf.de', 'https://www.sos-kinderdorf.de',
 'Mo–Fr 8–18 Uhr',
 ARRAY['Jugendhilfe','Wohngruppen','Familienberatung'],
 ARRAY['jugendhilfe','münchen','sos'], true, true),

('Diakonie Jugendhilfe Köln', 'jugendhilfe',
 'Diakonie Köln bietet umfassende Jugendhilfe für Kinder und Jugendliche. Beratung, Wohngruppen, Betreuung.',
 'Bonner Straße 500', '50968', 'Köln', 'Nordrhein-Westfalen', 'DE',
 50.8966, 6.9625, '0221 386 56 0', 'jugendhilfe@diakonie-koeln.de', 'https://www.diakonie-koeln.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Jugendhilfe','Wohngruppen','Familienberatung','Schulunterstützung'],
 ARRAY['jugendhilfe','köln','diakonie'], true, true),

('AWO Jugendhilfe Frankfurt', 'jugendhilfe',
 'AWO Frankfurt bietet Jugendhilfe für Kinder und Jugendliche. Beratung, Förderung und Freizeitangebote.',
 'Henschelstraße 11', '60314', 'Frankfurt am Main', 'Hessen', 'DE',
 50.1121, 8.7218, '069 298 07 0', 'jugendhilfe@awo-frankfurt.de', 'https://www.awo-frankfurt.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Jugendhilfe','Beratung','Freizeitangebote'],
 ARRAY['jugendhilfe','frankfurt','awo'], true, true),

('Caritas Jugendhilfe Stuttgart', 'jugendhilfe',
 'Caritas Stuttgart bietet Jugendhilfe und Familienberatung. Unterstützung für Kinder in schwierigen Situationen.',
 'Strombergstraße 11', '70188', 'Stuttgart', 'Baden-Württemberg', 'DE',
 48.7877, 9.2039, '0711 2633 0', 'jugendhilfe@caritas-stuttgart.de', 'https://www.caritas-stuttgart.de',
 'Mo–Fr 8–18 Uhr',
 ARRAY['Jugendhilfe','Wohngruppen','Familienberatung'],
 ARRAY['jugendhilfe','stuttgart','caritas'], true, true),

('SOS-Kinderdorf Düsseldorf', 'jugendhilfe',
 'SOS-Kinderdorf Düsseldorf bietet Jugendhilfe, Familienunterstützung und Wohngruppen für Kinder in Not.',
 'Kaiserswerther Straße 450', '40474', 'Düsseldorf', 'Nordrhein-Westfalen', 'DE',
 51.2840, 6.7744, '0211 450 11 0', 'duesseldorf@sos-kinderdorf.de', 'https://www.sos-kinderdorf.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Jugendhilfe','Wohngruppen','Familienberatung','Kinderschutz'],
 ARRAY['jugendhilfe','düsseldorf','sos'], true, true),

('AWO Jugendhilfe Nürnberg', 'jugendhilfe',
 'AWO Nürnberg bietet umfassende Jugendhilfe für Kinder und Jugendliche in der Region.',
 'Valznerweiherstraße 160', '90480', 'Nürnberg', 'Bayern', 'DE',
 49.4557, 11.1219, '0911 4506 0', 'jugendhilfe@awo-nuernberg.de', 'https://www.awo-nuernberg.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Jugendhilfe','Beratung','Freizeitangebote'],
 ARRAY['jugendhilfe','nürnberg','awo'], true, true),

('SOS-Kinderdorf Dresden', 'jugendhilfe',
 'SOS-Kinderdorf Dresden unterstützt Kinder und Jugendliche mit Jugendhilfe und Familienberatung.',
 'Gorbitzer Straße 39', '01169', 'Dresden', 'Sachsen', 'DE',
 51.0379, 13.6739, '0351 499 74 0', 'dresden@sos-kinderdorf.de', 'https://www.sos-kinderdorf.de',
 'Mo–Fr 8–18 Uhr',
 ARRAY['Jugendhilfe','Wohngruppen','Familienberatung'],
 ARRAY['jugendhilfe','dresden','sos'], true, true),

('Caritas Jugendhilfe Leipzig', 'jugendhilfe',
 'Caritas Leipzig bietet Jugendhilfe und Familienberatung für Kinder und Jugendliche in schwierigen Lagen.',
 'Stöckelstraße 4', '04347', 'Leipzig', 'Sachsen', 'DE',
 51.3488, 12.4198, '0341 98640 0', 'jugendhilfe@caritas-leipzig.de', 'https://www.caritas-leipzig.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Jugendhilfe','Wohngruppen','Familienberatung'],
 ARRAY['jugendhilfe','leipzig','caritas'], true, true),

('AWO Jugendhilfe Dortmund', 'jugendhilfe',
 'AWO Dortmund bietet Jugendhilfe, offene Jugendarbeit und Familienberatung für Kinder und Jugendliche.',
 'Klönnestraße 2', '44137', 'Dortmund', 'Nordrhein-Westfalen', 'DE',
 51.5136, 7.4705, '0231 18 48 0', 'jugendhilfe@awo-dortmund.de', 'https://www.awo-dortmund.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Jugendhilfe','Offene Jugendarbeit','Beratung'],
 ARRAY['jugendhilfe','dortmund','awo'], true, true),

('Diakonie Jugendhilfe Essen', 'jugendhilfe',
 'Diakonie Essen bietet Jugendhilfe für Kinder und Jugendliche. Wohngruppen, Beratung und Förderangebote.',
 'Hachestraße 8', '45130', 'Essen', 'Nordrhein-Westfalen', 'DE',
 51.4441, 7.0099, '0201 2209 0', 'jugendhilfe@diakonie-essen.de', 'https://www.diakonie-essen.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Jugendhilfe','Wohngruppen','Familienberatung'],
 ARRAY['jugendhilfe','essen','diakonie'], true, true),

('SOS-Kinderdorf Hannover', 'jugendhilfe',
 'SOS-Kinderdorf Hannover unterstützt Kinder und Familien mit Jugendhilfe und stationärer Betreuung.',
 'Heisterbergallee 3', '30453', 'Hannover', 'Niedersachsen', 'DE',
 52.3466, 9.6837, '0511 490 05 0', 'hannover@sos-kinderdorf.de', 'https://www.sos-kinderdorf.de',
 'Mo–Fr 8–18 Uhr',
 ARRAY['Jugendhilfe','Wohngruppen','Familienberatung','Kinderschutz'],
 ARRAY['jugendhilfe','hannover','sos'], true, true),

('AWO Jugendhilfe Bremen', 'jugendhilfe',
 'AWO Bremen bietet Jugendhilfe und Familienunterstützung für Kinder und Jugendliche in Bremen.',
 'Pagentorner Straße 2', '28195', 'Bremen', 'Bremen', 'DE',
 53.0802, 8.8079, '0421 34 04 0', 'jugendhilfe@awo-bremen.de', 'https://www.awo-bremen.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Jugendhilfe','Offene Jugendarbeit','Familienberatung'],
 ARRAY['jugendhilfe','bremen','awo'], true, true),

('Caritas Jugendhilfe Augsburg', 'jugendhilfe',
 'Caritas Augsburg bietet Jugendhilfe und Familienberatung. Unterstützung für Kinder und Jugendliche.',
 'Auf dem Kreuz 41', '86152', 'Augsburg', 'Bayern', 'DE',
 48.3616, 10.8987, '0821 3156 0', 'jugendhilfe@caritas-augsburg.de', 'https://www.caritas-augsburg.de',
 'Mo–Fr 8–18 Uhr',
 ARRAY['Jugendhilfe','Wohngruppen','Familienberatung'],
 ARRAY['jugendhilfe','augsburg','caritas'], true, true),

('SOS-Kinderdorf Freiburg', 'jugendhilfe',
 'SOS-Kinderdorf Freiburg bietet Jugendhilfe und Familienunterstützung für Kinder in schwierigen Lagen.',
 'Wintererstraße 25', '79104', 'Freiburg', 'Baden-Württemberg', 'DE',
 48.0053, 7.8518, '0761 291 80 0', 'freiburg@sos-kinderdorf.de', 'https://www.sos-kinderdorf.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Jugendhilfe','Wohngruppen','Familienberatung','Kinderschutz'],
 ARRAY['jugendhilfe','freiburg','sos'], true, true),

('AWO Jugendhilfe Bielefeld', 'jugendhilfe',
 'AWO Bielefeld bietet Jugendhilfe und offene Jugendarbeit für Kinder und Jugendliche in Bielefeld.',
 'Niederwall 26', '33602', 'Bielefeld', 'Nordrhein-Westfalen', 'DE',
 52.0220, 8.5341, '0521 9286 0', 'jugendhilfe@awo-bielefeld.de', 'https://www.awo-bielefeld.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Jugendhilfe','Offene Jugendarbeit','Familienberatung'],
 ARRAY['jugendhilfe','bielefeld','awo'], true, true),

('Caritas Jugendhilfe Wuppertal', 'jugendhilfe',
 'Caritas Wuppertal bietet Jugendhilfe und Familienberatung. Wohngruppen und ambulante Angebote.',
 'Hünefeldstraße 12', '42103', 'Wuppertal', 'Nordrhein-Westfalen', 'DE',
 51.2571, 7.1514, '0202 2470 0', 'jugendhilfe@caritas-wuppertal.de', 'https://www.caritas-wuppertal.de',
 'Mo–Fr 8–18 Uhr',
 ARRAY['Jugendhilfe','Wohngruppen','Familienberatung'],
 ARRAY['jugendhilfe','wuppertal','caritas'], true, true),

('Diakonie Jugendhilfe Bochum', 'jugendhilfe',
 'Diakonie Bochum bietet Jugendhilfe für Kinder und Jugendliche. Stationäre und ambulante Angebote.',
 'Hattinger Straße 6', '44789', 'Bochum', 'Nordrhein-Westfalen', 'DE',
 51.4799, 7.2158, '0234 32 71 0', 'jugendhilfe@diakonie-bochum.de', 'https://www.diakonie-bochum.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Jugendhilfe','Wohngruppen','Familienberatung'],
 ARRAY['jugendhilfe','bochum','diakonie'], true, true),

('AWO Jugendhilfe Kassel', 'jugendhilfe',
 'AWO Kassel bietet Jugendhilfe und Familienberatung für Kinder und Jugendliche in der Region.',
 'Wolfhager Straße 1', '34117', 'Kassel', 'Hessen', 'DE',
 51.3150, 9.4797, '0561 7391 0', 'jugendhilfe@awo-kassel.de', 'https://www.awo-kassel.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Jugendhilfe','Offene Jugendarbeit','Familienberatung'],
 ARRAY['jugendhilfe','kassel','awo'], true, true),

('Caritas Jugendhilfe Mannheim', 'jugendhilfe',
 'Caritas Mannheim bietet Jugendhilfe und Familienberatung. Wohngruppen und ambulante Hilfen.',
 'Mollstraße 13', '68165', 'Mannheim', 'Baden-Württemberg', 'DE',
 49.4919, 8.4867, '0621 120 00 0', 'jugendhilfe@caritas-mannheim.de', 'https://www.caritas-mannheim.de',
 'Mo–Fr 8–18 Uhr',
 ARRAY['Jugendhilfe','Wohngruppen','Familienberatung'],
 ARRAY['jugendhilfe','mannheim','caritas'], true, true),

('AWO Jugendhilfe Mainz', 'jugendhilfe',
 'AWO Mainz bietet Jugendhilfe und offene Jugendarbeit für Kinder und Jugendliche in Mainz.',
 'Schillerstraße 20', '55116', 'Mainz', 'Rheinland-Pfalz', 'DE',
 50.0011, 8.2726, '06131 9834 0', 'jugendhilfe@awo-mainz.de', 'https://www.awo-mainz.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Jugendhilfe','Offene Jugendarbeit','Familienberatung'],
 ARRAY['jugendhilfe','mainz','awo'], true, true),

('Diakonie Jugendhilfe Erfurt', 'jugendhilfe',
 'Diakonie Thüringen bietet Jugendhilfe und Familienberatung. Wohngruppen und ambulante Angebote.',
 'Puschkinstraße 4', '99084', 'Erfurt', 'Thüringen', 'DE',
 50.9791, 11.0359, '0361 5514 0', 'jugendhilfe@diakonie-thueringen.de', 'https://www.diakonie-thueringen.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Jugendhilfe','Wohngruppen','Familienberatung'],
 ARRAY['jugendhilfe','erfurt','diakonie'], true, true),

('Caritas Jugendhilfe Magdeburg', 'jugendhilfe',
 'Caritas Sachsen-Anhalt bietet Jugendhilfe für Kinder und Jugendliche in Magdeburg.',
 'Thälmannstraße 50', '39104', 'Magdeburg', 'Sachsen-Anhalt', 'DE',
 52.1325, 11.6393, '0391 5448 0', 'jugendhilfe@caritas-magdeburg.de', 'https://www.caritas-magdeburg.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Jugendhilfe','Wohngruppen','Familienberatung'],
 ARRAY['jugendhilfe','magdeburg','caritas'], true, true),

('AWO Jugendhilfe Rostock', 'jugendhilfe',
 'AWO Rostock bietet Jugendhilfe und Familienberatung für Kinder und Jugendliche in Mecklenburg.',
 'Erich-Schlesinger-Straße 50', '18059', 'Rostock', 'Mecklenburg-Vorpommern', 'DE',
 54.0801, 12.0882, '0381 490 43 0', 'jugendhilfe@awo-rostock.de', 'https://www.awo-rostock.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Jugendhilfe','Offene Jugendarbeit','Familienberatung'],
 ARRAY['jugendhilfe','rostock','awo'], true, true),

('Caritas Jugendhilfe Kiel', 'jugendhilfe',
 'Caritas Kiel bietet Jugendhilfe und Familienberatung. Wohngruppen und ambulante Unterstützung.',
 'Holstenstraße 58', '24103', 'Kiel', 'Schleswig-Holstein', 'DE',
 54.3215, 10.1368, '0431 662 77 0', 'jugendhilfe@caritas-kiel.de', 'https://www.caritas-kiel.de',
 'Mo–Fr 8–18 Uhr',
 ARRAY['Jugendhilfe','Wohngruppen','Familienberatung','Kinderschutz'],
 ARRAY['jugendhilfe','kiel','caritas'], true, true),

('Diakonie Jugendhilfe Lübeck', 'jugendhilfe',
 'Diakonie Lübeck bietet Jugendhilfe für Kinder und Jugendliche. Stationäre und ambulante Angebote.',
 'Kronsforder Allee 15', '23560', 'Lübeck', 'Schleswig-Holstein', 'DE',
 53.8783, 10.6930, '0451 4005 0', 'jugendhilfe@diakonie-luebeck.de', 'https://www.diakonie-luebeck.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Jugendhilfe','Wohngruppen','Familienberatung'],
 ARRAY['jugendhilfe','lübeck','diakonie'], true, true),

('AWO Jugendhilfe Saarbrücken', 'jugendhilfe',
 'AWO Saarland bietet Jugendhilfe und Familienberatung für Kinder und Jugendliche im Saarland.',
 'Ursulinenstraße 67', '66111', 'Saarbrücken', 'Saarland', 'DE',
 49.2338, 6.9988, '0681 40054 0', 'jugendhilfe@awo-saarland.de', 'https://www.awo-saarland.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Jugendhilfe','Offene Jugendarbeit','Familienberatung'],
 ARRAY['jugendhilfe','saarbrücken','awo'], true, true),

('Caritas Jugendhilfe Osnabrück', 'jugendhilfe',
 'Caritas Osnabrück bietet Jugendhilfe und Familienberatung. Wohngruppen und ambulante Angebote.',
 'Johannisstraße 91', '49074', 'Osnabrück', 'Niedersachsen', 'DE',
 52.2798, 8.0508, '0541 3384 0', 'jugendhilfe@caritas-osnabrueck.de', 'https://www.caritas-osnabrueck.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Jugendhilfe','Wohngruppen','Familienberatung'],
 ARRAY['jugendhilfe','osnabrück','caritas'], true, true),

-- ── ÖSTERREICH (10) ────────────────────────────────────────────────────────
('SOS Kinderdorf Wien', 'jugendhilfe',
 'SOS-Kinderdorf Wien bietet umfassende Jugendhilfe, stationäre Betreuung und Familienunterstützung.',
 'Marquardtgasse 3', '1090', 'Wien', 'Wien', 'AT',
 48.2175, 16.3549, '01 368 32 45', 'wien@sos-kinderdorf.at', 'https://www.sos-kinderdorf.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Jugendhilfe','Wohngruppen','Familienberatung','Kinderschutz'],
 ARRAY['jugendhilfe','wien','sos'], true, true),

('Caritas Jugendhilfe Wien', 'jugendhilfe',
 'Caritas Wien bietet Jugendhilfe, Familienberatung und Wohngruppen für Kinder und Jugendliche.',
 'Albrechtskreithgasse 19', '1160', 'Wien', 'Wien', 'AT',
 48.2093, 16.3167, '01 87812 0', 'jugendhilfe@caritas-wien.at', 'https://www.caritas.at',
 'Mo–Fr 8–18 Uhr',
 ARRAY['Jugendhilfe','Wohngruppen','Familienberatung'],
 ARRAY['jugendhilfe','wien','caritas'], true, true),

('Diakonie Jugendhilfe Wien', 'jugendhilfe',
 'Diakonie Österreich bietet Jugendhilfe und Familienberatung für Kinder und Jugendliche in Wien.',
 'Steinergasse 3', '1170', 'Wien', 'Wien', 'AT',
 48.2167, 16.3242, '01 40 84 80', 'jugendhilfe@diakonie.at', 'https://www.diakonie.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Jugendhilfe','Wohngruppen','Familienberatung'],
 ARRAY['jugendhilfe','wien','diakonie'], true, true),

('SOS Kinderdorf Graz', 'jugendhilfe',
 'SOS-Kinderdorf Graz bietet Jugendhilfe, stationäre Betreuung und Familienunterstützung in der Steiermark.',
 'Murlingengasse 37', '8020', 'Graz', 'Steiermark', 'AT',
 47.0643, 15.4310, '0316 58 02 0', 'graz@sos-kinderdorf.at', 'https://www.sos-kinderdorf.at',
 'Mo–Fr 8–18 Uhr',
 ARRAY['Jugendhilfe','Wohngruppen','Familienberatung','Kinderschutz'],
 ARRAY['jugendhilfe','graz','sos'], true, true),

('Caritas Jugendhilfe Linz', 'jugendhilfe',
 'Caritas OÖ bietet Jugendhilfe und Familienberatung für Kinder und Jugendliche in Linz.',
 'Kapuzinerstraße 84', '4020', 'Linz', 'Oberösterreich', 'AT',
 48.2972, 14.2784, '0732 7610 0', 'jugendhilfe@caritas-linz.at', 'https://www.caritas-linz.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Jugendhilfe','Wohngruppen','Familienberatung'],
 ARRAY['jugendhilfe','linz','caritas'], true, true),

('AWÖ Jugendhilfe Salzburg', 'jugendhilfe',
 'Die Arbeiterwohlfahrt Salzburg bietet Jugendhilfe und Familienberatung für Kinder in Salzburg.',
 'Paracelsusstraße 2', '5020', 'Salzburg', 'Salzburg', 'AT',
 47.8091, 13.0422, '0662 432 38 0', 'jugendhilfe@awoe-salzburg.at', 'https://www.awoe-salzburg.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Jugendhilfe','Beratung','Familienberatung'],
 ARRAY['jugendhilfe','salzburg','awo'], true, true),

('Diakonie Jugendhilfe Innsbruck', 'jugendhilfe',
 'Diakonie Tirol bietet Jugendhilfe und Familienberatung für Kinder und Jugendliche in Tirol.',
 'Heiliggeiststraße 16', '6020', 'Innsbruck', 'Tirol', 'AT',
 47.2651, 11.3926, '0512 59 80 0', 'jugendhilfe@diakonie-tirol.at', 'https://www.diakonie-tirol.at',
 'Mo–Fr 8–18 Uhr',
 ARRAY['Jugendhilfe','Wohngruppen','Familienberatung'],
 ARRAY['jugendhilfe','innsbruck','diakonie'], true, true),

('SOS Kinderdorf Innsbruck', 'jugendhilfe',
 'SOS-Kinderdorf Innsbruck bietet Jugendhilfe und stationäre Betreuung für Kinder in Tirol.',
 'Stafflerstraße 10A', '6020', 'Innsbruck', 'Tirol', 'AT',
 47.2645, 11.3908, '0512 39 23 80', 'innsbruck@sos-kinderdorf.at', 'https://www.sos-kinderdorf.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Jugendhilfe','Wohngruppen','Familienberatung','Kinderschutz'],
 ARRAY['jugendhilfe','innsbruck','sos'], true, true),

('Caritas Jugendhilfe Klagenfurt', 'jugendhilfe',
 'Caritas Kärnten bietet Jugendhilfe und Familienberatung für Kinder und Jugendliche in Kärnten.',
 'Sterneckstraße 26', '9020', 'Klagenfurt', 'Kärnten', 'AT',
 46.6148, 14.3100, '0463 5518 0', 'jugendhilfe@caritas-kaernten.at', 'https://www.caritas-kaernten.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Jugendhilfe','Wohngruppen','Familienberatung'],
 ARRAY['jugendhilfe','klagenfurt','caritas'], true, true),

('Diakonie Jugendhilfe St. Pölten', 'jugendhilfe',
 'Diakonie NÖ bietet Jugendhilfe und Familienberatung für Kinder und Jugendliche in Niederösterreich.',
 'Linzer Straße 8', '3100', 'St. Pölten', 'Niederösterreich', 'AT',
 48.2054, 15.6218, '02742 71 730', 'jugendhilfe@diakonie-noe.at', 'https://www.diakonie-noe.at',
 'Mo–Fr 8–18 Uhr',
 ARRAY['Jugendhilfe','Wohngruppen','Familienberatung','Kinderschutz'],
 ARRAY['jugendhilfe','st-pölten','diakonie'], true, true),

-- ── SCHWEIZ (8) ──────────────────────────────────────────────────────────
('SOS Kinderdorf Zürich', 'jugendhilfe',
 'SOS-Kinderdorf Zürich bietet Jugendhilfe und Familienunterstützung für Kinder in der Deutschschweiz.',
 'Rosengartenstraße 28', '8037', 'Zürich', 'Zürich', 'CH',
 47.3960, 8.5259, '044 366 50 50', 'zuerich@sos-kinderdorf.ch', 'https://www.sos-kinderdorf.ch',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Jugendhilfe','Wohngruppen','Familienberatung','Kinderschutz'],
 ARRAY['jugendhilfe','zürich','sos'], true, true),

('Pro Juventute Zürich', 'jugendhilfe',
 'Pro Juventute Zürich bietet Kinder- und Jugendhilfe, Beratung und Förderangebote. Betreibt Krisentelefon 147.',
 'Zentralstraße 55', '8003', 'Zürich', 'Zürich', 'CH',
 47.3752, 8.5220, '044 256 77 77', 'info@projuventute.ch', 'https://www.projuventute.ch',
 'Mo–Fr 8–17 Uhr',
 ARRAY['Jugendhilfe','Krisentelefon','Beratung','Förderangebote'],
 ARRAY['jugendhilfe','zürich','projuventute'], true, true),

('Caritas Jugendhilfe Bern', 'jugendhilfe',
 'Caritas Bern bietet Jugendhilfe und Familienberatung für Kinder und Jugendliche in der Region Bern.',
 'Dammweg 8-10', '3013', 'Bern', 'Bern', 'CH',
 46.9572, 7.4504, '031 380 65 65', 'jugendhilfe@caritasbern.ch', 'https://www.caritasbern.ch',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Jugendhilfe','Wohngruppen','Familienberatung'],
 ARRAY['jugendhilfe','bern','caritas'], true, true),

('SOS Kinderdorf Bern', 'jugendhilfe',
 'SOS-Kinderdorf Bern bietet Jugendhilfe und stationäre Betreuung für Kinder in der Region Bern.',
 'Muristraße 12', '3006', 'Bern', 'Bern', 'CH',
 46.9464, 7.4676, '031 359 67 67', 'bern@sos-kinderdorf.ch', 'https://www.sos-kinderdorf.ch',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Jugendhilfe','Wohngruppen','Familienberatung','Kinderschutz'],
 ARRAY['jugendhilfe','bern','sos'], true, true),

('Pro Juventute Bern', 'jugendhilfe',
 'Pro Juventute Bern bietet Kinder- und Jugendhilfe und Beratungsangebote für Familien in der Region.',
 'Monbijoustraße 22', '3011', 'Bern', 'Bern', 'CH',
 46.9460, 7.4432, '031 355 77 77', 'bern@projuventute.ch', 'https://www.projuventute.ch',
 'Mo–Fr 8–17 Uhr',
 ARRAY['Jugendhilfe','Beratung','Förderangebote','Krisentelefon'],
 ARRAY['jugendhilfe','bern','projuventute'], true, true),

('Caritas Jugendhilfe Basel', 'jugendhilfe',
 'Caritas Basel bietet Jugendhilfe und Familienberatung für Kinder und Jugendliche in der Region Basel.',
 'Gärtnerstraße 46', '4057', 'Basel', 'Basel-Stadt', 'CH',
 47.5672, 7.5952, '061 686 43 43', 'jugendhilfe@caritas-basel.ch', 'https://www.caritas-basel.ch',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Jugendhilfe','Wohngruppen','Familienberatung'],
 ARRAY['jugendhilfe','basel','caritas'], true, true),

('Pro Juventute Luzern', 'jugendhilfe',
 'Pro Juventute Luzern bietet Kinder- und Jugendhilfe und Beratungsangebote für Kinder und Familien.',
 'Tribschenstraße 42', '6005', 'Luzern', 'Luzern', 'CH',
 47.0488, 8.3218, '041 368 40 40', 'luzern@projuventute.ch', 'https://www.projuventute.ch',
 'Mo–Fr 8–17 Uhr',
 ARRAY['Jugendhilfe','Beratung','Förderangebote','Krisentelefon'],
 ARRAY['jugendhilfe','luzern','projuventute'], true, true),

('Caritas Jugendhilfe St. Gallen', 'jugendhilfe',
 'Caritas St. Gallen bietet Jugendhilfe und Familienberatung für Kinder und Jugendliche in der Ostschweiz.',
 'Teufener Straße 65', '9000', 'St. Gallen', 'St. Gallen', 'CH',
 47.4169, 9.3666, '071 228 55 55', 'jugendhilfe@caritas-stgallen.ch', 'https://www.caritas-stgallen.ch',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Jugendhilfe','Wohngruppen','Familienberatung','Kinderschutz'],
 ARRAY['jugendhilfe','st-gallen','caritas'], true, true);

END IF;
END $$;
