-- ============================================================
-- Migration 010e: Sozialkaufhaus (50) + Krisentelefon (50)
-- Quellen: caritas.de, diakonie.de, telefonseelsorge.de, sos-kinderdorf.at, 143.ch
-- ============================================================

DO $$ BEGIN
IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='organizations' AND table_schema='public') THEN

INSERT INTO public.organizations
  (name, category, description, address, zip_code, city, state, country,
   latitude, longitude, phone, email, website, opening_hours, services, tags, is_verified, is_active)
VALUES

-- ═══════════════════════════════════════════════════════════
-- SOZIALKAUFHAUS (50)
-- ═══════════════════════════════════════════════════════════

-- ── DEUTSCHLAND (32) ──────────────────────────────────────────────────────
('Caritas KaufBar Berlin', 'sozialkaufhaus',
 'Günstige Secondhand-Waren für einkommensschwache Menschen. Möbel, Hausrat, Kleidung und mehr zu Sozialtarifen.',
 'Onkel-Tom-Straße 82', '14169', 'Berlin', 'Berlin', 'DE',
 52.4396, 13.2605, '030 890 69 0', 'info@caritas-berlin.de', 'https://www.caritas-berlin.de',
 'Mo–Sa 9–18 Uhr',
 ARRAY['Möbel','Hausrat','Kleidung','Sozialtarif'],
 ARRAY['sozialkaufhaus','berlin','secondhand'], true, true),

('Diakonie Kaufhaus Hamburg Rahlstedt', 'sozialkaufhaus',
 'Secondhand-Kaufhaus der Diakonie Hamburg. Günstige Waren aus Spenden – für Bedürftige zu ermäßigten Preisen.',
 'Schweriner Straße 2', '22143', 'Hamburg', 'Hamburg', 'DE',
 53.6015, 10.1596, '040 6709 93 0', 'info@diakonie-hamburg.de', 'https://www.diakonie-hamburg.de',
 'Mo–Fr 9–18 Uhr, Sa 9–14 Uhr',
 ARRAY['Möbel','Kleidung','Hausrat','Elektrogeräte'],
 ARRAY['sozialkaufhaus','hamburg','secondhand'], true, true),

('Caritas Kaufhaus München', 'sozialkaufhaus',
 'Sozialkaufhaus der Caritas München. Möbel, Kleidung und Hausrat zu günstigen Preisen für alle Bürger.',
 'Guldeinstraße 26', '80339', 'München', 'Bayern', 'DE',
 48.1401, 11.5357, '089 5502 0', 'info@caritas-muenchen.de', 'https://www.caritas-muenchen.de',
 'Mo–Sa 9–18 Uhr',
 ARRAY['Möbel','Hausrat','Kleidung','Spielzeug'],
 ARRAY['sozialkaufhaus','münchen','secondhand'], true, true),

('Oxfam Shop Köln Schildergasse', 'sozialkaufhaus',
 'Oxfam-Shop mit Secondhand-Waren. Erlöse gehen in Entwicklungsprojekte weltweit. Günstige Preise für alle.',
 'Schildergasse 68', '50667', 'Köln', 'Nordrhein-Westfalen', 'DE',
 50.9374, 6.9576, '0221 257 65 20', 'info@oxfam.de', 'https://www.oxfam.de',
 'Mo–Sa 10–19 Uhr',
 ARRAY['Kleidung','Bücher','Accessoires','Sozialer Handel'],
 ARRAY['sozialkaufhaus','köln','oxfam'], true, true),

('AWO Sozialkaufhaus Frankfurt', 'sozialkaufhaus',
 'Das AWO Sozialkaufhaus Frankfurt bietet gebrauchte Waren günstig an und unterstützt damit soziale Arbeit.',
 'Günthersburgallee 82', '60389', 'Frankfurt am Main', 'Hessen', 'DE',
 50.1400, 8.7100, '069 59 80 15 0', 'info@awo-frankfurt.de', 'https://www.awo-frankfurt.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Möbel','Kleidung','Hausrat','Bücher'],
 ARRAY['sozialkaufhaus','frankfurt','secondhand'], true, true),

('Caritas Kaufhaus Stuttgart Möhringen', 'sozialkaufhaus',
 'Sozialkaufhaus der Caritas Stuttgart mit großer Auswahl an Möbeln, Kleidung und Haushaltsgegenständen.',
 'Sigmaringer Straße 131', '70567', 'Stuttgart', 'Baden-Württemberg', 'DE',
 48.7176, 9.1559, '0711 7100 0', 'info@caritas-stuttgart.de', 'https://www.caritas-stuttgart.de',
 'Mo–Sa 9–18 Uhr',
 ARRAY['Möbel','Kleidung','Hausrat','Elektro'],
 ARRAY['sozialkaufhaus','stuttgart','secondhand'], true, true),

('Oxfam Shop Düsseldorf', 'sozialkaufhaus',
 'Oxfam-Shop Düsseldorf mit Secondhand-Kleidung, Büchern und Accessoires. Erlöse für humanitäre Hilfe.',
 'Schadowstraße 58', '40212', 'Düsseldorf', 'Nordrhein-Westfalen', 'DE',
 51.2268, 6.7804, '0211 863 51 10', 'info@oxfam.de', 'https://www.oxfam.de',
 'Mo–Sa 10–18 Uhr',
 ARRAY['Kleidung','Bücher','Accessoires','Sozialer Handel'],
 ARRAY['sozialkaufhaus','düsseldorf','oxfam'], true, true),

('Caritas KaufHaus Nürnberg', 'sozialkaufhaus',
 'Sozialkaufhaus der Caritas Nürnberg – günstige Waren aus Spenden für Bedürftige zu Sozialtarifen.',
 'Gostenhof 23', '90443', 'Nürnberg', 'Bayern', 'DE',
 49.4537, 11.0618, '0911 2355 0', 'info@caritas-nuernberg.de', 'https://www.caritas-nuernberg.de',
 'Mo–Fr 9–17 Uhr, Sa 9–14 Uhr',
 ARRAY['Möbel','Kleidung','Hausrat','Elektrogeräte'],
 ARRAY['sozialkaufhaus','nürnberg','secondhand'], true, true),

('Sozialkaufhaus Diakonie Dresden', 'sozialkaufhaus',
 'Gebrauchte Waren zu günstigen Preisen. Einkommensschwache erhalten zusätzliche Rabatte. Erlös für soziale Projekte.',
 'Glacisstraße 35', '01099', 'Dresden', 'Sachsen', 'DE',
 51.0655, 13.7498, '0351 8102 0', 'info@diakonie-dresden.de', 'https://www.diakonie-dresden.de',
 'Mo–Sa 9–18 Uhr',
 ARRAY['Möbel','Kleidung','Hausrat','Bücher'],
 ARRAY['sozialkaufhaus','dresden','secondhand'], true, true),

('Caritas KaufBar Leipzig', 'sozialkaufhaus',
 'Das Sozialkaufhaus der Caritas Leipzig bietet Gebrauchtwaren zu Sozialtarifen für Bedürftige an.',
 'Weißenfelser Straße 63', '04229', 'Leipzig', 'Sachsen', 'DE',
 51.3208, 12.3390, '0341 9981 0', 'info@caritas-leipzig.de', 'https://www.caritas-leipzig.de',
 'Mo–Fr 9–17 Uhr, Sa 9–14 Uhr',
 ARRAY['Möbel','Kleidung','Elektro','Bücher'],
 ARRAY['sozialkaufhaus','leipzig','secondhand'], true, true),

('Sozialkaufhaus AWO Dortmund', 'sozialkaufhaus',
 'AWO-Secondhandladen in Dortmund mit günstigem Hausrat, Kleidung und Möbeln für alle Einkommensgruppen.',
 'Südwall 2-4', '44137', 'Dortmund', 'Nordrhein-Westfalen', 'DE',
 51.5136, 7.4697, '0231 9034 0', 'info@awo-dortmund.de', 'https://www.awo-dortmund.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Möbel','Kleidung','Hausrat','Spielzeug'],
 ARRAY['sozialkaufhaus','dortmund','secondhand'], true, true),

('Oxfam Shop Essen', 'sozialkaufhaus',
 'Oxfam-Shop Essen mit Secondhand-Mode, Büchern und Spielzeug. Erlöse fließen in humanitäre Projekte.',
 'Kettwiger Straße 35', '45127', 'Essen', 'Nordrhein-Westfalen', 'DE',
 51.4569, 7.0138, '0201 24 78 34', 'info@oxfam.de', 'https://www.oxfam.de',
 'Mo–Sa 10–18 Uhr',
 ARRAY['Kleidung','Bücher','Accessoires','Spielzeug'],
 ARRAY['sozialkaufhaus','essen','oxfam'], true, true),

('Caritas Kaufhaus Hannover', 'sozialkaufhaus',
 'Sozialkaufhaus mit günstigen Gebrauchtwaren für Einkommensschwache. Möbel, Kleidung und Haushaltsgeräte.',
 'Schwarze-Bären-Straße 1', '30449', 'Hannover', 'Niedersachsen', 'DE',
 52.3646, 9.7004, '0511 7998 0', 'info@caritas-hannover.de', 'https://www.caritas-hannover.de',
 'Mo–Sa 9–18 Uhr',
 ARRAY['Möbel','Kleidung','Hausrat','Elektronik'],
 ARRAY['sozialkaufhaus','hannover','secondhand'], true, true),

('AWO Sozialkaufhaus Bremen', 'sozialkaufhaus',
 'Das AWO-Sozialkaufhaus Bremen bietet gebrauchte Waren günstig an. Erlöse unterstützen soziale Projekte.',
 'Bürgermeister-Smidt-Straße 64', '28195', 'Bremen', 'Bremen', 'DE',
 53.0774, 8.8050, '0421 5399 0', 'info@awo-bremen.de', 'https://www.awo-bremen.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Möbel','Kleidung','Hausrat','Bücher'],
 ARRAY['sozialkaufhaus','bremen','secondhand'], true, true),

('Caritas KaufBar Freiburg', 'sozialkaufhaus',
 'Sozialkaufhaus der Caritas Freiburg – gebrauchte Waren zu günstigen Preisen für alle Bevölkerungsgruppen.',
 'Okenstraße 17', '79108', 'Freiburg', 'Baden-Württemberg', 'DE',
 48.0204, 7.8356, '0761 8974 0', 'info@caritas-freiburg.de', 'https://www.caritas-freiburg.de',
 'Mo–Sa 9–18 Uhr',
 ARRAY['Möbel','Kleidung','Hausrat','Elektro'],
 ARRAY['sozialkaufhaus','freiburg','secondhand'], true, true),

('Oxfam Shop Karlsruhe', 'sozialkaufhaus',
 'Oxfam-Shop Karlsruhe mit Secondhand-Mode und Accessoires. Alle Erlöse gehen an humanitäre Projekte.',
 'Kaiserstraße 147', '76133', 'Karlsruhe', 'Baden-Württemberg', 'DE',
 49.0083, 8.4045, '0721 98 34 99', 'info@oxfam.de', 'https://www.oxfam.de',
 'Mo–Sa 10–18 Uhr',
 ARRAY['Kleidung','Bücher','Accessoires','Spielzeug'],
 ARRAY['sozialkaufhaus','karlsruhe','oxfam'], true, true),

('Diakonie Kaufhaus Augsburg', 'sozialkaufhaus',
 'Sozialkaufhaus der Diakonie Augsburg mit vielfältiger Auswahl an Secondhand-Waren zu Sozialtarifen.',
 'Morellstraße 44', '86159', 'Augsburg', 'Bayern', 'DE',
 48.3726, 10.9012, '0821 9003 0', 'info@diakonie-augsburg.de', 'https://www.diakonie-augsburg.de',
 'Mo–Fr 9–17 Uhr, Sa 9–14 Uhr',
 ARRAY['Möbel','Kleidung','Hausrat','Bücher'],
 ARRAY['sozialkaufhaus','augsburg','secondhand'], true, true),

('Caritas Kaufhaus Bielefeld', 'sozialkaufhaus',
 'Das Sozialkaufhaus der Caritas Bielefeld bietet günstige Gebrauchtwaren für Einkommensschwache.',
 'Zimmerstraße 3', '33602', 'Bielefeld', 'Nordrhein-Westfalen', 'DE',
 52.0228, 8.5347, '0521 299 56 0', 'info@caritas-bielefeld.de', 'https://www.caritas-bielefeld.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Möbel','Kleidung','Hausrat','Spielzeug'],
 ARRAY['sozialkaufhaus','bielefeld','secondhand'], true, true),

('Sozialkaufhaus AWO Mannheim', 'sozialkaufhaus',
 'AWO-Sozialkaufhaus Mannheim – günstige Waren aus Spenden für Bedürftige und alle Einkommensgruppen.',
 'Reichskanzler-Müller-Straße 15', '68165', 'Mannheim', 'Baden-Württemberg', 'DE',
 49.4802, 8.4874, '0621 401 81 0', 'info@awo-mannheim.de', 'https://www.awo-mannheim.de',
 'Mo–Sa 9–18 Uhr',
 ARRAY['Möbel','Kleidung','Hausrat','Elektro'],
 ARRAY['sozialkaufhaus','mannheim','secondhand'], true, true),

('Diakonie Sozialkaufhaus Wuppertal', 'sozialkaufhaus',
 'Sozialkaufhaus der Diakonie Wuppertal mit günstigen Möbeln, Kleidung und Haushaltswaren.',
 'Schloßbleiche 26', '42103', 'Wuppertal', 'Nordrhein-Westfalen', 'DE',
 51.2571, 7.1479, '0202 2971 0', 'info@diakonie-wuppertal.de', 'https://www.diakonie-wuppertal.de',
 'Mo–Fr 9–17 Uhr, Sa 9–13 Uhr',
 ARRAY['Möbel','Kleidung','Hausrat','Bücher'],
 ARRAY['sozialkaufhaus','wuppertal','secondhand'], true, true),

('Caritas Kaufhaus Bochum', 'sozialkaufhaus',
 'Das Sozialkaufhaus der Caritas Bochum bietet Gebrauchtwaren günstig an.',
 'Kortumstraße 53', '44787', 'Bochum', 'Nordrhein-Westfalen', 'DE',
 51.4818, 7.2160, '0234 6100 0', 'info@caritas-bochum.de', 'https://www.caritas-bochum.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Möbel','Kleidung','Hausrat','Spielzeug'],
 ARRAY['sozialkaufhaus','bochum','secondhand'], true, true),

('AWO Sozialkaufhaus Kassel', 'sozialkaufhaus',
 'Günstige Gebrauchtwaren für Bedürftige in Kassel. Einkommensschwache erhalten besondere Rabatte.',
 'Wolfhager Straße 1', '34117', 'Kassel', 'Hessen', 'DE',
 51.3150, 9.4797, '0561 7391 0', 'info@awo-kassel.de', 'https://www.awo-kassel.de',
 'Mo–Fr 9–17 Uhr, Sa 9–14 Uhr',
 ARRAY['Möbel','Kleidung','Hausrat','Elektro'],
 ARRAY['sozialkaufhaus','kassel','secondhand'], true, true),

('Caritas KaufHaus Mainz', 'sozialkaufhaus',
 'Sozialkaufhaus der Caritas Mainz mit günstigem Secondhand für alle. Erlöse für soziale Projekte.',
 'Weintorstraße 8', '55116', 'Mainz', 'Rheinland-Pfalz', 'DE',
 50.0003, 8.2719, '06131 2527 0', 'info@caritas-mainz.de', 'https://www.caritas-mainz.de',
 'Mo–Sa 9–18 Uhr',
 ARRAY['Möbel','Kleidung','Hausrat','Bücher'],
 ARRAY['sozialkaufhaus','mainz','secondhand'], true, true),

('Diakonie Sozialkaufhaus Erfurt', 'sozialkaufhaus',
 'Sozialkaufhaus der Diakonie Thüringen in Erfurt. Günstige Gebrauchtwaren aus Spenden für Bedürftige.',
 'Puschkinstraße 4', '99084', 'Erfurt', 'Thüringen', 'DE',
 50.9791, 11.0359, '0361 5514 0', 'info@diakonie-thueringen.de', 'https://www.diakonie-thueringen.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Möbel','Kleidung','Hausrat','Elektrogeräte'],
 ARRAY['sozialkaufhaus','erfurt','secondhand'], true, true),

('Oxfam Shop Potsdam', 'sozialkaufhaus',
 'Oxfam-Shop Potsdam mit Secondhand-Waren aller Art. Erlöse für humanitäre Projekte weltweit.',
 'Friedrich-Ebert-Straße 5', '14467', 'Potsdam', 'Brandenburg', 'DE',
 52.3971, 13.0616, '0331 601 23 45', 'info@oxfam.de', 'https://www.oxfam.de',
 'Mo–Sa 10–18 Uhr',
 ARRAY['Kleidung','Bücher','Accessoires','Spielzeug'],
 ARRAY['sozialkaufhaus','potsdam','oxfam'], true, true),

('Caritas Sozialkaufhaus Rostock', 'sozialkaufhaus',
 'Sozialkaufhaus der Caritas Rostock – gebrauchte Waren günstig für alle Einkommensgruppen.',
 'Wismarsche Straße 30', '18057', 'Rostock', 'Mecklenburg-Vorpommern', 'DE',
 54.0917, 12.1276, '0381 8008 0', 'info@caritas-rostock.de', 'https://www.caritas-rostock.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Möbel','Kleidung','Hausrat','Bücher'],
 ARRAY['sozialkaufhaus','rostock','secondhand'], true, true),

('AWO Sozialkaufhaus Magdeburg', 'sozialkaufhaus',
 'Das AWO-Sozialkaufhaus Magdeburg bietet günstige Gebrauchtwaren für Bedürftige an.',
 'Regierungsstraße 51', '39104', 'Magdeburg', 'Sachsen-Anhalt', 'DE',
 52.1325, 11.6393, '0391 5400 0', 'info@awo-magdeburg.de', 'https://www.awo-magdeburg.de',
 'Mo–Fr 9–17 Uhr, Sa 9–13 Uhr',
 ARRAY['Möbel','Kleidung','Hausrat','Elektro'],
 ARRAY['sozialkaufhaus','magdeburg','secondhand'], true, true),

('Diakonie Sozialkaufhaus Kiel', 'sozialkaufhaus',
 'Sozialkaufhaus der Diakonie Kiel mit günstigen Gebrauchtwaren für Einkommensschwache.',
 'Holstenstraße 72', '24103', 'Kiel', 'Schleswig-Holstein', 'DE',
 54.3205, 10.1322, '0431 9740 0', 'info@diakonie-kiel.de', 'https://www.diakonie-kiel.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Möbel','Kleidung','Hausrat','Spielzeug'],
 ARRAY['sozialkaufhaus','kiel','secondhand'], true, true),

('Caritas Sozialkaufhaus Saarbrücken', 'sozialkaufhaus',
 'Das Sozialkaufhaus der Caritas im Saarland. Günstige Gebrauchtwaren und Sozialtarife für Bedürftige.',
 'Beschener Weg 40', '66121', 'Saarbrücken', 'Saarland', 'DE',
 49.2225, 7.0140, '0681 26760 0', 'info@caritas-saarbruecken.de', 'https://www.caritas-saarbruecken.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Möbel','Kleidung','Hausrat','Bücher'],
 ARRAY['sozialkaufhaus','saarbrücken','secondhand'], true, true),

('AWO Sozialkaufhaus Chemnitz', 'sozialkaufhaus',
 'AWO-Sozialkaufhaus Chemnitz mit vielfältiger Auswahl aus Spenden für Bedürftige.',
 'Morgenleite 47', '09122', 'Chemnitz', 'Sachsen', 'DE',
 50.8210, 12.9514, '0371 2305 0', 'info@awo-chemnitz.de', 'https://www.awo-chemnitz.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Möbel','Kleidung','Hausrat','Elektrogeräte'],
 ARRAY['sozialkaufhaus','chemnitz','secondhand'], true, true),

('Diakonie Sozialkaufhaus Lübeck', 'sozialkaufhaus',
 'Sozialkaufhaus der Diakonie Lübeck – günstige Gebrauchtwaren für Bedürftige in Lübeck.',
 'Kronsforder Allee 15', '23560', 'Lübeck', 'Schleswig-Holstein', 'DE',
 53.8783, 10.6930, '0451 4005 0', 'info@diakonie-luebeck.de', 'https://www.diakonie-luebeck.de',
 'Mo–Fr 9–17 Uhr, Sa 9–13 Uhr',
 ARRAY['Möbel','Kleidung','Hausrat','Bücher'],
 ARRAY['sozialkaufhaus','lübeck','secondhand'], true, true),

('Caritas KaufHaus Osnabrück', 'sozialkaufhaus',
 'Sozialkaufhaus der Caritas Osnabrück mit günstiger Secondhand-Ware für alle Einkommensgruppen.',
 'Johannisstraße 91', '49074', 'Osnabrück', 'Niedersachsen', 'DE',
 52.2798, 8.0508, '0541 3384 0', 'info@caritas-osnabrueck.de', 'https://www.caritas-osnabrueck.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Möbel','Kleidung','Hausrat','Spielzeug'],
 ARRAY['sozialkaufhaus','osnabrück','secondhand'], true, true),

-- ── ÖSTERREICH (10) ────────────────────────────────────────────────────────
('Caritas Sozialmarkt Wien', 'sozialkaufhaus',
 'Der Sozialmarkt der Caritas Wien bietet bedürftigen Menschen günstige Lebensmittel und Haushaltswaren.',
 'Baumgasse 73', '1030', 'Wien', 'Wien', 'AT',
 48.2069, 16.4056, '01 87812 0', 'sozialmarkt@caritas-wien.at', 'https://www.caritas.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Lebensmittel','Hausrat','Kleidung','Sozialtarif'],
 ARRAY['sozialkaufhaus','wien','sozialmarkt'], true, true),

('Rotes Kreuz Secondhand Wien', 'sozialkaufhaus',
 'Das Rote Kreuz betreibt Secondhand-Shops in Wien mit günstigen Waren. Erlöse für humanitäre Arbeit.',
 'Wiedner Hauptstraße 32', '1040', 'Wien', 'Wien', 'AT',
 48.1960, 16.3659, '01 589 00 0', 'info@w.roteskreuz.at', 'https://www.w.roteskreuz.at',
 'Mo–Fr 10–18 Uhr, Sa 10–15 Uhr',
 ARRAY['Kleidung','Hausrat','Bücher','Secondhand'],
 ARRAY['sozialkaufhaus','wien','secondhand'], true, true),

('Humana Secondhand Graz', 'sozialkaufhaus',
 'Humana-Sozialkaufhaus in Graz – günstige Kleidung und Accessoires. Erlöse für Bildungsprojekte in Afrika.',
 'Jakominiplatz 4', '8010', 'Graz', 'Steiermark', 'AT',
 47.0704, 15.4397, '0316 829 00 78', 'info@humana-kleidersammlung.at', 'https://www.humana-kleidersammlung.at',
 'Mo–Sa 9–18 Uhr',
 ARRAY['Kleidung','Accessoires','Sozialer Handel'],
 ARRAY['sozialkaufhaus','graz','humana'], true, true),

('Diakonie Kaufhaus Linz', 'sozialkaufhaus',
 'Sozialkaufhaus der Diakonie Linz. Günstige Gebrauchtwaren für Bedürftige zu Sozialtarifen.',
 'Coulinstraße 2', '4020', 'Linz', 'Oberösterreich', 'AT',
 48.3046, 14.2790, '0732 7660 0', 'info@diakonie-linz.at', 'https://www.diakonie-linz.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Möbel','Kleidung','Hausrat','Elektro'],
 ARRAY['sozialkaufhaus','linz','secondhand'], true, true),

('Caritas Secondhand Salzburg', 'sozialkaufhaus',
 'Caritas Salzburg betreibt Secondhand-Shops mit günstigen Waren für alle. Erlöse für soziale Projekte.',
 'Nonntaler Hauptstraße 49', '5020', 'Salzburg', 'Salzburg', 'AT',
 47.7945, 13.0483, '0662 8015 200', 'info@caritas-salzburg.at', 'https://www.caritas-salzburg.at',
 'Mo–Sa 9–18 Uhr',
 ARRAY['Kleidung','Hausrat','Bücher','Spielzeug'],
 ARRAY['sozialkaufhaus','salzburg','secondhand'], true, true),

('Humana Secondhand Innsbruck', 'sozialkaufhaus',
 'Humana-Shop in Innsbruck mit günstiger Kleidung und Accessoires. Erlöse für Entwicklungshilfe.',
 'Wilhelm-Greil-Straße 23', '6020', 'Innsbruck', 'Tirol', 'AT',
 47.2681, 11.3957, '0512 58 66 52', 'info@humana-kleidersammlung.at', 'https://www.humana-kleidersammlung.at',
 'Mo–Sa 9–18 Uhr',
 ARRAY['Kleidung','Accessoires','Sozialer Handel'],
 ARRAY['sozialkaufhaus','innsbruck','humana'], true, true),

('Rotes Kreuz Secondhand Klagenfurt', 'sozialkaufhaus',
 'Das Rote Kreuz Kärnten betreibt Secondhand-Läden in Klagenfurt. Günstige Waren, Erlöse für humanitäre Hilfe.',
 'Sterneckstraße 26', '9020', 'Klagenfurt', 'Kärnten', 'AT',
 46.6148, 14.3100, '0463 5518 310', 'info@k.roteskreuz.at', 'https://www.roteskreuz.at',
 'Mo–Fr 9–17 Uhr, Sa 9–13 Uhr',
 ARRAY['Kleidung','Hausrat','Bücher','Secondhand'],
 ARRAY['sozialkaufhaus','klagenfurt','secondhand'], true, true),

('Diakonie Sozialkaufhaus Villach', 'sozialkaufhaus',
 'Die Diakonie betreibt in Villach einen Sozialkaufhaus für Bedürftige und Einkommensschwache.',
 'Bahnhofstraße 24', '9500', 'Villach', 'Kärnten', 'AT',
 46.6124, 13.8507, '04242 2420 800', 'info@diakonie-kaernten.at', 'https://www.diakonie-kaernten.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Möbel','Kleidung','Hausrat','Bücher'],
 ARRAY['sozialkaufhaus','villach','secondhand'], true, true),

('Caritas Sozialmarkt St. Pölten', 'sozialkaufhaus',
 'Sozialmarkt der Caritas NÖ in St. Pölten. Günstige Lebensmittel und Waren für einkommensschwache Personen.',
 'Herzogenburger Straße 39', '3100', 'St. Pölten', 'Niederösterreich', 'AT',
 48.2082, 15.6320, '02742 819 0', 'info@caritas-noe.at', 'https://www.caritas-noe.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Lebensmittel','Hausrat','Kleidung','Sozialtarif'],
 ARRAY['sozialkaufhaus','st-pölten','sozialmarkt'], true, true),

('AWÖ Sozialkaufhaus Wels', 'sozialkaufhaus',
 'Die Arbeiterwohlfahrt OÖ betreibt ein Sozialkaufhaus in Wels mit günstigen Gebrauchtwaren.',
 'Stadtplatz 1', '4600', 'Wels', 'Oberösterreich', 'AT',
 48.1572, 14.0238, '07242 490 0', 'info@awoe-ooe.at', 'https://www.awoe-ooe.at',
 'Mo–Fr 9–17 Uhr, Sa 9–13 Uhr',
 ARRAY['Möbel','Kleidung','Hausrat','Spielzeug'],
 ARRAY['sozialkaufhaus','wels','secondhand'], true, true),

-- ── SCHWEIZ (8) ──────────────────────────────────────────────────────────
('Brocki Zürich – Caritas', 'sozialkaufhaus',
 'Das Caritas-Brockenhaus Zürich verkauft Secondhand-Waren günstig. Erlöse gehen in soziale Projekte.',
 'Letzigraben 133', '8047', 'Zürich', 'Zürich', 'CH',
 47.3812, 8.4982, '044 404 45 45', 'info@caritas-zh.ch', 'https://www.caritas-zuerich.ch',
 'Mo–Fr 9–18 Uhr, Sa 9–17 Uhr',
 ARRAY['Möbel','Kleidung','Hausrat','Bücher'],
 ARRAY['sozialkaufhaus','zürich','brocki'], true, true),

('Brocki Bern – Caritas', 'sozialkaufhaus',
 'Das Caritas-Brockenhaus Bern bietet günstige Secondhand-Waren für alle. Große Auswahl aus Spenden.',
 'Murtenstraße 10', '3008', 'Bern', 'Bern', 'CH',
 46.9459, 7.4226, '031 380 65 65', 'info@caritasbern.ch', 'https://www.caritasbern.ch',
 'Mo–Sa 9–17 Uhr',
 ARRAY['Möbel','Kleidung','Hausrat','Spielzeug'],
 ARRAY['sozialkaufhaus','bern','brocki'], true, true),

('Oxfam Shop Zürich', 'sozialkaufhaus',
 'Oxfam-Shop Zürich mit Secondhand-Mode und Accessoires. Alle Erlöse für humanitäre Projekte.',
 'Zähringerstraße 22', '8001', 'Zürich', 'Zürich', 'CH',
 47.3769, 8.5430, '044 262 45 45', 'info@oxfam.ch', 'https://www.oxfam.ch',
 'Mo–Sa 10–18 Uhr',
 ARRAY['Kleidung','Bücher','Accessoires','Sozialer Handel'],
 ARRAY['sozialkaufhaus','zürich','oxfam'], true, true),

('Caritas Brockenhaus Basel', 'sozialkaufhaus',
 'Caritas Basel betreibt ein Brockenhaus mit günstigen Gebrauchtwaren für Bedürftige.',
 'Gärtnerstraße 46', '4057', 'Basel', 'Basel-Stadt', 'CH',
 47.5672, 7.5952, '061 686 43 43', 'info@caritas-basel.ch', 'https://www.caritas-basel.ch',
 'Mo–Sa 9–17 Uhr',
 ARRAY['Möbel','Kleidung','Hausrat','Bücher'],
 ARRAY['sozialkaufhaus','basel','brocki'], true, true),

('Caritas Brocki Luzern', 'sozialkaufhaus',
 'Das Brockenhaus der Caritas Luzern bietet günstige Waren aus Spenden für alle Einkommensgruppen.',
 'Maihofstraße 76', '6006', 'Luzern', 'Luzern', 'CH',
 47.0618, 8.3101, '041 368 50 50', 'info@caritas-luzern.ch', 'https://www.caritas-luzern.ch',
 'Mo–Fr 9–17 Uhr, Sa 9–16 Uhr',
 ARRAY['Möbel','Kleidung','Hausrat','Spielzeug'],
 ARRAY['sozialkaufhaus','luzern','brocki'], true, true),

('Oxfam Shop Bern', 'sozialkaufhaus',
 'Oxfam-Shop Bern mit Secondhand-Kleidung, Büchern und Accessoires. Erlöse für humanitäre Hilfe.',
 'Lorrainestraße 13', '3013', 'Bern', 'Bern', 'CH',
 46.9598, 7.4436, '031 330 67 70', 'info@oxfam.ch', 'https://www.oxfam.ch',
 'Mo–Sa 10–18 Uhr',
 ARRAY['Kleidung','Bücher','Accessoires','Sozialer Handel'],
 ARRAY['sozialkaufhaus','bern','oxfam'], true, true),

('Humana Secondhand Basel', 'sozialkaufhaus',
 'Humana-Secondhand-Shop in Basel. Günstige Mode aus zweiter Hand, Erlöse für Bildungsprojekte.',
 'Lindenberg 16', '4052', 'Basel', 'Basel-Stadt', 'CH',
 47.5476, 7.5988, '061 271 27 27', 'info@humana-kleidersammlung.at', 'https://www.humana-kleidersammlung.at',
 'Mo–Sa 9–18 Uhr',
 ARRAY['Kleidung','Accessoires','Sozialer Handel'],
 ARRAY['sozialkaufhaus','basel','humana'], true, true),

('Caritas Brockenhaus St. Gallen', 'sozialkaufhaus',
 'Das Brockenhaus der Caritas St. Gallen bietet günstige Gebrauchtwaren für alle Bevölkerungsgruppen.',
 'Teufener Straße 65', '9000', 'St. Gallen', 'St. Gallen', 'CH',
 47.4169, 9.3666, '071 228 55 55', 'info@caritas-stgallen.ch', 'https://www.caritas-stgallen.ch',
 'Mo–Fr 9–17 Uhr, Sa 9–16 Uhr',
 ARRAY['Möbel','Kleidung','Hausrat','Bücher'],
 ARRAY['sozialkaufhaus','st-gallen','brocki'], true, true),

-- ═══════════════════════════════════════════════════════════
-- KRISENTELEFON (50)
-- ═══════════════════════════════════════════════════════════

-- ── DEUTSCHLAND (32) ──────────────────────────────────────────────────────
('TelefonSeelsorge Deutschland – Evangelisch', 'krisentelefon',
 'Kostenlose, anonyme Krisenbegleitung rund um die Uhr. Ehrenamtliche Berater helfen bei seelischen Krisen, Depressionen und Suizidgedanken.',
 'Zentraler Dienst, bundesweit', '00000', 'bundesweit', '', 'DE',
 51.1657, 10.4515, '0800 111 0 111', 'info@telefonseelsorge.de', 'https://www.telefonseelsorge.de',
 '24/7 – täglich, kostenlos, anonym',
 ARRAY['Krisenbegleitung','Suizidprävention','Lebensberatung'],
 ARRAY['krisentelefon','deutschland','seelsorge'], true, true),

('TelefonSeelsorge Deutschland – Katholisch', 'krisentelefon',
 'Kostenlose, anonyme Seelsorge und Krisenberatung rund um die Uhr. Auch online und per Chat erreichbar.',
 'Zentraler Dienst, bundesweit', '00000', 'bundesweit', '', 'DE',
 51.1657, 10.4515, '0800 111 0 222', 'info@telefonseelsorge.de', 'https://www.telefonseelsorge.de',
 '24/7 – täglich, kostenlos, anonym',
 ARRAY['Krisenbegleitung','Suizidprävention','Seelsorge'],
 ARRAY['krisentelefon','deutschland','seelsorge'], true, true),

('EU-Helpline Deutschland – 116 123', 'krisentelefon',
 'Europaweite Krisenhotline 116 123 – kostenlos, anonym, rund um die Uhr erreichbar in Deutschland.',
 'Zentraler Dienst, bundesweit', '00000', 'bundesweit', '', 'DE',
 51.1657, 10.4515, '116 123', 'info@telefonseelsorge.de', 'https://www.telefonseelsorge.de',
 '24/7 – täglich, kostenlos, anonym',
 ARRAY['EU-Hotline','Krisenbegleitung','Lebensberatung'],
 ARRAY['krisentelefon','deutschland','eu-helpline'], true, true),

('Nummer gegen Kummer – Kinder und Jugendliche', 'krisentelefon',
 'Kostenlose Beratung für Kinder und Jugendliche in schwierigen Situationen. 116 111 deutschlandweit erreichbar.',
 'Mühlendamm 3', '10178', 'Berlin', 'Berlin', 'DE',
 52.5163, 13.4024, '116 111', 'info@nummergegenkummer.de', 'https://www.nummergegenkummer.de',
 'Mo–Sa 14–20 Uhr',
 ARRAY['Kinderberatung','Jugendberatung','Krisenbegleitung'],
 ARRAY['krisentelefon','deutschland','jugend'], true, true),

('Elterntelefon – Nummer gegen Kummer', 'krisentelefon',
 'Kostenlose Beratung für Eltern in Erziehungsfragen und Krisen. 0800 111 0 550 bundesweit erreichbar.',
 'Mühlendamm 3', '10178', 'Berlin', 'Berlin', 'DE',
 52.5163, 13.4024, '0800 111 0 550', 'info@nummergegenkummer.de', 'https://www.nummergegenkummer.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Elternberatung','Erziehungshilfe','Krisenbegleitung'],
 ARRAY['krisentelefon','deutschland','eltern'], true, true),

('Hilfetelefon Gewalt gegen Frauen', 'krisentelefon',
 'Bundesweites Hilfetelefon für Frauen in Gewaltsituationen. Kostenlos, anonym, rund um die Uhr erreichbar.',
 'Zentraler Dienst, bundesweit', '00000', 'bundesweit', '', 'DE',
 51.1657, 10.4515, '116 016', 'hilfetelefon@gewaltgegenfrauen.de', 'https://www.hilfetelefon.de',
 '24/7 – täglich, kostenlos, anonym',
 ARRAY['Gewaltschutz','Frauenhilfe','Krisenbegleitung'],
 ARRAY['krisentelefon','deutschland','frauen'], true, true),

('Giftnotruf Berlin', 'krisentelefon',
 'Vergiftungsberatung rund um die Uhr für Ärzte und Bevölkerung. Schnelle Hilfe bei Vergiftungsnotfällen.',
 'Charitéplatz 1', '10117', 'Berlin', 'Berlin', 'DE',
 52.5252, 13.3799, '030 19240', 'giftnotruf@charite.de', 'https://www.giftnotruf.de',
 '24/7 – täglich',
 ARRAY['Vergiftungsberatung','Notfallhilfe','Medizin'],
 ARRAY['krisentelefon','berlin','gift'], true, true),

('Giftinformationszentrum München (GIZ-S)', 'krisentelefon',
 'Das Giftinformationszentrum in München berät bei Vergiftungen aller Art rund um die Uhr.',
 'Marchioninistraße 15', '81377', 'München', 'Bayern', 'DE',
 48.0990, 11.4641, '089 19240', 'giz-s@lmu.de', 'https://www.giz-s.de',
 '24/7 – täglich',
 ARRAY['Vergiftungsberatung','Notfallhilfe','Medizin'],
 ARRAY['krisentelefon','münchen','gift'], true, true),

('Krisentelefon München – Caritas', 'krisentelefon',
 'Caritas München bietet telefonische Krisenberatung für Menschen in akuten psychischen Notsituationen.',
 'Landwehrstraße 15', '80336', 'München', 'Bayern', 'DE',
 48.1359, 11.5564, '089 723 45 67', 'krisenberatung@caritas-muenchen.de', 'https://www.caritas-muenchen.de',
 'Mo–Fr 8–20 Uhr',
 ARRAY['Krisenberatung','Psychosoziale Hilfe','Notfall'],
 ARRAY['krisentelefon','münchen','caritas'], true, true),

('Krisentelefon Hamburg – Diakonie', 'krisentelefon',
 'Telefonische Krisenberatung der Diakonie Hamburg für Menschen in schweren Lebenssituationen.',
 'Poststraße 28', '20354', 'Hamburg', 'Hamburg', 'DE',
 53.5526, 9.9965, '040 280 25 14', 'krisentelefon@diakonie-hamburg.de', 'https://www.diakonie-hamburg.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Krisenberatung','Lebensberatung','Notfall'],
 ARRAY['krisentelefon','hamburg','diakonie'], true, true),

('Psychiatrische Krisenhotline Berlin', 'krisentelefon',
 'Psychiatrischer Krisendienst Berlin – 24h-Notfalltelefon für Menschen in psychischen Krisen.',
 'Reinhardtstraße 21', '10117', 'Berlin', 'Berlin', 'DE',
 52.5244, 13.3836, '030 390 63 00', 'krisendienst@charite.de', 'https://www.charite.de',
 '24/7 – täglich',
 ARRAY['Psychiatrische Notaufnahme','Krisenberatung','Notfall'],
 ARRAY['krisentelefon','berlin','psychiatrie'], true, true),

('Krisendienst Psychiatrie Bayern', 'krisentelefon',
 'Der Krisendienst Psychiatrie Bayern ist rund um die Uhr erreichbar und hilft bei psychischen Krisen.',
 'Zentraler Dienst, Bayern', '80331', 'München', 'Bayern', 'DE',
 48.1374, 11.5755, '0800 655 3000', 'krisendienst@psychiatrie-und-psychotherapie-in-muenchen.de', 'https://www.krisendienst-psychiatrie.de',
 '24/7 – täglich, kostenlos',
 ARRAY['Psychiatrische Notaufnahme','Krisenberatung','Notfall'],
 ARRAY['krisentelefon','münchen','psychiatrie'], true, true),

('Suizidpräventionsstelle Frankfurt', 'krisentelefon',
 'Krisentelefon und Beratungsstelle der Caritas Frankfurt für Menschen in Suizidkrisen und Depressionen.',
 'Kennedyallee 7', '60596', 'Frankfurt am Main', 'Hessen', 'DE',
 50.0989, 8.6827, '069 710 49 55 0', 'info@caritas-frankfurt.de', 'https://www.caritas-frankfurt.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Suizidprävention','Krisenberatung','Depression'],
 ARRAY['krisentelefon','frankfurt','suizid'], true, true),

('Krisentelefon Köln – AWO', 'krisentelefon',
 'AWO Köln bietet telefonische Krisenberatung für Menschen in seelischen Notlagen und Krisen.',
 'Rubensstraße 7-13', '50676', 'Köln', 'Nordrhein-Westfalen', 'DE',
 50.9278, 6.9466, '0221 93 28 28 0', 'krisentelefon@awo-koeln.de', 'https://www.awo-koeln.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Krisenberatung','Suizidprävention','Lebensberatung'],
 ARRAY['krisentelefon','köln','awo'], true, true),

('Krisen- und Beratungstelefon Stuttgart', 'krisentelefon',
 'Die Caritas Stuttgart betreibt ein Krisentelefon für Menschen in psychischen Notlagen und Lebenskrisen.',
 'Strombergstraße 11', '70188', 'Stuttgart', 'Baden-Württemberg', 'DE',
 48.7877, 9.2039, '0711 641 24 67', 'krisentelefon@caritas-stuttgart.de', 'https://www.caritas-stuttgart.de',
 'Mo–Fr 8–18 Uhr',
 ARRAY['Krisenberatung','Lebensberatung','Notfall'],
 ARRAY['krisentelefon','stuttgart','caritas'], true, true),

('Kinderschutztelefon – DRK Bundesweit', 'krisentelefon',
 'DRK-Kinderschutztelefon für Kinder und Jugendliche in Not. Kostenlos und anonym bundesweit erreichbar.',
 'Carstennstraße 58', '12205', 'Berlin', 'Berlin', 'DE',
 52.4241, 13.3188, '0800 111 0 333', 'info@drk.de', 'https://www.drk.de',
 'Mo–Sa 14–20 Uhr, kostenlos',
 ARRAY['Kinderschutz','Jugendberatung','Krisenbegleitung'],
 ARRAY['krisentelefon','deutschland','kinder'], true, true),

('Frauennotruf Frankfurt', 'krisentelefon',
 'Beratung und Krisentelefon für Frauen nach sexueller Gewalt oder häuslicher Gewalt in Frankfurt.',
 'Kiesstraße 14', '60486', 'Frankfurt am Main', 'Hessen', 'DE',
 50.1158, 8.6418, '069 70 94 94', 'info@frauennotruf-frankfurt.de', 'https://www.frauennotruf-frankfurt.de',
 '24/7 – täglich',
 ARRAY['Frauenhilfe','Gewaltberatung','Krisenbegleitung'],
 ARRAY['krisentelefon','frankfurt','frauen'], true, true),

('Landesweite Krisenhotline NRW', 'krisentelefon',
 'Telefonseelsorge NRW – kostenlose Krisenhotline für Menschen in psychischen Notlagen in NRW.',
 'Zentraler Dienst NRW', '40210', 'Düsseldorf', 'Nordrhein-Westfalen', 'DE',
 51.2194, 6.7933, '0800 111 0 111', 'info@telefonseelsorge-nrw.de', 'https://www.telefonseelsorge.de',
 '24/7 – täglich, kostenlos, anonym',
 ARRAY['Krisenberatung','Seelsorge','Notfall'],
 ARRAY['krisentelefon','nrw','seelsorge'], true, true),

('Krisentelefon Hannover – Sozialpsychiatrischer Dienst', 'krisentelefon',
 'Sozialpsychiatrischer Dienst Hannover bietet Krisenintervention und telefonische Beratung.',
 'Hamburger Allee 24', '30161', 'Hannover', 'Niedersachsen', 'DE',
 52.3846, 9.7384, '0511 3490 0', 'info@spdi-hannover.de', 'https://www.hannover.de',
 'Mo–Fr 8–16 Uhr',
 ARRAY['Krisenintervention','Psychiatrie','Beratung'],
 ARRAY['krisentelefon','hannover','psychiatrie'], true, true),

('Krisentelefon Dresden – Caritas', 'krisentelefon',
 'Caritas Dresden bietet telefonische Krisenberatung für Menschen in akuten seelischen Notlagen.',
 'Magazingasse 15', '01067', 'Dresden', 'Sachsen', 'DE',
 51.0530, 13.7348, '0351 484 85 50', 'krisentelefon@caritas-dresden.de', 'https://www.caritas-dresden.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Krisenberatung','Seelsorge','Lebensberatung'],
 ARRAY['krisentelefon','dresden','caritas'], true, true),

('Depressionshotline Hamburg', 'krisentelefon',
 'Spezielle Beratungshotline für Menschen mit Depressionen in Hamburg – Unterstützung und Vermittlung.',
 'Hühnerposten 5', '20097', 'Hamburg', 'Hamburg', 'DE',
 53.5540, 10.0082, '040 2511 60 70', 'info@depressionsliga.de', 'https://www.deutsche-depressionshilfe.de',
 'Mo–Di 13–17 Uhr, Mi 8:30–12:30 Uhr',
 ARRAY['Depressionsberatung','Krisenbegleitung','Suizidprävention'],
 ARRAY['krisentelefon','hamburg','depression'], true, true),

('Krisentelefon Leipzig – Diakonie', 'krisentelefon',
 'Die Diakonie Leipzig bietet telefonische Krisenberatung für Menschen in akuten Lebenskrisen.',
 'Gustav-Adolff-Straße 5', '04105', 'Leipzig', 'Sachsen', 'DE',
 51.3395, 12.3797, '0341 129 96 0', 'krisentelefon@diakonie-leipzig.de', 'https://www.diakonie-leipzig.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Krisenberatung','Lebensberatung','Notfall'],
 ARRAY['krisentelefon','leipzig','diakonie'], true, true),

('Bundesweite Suizidprävention – Dt. Gesellschaft', 'krisentelefon',
 'Die Deutsche Gesellschaft für Suizidprävention koordiniert bundesweit Präventionsangebote.',
 'Friedrichstraße 217', '10969', 'Berlin', 'Berlin', 'DE',
 52.5078, 13.3922, '030 2514 5141', 'info@suizidpraevention-deutschland.de', 'https://www.suizidpraevention-deutschland.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Suizidprävention','Beratung','Information'],
 ARRAY['krisentelefon','deutschland','suizid'], true, true),

('Krisentelefon Nürnberg – Stadtmission', 'krisentelefon',
 'Die Stadtmission Nürnberg bietet Krisentelefon und Seelsorge für Menschen in Notlagen.',
 'Innere Cramer-Klett-Straße 16', '90403', 'Nürnberg', 'Bayern', 'DE',
 49.4566, 11.0842, '0911 234 56 78', 'krisentelefon@stadtmission-nuernberg.de', 'https://www.stadtmission-nuernberg.de',
 'Mo–Fr 8–20 Uhr',
 ARRAY['Krisenberatung','Seelsorge','Notfall'],
 ARRAY['krisentelefon','nürnberg','stadtmission'], true, true),

('Krisentelefon Freiburg – Caritas', 'krisentelefon',
 'Caritas Freiburg bietet telefonische Krisenberatung für Menschen in psychischen und sozialen Notlagen.',
 'Herrenstraße 25', '79098', 'Freiburg', 'Baden-Württemberg', 'DE',
 47.9965, 7.8474, '0761 200 39 0', 'krisentelefon@caritas-freiburg.de', 'https://www.caritas-freiburg.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Krisenberatung','Lebensberatung','Notfall'],
 ARRAY['krisentelefon','freiburg','caritas'], true, true),

('Krisentelefon Karlsruhe – Diakonie', 'krisentelefon',
 'Diakonie Karlsruhe bietet telefonische Beratung und Krisenintervention für Menschen in Not.',
 'Karl-Friedrich-Straße 9', '76133', 'Karlsruhe', 'Baden-Württemberg', 'DE',
 49.0078, 8.4042, '0721 9349 0', 'krisentelefon@diakonie-karlsruhe.de', 'https://www.diakonie-karlsruhe.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Krisenberatung','Seelsorge','Notfall'],
 ARRAY['krisentelefon','karlsruhe','diakonie'], true, true),

('Krisentelefon Mannheim – AWO', 'krisentelefon',
 'Die AWO Mannheim bietet telefonische Krisenberatung für Menschen in schwierigen Lebenssituationen.',
 'Mollstraße 13', '68165', 'Mannheim', 'Baden-Württemberg', 'DE',
 49.4919, 8.4867, '0621 120 00 0', 'krisentelefon@awo-mannheim.de', 'https://www.awo-mannheim.de',
 'Mo–Fr 9–16 Uhr',
 ARRAY['Krisenberatung','Lebensberatung','Sozialberatung'],
 ARRAY['krisentelefon','mannheim','awo'], true, true),

('Telefonseelsorge Dortmund', 'krisentelefon',
 'Ehrenamtliche Telefonseelsorge in Dortmund – kostenlos, anonym, 24 Stunden erreichbar.',
 'Reinoldistraße 7-9', '44135', 'Dortmund', 'Nordrhein-Westfalen', 'DE',
 51.5144, 7.4668, '0800 111 0 111', 'info@telefonseelsorge-dortmund.de', 'https://www.telefonseelsorge.de',
 '24/7 – täglich, kostenlos, anonym',
 ARRAY['Krisenberatung','Seelsorge','Notfall'],
 ARRAY['krisentelefon','dortmund','seelsorge'], true, true),

('Telefonseelsorge Bochum', 'krisentelefon',
 'Telefonseelsorge Bochum – kostenlose, anonyme Krisenbegleitung. Ehrenamtliche Berater rund um die Uhr.',
 'Hattinger Straße 6', '44789', 'Bochum', 'Nordrhein-Westfalen', 'DE',
 51.4799, 7.2158, '0800 111 0 222', 'info@telefonseelsorge-bochum.de', 'https://www.telefonseelsorge.de',
 '24/7 – täglich, kostenlos, anonym',
 ARRAY['Krisenberatung','Seelsorge','Notfall'],
 ARRAY['krisentelefon','bochum','seelsorge'], true, true),

('Krisentelefon Magdeburg – Diakonie', 'krisentelefon',
 'Diakonie Magdeburg bietet telefonische Krisenintervention und Beratung für Menschen in Not.',
 'Olvenstedter Straße 3', '39108', 'Magdeburg', 'Sachsen-Anhalt', 'DE',
 52.1355, 11.6188, '0391 850 76 0', 'krisentelefon@diakonie-magdeburg.de', 'https://www.diakonie-magdeburg.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Krisenintervention','Lebensberatung','Notfall'],
 ARRAY['krisentelefon','magdeburg','diakonie'], true, true),

('Telefonseelsorge Erfurt', 'krisentelefon',
 'Telefonseelsorge Erfurt – kostenlose Krisenberatung für Menschen in Thüringen. Ehrenamtliche Helfer.',
 'Regierungsstraße 51', '99084', 'Erfurt', 'Thüringen', 'DE',
 50.9786, 11.0335, '0800 111 0 111', 'info@telefonseelsorge-erfurt.de', 'https://www.telefonseelsorge.de',
 '24/7 – täglich, kostenlos, anonym',
 ARRAY['Krisenberatung','Seelsorge','Notfall'],
 ARRAY['krisentelefon','erfurt','seelsorge'], true, true),

('Krisentelefon Rostock – Caritas', 'krisentelefon',
 'Caritas Rostock bietet telefonische Krisenberatung für Menschen in Mecklenburg-Vorpommern.',
 'Wismarsche Straße 30', '18057', 'Rostock', 'Mecklenburg-Vorpommern', 'DE',
 54.0917, 12.1276, '0381 455 67 80', 'krisentelefon@caritas-rostock.de', 'https://www.caritas-rostock.de',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Krisenberatung','Lebensberatung','Notfall'],
 ARRAY['krisentelefon','rostock','caritas'], true, true),

-- ── ÖSTERREICH (10) ────────────────────────────────────────────────────────
('Telefonseelsorge Austria – 142', 'krisentelefon',
 'Österreichweite Telefonseelsorge – kostenlos, anonym, rund um die Uhr. Hilfe bei Krisen, Einsamkeit, Suizidgedanken.',
 'Zentraler Dienst, österreichweit', '00000', 'bundesweit', '', 'AT',
 47.8095, 13.0550, '142', 'info@telefonseelsorge.at', 'https://www.telefonseelsorge.at',
 '24/7 – täglich, kostenlos, anonym',
 ARRAY['Krisenberatung','Suizidprävention','Seelsorge'],
 ARRAY['krisentelefon','österreich','seelsorge'], true, true),

('Rat auf Draht – 147 (Kinder & Jugendliche)', 'krisentelefon',
 'Österreichweite Krisenhotline für Kinder und Jugendliche – 147, kostenlos, anonym, rund um die Uhr.',
 'Argentinierstraße 24', '1040', 'Wien', 'Wien', 'AT',
 48.1919, 16.3738, '147', 'info@rataufdraht.at', 'https://www.rataufdraht.at',
 '24/7 – täglich, kostenlos, anonym',
 ARRAY['Kinderberatung','Jugendberatung','Krisenbegleitung'],
 ARRAY['krisentelefon','österreich','jugend'], true, true),

('Frauennotruf Wien – 0800 222 555', 'krisentelefon',
 'Frauennotruf Wien – kostenlos, rund um die Uhr für Frauen in Gewaltsituationen erreichbar.',
 'Währinger Gürtel 43', '1090', 'Wien', 'Wien', 'AT',
 48.2214, 16.3489, '0800 222 555', 'info@frauennotruf.at', 'https://www.wien.gv.at/frauennotruf',
 '24/7 – täglich, kostenlos, anonym',
 ARRAY['Frauenhilfe','Gewaltberatung','Krisenbegleitung'],
 ARRAY['krisentelefon','wien','frauen'], true, true),

('Männernotruf Österreich – 0800 400 777', 'krisentelefon',
 'Kostenloser Männernotruf für Österreich – Beratung für Männer in Krisensituationen und bei Gewalterfahrungen.',
 'Zentraler Dienst, österreichweit', '00000', 'bundesweit', '', 'AT',
 47.8095, 13.0550, '0800 400 777', 'info@maennernotruf.at', 'https://www.maennernotruf.at',
 '24/7 – täglich, kostenlos, anonym',
 ARRAY['Männerberatung','Krisenbegleitung','Gewaltberatung'],
 ARRAY['krisentelefon','österreich','männer'], true, true),

('Psychiatrische Soforthilfe Wien – 01 31330', 'krisentelefon',
 'Psychiatrische Krisenhotline Wien – 24h-Notruf für Menschen in psychischen Notlagen in Wien.',
 'Spitalgasse 23', '1090', 'Wien', 'Wien', 'AT',
 48.2189, 16.3478, '01 31330', 'info@psd-wien.at', 'https://www.psd-wien.at',
 '24/7 – täglich',
 ARRAY['Psychiatrische Notaufnahme','Krisenberatung','Notfall'],
 ARRAY['krisentelefon','wien','psychiatrie'], true, true),

('Giftnotruf Österreich – 01 406 43 43', 'krisentelefon',
 'Vergiftungsberatung rund um die Uhr für Österreich. Medizinische Sofortberatung bei Vergiftungsnotfällen.',
 'Währinger Gürtel 18-20', '1090', 'Wien', 'Wien', 'AT',
 48.2188, 16.3536, '01 406 43 43', 'info@goeg.at', 'https://www.vergiftungsberatung.at',
 '24/7 – täglich',
 ARRAY['Vergiftungsberatung','Notfallhilfe','Medizin'],
 ARRAY['krisentelefon','österreich','gift'], true, true),

('Sozialtelefon Graz – 0316 7060', 'krisentelefon',
 'Sozial- und Krisenberatungstelefon der Diakonie Graz für Menschen in Lebenskrisen.',
 'Riesstraße 79', '8010', 'Graz', 'Steiermark', 'AT',
 47.0570, 15.4668, '0316 7060', 'info@diakonie-steiermark.at', 'https://www.diakonie-steiermark.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Krisenberatung','Sozialberatung','Lebensberatung'],
 ARRAY['krisentelefon','graz','diakonie'], true, true),

('Krisentelefon Linz – Caritas', 'krisentelefon',
 'Caritas OÖ betreibt ein Krisentelefon in Linz für Menschen in seelischen Notlagen.',
 'Kapuzinerstraße 84', '4020', 'Linz', 'Oberösterreich', 'AT',
 48.2972, 14.2784, '0732 7610 200', 'krisentelefon@caritas-linz.at', 'https://www.caritas-linz.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Krisenberatung','Lebensberatung','Notfall'],
 ARRAY['krisentelefon','linz','caritas'], true, true),

('Frauennotruf Salzburg – 0662 88 11 00', 'krisentelefon',
 'Beratungs- und Krisentelefon für Frauen in Gewaltsituationen in Salzburg. Anonym und kostenlos.',
 'Nonntaler Hauptstraße 49', '5020', 'Salzburg', 'Salzburg', 'AT',
 47.7945, 13.0483, '0662 88 11 00', 'info@frauennotruf-salzburg.at', 'https://www.frauennotruf-salzburg.at',
 '24/7 – täglich, kostenlos, anonym',
 ARRAY['Frauenhilfe','Gewaltberatung','Krisenbegleitung'],
 ARRAY['krisentelefon','salzburg','frauen'], true, true),

('Krisentelefon Innsbruck – Diakonie Tirol', 'krisentelefon',
 'Diakonie Tirol bietet telefonische Krisenberatung für Menschen in psychischen und sozialen Krisen.',
 'Heiliggeiststraße 16', '6020', 'Innsbruck', 'Tirol', 'AT',
 47.2651, 11.3926, '0512 59 80 300', 'krisentelefon@diakonie-tirol.at', 'https://www.diakonie-tirol.at',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Krisenberatung','Lebensberatung','Notfall'],
 ARRAY['krisentelefon','innsbruck','diakonie'], true, true),

-- ── SCHWEIZ (8) ──────────────────────────────────────────────────────────
('Die Dargebotene Hand – 143', 'krisentelefon',
 'Schweizweite Krisenhotline – 143, kostenlos, anonym, rund um die Uhr. Hilfe bei Krisen und Suizidgedanken.',
 'Zentraler Dienst, schweizweit', '00000', 'bundesweit', '', 'CH',
 46.8182, 8.2275, '143', 'info@143.ch', 'https://www.143.ch',
 '24/7 – täglich, kostenlos, anonym',
 ARRAY['Krisenberatung','Suizidprävention','Seelsorge'],
 ARRAY['krisentelefon','schweiz','seelsorge'], true, true),

('Pro Juventute – 147 (Kinder & Jugendliche CH)', 'krisentelefon',
 'Schweizer Krisenhotline für Kinder und Jugendliche – 147, kostenlos, anonym, 24/7.',
 'Zentraler Dienst, schweizweit', '00000', 'bundesweit', '', 'CH',
 46.8182, 8.2275, '147', 'info@projuventute.ch', 'https://www.projuventute.ch',
 '24/7 – täglich, kostenlos, anonym',
 ARRAY['Kinderberatung','Jugendberatung','Krisenbegleitung'],
 ARRAY['krisentelefon','schweiz','jugend'], true, true),

('Frauennotruf Zürich – 044 291 46 46', 'krisentelefon',
 'Beratungs- und Krisentelefon für Frauen in Gewaltsituationen in Zürich. Kostenlos, anonym.',
 'Strickgasse 4', '8004', 'Zürich', 'Zürich', 'CH',
 47.3742, 8.5280, '044 291 46 46', 'info@fraueninformationszentrum.ch', 'https://www.frauenberatung.ch',
 '24/7 – täglich, kostenlos, anonym',
 ARRAY['Frauenhilfe','Gewaltberatung','Krisenbegleitung'],
 ARRAY['krisentelefon','zürich','frauen'], true, true),

('Giftinformationszentrum Schweiz – 145', 'krisentelefon',
 'Schweizer Toxikologisches Informationszentrum – 24h-Notfallberatung bei Vergiftungen.',
 'Freiestraße 16', '8032', 'Zürich', 'Zürich', 'CH',
 47.3631, 8.5683, '145', 'info@tox.ch', 'https://www.toxcenter.ch',
 '24/7 – täglich',
 ARRAY['Vergiftungsberatung','Notfallhilfe','Medizin'],
 ARRAY['krisentelefon','schweiz','gift'], true, true),

('Krisentelefon Bern – Berner Gesundheit', 'krisentelefon',
 'Berner Gesundheit bietet telefonische Beratung und Krisenintervention für Menschen in Lebenskrisen.',
 'Dammweg 8-10', '3013', 'Bern', 'Bern', 'CH',
 46.9572, 7.4504, '031 370 70 70', 'info@beges.ch', 'https://www.berner-gesundheit.ch',
 'Mo–Fr 8–17 Uhr',
 ARRAY['Krisenberatung','Suchtberatung','Lebensberatung'],
 ARRAY['krisentelefon','bern','beratung'], true, true),

('Krisentelefon Basel – Dargebotene Hand', 'krisentelefon',
 'Regionalstelle der Dargebotenen Hand in Basel – telefonische Krisenberatung für Basel und Umgebung.',
 'Spalenberg 55', '4051', 'Basel', 'Basel-Stadt', 'CH',
 47.5584, 7.5869, '143', 'info@143-bs.ch', 'https://www.143.ch',
 '24/7 – täglich, kostenlos, anonym',
 ARRAY['Krisenberatung','Seelsorge','Suizidprävention'],
 ARRAY['krisentelefon','basel','seelsorge'], true, true),

('Krisentelefon Luzern – Caritas', 'krisentelefon',
 'Caritas Luzern bietet telefonische Krisenberatung für Menschen in schwierigen Lebenssituationen.',
 'Kasernenplatz 3', '6003', 'Luzern', 'Luzern', 'CH',
 47.0469, 8.3100, '041 368 50 50', 'krisentelefon@caritas-luzern.ch', 'https://www.caritas-luzern.ch',
 'Mo–Fr 9–17 Uhr',
 ARRAY['Krisenberatung','Lebensberatung','Notfall'],
 ARRAY['krisentelefon','luzern','caritas'], true, true),

('Frauennotruf Bern – 031 311 14 55', 'krisentelefon',
 'Beratungs- und Krisentelefon für Frauen in Gewaltsituationen in der Region Bern.',
 'Marktgasse 36', '3011', 'Bern', 'Bern', 'CH',
 46.9480, 7.4481, '031 311 14 55', 'info@frauennotruf-bern.ch', 'https://www.frauennotruf-bern.ch',
 '24/7 – täglich, kostenlos, anonym',
 ARRAY['Frauenhilfe','Gewaltberatung','Krisenbegleitung'],
 ARRAY['krisentelefon','bern','frauen'], true, true);

END IF;
END $$;
